// Generated by rust-js from test/corpus/assert_failure.rs. Do not edit.

import { $assertFailed } from "@rust-js/runtime";

function main() {
  const total = [1, 2, 3].reduce((a, b) => (a + b) | 0, 0);
  if (total !== 6) {
    const kind = "Eq";
    $assertFailed(kind, String(total), "6");
  }
  console.log("first holds");
  if (total !== 7) {
    const kind$1 = "Eq";
    $assertFailed(kind$1, String(total), "7", "totals differ");
  }
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
