// Generated by rust-js from test/corpus/assignment_order_compound.rs. Do not edit.

function $at(items, index) {
  if (index < 0 || index >= items.length)
    throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return index;
}

function value(x) {
  console.log("value");
  return x;
}

function main() {
  let v = [];
  const i = 0;
  const value$1 = value(1);
  v[$at(v, i)] = (v[$at(v, i)] + value$1) | 0;
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
