// Generated by rust-js from test/corpus/begin_panic_string.rs. Do not edit.

function main() {
  const left = 3;
  const message = `${left} left`;
  if (left > 0) {
    throw new Error(message);
  }
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
