// Generated by rust-js from test/corpus/closure_capture.rs. Do not edit.

function $range(start, end) {
  return Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

function make_counter() {
  let count = 0;
  return () => {
    count = (count + 1) | 0;
    return count;
  };
}

function apply(f, items) {
  for (const x of items) {
    f(x);
  }
}

function main() {
  let total = 0;
  apply(
    (x) => {
      total = (total + x) | 0;
    },
    [1, 2, 3],
  );
  console.log(`total ${total}`);
  let a = make_counter();
  let b = make_counter();
  console.log(`${a()} ${a()} ${b()} ${a()}`);
  let names = ["x"];
  let add = (s) => {
    names.push(s);
  };
  add("y");
  add("z");
  console.log(`[${names.map((item) => $debugStr(item)).join(", ")}]`);
  const base = 10;
  const adders = $range(0, 3).map((i) => (x) => (x + Math.imul(i, base)) | 0);
  console.log(
    `[${adders
      .map((f) => f(1))
      .map((item) => String(item))
      .join(", ")}]`,
  );
  let value = 5;
  let double = () => {
    value = Math.imul(value, 2);
  };
  double();
  double();
  console.log(`value ${value}`);
  const text = "moved";
  const owns = () => Array.from(text).length;
  console.log(`len ${owns()}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
