// Generated by rust-js from test/corpus/drop_skipped_items.rs. Do not edit.

import { $skipWhile } from "@rust-js/runtime";

function main() {
  const fragments = [[1], [2], [3]];
  let fragments$live = true;
  try {
    fragments$live = false;
    const skip = (f) => f[0] < 2;
    const kept = $skipWhile(fragments, (item) => {
      if (skip(item)) {
        fragmentDrop_drop(item);
        return true;
      }
      return false;
    });
    try {
      console.log(`kept ${kept.length}`);
    } finally {
      for (const item of kept) {
        fragmentDrop_drop(item);
      }
    }
  } finally {
    if (fragments$live) {
      for (const item$1 of fragments) {
        fragmentDrop_drop(item$1);
      }
    }
  }
}

export function entry() {
  main();
}

function fragmentDrop_drop(fragment) {
  console.log(`drop ${fragment[0]}`);
}
//# sourceMappingURL=case.js.map
