// Generated by rust-js from test/corpus/drop_impl_param_call.rs. Do not edit.

function $traitImpl(cache, keys, make) {
  // Each key is a dictionary or a drop, held weakly: a drop made for one call
  // goes when it does. No drop, `undefined`, is keyed by this function.
  for (let i = 0; i < keys.length - 1; i++) {
    const key = keys[i] ?? $traitImpl;
    if (!cache.has(key)) cache.set(key, new WeakMap());
    cache = cache.get(key);
  }
  const key = keys[keys.length - 1] ?? $traitImpl;
  if (!cache.has(key)) cache.set(key, make());
  return cache.get(key);
}

var $wrapPeek;

function discard(_u, dropU) {
  dropU?.(_u);
}

function peeked(p, PPeek, dropP) {
  return PPeek.peek(p);
}

function main() {
  const w = [undefined];
  let w$live = true;
  try {
    console.log(
      `${peeked(
        w,
        wrapPeek({ clone: (value) => value }, (loud) => {
          loudDrop_drop({ value: loud });
        }),
        (wrap) => {
          loudDrop_drop({ value: wrap[0] });
        },
      )}`,
    );
    w$live = false;
    console.log(`${peeked(["text"], wrapPeek({ clone: (value) => value }))}`);
  } finally {
    if (w$live) {
      loudDrop_drop({ value: w[0] });
    }
  }
}

export function entry() {
  main();
}

function wrapPeek_peek(wrap, TClone, dropT) {
  const value = TClone.clone(wrap[0]);
  dropT?.(value);
  discard(TClone.clone(wrap[0]), dropT);
  return 1;
}

function loudDrop_drop(self) {
  console.log("dropped");
}

function wrapPeek(TClone, dropT) {
  if ($wrapPeek === undefined) {
    $wrapPeek = new WeakMap();
  }
  return $traitImpl($wrapPeek, [TClone, dropT], () => ({
    peek: (arg0) => wrapPeek_peek(arg0, TClone, dropT),
  }));
}
//# sourceMappingURL=case.js.map
