// Generated by rust-js from test/corpus/drop_impl_dictionary.rs. Do not edit.

function $traitImpl(cache, keys, make) {
  // Each key is a dictionary or a drop, held weakly: a drop made for one call
  // goes when it does. No drop, `undefined`, is keyed by this function.
  for (let i = 0; i < keys.length - 1; i++) {
    const key = keys[i] ?? $traitImpl;
    if (!cache.has(key)) cache.set(key, new WeakMap());
    cache = cache.get(key);
  }
  const key = keys[keys.length - 1] ?? $traitImpl;
  if (!cache.has(key)) cache.set(key, make());
  return cache.get(key);
}

var $wrapConsume, $wrapTake, $wrapReset, $loudDefault;

function eat(c, CConsume, dropC) {
  let c$live = true;
  try {
    c$live = false;
    return CConsume.consume(c);
  } finally {
    if (c$live) {
      dropC?.(c);
    }
  }
}

function taken(c, CTake, dropC) {
  let c$live = true;
  try {
    c$live = false;
    return CTake.take(c);
  } finally {
    if (c$live) {
      dropC?.(c);
    }
  }
}

function main() {
  console.log(
    `${eat(
      [["through the dictionary"]],
      wrapConsume({ clone: (value) => value }, loudDrop_drop),
      (wrap) => {
        loudDrop_drop(wrap[0]);
      },
    )}`,
  );
  console.log(
    `${wrapConsume_consume([["called directly"]], { clone: (value) => value }, loudDrop_drop)}`,
  );
  console.log(`${eat([5], wrapConsume({ clone: (value) => value }))}`);
  console.log(
    `${taken([7], wrapTake())} ${taken([["taken"]], wrapTake(loudDrop_drop), (wrap$1) => {
      loudDrop_drop(wrap$1[0]);
    })}`,
  );
  console.log(`${taken([8], wrapTake())}`);
  let wrapped = [["replaced"]];
  try {
    wrapReset_reset(wrapped, loudDefault(), loudDrop_drop);
    console.log("reset");
  } finally {
    loudDrop_drop(wrapped[0]);
  }
}

export function entry() {
  main();
}

function wrapConsume_consume(wrap, TClone, dropT) {
  try {
    return 1;
  } finally {
    dropT?.(wrap[0]);
  }
}

function wrapTake_take(wrap, dropT) {
  try {
    return 2;
  } finally {
    dropT?.(wrap[0]);
  }
}

function wrapReset_reset(wrap, TDefault, dropT) {
  const next = TDefault.default();
  dropT?.(wrap[0]);
  wrap[0] = next;
}

function loudDefault_default() {
  return ["made by default"];
}

function loudDrop_drop(loud) {
  console.log(`drop ${loud[0]}`);
}

function wrapConsume(TClone, dropT) {
  if ($wrapConsume === undefined) {
    $wrapConsume = new WeakMap();
  }
  return $traitImpl($wrapConsume, [TClone, dropT], () => ({
    consume: (arg0) => wrapConsume_consume(arg0, TClone, dropT),
  }));
}

function wrapTake(dropT) {
  if ($wrapTake === undefined) {
    $wrapTake = new WeakMap();
  }
  return $traitImpl($wrapTake, [dropT], () => ({ take: (arg0) => wrapTake_take(arg0, dropT) }));
}

function wrapReset(TDefault, dropT) {
  if ($wrapReset === undefined) {
    $wrapReset = new WeakMap();
  }
  return $traitImpl($wrapReset, [TDefault, dropT], () => ({
    reset: (arg0) => wrapReset_reset(arg0, TDefault, dropT),
  }));
}

export function loudDefault() {
  if ($loudDefault === undefined) {
    $loudDefault = { default: loudDefault_default };
  }
  return $loudDefault;
}
//# sourceMappingURL=case.js.map
