// Generated by rust-js from test/corpus/empty_pattern.rs. Do not edit.

import { $debugStr, $replace, $split } from "@rust-js/runtime";

function show(text, pattern) {
  console.log(
    `${$debugStr($replace(text, pattern, "-"))} [${$split(text, pattern)
      .slice()
      .map((item) => $debugStr(item))
      .join(", ")}]`,
  );
}

function main() {
  for (const text of ["🦀x", "ab", "", "é"]) {
    show(text, "");
  }
  show("a,b", ",");
  console.log(`${$replace("x🦀y", "", "|")}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
