// Generated by rust-js from test/corpus/evidence_paths.rs. Do not edit.

import { $debugStr, $displayF64, $someValue, $traitImpl, $unwrap } from "@rust-js/runtime";

var $smallInt, $u8NonZero, $i32Source, $i32ProduceU32, $celsiusDisplay, $optionGetterT, $iDigits;

function check(i, j, IInt, ITNonZero) {
  return IInt.value(i) > 0 && ITNonZero.non_zero(j);
}

function produced(t, TSource) {
  return TSource.Produce().produce(t);
}

function shout(x, TToString) {
  return TToString.to_string(x).toUpperCase();
}

function main() {
  console.log(
    `${check([3], 1, smallInt(), u8NonZero())} ${check([3], 0, smallInt(), u8NonZero())}`,
  );
  console.log(`${produced(21, i32Source())}`);
  console.log(
    `${shout(12, { to_string: String })} ${shout("abc", { to_string: (value) => value })} ${shout([21.5], { to_string: celsiusDisplay_fmt })}`,
  );
  const arg = optionGetterT({ clone: (value) => value }).twice(4);
  const arg$1 = optionGetterT({ clone: (value) => value }).twice("hi");
  console.log(`(${arg[0]}, ${arg[1]}) (${$debugStr(arg$1[0])}, ${$debugStr(arg$1[1])})`);
  console.log(`${iDigits().digit_sum([1, 2, 3])}`);
}

export function entry() {
  main();
}

function smallInt_value(small) {
  return small[0];
}

function u8NonZero_non_zero(self) {
  return self !== 0;
}

function i32ProduceU32_produce(self) {
  return Math.imul(self >>> 0, 2) >>> 0;
}

function celsiusDisplay_fmt(celsius) {
  return `${$displayF64(celsius[0])}°C`;
}

function optionGetterT_get(option, TClone) {
  return TClone.clone($someValue($unwrap(option)));
}

function iDigits_digit_iter(self) {
  return self;
}

function smallInt() {
  if ($smallInt === undefined) {
    $smallInt = { value: smallInt_value };
  }
  return $smallInt;
}

function u8NonZero() {
  if ($u8NonZero === undefined) {
    $u8NonZero = { non_zero: u8NonZero_non_zero };
  }
  return $u8NonZero;
}

function i32Source() {
  if ($i32Source === undefined) {
    $i32Source = { Produce: () => i32ProduceU32() };
  }
  return $i32Source;
}

function i32ProduceU32() {
  if ($i32ProduceU32 === undefined) {
    $i32ProduceU32 = { produce: i32ProduceU32_produce };
  }
  return $i32ProduceU32;
}

export function celsiusDisplay() {
  if ($celsiusDisplay === undefined) {
    $celsiusDisplay = { fmt: celsiusDisplay_fmt };
  }
  return $celsiusDisplay;
}

function optionGetterT(TClone) {
  if ($optionGetterT === undefined) {
    $optionGetterT = new WeakMap();
  }
  return $traitImpl($optionGetterT, [TClone], () => ({
    get: (arg0) => optionGetterT_get(arg0, TClone),
    twice: (self) => {
      const x = optionGetterT_get(self, { clone: (value) => value });
      return [x, x];
    },
  }));
}

function iDigits() {
  if ($iDigits === undefined) {
    $iDigits = {
      digit_iter: iDigits_digit_iter,
      digit_sum: (self) =>
        iDigits_digit_iter(self)
          .map((d) => d)
          .reduce((s, d) => (s + d) >>> 0, 0),
    };
  }
  return $iDigits;
}
//# sourceMappingURL=case.js.map
