// Generated by rust-js from test/corpus/formatter_asked.rs. Do not edit.

var $wDisplay;

function main() {
  console.log(`${wDisplay_fmt(undefined)}`);
}

export function entry() {
  main();
}

function wDisplay_fmt(w, options) {
  return `${options?.width == null ? "None" : `Some(${options?.width})`} ${options?.align == null}`;
}

export function wDisplay() {
  if ($wDisplay === undefined) {
    $wDisplay = { fmt: wDisplay_fmt };
  }
  return $wDisplay;
}
//# sourceMappingURL=case.js.map
