// Generated by rust-js from test/corpus/higher_ranked_bound.rs. Do not edit.

function $traitImpl(cache, keys, make) {
  // Each key is a dictionary or a drop, held weakly: a drop made for one call
  // goes when it does. No drop, `undefined`, is keyed by this function.
  for (let i = 0; i < keys.length - 1; i++) {
    const key = keys[i] ?? $traitImpl;
    if (!cache.has(key)) cache.set(key, new WeakMap());
    cache = cache.get(key);
  }
  const key = keys[keys.length - 1] ?? $traitImpl;
  if (!cache.has(key)) cache.set(key, make());
  return cache.get(key);
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

var $tNamed, $tShout;

function loud(value, TShout) {
  return TShout.shout(value);
}

function main() {
  console.log(
    `${loud("quiet", tShout(tNamed({ fmt: (value) => $debugStr(value) })))} ${loud(3, tShout(tNamed({ fmt: (value) => (value == null ? "None" : `Some(${value})`) })))}`,
  );
}

export function entry() {
  main();
}

function tNamed_name(self, TDebug, dropT) {
  return TDebug.fmt(self);
}

function tShout_shout(self, TNamed, dropT) {
  return TNamed.name(self).toUpperCase();
}

function tNamed(TDebug, dropT) {
  if ($tNamed === undefined) {
    $tNamed = new WeakMap();
  }
  return $traitImpl($tNamed, [TDebug, dropT], () => ({
    name: (arg0) => tNamed_name(arg0, TDebug, dropT),
  }));
}

function tShout(TNamed, dropT) {
  if ($tShout === undefined) {
    $tShout = new WeakMap();
  }
  return $traitImpl($tShout, [TNamed, dropT], () => ({
    shout: (arg0) => tShout_shout(arg0, TNamed, dropT),
  }));
}
//# sourceMappingURL=case.js.map
