// Generated by rust-js from test/corpus/higher_ranked_bound.rs. Do not edit.

import { $debugStr, $traitImpl } from "@rust-js/runtime";

var $tNamed, $tShout;

function loud(value, TShout) {
  return TShout.shout(value);
}

function main() {
  console.log(
    `${loud("quiet", tShout(tNamed({ fmt: (value) => $debugStr(value) })))} ${loud(3, tShout(tNamed({ fmt: (value) => (value == null ? "None" : `Some(${value})`) })))}`,
  );
}

export function entry() {
  main();
}

function tNamed_name(self, TDebug, dropT) {
  return TDebug.fmt(self);
}

function tShout_shout(self, TNamed, dropT) {
  return TNamed.name(self).toUpperCase();
}

function tNamed(TDebug, dropT) {
  if ($tNamed === undefined) {
    $tNamed = new WeakMap();
  }
  return $traitImpl($tNamed, [TDebug, dropT], () => ({
    name: (arg0) => tNamed_name(arg0, TDebug, dropT),
  }));
}

function tShout(TNamed, dropT) {
  if ($tShout === undefined) {
    $tShout = new WeakMap();
  }
  return $traitImpl($tShout, [TNamed, dropT], () => ({
    shout: (arg0) => tShout_shout(arg0, TNamed, dropT),
  }));
}
//# sourceMappingURL=case.js.map
