// Generated by rust-js from test/corpus/index_out_of_bounds.rs. Do not edit.

function $index(items, index) {
  if (index < 0 || index >= items.length)
    throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return items[index];
}

function main() {
  const v = [1, 2, 3];
  const i = (v.length + 2) >>> 0;
  console.log(`reading ${i}`);
  console.log(`${$index(v, i)}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
