// Generated by rust-js from test/corpus/lazy_chains.rs. Do not edit.

import { $lazyTakeWhile, $position } from "@rust-js/runtime";

function noisy(tag, x) {
  console.log(`${tag} ${x}`);
  return x;
}

function main() {
  const v = [1, 2, 3, 4];
  const kept = v
    .values()
    .map((x) => noisy("map", Math.imul(x, 2)))
    .filter((x) => noisy("filter", x) > 2)
    .toArray();
  console.log(`[${kept.map((item) => String(item)).join(", ")}]`);
  const first = v
    .values()
    .map((x) => noisy("take", x))
    .take(2)
    .toArray();
  console.log(`[${first.map((item) => String(item)).join(", ")}]`);
  const arg = v
    .values()
    .map((x) => noisy("find", x))
    .find((x) => x > 1);
  console.log(`${arg == null ? "None" : `Some(${arg})`}`);
  console.log(
    `${v
      .values()
      .map((x) => noisy("any", x))
      .some((x) => x === 2)}`,
  );
  const arg$1 = $position(
    v.values().map((x) => noisy("position", x)),
    (x) => x === 3,
  );
  console.log(`${arg$1 == null ? "None" : `Some(${arg$1})`}`);
  const arg$2 = v
    .values()
    .map((x) => {
      if (noisy("find_map", x) > 1) {
        return Math.imul(x, 10);
      } else {
        return undefined;
      }
    })
    .find((item) => item != null);
  console.log(`${arg$2 == null ? "None" : `Some(${arg$2})`}`);
  for (const x of $lazyTakeWhile(
    v.values().map((x) => noisy("loop", x)),
    (x) => x < 3,
  )) {
    console.log(`body ${x}`);
  }
  for (const [i, x$1] of v
    .values()
    .filter((x) => noisy("odd", x) % 2 === 1)
    .map((x, i) => [i, x])) {
    console.log(`${i} ${x$1}`);
  }
  const total = v.map((x) => noisy("sum", x)).reduce((a, b) => (a + b) | 0, 0);
  const inspect = (x) => {
    console.log(`saw ${x}`);
  };
  const count = v
    .map((item) => {
      inspect(item);
      return item;
    })
    .filter((x) => x > 2).length;
  console.log(`${total} ${count}`);
  const doubled = v
    .map((x) => Math.imul(x, 2))
    .filter((x) => x % 4 === 0)
    .slice(0, 1);
  console.log(`[${doubled.map((item) => String(item)).join(", ")}]`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
