// Generated by rust-js from test/corpus/nested_options.rs. Do not edit.

import { $debugStr, $eq, $pop, $some, $someAt, $someValue } from "@rust-js/runtime";

const NOTHING_FOUND = { $someNone: 0 };
const DEEP = { $someNone: 1 };
const FOUND_UNIT = { $someNone: 0 };

function lookup(table, i) {
  return $someAt(table, i);
}

function depth(o) {
  if (o == null) {
    return 0;
  } else if (o != null && $someValue(o) == null) {
    return 1;
  } else if (o != null && $someValue(o) != null && $someValue($someValue(o)) == null) {
    return 2;
  } else {
    const n = $someValue($someValue(o));
    return (3 + n) & 255;
  }
}

function main() {
  const table = [1, undefined];
  for (let i = 0; i < 3; i++) {
    const arg = lookup(table, i);
    console.log(
      `${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(arg)}`,
    );
  }
  const found = table.length > 1 ? $some(undefined) : undefined;
  console.log(`${found == null ? "None" : "Some(())"} ${found != null}`);
  console.log(
    `${depth(undefined)} ${depth($some(undefined))} ${depth($some($some(undefined)))} ${depth(4)}`,
  );
  const units = [$some(undefined), undefined];
  const firsts = [$someAt(units, 0), $someAt(units, 1), $someAt(units, 5)];
  console.log(
    `[${firsts.map((item) => ((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${unitDebug_fmt($someValue(value))})`))($someValue(value))})`))(item)).join(", ")}]`,
  );
  const inner = lookup(table, 0);
  const doubled =
    inner != null
      ? $some($someValue(inner) != null ? Math.imul($someValue(inner), 2) : undefined)
      : undefined;
  const arg$1 = $someValue(lookup(table, 1) ?? 9);
  console.log(
    `${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(doubled)} ${arg$1 == null ? "None" : `Some(${arg$1})`} ${$eq(lookup(table, 1), $some(undefined))}`,
  );
  const value = lookup(table, 0);
  if (value != null && $someValue(value) != null) {
    const n = $someValue(value);
    console.log(`got ${n}`);
  }
  const e = { name: "a", note: $some(undefined) };
  let f = { ...e };
  f.note = "n";
  console.log(`${entryDebug_fmt(e)} ${entryDebug_fmt(f)} ${$eq(e, f)}`);
  const value$1 = () => {};
  const tmp = table.length > 1 ? $some(value$1()) : undefined;
  const option = 1;
  const map = () => {};
  const arg$2 = option != null ? $some(map(option)) : undefined;
  const arg$3 = $some(undefined);
  console.log(
    `${tmp == null ? "None" : "Some(())"} ${arg$2 == null ? "None" : "Some(())"} ${arg$3 == null ? "None" : "Some(())"}`,
  );
  let grid = [1, 2];
  const kept = grid == null || grid.$someNone !== undefined ? grid : grid.slice();
  if (grid != null && $someValue(grid) != null) {
    const cells = $someValue(grid);
    cells[0] = 9;
  }
  const arg$4 = kept == null || kept.$someNone !== undefined ? kept : kept.slice();
  const arg$5 = grid == null || grid.$someNone !== undefined ? grid : grid.slice();
  console.log(
    `${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some([${value.map((item) => String(item)).join(", ")}])`))($someValue(value))})`))(arg$4)} ${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some([${value.map((item) => String(item)).join(", ")}])`))($someValue(value))})`))(arg$5)}`,
  );
  console.log(
    `${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${value})`))($someValue(value))})`))(NOTHING_FOUND)} ${depth(DEEP)} ${FOUND_UNIT == null ? "None" : `Some(${unitDebug_fmt($someValue(FOUND_UNIT))})`} ${$eq(NOTHING_FOUND, lookup(table, 1))}`,
  );
  let stack = [$some(undefined), undefined];
  while (true) {
    const top = $pop(stack);
    if (top != null) {
      const top$1 = $someValue(top);
      console.log(`${top$1 == null ? "None" : `Some(${unitDebug_fmt($someValue(top$1))})`}`);
    } else {
      break;
    }
  }
}

export function entry() {
  main();
}

function unitDebug_fmt(unit) {
  return "Unit";
}

function entryDebug_fmt(entry$1) {
  return `Entry { name: ${$debugStr(entry$1.name)}, note: ${((value) => (value == null ? "None" : `Some(${((value) => (value == null ? "None" : `Some(${$debugStr(value)})`))($someValue(value))})`))(entry$1.note)} }`;
}
//# sourceMappingURL=case.js.map
