// Generated by rust-js from test/corpus/options_handed_on.rs. Do not edit.

import {
  $debugF64,
  $debugStr,
  $displayF64,
  $formatFloat,
  $formatted,
  $pretty,
} from "@rust-js/runtime";

var $metersDisplay, $nameDisplay, $pairDebug;

function show(value, TDisplay) {
  return `[${TDisplay.fmt(value, { width: 6, align: ">" })}]`;
}

function debug(value, TDebug) {
  return `[${TDebug.fmt(value, { width: 4, align: "<" })}]`;
}

function main() {
  console.log(
    `[${metersDisplay_fmt([1.5], {
      width: 8,
      precision: 2,
    })}] [${metersDisplay_fmt([2], { plus: true })}] [${metersDisplay_fmt([-0.25], {
      width: 9,
      precision: 1,
      align: "<",
    })}]`,
  );
  console.log(
    `${show(42, { fmt: (value, options) => $formatted(String(value), options, true) })} ${show("ab", { fmt: $formatted })} ${show([3], metersDisplay())} ${show(["xyz"], nameDisplay())}`,
  );
  const d = {
    value: 7,
    impl: { fmt: (value, options) => $formatted(String(value), options, true) },
  };
  console.log(
    `[${d.impl.fmt(d.value, { width: 4, align: "<" })}] [${nameDisplay_fmt(["rust"], {
      width: 7,
      align: "^",
    })}] [${nameDisplay_fmt(["rust"], { precision: 2 })}]`,
  );
  const arg = { x: -3, y: 0.25 };
  console.log(
    `[${pointDebug_fmt(
      { x: 1, y: 2 },
      { width: 5 },
    )}] [${arg == null ? "None" : `Some(${pointDebug_fmt(arg, { precision: 1 })})`}]`,
  );
  console.log(`${pointDebug_fmt({ x: 4, y: 5.5 }, { alternate: true, width: 5 })}`);
  console.log(`${metersDisplay_fmt([0.5])}`);
  console.log(
    `[${pairDebug_fmt([7, "a"], { width: 4 })}] ${debug(1, { fmt: (value, options) => $formatted(String(value), options, true) })} ${debug([2, "b"], pairDebug())}`,
  );
  const b = { value: [-2.5], impl: metersDisplay() };
  console.log(
    `[${b.impl.fmt(b.value, {
      width: 8,
      precision: 1,
      plus: true,
      zero: true,
    })}] [${metersDisplay_fmt([1], {
      width: 12,
      fill: "*",
      align: "^",
    })}] [${String(true).padStart(5)}]`,
  );
}

export function entry() {
  main();
}

function metersDisplay_fmt(meters, options) {
  let f = $formatFloat(meters[0], options, $displayF64);
  f += " m";
  return f;
}

function nameDisplay_fmt(name, options) {
  return $formatted(name[0], options);
}

function pointDebug_fmt(point, options) {
  const shown = $formatted(String(point.x), options, true);
  const shown$1 = $formatFloat(point.y, options, $debugF64);
  return options?.alternate
    ? $pretty("Point {", [`x: ${shown}`, `y: ${shown$1}`], "}")
    : `Point { x: ${shown}, y: ${shown$1} }`;
}

function pairDebug_fmt(pair, options) {
  return options?.alternate
    ? $pretty("Pair(", [$formatted(String(pair[0]), options, true), $debugStr(pair[1])], ")")
    : `Pair(${$formatted(String(pair[0]), options, true)}, ${$debugStr(pair[1])})`;
}

export function metersDisplay() {
  if ($metersDisplay === undefined) {
    $metersDisplay = { fmt: metersDisplay_fmt };
  }
  return $metersDisplay;
}

export function nameDisplay() {
  if ($nameDisplay === undefined) {
    $nameDisplay = { fmt: nameDisplay_fmt };
  }
  return $nameDisplay;
}

export function pairDebug() {
  if ($pairDebug === undefined) {
    $pairDebug = { fmt: pairDebug_fmt };
  }
  return $pairDebug;
}
//# sourceMappingURL=case.js.map
