// Generated by rust-js from test/corpus/range_searches.rs. Do not edit.

function $bigRange(start, end) {
  const items = [];
  for (let i = start; i < end; i++) items.push(i);
  return items;
}

function $range(start, end) {
  return Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);
}

function $position(items, found) {
  const i = items.findIndex(found);
  return i < 0 ? undefined : i;
}

function main() {
  const n = 5;
  console.log(`${$range(0, n).every((i) => i < 5)}`);
  console.log(`${$range(0, n).some((i) => i === 3)}`);
  const arg = $range(1, n + 1).find((i) => i % 2 === 0);
  console.log(`${arg == null ? "None" : `Some(${arg})`}`);
  const arg$1 = $position($range(0, n), (i) => Math.imul(i, i) > 5);
  console.log(`${arg$1 == null ? "None" : `Some(${arg$1})`}`);
  console.log(`${$bigRange(0n, 3n).every((i) => i < 3n)}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
