// Generated by rust-js from test/corpus/replacement_character.rs. Do not edit.

function main() {
  console.log("�");
  console.error("�");
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
