// Generated by rust-js from test/corpus/returned_references.rs. Do not edit.

function $unwrap(value, message = "called `Option::unwrap()` on a `None` value") {
  if (value == null) {
    throw new Error(message);
  }
  return value;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

function pick(items, log) {
  log.push("pick");
  return $unwrap(items.at(-1));
}

function value(log) {
  log.push("value");
  return 5;
}

function main() {
  let items = [
    { name: "a", count: 1 },
    { name: "b", count: 2 },
  ];
  $unwrap(items.at(-1)).count = 9;
  const item = $unwrap(items[1]);
  item.count = (item.count + 1) >>> 0;
  let log = [];
  const value$1 = value(log);
  pick(items, log).count = value$1;
  console.log(
    `[${items.map((item) => itemDebug_fmt(item)).join(", ")}] [${log.map((item) => $debugStr(item)).join(", ")}]`,
  );
  let stock = new Map();
  stock.set("pen", { name: "pen", count: 3 });
  const item$1 = $unwrap(stock.get("pen"));
  item$1.count = Math.imul(item$1.count, 4) >>> 0;
  console.log(`${$unwrap(stock.get("pen"), "key not found").count}`);
}

export function entry() {
  main();
}

function itemDebug_fmt(item) {
  return `Item { name: ${$debugStr(item.name)}, count: ${item.count} }`;
}
//# sourceMappingURL=case.js.map
