// Generated by rust-js from test/corpus/size_of.rs. Do not edit.

function main() {
  console.log("1 4 8 8");
  console.log("4 4 8");
  console.log("10 1 8");
  const w = { a: 1n, b: 2 };
  console.log("16 2");
  const numbers = [1, 2, 3];
  console.log("12 2");
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
