// Generated by rust-js from test/corpus/statics.rs. Do not edit.

import { NAME, SIDES } from "./shapes.js";

// Shortest round-trip decimal, using exact rational arithmetic.
// Rust Display uses decimal notation, including for very small/large values.
// Not JS's `String(x)`, though its digits are also the shortest: when two are
// equally close, JS takes the even one (1888570120608320.2), and Rust the
// larger (1888570120608320.3).
function $displayF64(value) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const x = Math.abs(value);
  if (x === 0) return sign + "0";

  const bitsView = new DataView(new ArrayBuffer(8));
  bitsView.setFloat64(0, x);
  const bits = bitsView.getBigUint64(0);
  const exponentBits = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponentBits === 0 ? fraction : fraction + (1n << 52n);
  const binaryExponent = exponentBits === 0 ? -1074 : exponentBits - 1023 - 52;
  const numerator = binaryExponent >= 0 ? significand << BigInt(binaryExponent) : significand;
  const denominator = binaryExponent < 0 ? 1n << BigInt(-binaryExponent) : 1n;

  // The floating-point logarithm is only an estimate; correct it exactly.
  let exponent = Math.floor(Math.log10(x));
  const atLeastPowerOfTen = (e) =>
    e >= 0
      ? numerator >= denominator * 10n ** BigInt(e)
      : numerator * 10n ** BigInt(-e) >= denominator;
  while (!atLeastPowerOfTen(exponent)) exponent--;
  while (atLeastPowerOfTen(exponent + 1)) exponent++;

  for (let precision = 1; precision <= 17; precision++) {
    const power = exponent - precision + 1;
    const n = power < 0 ? numerator * 10n ** BigInt(-power) : numerator;
    const d = power > 0 ? denominator * 10n ** BigInt(power) : denominator;
    const floor = n / d;
    const rounded = floor + (2n * (n % d) >= d ? 1n : 0n);
    // The rounding interval can be asymmetric at a binary power boundary.
    let best;
    let bestDistance;
    for (const candidate of [rounded, rounded - 1n, rounded + 1n]) {
      if (candidate > 0n && Number(`${candidate}e${power}`) === x) {
        const delta = candidate * d - n;
        const distance = delta < 0n ? -delta : delta;
        if (
          best === undefined ||
          distance < bestDistance ||
          (distance === bestDistance && candidate > best)
        ) {
          best = candidate;
          bestDistance = distance;
        }
      }
    }
    if (best !== undefined) {
      let digits = best.toString();
      let decimalPower = power;
      while (digits.endsWith("0")) {
        digits = digits.slice(0, -1);
        decimalPower++;
      }
      const point = digits.length + decimalPower;
      const body =
        point <= 0
          ? "0." + "0".repeat(-point) + digits
          : point >= digits.length
            ? digits + "0".repeat(point - digits.length)
            : digits.slice(0, point) + "." + digits.slice(point);
      return sign + body;
    }
  }
  throw new Error("No f64 round-trip decimal found");
}

const $printed = ["", ""];
function $print(text) {
  $write(text, 0);
}
function $eprint(text) {
  $write(text, 1);
}
function $write(text, error) {
  const stream = globalThis.process?.[error ? "stderr" : "stdout"];
  if (stream?.write) {
    stream.write(text);
    return;
  }
  const log = error ? console.error : console.log;
  const lines = ($printed[error] + text).split("\n");
  const rest = lines.pop();
  for (const line of lines) log(line);
  // What's left unended is written when this task ends, so none is lost.
  if (rest !== "" && $printed[error] === "") {
    queueMicrotask(() => {
      if ($printed[error] !== "") log($printed[error]);
      $printed[error] = "";
    });
  }
  $printed[error] = rest;
}

function $debugF64(value) {
  const size = Math.abs(value);
  if (Number.isFinite(value) && size !== 0 && (size < 1e-4 || size >= 1e16)) {
    return value.toExponential().replace("e+", "e");
  }
  const text = $displayF64(value);
  return Number.isFinite(value) && !text.includes(".") ? text + ".0" : text;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

const ORIGIN = { x: 0, y: 0 };

const CORNER = { x: 2, y: -3 };

const LIMIT = 1099511627776n;
const GREETING = "hi";
const NAMES = ["ann", "bo", "cy"];
const PRIMES = [2, 3, 5, 7];
const EMPTY = [];
const LEVELS = ["Low", { TAG: "High", _0: 9 }];
const MAYBE = "z";
const PAIR = [true, 2.5];
const BOXED = { x: 3, y: 4 };

const COMPUTED = -42;
const WORDS = ["one", "two"];

function moved(dx) {
  let p = { ...ORIGIN };
  p.x = (p.x + dx) | 0;
  return p;
}

function counted() {
  return WORDS.length;
}

function main() {
  console.log(
    `${pointDebug_fmt(moved(5))} ${pointDebug_fmt({ ...ORIGIN })} ${pointDebug_fmt(moved(-2))}`,
  );
  console.log(`${LIMIT} ${GREETING} ${NAMES.join(",")}`);
  console.log(
    `[${PRIMES.map((item) => String(item)).join(", ")}] ${PRIMES.reduce((a, b) => (a + b) >>> 0, 0)} [${EMPTY.map((item) => String(item)).join(", ")}]`,
  );
  console.log(
    `[${LEVELS.map((item) => levelDebug_fmt(item)).join(", ")}] ${MAYBE == null ? "None" : `Some(${$debugStr(MAYBE, "'")})`} (${PAIR[0]}, ${$debugF64(PAIR[1])})`,
  );
  console.log(`${(BOXED.x + BOXED.y) | 0} ${COMPUTED} ${counted()}`);
  console.log(
    `${pointDebug_fmt({ ...CORNER })} [${SIDES.map((item) => String(item)).join(", ")}] ${NAME}`,
  );
  for (const name of NAMES) {
    $print(`${name} `);
  }
  console.log("");
}

export function entry() {
  main();
}

function pointDebug_fmt(point) {
  return `Point { x: ${point.x}, y: ${point.y} }`;
}

function levelDebug_fmt(level) {
  if (level === "Low") {
    return "Low";
  } else {
    return `High(${level._0})`;
  }
}
//# sourceMappingURL=case.js.map
