// Generated by rust-js from test/corpus/string_slice_bounds.rs. Do not edit.

import { $strSlice } from "@rust-js/runtime";

function main() {
  const s = "héllo";
  console.log(`${$strSlice(s, 3)}`);
  console.log(`${$strSlice(s, 3, 20)}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
