// Generated by rust-js from test/corpus/unsized_struct_slice.rs. Do not edit.

function check(val) {
  console.log(`${val.a} [${val.inner.map((item) => String(item)).join(", ")}]`);
  return val.inner.length;
}

function main() {
  const foo = { a: 32, inner: [1, 2, 3] };
  console.log(`${check(foo)}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
