// Generated by rust-js from test/corpus/unwrap_none.rs. Do not edit.

function $unwrap(value, message = "called `Option::unwrap()` on a `None` value") {
  if (value == null) {
    throw new Error(message);
  }
  return value;
}

function $position(items, found) {
  const i = items.findIndex(found);
  return i < 0 ? undefined : i;
}

function find(v, x) {
  return $position(v, (y) => y === x);
}

function main() {
  const arg = find([4, 5], 5);
  console.log(`${arg == null ? "None" : `Some(${arg})`}`);
  const at = $unwrap(find([4, 5], 6));
  console.log(`${at}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
