// Generated by rust-js from test/corpus/unwrap_none.rs. Do not edit.

import { $position, $unwrap } from "@rust-js/runtime";

function find(v, x) {
  return $position(v, (y) => y === x);
}

function main() {
  const arg = find([4, 5], 5);
  console.log(`${arg == null ? "None" : `Some(${arg})`}`);
  const at = $unwrap(find([4, 5], 6));
  console.log(`${at}`);
}

export function entry() {
  main();
}
//# sourceMappingURL=case.js.map
