// The playground itself (ADRs 0032, 0044), as GitHub Pages serves it: its
// static build, in Chromium. It needs rust-js.wasm (`bun run wasm`), the
// compiler it runs; without one, this is skipped.

import { expect, test } from "bun:test";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { chromium } from "@playwright/test";
import { expectSnapshot, root, run } from "./support";

const wasm = join(root, "wasm/target/wasm32-wasip1/release/rust-js.wasm");

// The site is compiled by rust-js.wasm, and the snapshot by the native
// compiler (test/snapshots.test.ts): the same source should give the same JS.
// When it doesn't, the wasm was built from older code than the compiler's.
test.skipIf(!existsSync(wasm))("rust-js.wasm compiles the playground as the native compiler does", () => {
  run(["bun", "wasm/web/compile-rust.ts"]);
  expectSnapshot(join(root, "wasm/web/rust"), join(root, "test/snapshots/playground"), {
    // The WASI compiler sees the crate at /wasm/web/rust.
    normalize: (text) => text.replace("// Generated by rust-js from /wasm/web/rust/", "// Generated by rust-js from wasm/web/rust/"),
    hint: "rust-js.wasm writes other JS than test/snapshots/playground: if test/snapshots.test.ts passes, the wasm is out of date; rebuild it with `bun run wasm`",
    bless: false,
  });
}, 300_000);

test.skipIf(!existsSync(wasm))("the playground loads, compiles, runs tests and shows errors, as React components", async () => {
  run(["bun", "run", "site"]);
  const server = Bun.spawn(["bun", "wasm/web/preview.ts"], { cwd: root, env: { ...process.env, PORT: "0" }, stdout: "pipe" });
  const browser = await chromium.launch({ headless: true });
  try {
    // preview.ts prints where it serves the site.
    const reader = server.stdout.getReader();
    let printed = "";
    while (!printed.includes("\n")) printed += new TextDecoder().decode((await reader.read()).value);
    const url = printed.match(/https?:\/\/\S+/)![0];
    const page = await browser.newPage();
    const errors: string[] = [];
    page.on("pageerror", (e) => errors.push(e.message));
    await page.goto(url);
    // React rendered the page, and the old code found its parts in it.
    await page.locator("#app > h1", { hasText: "rust-js playground" }).waitFor();
    const status = page.locator("#status");
    await status.filter({ hasText: "Ready." }).waitFor({ timeout: 60_000 });
    expect(await page.locator(".cm-editor").count()).toBe(2);
    await page.locator("#test").click();
    await status.filter({ hasText: "Tests: 5 passed, 0 failed." }).waitFor({ timeout: 60_000 });
    await page.locator("#example").selectOption("modules");
    await page.locator("#source-files li", { hasText: "stats.rs" }).waitFor();
    await page.locator("#compile").click();
    await status.filter({ hasText: "Compiled: 5 JS files." }).waitFor({ timeout: 60_000 });
    // Another output file, from the JavaScript side's FileTree.
    await page.locator("#output-files button", { hasText: "stats.js" }).click();
    await page.locator("#output-files button[aria-current=true]", { hasText: "stats.js" }).waitFor();
    await page.locator(".cm-content[aria-label='Generated JavaScript']", { hasText: "from /in/stats.rs" }).waitFor();
    // An unsaved edit, compiled with ⌘/Ctrl-Enter: rustc's errors, as text.
    await page.locator(".cm-content[aria-label='Rust source']").click();
    await page.keyboard.press("ControlOrMeta+a");
    await page.keyboard.type('pub fn main() { let x: i32 = "no"; }');
    await page.keyboard.press("ControlOrMeta+Enter");
    await status.filter({ hasText: "Failed" }).waitFor({ timeout: 60_000 });
    await page.locator(".cm-content[aria-label='Generated JavaScript']", { hasText: "mismatched types" }).waitFor();
    expect(await page.locator("#output-files li").textContent()).toBe("(none)");
    expect(errors).toEqual([]);
  } finally {
    await browser.close();
    server.kill();
  }
}, 180_000);
