// A crate's settings for the JS rust-js writes (ADR 0117): the options of
// the formatter it has, and its hooks, transforms, which change a module's
// text, the map moved to it, and checks, which read what was written, what
// they say of the JS said of the Rust.

import { beforeAll, expect, test } from "bun:test";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { runSync } from "./child";
import { decodeMappings, lookup } from "./sourcemap";
import { buildCompiler, buildReact, compiler, fixture, root, target } from "./support";

beforeAll(buildCompiler);

const rust = `pub fn greet(name: &str) -> String {
    let greeting = format!("Hello, {name}!");
    greeting
}
`;

/** `source`, of a crate whose Cargo.toml has `settings`, compiled with `flags`. */
function build(settings: string, flags: string[] = [], source = rust) {
  const dir = fixture("settings");
  mkdirSync(join(dir, "src"));
  writeFileSync(join(dir, "src", "lib.rs"), source);
  writeFileSync(join(dir, "Cargo.toml"), `[package]\nname = "set"\nversion = "0.0.0"\nedition = "2024"\n\n${settings}\n`);
  const p = runSync([compiler, join(dir, "src", "lib.rs"), "-o", join(dir, "out", "lib.js"), ...flags], dir, 60_000);
  const js = join(dir, "out", "lib.js");
  return { ...p, dir, js: existsSync(js) ? readFileSync(js, "utf8") : "", map: existsSync(`${js}.map`) ? readFileSync(`${js}.map`, "utf8") : "" };
}

/** A crate whose Cargo.toml has `hooks`, compiled with `flags`. */
const compile = (hooks: string, flags: string[] = []) => build(`[package.metadata.rust-js.hooks]\n${hooks}`, flags);

/** Where `word`, on the JS line that has it, maps to in the Rust: 1-based. */
function rustOf(js: string, map: string, word: string) {
  const line = js.split("\n").findIndex((text) => text.includes(word));
  const found = lookup(decodeMappings(JSON.parse(map).mappings), line, js.split("\n")[line].indexOf(word));
  return found && [found.srcLine + 1, found.srcCol + 1];
}

test("a transform's text is written, and the map moved to it", () => {
  const out = compile(`transform = [["sh", "-c", "echo \\"// formatted: $1\\"; echo; cat", "sh", "{file}"]]`);
  expect(out.stderr).toBe("");
  expect(out.code).toBe(0);
  expect(out.js).toStartWith(`// formatted: ${join(out.dir, "out", "lib.js")}\n\n// Generated by rust-js`);
  expect(out.js).toEndWith("//# sourceMappingURL=lib.js.map\n");
  // Where the unformatted JS's statement came from: the Rust's `let`.
  const plain = compile("");
  expect(rustOf(plain.js, plain.map, "greeting =")).toEqual([2, 5]);
  expect(rustOf(out.js, out.map, "greeting =")).toEqual([2, 5]);
});

test("a transform that changes the program, or fails, is refused, and its input kept", () => {
  const plain = compile("");
  for (const transform of [`["sh", "-c", "grep -v return"]`, `["sh", "-c", "cat; exit 3"]`]) {
    const out = compile(`transform = [${transform}, ["sh", "-c", "echo '// second'; cat"]]`);
    expect(out.code).toBe(0);
    expect(out.stderr).toContain("warning: rust-js: the transform `sh` ");
    // The next transform is run on what's kept.
    expect(out.js.replace(out.dir, "")).toBe(`// second\n${plain.js.replace(plain.dir, "")}`);
  }
});

test("what a check says of the JS is said of the Rust, and the rest as it is", () => {
  const out = compile(
    `check = [{ run = ["sh", "-c", "echo \\"$1:4:9: never reassigned\\"; echo \\"$1(4,9): error TS1: a type\\"; echo 'a line of its own'", "sh", "{files}"], fail = "never" }]`,
  );
  expect(out.code).toBe(0);
  expect(out.stderr).toContain("src/lib.rs:2:5: [sh] never reassigned\n");
  expect(out.stderr).toContain("src/lib.rs:2:5: [sh] error TS1: a type\n");
  expect(out.stderr).toContain("a line of its own\n");
});

test("a check that fails fails the build, if it says so", () => {
  const check = (fail: string) => compile(`check = [{ run = ["sh", "-c", "echo \\"$1:4:9: bad\\"; exit 1", "sh", "{files}"], fail = "${fail}" }]`);
  const failing = check("build");
  expect(failing.code).not.toBe(0);
  expect(failing.stderr).toContain("src/lib.rs:2:5: [sh] bad");
  expect(check("never").code).toBe(0);
});

test("a check run only in a build isn't run for a save", () => {
  const hooks = `check = [{ run = ["sh", "-c", "touch ran"], when = "build" }]`;
  const saved = compile(hooks, ["--hooks", "save"]);
  expect(saved.code).toBe(0);
  expect(existsSync(join(saved.dir, "ran"))).toBe(false);
  const built = compile(hooks);
  expect(existsSync(join(built.dir, "ran"))).toBe(true);
});

const long = `pub fn total(first_amount: f64, second_amount: f64, third_amount: f64, fourth_amount: f64, fifth_amount: f64, sixth_amount: f64) -> f64 {
    first_amount + second_amount + third_amount + fourth_amount + fifth_amount + sixth_amount
}

pub fn hi() -> &'static str {
    "hi"
}
`;

test("the formatter's options are oxfmt's, and the map follows them", () => {
  const signature = "export function total(firstAmount, secondAmount, thirdAmount, fourthAmount, fifthAmount, sixthAmount) {";
  // 103 columns: past oxfmt's default, 100, and within 120.
  expect(build("", [], long).js).not.toContain(signature);
  const wide = build("[package.metadata.rust-js.format]\nprintWidth = 120", [], long);
  expect(wide.stderr).toBe("");
  expect(wide.js).toContain(`\n${signature}\n`);
  const styled = build("[package.metadata.rust-js.format]\ntabWidth = 4\nsingleQuote = true\nsemi = false", [], `${rust}\n${long}`);
  expect(styled.js).toContain("\n    const greeting = `Hello, ${name}!`\n");
  expect(styled.js).toContain("\n    return 'hi'\n");
  expect(rustOf(styled.js, styled.map, "greeting =")).toEqual([2, 5]);
});

test("an option the formatter hasn't, or a value it can't take, fails the build", () => {
  for (const [option, error] of [
    ["printWidht = 120", "printWidht"],
    ["printWidth = 0", "printWidth"],
    ['trailingComma = "most"', "trailingComma"],
  ]) {
    const out = build(`[package.metadata.rust-js.format]\n${option}`);
    expect([option, out.code]).toEqual([option, 1]);
    expect(out.stderr).toContain("Cargo.toml");
    expect(out.stderr).toContain(error);
  }
});

// A formatter a team has, Prettier, on JSX, which it lays out otherwise than
// oxfmt, at its own 80 columns, given lines of 200: it breaks JSX's text,
// with a `{" "}` oxfmt's lines hadn't, and it's the same program, so it's
// kept, and the map finds the Rust each probe did before it.
test("Prettier's layout of the app's JSX is kept, and the map still finds the Rust", () => {
  buildReact();
  const app = (settings: string) => {
    const dir = fixture("prettier");
    mkdirSync(join(dir, "src"));
    copyFileSync(join(root, "examples", "vite-react", "src", "App.rs"), join(dir, "src", "App.rs"));
    writeFileSync(join(dir, "Cargo.toml"), `[package]\nname = "app"\nversion = "0.0.0"\nedition = "2024"\n\n${settings}\n`);
    const js = join(dir, "src", "App.jsx");
    const p = runSync(
      [compiler, join(dir, "src", "App.rs"), "-o", js, "--", "-L", target, ...["js", "webapi", "react"].flatMap((name) => ["--extern", `${name}=${join(target, `lib${name}.rmeta`)}`])],
      dir,
      120_000,
    );
    expect(p.code).toBe(0);
    return { stderr: p.stderr, js: readFileSync(js, "utf8"), map: readFileSync(`${js}.map`, "utf8") };
  };
  const wide = "[package.metadata.rust-js.format]\nprintWidth = 200";
  const plain = app(wide);
  expect(plain.js).not.toContain('{" "}');
  const pretty = app(`${wide}\n\n[package.metadata.rust-js.hooks]\ntransform = [["${join(root, "node_modules", ".bin", "prettier")}", "--stdin-filepath", "{file}"]]`);
  expect(pretty.stderr).toBe("");
  expect(pretty.js).toContain('{" "}');
  for (const word of ["useState(0)", "setCount((count)", "font-bold text-emerald-500", "Get started", "heroImg}"]) {
    expect([word, rustOf(pretty.js, pretty.map, word)]).toEqual([word, rustOf(plain.js, plain.map, word)]);
  }
}, 300_000);
