// Generated by rust-js from examples/lexer.rs. Do not edit.

function $unwrap(value, message = "called `Option::unwrap()` on a `None` value") {
  if (value == null) {
    throw new Error(message);
  }
  return value;
}

function $toDigit(c, radix) {
  const digit = parseInt(c, 36);
  return digit < radix ? digit : undefined;
}

function $iter(items) {
  return {
    items,
    at: 0,
    next() {
      return this.at < this.items.length
        ? { value: this.items[this.at++], done: false }
        : { value: undefined, done: true };
    },
    [Symbol.iterator]() {
      return this;
    },
  };
}

function $next(it) {
  const step = it.next();
  return step.done ? undefined : step.value;
}

function $peek(it) {
  return it.items[it.at];
}

function $nextIf(it, f) {
  return it.at < it.items.length && f(it.items[it.at]) ? it.items[it.at++] : undefined;
}

function $rest(it) {
  const rest = it.items.slice(it.at);
  it.at = it.items.length;
  return rest;
}

function $restStr(it) {
  return it.items.slice(it.at).join("");
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

export const Lexer = {
  new(src) {
    return { chars: $iter(Array.from(src)), line: 1 };
  },
  number(lexer, first) {
    let n = $unwrap($toDigit(first, 10));
    while (true) {
      const value = $peek(lexer.chars);
      if (value != null) {
        const match = $toDigit(value, 10);
        if (match != null) {
          n = ((Math.imul(n, 10) >>> 0) + match) >>> 0;
          $next(lexer.chars);
        } else {
          break;
        }
      } else {
        break;
      }
    }
    return n;
  },
  word(lexer, first) {
    let w = first;
    while (true) {
      const c = $nextIf(lexer.chars, (c) => /^[\p{Alphabetic}\p{N}]$/u.test(c) || c === "_");
      if (c != null) {
        w += c;
      } else {
        break;
      }
    }
    return w;
  },
  tokens(lexer) {
    let out = [];
    while (true) {
      const c = $next(lexer.chars);
      if (c != null) {
        if (c === "\n") {
          lexer.line = (lexer.line + 1) >>> 0;
        } else if (!/^\p{White_Space}$/u.test(c)) {
          if (c >= "0" && c <= "9") {
            const n = Lexer.number(lexer, c);
            out.push({ TAG: "Num", _0: n });
          } else if ((c >= "a" && c <= "z") || (c >= "A" && c <= "Z") || c === "_") {
            const w = Lexer.word(lexer, c);
            out.push({ TAG: "Ident", _0: w });
          } else if (c === '"') {
            let s = "";
            while (true) {
              const match = $next(lexer.chars);
              if (match === '"') {
                break;
              } else if (match != null) {
                s += match;
              } else {
                return { TAG: "Err", _0: `line ${lexer.line}: unterminated string` };
              }
            }
            out.push({ TAG: "Str", _0: s });
          } else if (c === "/" && $nextIf(lexer.chars, (item) => item === "/") != null) {
            while ($nextIf(lexer.chars, (c) => c !== "\n") != null) {}
          } else {
            out.push({ TAG: "Sym", _0: c });
          }
        }
      } else {
        break;
      }
    }
    return { TAG: "Ok", _0: out };
  },
};

export function pairs(v) {
  let it = $iter(v);
  let out = [];
  while (true) {
    const value = $next(it);
    const value$1 = $next(it);
    if (value != null && value$1 != null) {
      out.push([value, value$1]);
    } else {
      break;
    }
  }
  const rest = $rest(it);
  return [out, rest];
}

export function capitalize(s) {
  let chars = $iter(Array.from(s));
  const match = $next(chars);
  if (match != null) {
    return match.toUpperCase() + $restStr(chars);
  } else {
    return "";
  }
}

export function report() {
  let out = "";
  for (const src of ['let x_1 = 42 + y;\n// note\nprint("hi there") 7', 'a "open', "  "]) {
    const arg = Lexer.tokens(Lexer.new(src));
    out += `${arg.TAG === "Ok" ? `Ok([${arg._0.map((item) => tokDebug_fmt(item)).join(", ")}])` : `Err(${$debugStr(arg._0)})`}\n`;
  }
  const arg$1 = pairs([1, 2, 3, 4, 5]);
  const arg$2 = pairs([]);
  out += `([${arg$1[0].map((item) => `(${item[0]}, ${item[1]})`).join(", ")}], [${arg$1[1].map((item) => String(item)).join(", ")}]) ([${arg$2[0].map((item) => `(${item[0]}, ${item[1]})`).join(", ")}], [${arg$2[1].map((item) => String(item)).join(", ")}])\n`;
  out += `${capitalize("hello")} ${capitalize("ßig")} ${$debugStr(capitalize(""))}\n`;
  let words = $iter("one two three four".split(" "));
  const first = $next(words);
  const rest = $rest(words);
  out += `${first == null ? "None" : `Some(${$debugStr(first)})`} [${rest.map((item) => $debugStr(item)).join(", ")}]\n`;
  return out;
}

function tokDebug_fmt(tok) {
  if (tok.TAG === "Num") {
    return `Num(${tok._0})`;
  } else if (tok.TAG === "Ident") {
    return `Ident(${$debugStr(tok._0)})`;
  } else if (tok.TAG === "Sym") {
    return `Sym(${$debugStr(tok._0, "'")})`;
  } else {
    return `Str(${$debugStr(tok._0)})`;
  }
}
//# sourceMappingURL=lexer.js.map
