// Generated by rust-js from wasm/web/rust/compiler.rs. Do not edit.

import { ConsoleStdout, Directory, File, OpenFile, PreopenDirectory, WASI } from "@bjorn3/browser_wasi_shim";

function $stripSuffix(s, suffix) {
  return s.endsWith(suffix) ? s.slice(0, s.length - suffix.length) : undefined;
}

function $rsplitOnce(s, separator) {
  const i = s.lastIndexOf(separator);
  return i < 0 ? undefined : [s.slice(0, i), s.slice(i + separator.length)];
}

function $try(f) {
  try {
    return { TAG: "Ok", _0: f() };
  } catch (e) {
    return { TAG: "Err", _0: e };
  }
}

export function ms(t) {
  return t.toFixed(0) + " ms";
}

export function mb(n) {
  return (n / 1048576).toFixed(1) + " MB";
}

export async function load(stat) {
  const start = performance.now();
  const module = loadCompiler(start, stat);
  const sysroot = loadSysroot(start, stat);
  const webCrate = loadWebCrate(start, stat);
  const examples = loadExamples();
  const loaded = {
    module: await module,
    sysroot: await sysroot,
    webCrate: await webCrate,
    examples: await examples
  };
  stat("ready after", ms(performance.now() - start));
  return loaded;
}

async function loadCompiler(start, stat) {
  const module = await WebAssembly.compileStreaming(window.fetch("./rust-js.wasm"));
  stat("download + compile rust-js.wasm", ms(performance.now() - start));
  return module;
}

async function loadSysroot(start, stat) {
  const names = await (await window.fetch("./sysroot.json")).json();
  let downloads = [];
  for (const name of names) {
    downloads.push(loadSysrootFile(name));
  }
  let entries = [];
  let size = 0;
  for (const download of downloads) {
    const entry = await download;
    size = size + entry[1].data.length >>> 0;
    entries.push(entry);
  }
  stat("download sysroot", ms(performance.now() - start) + " (" + String(entries.length) + " files, " + mb(size) + ")");
  return new Map(entries);
}

async function loadSysrootFile(name) {
  const response = await window.fetch("./sysroot/" + name);
  const bytes = new Uint8Array(await response.arrayBuffer());
  return [name, new File(bytes, { readonly: true })];
}

async function loadWebCrate(start, stat) {
  const bytes = await (await window.fetch("./web/libweb.rmeta")).arrayBuffer();
  stat("download web crate", ms(performance.now() - start) + " (" + mb(bytes.byteLength) + ")");
  return new File(new Uint8Array(bytes), { readonly: true });
}

async function loadExamples() {
  return await (await window.fetch("./examples.json")).json();
}

async function fetchExampleFile(name, path) {
  const response = await window.fetch("./examples/" + name + "/" + path);
  return [path, await response.text()];
}

export async function loadExample(name, paths) {
  let downloads = [];
  for (const path of paths) {
    downloads.push(fetchExampleFile(name, path));
  }
  let texts = [];
  for (const download of downloads) {
    texts.push(await download);
  }
  return texts;
}

function dir(name, entry) {
  return new Directory(new Map([[name, entry]]));
}

function directoryOf(sources) {
  const top = new Map([]);
  for (const item of Array.from(sources)) {
    let folder = top;
    let name;
    const match = $rsplitOnce(item[0], "/");
    if (match != null) {
      for (const part of match[0].split("/")) {
        if (!folder.has(part)) {
          folder.set(part, new Directory(new Map([])));
        }
        folder = folder.get(part).contents;
      }
      name = match[1];
    } else {
      name = item[0];
    }
    const bytes = new TextEncoder().encode(item[1]);
    folder.set(name, new File(bytes));
  }
  return top;
}

function jsFilesIn(folder, prefix, found) {
  for (const item of Array.from(folder.contents)) {
    if (item[1] instanceof Directory) {
      jsFilesIn(item[1], prefix + item[0] + "/", found);
    } else if (item[1] instanceof File && item[0].endsWith(".js")) {
      const text = new TextDecoder().decode(item[1].data);
      found.push([prefix + item[0], text]);
    }
  }
}

export async function compile(loaded, sources, rootFile, test) {
  const stderr = { value: [] };
  const stdoutLines = stderr;
  const stderrLines = stderr;
  const outDir = new PreopenDirectory("/out", new Map([]));
  const sysrootDir = new Directory(loaded.sysroot);
  const fds = [
    new OpenFile(new File([])),
    ConsoleStdout.lineBuffered((line) => {
      stdoutLines.value.push(line);
    }),
    ConsoleStdout.lineBuffered((line) => {
      stderrLines.value.push(line);
    }),
    new PreopenDirectory("/in", directoryOf(sources)),
    outDir,
    new PreopenDirectory("/sysroot", new Map([["lib", dir("rustlib", dir("wasm32-unknown-unknown", dir("lib", sysrootDir)))]])),
    new PreopenDirectory("/web", new Map([["libweb.rmeta", loaded.webCrate]]))
  ];
  let outFile;
  const match = $stripSuffix(rootFile, ".rs");
  if (match != null) {
    outFile = "/out/" + match + ".js";
  } else {
    outFile = "/out/" + rootFile;
  }
  let args = ["rust-js"];
  if (test) {
    args.push("--test");
  }
  for (const arg of [
    "/in/" + rootFile,
    "-o",
    outFile
  ]) {
    args.push(arg);
  }
  for (const arg$1 of [
    "--",
    "--target",
    "wasm32-unknown-unknown",
    "--sysroot",
    "/sysroot"
  ]) {
    args.push(arg$1);
  }
  if (test) {
    args.push("--cfg=browser");
  }
  args.push("--extern");
  args.push("web=/web/libweb.rmeta");
  const wasi = new WASI(args, ["RUSTC_ICE=0"], fds, { debug: false });
  const t0 = performance.now();
  const imports = { wasi_snapshot_preview1: wasi.wasiImport };
  const instance = await WebAssembly.instantiate(loaded.module, imports);
  const t1 = performance.now();
  const started = $try(() => wasi.start(instance));
  const t2 = performance.now();
  const ok = started.TAG === "Ok" && started._0 === 0;
  let exit;
  if (started.TAG === "Ok") {
    exit = String(started._0);
  } else {
    exit = "trap (" + (started._0 instanceof Error ? started._0.message : String(started._0)) + ")";
  }
  let files = [];
  if (ok) {
    jsFilesIn(outDir.dir, "", files);
  }
  const memory = instance.exports.memory.buffer;
  return {
    exit,
    ok,
    files: new Map(files),
    stderr: stderr.value.join("\n"),
    instantiate: t1 - t0,
    run: t2 - t1,
    memory: memory.byteLength
  };
}
//# sourceMappingURL=compiler.js.map
