// Generated by rust-js from wasm/web/rust/lib.rs. Do not edit.

import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import * as app from "./components/app.jsx";

function $unwrap(value, message = "called `Option::unwrap()` on a `None` value") {
  if (value == null) {
    throw new Error(message);
  }
  return value;
}

export function start() {
  const root = createRoot($unwrap(document.getElementById("app"), "the page has an #app"));
  root.render(<StrictMode>
    <app.App />
  </StrictMode>);
}
//# sourceMappingURL=lib.jsx.map
