// Generated by rust-js from wasm/web/rust/listen.rs. Do not edit.

export function listen(target, type_, f, controller) {
  target.addEventListener(type_, f, {
    capture: undefined,
    passive: undefined,
    once: undefined,
    signal: controller.signal,
  });
}
//# sourceMappingURL=listen.js.map
