// Generated by rust-js from wasm/web/rust/tree.rs. Do not edit.

function $rsplitOnce(s, separator) {
  const i = s.lastIndexOf(separator);
  return i < 0 ? undefined : [s.slice(0, i), s.slice(i + separator.length)];
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

export function buildTree(paths) {
  let tree = [];
  for (const path of paths) {
    let folder = tree;
    let name;
    const match = $rsplitOnce(path, "/");
    if (match != null) {
      for (const part of match[0].split("/")) {
        if (!folder.some((param) => param[0] === part)) {
          folder.push([part, { TAG: "Folder", _0: [] }]);
        }
        let tmp;
        const match$1 = folder.find((param) => param[0] === part);
        if (match$1 != null && match$1[1].TAG === "Folder") {
          tmp = match$1[1]._0;
        } else {
          throw new Error("internal error: entered unreachable code: a folder, found or just made");
        }
        folder = tmp;
      }
      name = match[1];
    } else {
      name = path;
    }
    folder.push([name, { TAG: "File", _0: path }]);
  }
  return tree;
}

export function inOrder(tree, first) {
  const key = (param) => {
    if (param[1].TAG === "Folder") {
      return param[0] + "/";
    } else {
      return param[0];
    }
  };
  const isFirst = (entry) => entry.TAG === "File" && entry._0 === first;
  let entries = tree.slice();
  entries.sort((a, b) => {
    if (isFirst(a[1])) {
      return -1;
    } else if (isFirst(b[1])) {
      return 1;
    } else {
      return $cmp(key(a), key(b));
    }
  });
  return entries;
}
//# sourceMappingURL=tree.js.map
