// Generated by rust-js from test/jsx/lib.rs. Do not edit.

import { Activity, Profiler, StrictMode, Suspense, ViewTransition, useRef } from "react";

export function App() {
  const object = useRef(undefined);
  const onRender = () => {};
  const action = () => {};
  const ref = () => {};
  return (
    <Profiler id="test" onRender={onRender}>
      <ViewTransition name="page">
        <form action={action}>
          <input ref={object} />
          <input ref={ref} />
          <button formAction="/save" style={{ color: "red" }}>
            Save
          </button>
        </form>
      </ViewTransition>
      <Suspense />
      <Activity />
      <StrictMode />
    </Profiler>
  );
}
//# sourceMappingURL=lib.jsx.map
