// Generated by rust-js from examples/api.rs. Do not edit.

function $traitImpl(cache, keys, make) {
  for (let i = 0; i < keys.length - 1; i++) {
    const key = keys[i];
    if (!cache.has(key)) cache.set(key, new WeakMap());
    cache = cache.get(key);
  }
  const key = keys[keys.length - 1];
  if (!cache.has(key)) cache.set(key, make());
  return cache.get(key);
}

// Shortest round-trip decimal, using exact rational arithmetic.
// Rust Display uses decimal notation, including for very small/large values.
// Not JS's `String(x)`, though its digits are also the shortest: when two are
// equally close, JS takes the even one (1888570120608320.2), and Rust the
// larger (1888570120608320.3).
function $displayF64(value) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const x = Math.abs(value);
  if (x === 0) return sign + "0";

  const bitsView = new DataView(new ArrayBuffer(8));
  bitsView.setFloat64(0, x);
  const bits = bitsView.getBigUint64(0);
  const exponentBits = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponentBits === 0 ? fraction : fraction + (1n << 52n);
  const binaryExponent = exponentBits === 0 ? -1074 : exponentBits - 1023 - 52;
  const numerator = binaryExponent >= 0 ? significand << BigInt(binaryExponent) : significand;
  const denominator = binaryExponent < 0 ? 1n << BigInt(-binaryExponent) : 1n;

  // The floating-point logarithm is only an estimate; correct it exactly.
  let exponent = Math.floor(Math.log10(x));
  const atLeastPowerOfTen = (e) =>
    e >= 0
      ? numerator >= denominator * 10n ** BigInt(e)
      : numerator * 10n ** BigInt(-e) >= denominator;
  while (!atLeastPowerOfTen(exponent)) exponent--;
  while (atLeastPowerOfTen(exponent + 1)) exponent++;

  for (let precision = 1; precision <= 17; precision++) {
    const power = exponent - precision + 1;
    const n = power < 0 ? numerator * 10n ** BigInt(-power) : numerator;
    const d = power > 0 ? denominator * 10n ** BigInt(power) : denominator;
    const floor = n / d;
    const rounded = floor + (2n * (n % d) >= d ? 1n : 0n);
    // The rounding interval can be asymmetric at a binary power boundary.
    let best;
    let bestDistance;
    for (const candidate of [rounded, rounded - 1n, rounded + 1n]) {
      if (candidate > 0n && Number(`${candidate}e${power}`) === x) {
        const delta = candidate * d - n;
        const distance = delta < 0n ? -delta : delta;
        if (
          best === undefined ||
          distance < bestDistance ||
          (distance === bestDistance && candidate > best)
        ) {
          best = candidate;
          bestDistance = distance;
        }
      }
    }
    if (best !== undefined) {
      let digits = best.toString();
      let decimalPower = power;
      while (digits.endsWith("0")) {
        digits = digits.slice(0, -1);
        decimalPower++;
      }
      const point = digits.length + decimalPower;
      const body =
        point <= 0
          ? "0." + "0".repeat(-point) + digits
          : point >= digits.length
            ? digits + "0".repeat(point - digits.length)
            : digits.slice(0, point) + "." + digits.slice(point);
      return sign + body;
    }
  }
  throw new Error("No f64 round-trip decimal found");
}

function $debug(v) {
  if (typeof v === "string") {
    return JSON.stringify(v);
  }
  if (Array.isArray(v)) {
    return "[" + v.map($debug).join(", ") + "]";
  }
  if (v === undefined) {
    return "()";
  }
  // A `HashMap` and a `HashSet` (ADR 0059), in braces as Rust shows them.
  if (v instanceof Map) {
    return "{" + [...v].map(([k, x]) => $debug(k) + ": " + $debug(x)).join(", ") + "}";
  }
  if (v instanceof Set) {
    return "{" + [...v].map($debug).join(", ") + "}";
  }
  if (typeof v === "object" && v !== null) {
    return (
      "{ " +
      Object.entries(v)
        .map(([k, x]) => k + ": " + $debug(x))
        .join(", ") +
      " }"
    );
  }
  return String(v);
}

// `Some(x)` of a generic `T` (ADR 0051): `x`, unless it looks like `None`,
// as `undefined`, `null` or such a box does. Then it's a box one deeper.
function $some(x) {
  if (x == null) return { $someNone: 0 };
  if (typeof x === "object" && "$someNone" in x) return { $someNone: x.$someNone + 1 };
  return x;
}

// What's in a `$some`: the box one level shallower.
function $someValue(x) {
  if (x != null && typeof x === "object" && "$someNone" in x) {
    return x.$someNone === 0 ? undefined : { $someNone: x.$someNone - 1 };
  }
  return x;
}

function $sortedEntries(map, cmp) {
  return Array.from(map).sort((a, b) => cmp(a[0], b[0]));
}

class $JsonError extends Error {
  constructor(message, line = 0, column = 0) {
    super(message);
    this.line = line;
    this.column = column;
  }
}
function $jsonError(message) {
  return new $JsonError(message);
}
// A float as serde_json writes one: its shortest digits, fixed from 1e-5
// to 1e15, else `1.5e+16`.
function $jsonNumber(x) {
  if (!Number.isFinite(x)) return "null";
  if (x === 0) return Object.is(x, -0) ? "-0.0" : "0.0";
  const [mantissa, exponent] = x.toExponential().split("e");
  const e = Number(exponent);
  if (e < -5 || e > 15) return `${mantissa}e${e < 0 ? "-" : "+"}${Math.abs(e)}`;
  const fixed = String(x);
  return fixed.includes(".") ? fixed : `${fixed}.0`;
}

function $jsonWriter(pretty) {
  // For each array or object open: whether nothing is in it yet.
  const empty = [];
  const next = (json) => {
    const first = empty[empty.length - 1];
    empty[empty.length - 1] = false;
    if (pretty) json.text += (first ? "\n" : ",\n") + "  ".repeat(empty.length);
    else if (!first) json.text += ",";
  };
  const open = (json, bracket) => {
    empty.push(true);
    json.text += bracket;
  };
  const close = (json, bracket) => {
    if (!empty.pop() && pretty) json.text += "\n" + "  ".repeat(empty.length);
    json.text += bracket;
  };
  return {
    text: "",
    raw(text) {
      this.text += text;
    },
    string(s) {
      this.text += JSON.stringify(s);
    },
    number(x) {
      this.text += $jsonNumber(x);
    },
    beginArray() {
      open(this, "[");
    },
    element() {
      next(this);
    },
    endArray() {
      close(this, "]");
    },
    beginObject() {
      open(this, "{");
    },
    key(k) {
      next(this);
      this.text += JSON.stringify(k) + (pretty ? ": " : ":");
    },
    endObject() {
      close(this, "}");
    },
  };
}
function $toJson(value, write, pretty) {
  const json = $jsonWriter(pretty);
  try {
    write(value, json);
  } catch (e) {
    if (e instanceof $JsonError)
      return { TAG: "Err", _0: { message: e.message, line: e.line, column: e.column } };
    throw e;
  }
  return { TAG: "Ok", _0: json.text };
}

// What serde's impls and derives read, the same whatever they read from:
// the text (`$JsonReader`), or a value already read (`$JsonContent`), which
// is how serde reads a tagged or an untagged enum.
class $JsonDecoder {
  // An integer type, named as serde names it, from `min` to `max`.
  int(name, min, max) {
    return this.deserializeNumber(name, (n) => {
      if (n.kind === "f")
        throw $jsonError(
          `invalid type: floating point \`${$jsonNumber(n.value)}\`, expected ${name}`,
        );
      if (n.kind === "u" ? n.value > max : n.value < min) {
        throw $jsonError(`invalid value: integer \`${n.value}\`, expected ${name}`);
      }
      return Number(n.value);
    });
  }

  f64() {
    return this.deserializeNumber("f64", (n) => Number(n.value));
  }

  string() {
    return this.deserializeStr("a string", (s) => s);
  }

  char() {
    return this.deserializeStr("a character", $jsonChar);
  }

  vec(read) {
    return this.deserializeSeq("a sequence", (seq) => {
      const items = [];
      while (seq.next()) items.push(seq.value(read));
      return items;
    });
  }

  tuple(reads) {
    const expected = `a tuple of size ${reads.length}`;
    return this.deserializeSeq(expected, (seq) =>
      reads.map((read, i) => seq.element(read, i, expected)),
    );
  }

  array(length, read) {
    const expected = length === 0 ? "an empty array" : `an array of length ${length}`;
    return this.deserializeSeq(expected, (seq) =>
      Array.from({ length }, (_, i) => seq.element(read, i, expected)),
    );
  }

  map(readKey, read) {
    return this.deserializeMap("a map", (map) => {
      const entries = new Map();
      while (map.next()) {
        const key = readKey(map.key());
        entries.set(key, map.value(read));
      }
      return entries;
    });
  }

  // A struct's fields: `[name, read]`, or `[[name, ...aliases], read]`, and
  // `missing`, the value it has when it's not there, for `#[serde(default)]`.
  // `build` makes the struct of their values.
  struct(expected, fields, build, options = {}) {
    return this.deserializeMap(
      options.expecting ?? expected,
      (map) => this.structMap(map, fields, build, options),
      (seq) => this.structSeq(seq, expected, fields, build, options),
    );
  }

  // An untagged struct variant, which serde reads from an object only.
  untaggedStruct(expected, fields, build, options = {}) {
    return this.deserializeAny(options.expecting ?? expected, {
      map: (map) => this.structMap(map, fields, build, options),
    });
  }

  structMap(map, fields, build, { deny = false, container } = {}) {
    const values = new Array(fields.length);
    const seen = new Array(fields.length).fill(false);
    while (map.next()) {
      const i = $jsonField(map.key().string(), fields, deny);
      if (i < 0) {
        map.value((json) => json.ignoreValue());
        continue;
      }
      if (seen[i]) throw $jsonError(`duplicate field \`${$jsonName(fields[i][0])}\``);
      values[i] = map.value(fields[i][1]);
      seen[i] = true;
    }
    const defaults = container?.();
    fields.forEach(([names, read, missing], i) => {
      if (!seen[i])
        values[i] = missing ? missing(defaults) : read(new $JsonMissing($jsonName(names)));
    });
    return build(values, defaults);
  }

  structSeq(seq, expected, fields, build, { container, expecting } = {}) {
    const length =
      expecting ?? `${expected} with ${fields.length} element${fields.length === 1 ? "" : "s"}`;
    const defaults = container?.();
    const values = fields.map(([, read, missing], i) =>
      seq.element(read, i, length, missing, defaults),
    );
    return build(values, defaults);
  }

  // A tuple struct's fields: `read`, or `[read, missing]`.
  tupleStruct(expected, fields, build = (values) => values, { container, expecting } = {}) {
    const length =
      expecting ?? `${expected} with ${fields.length} element${fields.length === 1 ? "" : "s"}`;
    return this.deserializeSeq(expecting ?? expected, (seq) => {
      const defaults = container?.();
      const values = fields.map((field, i) => {
        const [read, missing] = typeof field === "function" ? [field] : field;
        return seq.element(read, i, length, missing, defaults);
      });
      return build(values, defaults);
    });
  }

  // An internally tagged enum's unit variant, whose other fields are
  // ignored (serde's `InternallyTaggedUnitVisitor`).
  taggedUnit(expected) {
    return this.deserializeAny(expected, {
      seq: () => undefined,
      map: (map) => {
        while (map.next()) {
          map.key().ignore();
          map.value((json) => json.ignoreValue());
        }
        return undefined;
      },
    });
  }

  // An untagged unit variant: `null` (serde's `UntaggedUnitVisitor`).
  untaggedUnit(expected) {
    return this.deserializeAny(expected, { unit: () => undefined });
  }

  // `#[serde(tag = "type")]`: the tag, found among the other fields, which
  // are kept for the variant to read (serde's `TaggedContentVisitor`).
  internallyTagged(tag, expected, variants, visit, other) {
    const [variant, rest] = this.deserializeAny(expected, {
      seq: (seq) => {
        if (!seq.next()) throw $jsonError(`missing field \`${tag}\``);
        const variant = seq.value((json) => json.identifier(variants, other));
        const items = [];
        while (seq.next()) items.push(seq.value((json) => json.content()));
        return [variant, { type: "seq", value: items }];
      },
      map: (map) => {
        let variant;
        const entries = [];
        while (map.next()) {
          const key = map.key().string();
          if (key !== tag) {
            entries.push([{ type: "str", value: key }, map.value((json) => json.content())]);
            continue;
          }
          if (variant !== undefined) throw $jsonError(`duplicate field \`${tag}\``);
          variant = map.value((json) => json.identifier(variants, other));
        }
        if (variant === undefined) throw $jsonError(`missing field \`${tag}\``);
        return [variant, { type: "map", value: entries }];
      },
    });
    return visit(variant, new $JsonContent(rest, true));
  }

  // `#[serde(tag = "t", content = "c")]`, as serde's derive reads one: the
  // tag, then the content, or the content first, kept until the tag says
  // how to read it.
  adjacentlyTagged(tag, content, expected, variants, visit, { deny = false, other } = {}) {
    const variantOf = (json) =>
      json.enum(
        variants,
        (name, access) => {
          access.unit();
          return name;
        },
        other,
      );
    // The next key that's the tag or the content, skipping any other.
    const relevant = (map) => {
      while (map.next()) {
        const key = map.key().string();
        if (key === tag) return "tag";
        if (key === content) return "content";
        if (deny) {
          throw $jsonError(
            `invalid value: string ${$debugStr(key)}, expected ${$debugStr(tag)} or ${$debugStr(content)}`,
          );
        }
        map.value((json) => json.ignoreValue());
      }
      return undefined;
    };
    const finish = (map, value) => {
      const key = relevant(map);
      if (key !== undefined)
        throw $jsonError(`duplicate field \`${key === "tag" ? tag : content}\``);
      return value;
    };
    return this.deserializeMap(
      expected,
      (map) => {
        const first = relevant(map);
        if (first === "tag") {
          const variant = map.value(variantOf);
          const second = relevant(map);
          if (second === "tag") throw $jsonError(`duplicate field \`${tag}\``);
          if (second === "content")
            return finish(
              map,
              map.value((json) => visit(variant, json)),
            );
          return visit(variant, new $JsonMissing(content));
        }
        if (first === "content") {
          const buffered = map.value((json) => json.content());
          const second = relevant(map);
          if (second === "tag") {
            const variant = map.value(variantOf);
            return finish(map, visit(variant, new $JsonContent(buffered, true)));
          }
          if (second === "content") throw $jsonError(`duplicate field \`${content}\``);
        }
        throw $jsonError(`missing field \`${tag}\``);
      },
      (seq) => {
        if (!seq.next()) throw $jsonError(`invalid length 0, expected ${expected}`);
        const variant = seq.value((json) => json.identifier(variants, other));
        if (!seq.next()) throw $jsonError(`invalid length 1, expected ${expected}`);
        return seq.value((json) => visit(variant, json));
      },
    );
  }

  // `#[serde(untagged)]`: the value, read once and kept, then each way of
  // reading it in turn, the first that works.
  untagged(message, attempts) {
    const content = this.content();
    for (const attempt of attempts) {
      try {
        return attempt(new $JsonContent(content, false));
      } catch (e) {
        if (!(e instanceof $JsonError)) throw e;
      }
    }
    throw $jsonError(message);
  }
}

// serde_json's reader (ADR 0078): its `Deserializer`, ported step for step,
// with its methods' names. It reads the text's UTF-8 bytes, as serde_json
// does, so a mistake is found at the same byte, with the same message, and
// its column counts bytes.
class $JsonReader extends $JsonDecoder {
  constructor(text) {
    super();
    this.bytes = new TextEncoder().encode(text);
    this.index = 0;
    this.remainingDepth = 128;
  }

  // The next byte, or -1 at the end.
  peek() {
    return this.index < this.bytes.length ? this.bytes[this.index] : -1;
  }

  next() {
    return this.index < this.bytes.length ? this.bytes[this.index++] : -1;
  }

  // `position_of_index`: the line, and the bytes before `index` on it.
  errorAt(index, message) {
    const start = index === 0 ? 0 : this.bytes.lastIndexOf(10, index - 1) + 1;
    let line = 1;
    for (let i = 0; i < start; i++) if (this.bytes[i] === 10) line++;
    return new $JsonError(message, line, index - start);
  }

  error(message) {
    return this.errorAt(this.index, message);
  }

  peekError(message) {
    return this.errorAt(Math.min(this.bytes.length, this.index + 1), message);
  }

  // `fix_position`: a visitor's message has no place, until it gets where
  // the reader is.
  fixPosition(e) {
    return e instanceof $JsonError && e.line === 0 ? this.error(e.message) : e;
  }

  end() {
    if (this.parseWhitespace() !== -1) throw this.peekError("trailing characters");
  }

  parseWhitespace() {
    for (;;) {
      const c = this.peek();
      if (c !== 32 && c !== 10 && c !== 9 && c !== 13) return c;
      this.index++;
    }
  }

  parseIdent(rest) {
    for (let i = 0; i < rest.length; i++) {
      const c = this.next();
      if (c === -1) throw this.error("EOF while parsing a value");
      if (c !== rest.charCodeAt(i)) throw this.error("expected ident");
    }
  }

  // What's there instead of `expected`, read past, in serde's words.
  peekInvalidType(expected) {
    const c = this.peek();
    let unexpected;
    if (c === 110) {
      this.index++;
      this.parseIdent("ull");
      unexpected = "null";
    } else if (c === 116) {
      this.index++;
      this.parseIdent("rue");
      unexpected = "boolean `true`";
    } else if (c === 102) {
      this.index++;
      this.parseIdent("alse");
      unexpected = "boolean `false`";
    } else if (c === 45) {
      this.index++;
      unexpected = $jsonUnexpectedNumber(this.parseInteger(false));
    } else if (c >= 48 && c <= 57) {
      unexpected = $jsonUnexpectedNumber(this.parseInteger(true));
    } else if (c === 34) {
      this.index++;
      unexpected = `string ${$debugStr(this.parseStr())}`;
    } else if (c === 91) {
      unexpected = "sequence";
    } else if (c === 123) {
      unexpected = "map";
    } else {
      return this.peekError("expected value");
    }
    return this.fixPosition($jsonError(`invalid type: ${unexpected}, expected ${expected}`));
  }

  // A number: `{ kind, value }`, a `"u"`nsigned or `"i"`nteger (a BigInt
  // past 2^53) where it's an integer that fits in 64 bits, else an `"f"`.
  deserializeNumber(expected, visit) {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek === 45) {
        this.index++;
        return visit(this.parseInteger(false));
      }
      if (peek >= 48 && peek <= 57) return visit(this.parseInteger(true));
      throw this.peekInvalidType(expected);
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  parseInteger(positive) {
    const c = this.next();
    if (c === -1) throw this.error("EOF while parsing a value");
    if (c === 48) {
      const p = this.peek();
      if (p >= 48 && p <= 57) throw this.peekError("invalid number");
      return this.parseNumber(positive, 0);
    }
    if (c < 49 || c > 57) throw this.error("invalid number");
    let significand = c - 48;
    for (;;) {
      const p = this.peek();
      if (p < 48 || p > 57) return this.parseNumber(positive, significand);
      const grown = $jsonGrow(significand, p - 48);
      if (grown > 18446744073709551615n) {
        return { kind: "f", value: this.parseLongInteger(positive, significand) };
      }
      this.index++;
      significand = grown;
    }
  }

  parseNumber(positive, significand) {
    const p = this.peek();
    if (p === 46) return { kind: "f", value: this.parseDecimal(positive, significand, 0) };
    if (p === 101 || p === 69)
      return { kind: "f", value: this.parseExponent(positive, significand, 0) };
    if (positive) return { kind: "u", value: significand };
    // `-0`, and below `i64::MIN`, are floats.
    if (significand === 0 || significand > 9223372036854775808n) {
      return { kind: "f", value: -Number(significand) };
    }
    return { kind: "i", value: -significand };
  }

  parseDecimal(positive, significand, exponentBeforeDecimalPoint) {
    this.index++;
    let exponentAfterDecimalPoint = 0;
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) {
      const grown = $jsonGrow(significand, p - 48);
      if (grown > 18446744073709551615n) {
        const exponent = exponentBeforeDecimalPoint + exponentAfterDecimalPoint;
        return this.parseDecimalOverflow(positive, significand, exponent);
      }
      this.index++;
      significand = grown;
      exponentAfterDecimalPoint--;
    }
    if (exponentAfterDecimalPoint === 0) {
      throw this.peekError(this.peek() === -1 ? "EOF while parsing a value" : "invalid number");
    }
    const exponent = exponentBeforeDecimalPoint + exponentAfterDecimalPoint;
    const p = this.peek();
    return p === 101 || p === 69
      ? this.parseExponent(positive, significand, exponent)
      : this.f64FromParts(positive, significand, exponent);
  }

  parseExponent(positive, significand, startingExp) {
    this.index++;
    let positiveExp = true;
    const sign = this.peek();
    if (sign === 43) {
      this.index++;
    } else if (sign === 45) {
      this.index++;
      positiveExp = false;
    }
    const c = this.next();
    if (c === -1) throw this.error("EOF while parsing a value");
    if (c < 48 || c > 57) throw this.error("invalid number");
    let exp = c - 48;
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) {
      this.index++;
      if (exp * 10 + (p - 48) > 2147483647) {
        return this.parseExponentOverflow(positive, significand == 0, positiveExp);
      }
      exp = exp * 10 + (p - 48);
    }
    // i32's saturating add and subtract.
    const finalExp = Math.max(
      -2147483648,
      Math.min(2147483647, positiveExp ? startingExp + exp : startingExp - exp),
    );
    return this.f64FromParts(positive, significand, finalExp);
  }

  // Not correctly rounded, as serde_json's isn't without its
  // `float_roundtrip` feature: the significand times or over a power of ten.
  f64FromParts(positive, significand, exponent) {
    let f = Number(significand);
    for (;;) {
      const pow = $JSON_POW10[Math.abs(exponent)];
      if (pow !== undefined) {
        if (exponent >= 0) {
          f *= pow;
          if (!Number.isFinite(f)) throw this.error("number out of range");
        } else {
          f /= pow;
        }
        break;
      }
      if (f === 0) break;
      if (exponent >= 0) throw this.error("number out of range");
      f /= 1e308;
      exponent += 308;
    }
    return positive ? f : -f;
  }

  parseLongInteger(positive, significand) {
    let exponent = 0;
    for (;;) {
      const p = this.peek();
      if (p >= 48 && p <= 57) {
        this.index++;
        exponent++;
      } else if (p === 46) {
        return this.parseDecimal(positive, significand, exponent);
      } else if (p === 101 || p === 69) {
        return this.parseExponent(positive, significand, exponent);
      } else {
        return this.f64FromParts(positive, significand, exponent);
      }
    }
  }

  parseDecimalOverflow(positive, significand, exponent) {
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) this.index++;
    const p = this.peek();
    return p === 101 || p === 69
      ? this.parseExponent(positive, significand, exponent)
      : this.f64FromParts(positive, significand, exponent);
  }

  parseExponentOverflow(positive, zeroSignificand, positiveExp) {
    if (!zeroSignificand && positiveExp) throw this.error("number out of range");
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) this.index++;
    return positive ? 0 : -0;
  }

  // A string, after its opening quote.
  parseStr() {
    const bytes = this.bytes;
    let text = "";
    let start = this.index;
    for (;;) {
      while (this.index < bytes.length) {
        const c = bytes[this.index];
        if (c === 34 || c === 92 || c < 32) break;
        this.index++;
      }
      if (this.index === bytes.length) throw this.error("EOF while parsing a string");
      const c = bytes[this.index];
      if (c === 34) {
        text += $JSON_UTF8.decode(bytes.subarray(start, this.index));
        this.index++;
        return text;
      }
      if (c !== 92) {
        this.index++;
        throw this.error("control character (\\u0000-\\u001F) found while parsing a string");
      }
      text += $JSON_UTF8.decode(bytes.subarray(start, this.index));
      this.index++;
      text += this.parseEscape();
      start = this.index;
    }
  }

  parseEscape() {
    const c = this.next();
    if (c === -1) throw this.error("EOF while parsing a string");
    switch (c) {
      case 34:
        return '"';
      case 92:
        return "\\";
      case 47:
        return "/";
      case 98:
        return "\b";
      case 102:
        return "\f";
      case 110:
        return "\n";
      case 114:
        return "\r";
      case 116:
        return "\t";
      case 117:
        return this.parseUnicodeEscape();
    }
    throw this.error("invalid escape");
  }

  parseUnicodeEscape() {
    const n = this.decodeHexEscape();
    // A trailing surrogate, which serde_json calls a leading one.
    if (n >= 0xdc00 && n <= 0xdfff) throw this.error("lone leading surrogate in hex escape");
    if (n < 0xd800 || n > 0xdbff) return String.fromCharCode(n);
    for (const expected of [92, 117]) {
      if (this.peek() === -1) throw this.error("EOF while parsing a string");
      const c = this.bytes[this.index++];
      if (c !== expected) throw this.error("unexpected end of hex escape");
    }
    const n2 = this.decodeHexEscape();
    if (n2 < 0xdc00 || n2 > 0xdfff) throw this.error("lone leading surrogate in hex escape");
    return String.fromCharCode(n, n2);
  }

  decodeHexEscape() {
    if (this.index + 4 > this.bytes.length) {
      this.index = this.bytes.length;
      throw this.error("EOF while parsing a string");
    }
    let n = 0;
    let valid = true;
    for (let i = 0; i < 4; i++) {
      const digit = $jsonHexDigit(this.bytes[this.index + i]);
      valid &&= digit >= 0;
      n = n * 16 + digit;
    }
    this.index += 4;
    if (!valid) throw this.error("invalid escape");
    return n;
  }

  ignoreStr() {
    const bytes = this.bytes;
    for (;;) {
      while (this.index < bytes.length) {
        const c = bytes[this.index];
        if (c === 34 || c === 92 || c < 32) break;
        this.index++;
      }
      if (this.index === bytes.length) throw this.error("EOF while parsing a string");
      const c = bytes[this.index];
      if (c === 34) {
        this.index++;
        return;
      }
      if (c !== 92)
        throw this.error("control character (\\u0000-\\u001F) found while parsing a string");
      this.index++;
      const escape = this.next();
      if (escape === -1) throw this.error("EOF while parsing a string");
      if (escape === 117) this.decodeHexEscape();
      else if (!'"\\/bfnrt'.includes(String.fromCharCode(escape)))
        throw this.error("invalid escape");
    }
  }

  parseObjectColon() {
    const c = this.parseWhitespace();
    if (c === 58) {
      this.index++;
      return;
    }
    throw this.peekError(c === -1 ? "EOF while parsing an object" : "expected `:`");
  }

  endSeq() {
    const c = this.parseWhitespace();
    if (c === 93) {
      this.index++;
      return;
    }
    if (c === 44) {
      this.index++;
      throw this.peekError(
        this.parseWhitespace() === 93 ? "trailing comma" : "trailing characters",
      );
    }
    throw this.peekError(c === -1 ? "EOF while parsing a list" : "trailing characters");
  }

  endMap() {
    const c = this.parseWhitespace();
    if (c === 125) {
      this.index++;
      return;
    }
    throw this.peekError(
      c === 44
        ? "trailing comma"
        : c === -1
          ? "EOF while parsing an object"
          : "trailing characters",
    );
  }

  ignoreValue() {
    const frames = [];
    let enclosing;
    for (;;) {
      const peek = this.parseWhitespace();
      if (peek === -1) throw this.peekError("EOF while parsing a value");
      let frame;
      if (peek === 110) {
        this.index++;
        this.parseIdent("ull");
      } else if (peek === 116) {
        this.index++;
        this.parseIdent("rue");
      } else if (peek === 102) {
        this.index++;
        this.parseIdent("alse");
      } else if (peek === 45) {
        this.index++;
        this.ignoreInteger();
      } else if (peek >= 48 && peek <= 57) {
        this.ignoreInteger();
      } else if (peek === 34) {
        this.index++;
        this.ignoreStr();
      } else if (peek === 91 || peek === 123) {
        if (enclosing !== undefined) frames.push(enclosing);
        enclosing = undefined;
        this.index++;
        frame = peek;
      } else {
        throw this.peekError("expected value");
      }
      let acceptComma = true;
      if (frame !== undefined) {
        acceptComma = false;
      } else if (enclosing !== undefined) {
        frame = enclosing;
        enclosing = undefined;
      } else if (frames.length > 0) {
        frame = frames.pop();
      } else {
        return;
      }
      for (;;) {
        const c = this.parseWhitespace();
        if (c === 44 && acceptComma) {
          this.index++;
          break;
        }
        if (c === -1)
          throw this.peekError(
            frame === 91 ? "EOF while parsing a list" : "EOF while parsing an object",
          );
        if (!((c === 93 && frame === 91) || (c === 125 && frame === 123))) {
          if (acceptComma)
            throw this.peekError(frame === 91 ? "expected `,` or `]`" : "expected `,` or `}`");
          break;
        }
        this.index++;
        if (frames.length === 0) return;
        frame = frames.pop();
        acceptComma = true;
      }
      if (frame === 123) {
        const quote = this.parseWhitespace();
        if (quote !== 34)
          throw this.peekError(
            quote === -1 ? "EOF while parsing an object" : "key must be a string",
          );
        this.index++;
        this.ignoreStr();
        const colon = this.parseWhitespace();
        if (colon !== 58)
          throw this.peekError(colon === -1 ? "EOF while parsing an object" : "expected `:`");
        this.index++;
      }
      enclosing = frame;
    }
  }

  ignoreInteger() {
    const c = this.next();
    if (c === 48) {
      const p = this.peek();
      if (p >= 48 && p <= 57) throw this.peekError("invalid number");
    } else if (c >= 49 && c <= 57) {
      for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) this.index++;
    } else {
      throw this.error("invalid number");
    }
    const p = this.peek();
    if (p === 46) this.ignoreDecimal();
    else if (p === 101 || p === 69) this.ignoreExponent();
  }

  ignoreDecimal() {
    this.index++;
    let atLeastOneDigit = false;
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) {
      this.index++;
      atLeastOneDigit = true;
    }
    if (!atLeastOneDigit) throw this.peekError("invalid number");
    const p = this.peek();
    if (p === 101 || p === 69) this.ignoreExponent();
  }

  ignoreExponent() {
    this.index++;
    const sign = this.peek();
    if (sign === 43 || sign === 45) this.index++;
    const c = this.next();
    if (c < 48 || c > 57) throw this.error("invalid number");
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) this.index++;
  }

  // An array or an object: `visit` reads what's inside, and the closing
  // bracket is looked for even when it fails, as serde_json does.
  nested(visit, end) {
    if (--this.remainingDepth === 0) throw this.peekError("recursion limit exceeded");
    this.index++;
    let value;
    let failure;
    try {
      value = visit();
    } catch (e) {
      if (!(e instanceof $JsonError)) throw e;
      failure = e;
    }
    this.remainingDepth++;
    try {
      end();
    } catch (e) {
      if (!(e instanceof $JsonError)) throw e;
      failure ??= e;
    }
    if (failure) throw failure;
    return value;
  }

  // `deserialize_seq`: `[ .. ]`, which `visit` reads with a `$JsonSeq`.
  deserializeSeq(expected, visit) {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek !== 91) throw this.peekInvalidType(expected);
      return this.nested(
        () => visit(new $JsonSeq(this)),
        () => this.endSeq(),
      );
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  // `deserialize_map` and `deserialize_struct`: `{ .. }`, or for a struct,
  // `[ .. ]` too.
  deserializeMap(expected, visitMap, visitSeq) {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek === 91 && visitSeq)
        return this.nested(
          () => visitSeq(new $JsonSeq(this)),
          () => this.endSeq(),
        );
      if (peek !== 123) throw this.peekInvalidType(expected);
      return this.nested(
        () => visitMap(new $JsonMap(this)),
        () => this.endMap(),
      );
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  deserializeStr(expected, visit) {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek !== 34) throw this.peekInvalidType(expected);
      this.index++;
      return visit(this.parseStr());
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  // What serde's own impls read, from the text.

  bool() {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek === 116) {
        this.index++;
        this.parseIdent("rue");
        return true;
      }
      if (peek === 102) {
        this.index++;
        this.parseIdent("alse");
        return false;
      }
      throw this.peekInvalidType("a boolean");
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  unit(expected = "unit") {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek !== 110) throw this.peekInvalidType(expected);
      this.index++;
      this.parseIdent("ull");
      return undefined;
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  unitStruct(expected) {
    return this.unit(expected);
  }

  option(read) {
    if (this.parseWhitespace() !== 110) return read(this);
    this.index++;
    this.parseIdent("ull");
    return undefined;
  }

  // `deserialize_any`: whatever's there, for the `visitor` method of its
  // kind (`unit`, `bool`, `number`, `string`, `seq` or `map`), which is
  // `expected` if the visitor has none.
  deserializeAny(expected, visitor) {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    const invalid = (unexpected) => $jsonError(`invalid type: ${unexpected}, expected ${expected}`);
    try {
      if (peek === 110) {
        this.index++;
        this.parseIdent("ull");
        if (visitor.unit) return visitor.unit();
        throw invalid("null");
      }
      if (peek === 116 || peek === 102) {
        this.index++;
        this.parseIdent(peek === 116 ? "rue" : "alse");
        if (visitor.bool) return visitor.bool(peek === 116);
        throw invalid(`boolean \`${peek === 116}\``);
      }
      if (peek === 45 || (peek >= 48 && peek <= 57)) {
        if (peek === 45) this.index++;
        const n = this.parseInteger(peek !== 45);
        if (visitor.number) return visitor.number(n);
        throw invalid($jsonUnexpectedNumber(n));
      }
      if (peek === 34) {
        this.index++;
        const s = this.parseStr();
        if (visitor.string) return visitor.string(s);
        throw invalid(`string ${$debugStr(s)}`);
      }
      if (peek === 91) {
        return this.nested(
          () => {
            if (!visitor.seq) throw invalid("sequence");
            return visitor.seq(new $JsonSeq(this));
          },
          () => this.endSeq(),
        );
      }
      if (peek === 123) {
        return this.nested(
          () => {
            if (!visitor.map) throw invalid("map");
            return visitor.map(new $JsonMap(this));
          },
          () => this.endMap(),
        );
      }
      throw this.peekError("expected value");
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  // serde's `ContentVisitor`: the value, read into a `{ type, value }`.
  content() {
    return this.deserializeAny("any value", {
      unit: () => ({ type: "unit" }),
      bool: (value) => ({ type: "bool", value }),
      number: (value) => ({ type: "num", value }),
      string: (value) => ({ type: "str", value }),
      seq: (seq) => {
        const items = [];
        while (seq.next()) items.push(seq.value((json) => json.content()));
        return { type: "seq", value: items };
      },
      map: (map) => {
        const entries = [];
        while (map.next()) {
          const key = map.key().content();
          entries.push([key, map.value((json) => json.content())]);
        }
        return { type: "map", value: entries };
      },
    });
  }

  // `deserialize_enum`: `"Name"`, or `{"Name": ..}`. `visit` gets the
  // variant's name and a `$JsonVariant` to read what it holds.
  enum(variants, visit, other) {
    const peek = this.parseWhitespace();
    if (peek === 34) return visit(this.identifier(variants, other), new $JsonVariant(this, true));
    if (peek !== 123)
      throw this.peekError(peek === -1 ? "EOF while parsing a value" : "expected value");
    if (--this.remainingDepth === 0) throw this.peekError("recursion limit exceeded");
    this.index++;
    let value;
    try {
      const c = this.parseWhitespace();
      if (c !== 34) {
        throw this.peekError(
          c === 125
            ? "expected value"
            : c === -1
              ? "EOF while parsing an object"
              : "key must be a string",
        );
      }
      const name = this.identifier(variants, other);
      this.parseObjectColon();
      value = visit(name, new $JsonVariant(this, false));
    } finally {
      this.remainingDepth++;
    }
    const c = this.parseWhitespace();
    if (c === 125) {
      this.index++;
      return value;
    }
    throw this.error(c === -1 ? "EOF while parsing an object" : "expected value");
  }

  // A variant's name, from a string.
  identifier(variants, other) {
    return this.deserializeStr("variant identifier", (name) =>
      $jsonVariantNamed(name, variants, other),
    );
  }
}

// A value already read (serde's `ContentDeserializer`, or when not `owned`,
// its `ContentRefDeserializer`): `{ type, value }`, where `type` is `unit`,
// `bool`, `num`, `str`, `seq` or `map`.
class $JsonContent extends $JsonDecoder {
  constructor(content, owned) {
    super();
    this.data = content;
    this.owned = owned;
  }

  invalid(expected) {
    return $jsonError(`invalid type: ${$jsonUnexpectedContent(this.data)}, expected ${expected}`);
  }

  deserializeNumber(expected, visit) {
    if (this.data.type === "num") return visit(this.data.value);
    throw this.invalid(expected);
  }

  deserializeStr(expected, visit) {
    if (this.data.type === "str") return visit(this.data.value);
    throw this.invalid(expected);
  }

  visitSeq(visit) {
    const seq = new $JsonContentSeq(this.data.value, this.owned);
    const value = visit(seq);
    seq.end();
    return value;
  }

  visitMap(visit) {
    const map = new $JsonContentMap(this.data.value, this.owned);
    const value = visit(map);
    map.end();
    return value;
  }

  deserializeSeq(expected, visit) {
    if (this.data.type === "seq") return this.visitSeq(visit);
    throw this.invalid(expected);
  }

  deserializeMap(expected, visitMap, visitSeq) {
    if (this.data.type === "seq" && visitSeq) return this.visitSeq(visitSeq);
    if (this.data.type === "map") return this.visitMap(visitMap);
    throw this.invalid(expected);
  }

  deserializeAny(expected, visitor) {
    const { type, value } = this.data;
    if (type === "seq" && visitor.seq) return this.visitSeq(visitor.seq);
    if (type === "map" && visitor.map) return this.visitMap(visitor.map);
    const visit = {
      unit: visitor.unit,
      bool: visitor.bool,
      num: visitor.number,
      str: visitor.string,
    }[type];
    if (visit) return visit(value);
    throw this.invalid(expected);
  }

  bool() {
    if (this.data.type === "bool") return this.data.value;
    throw this.invalid("a boolean");
  }

  unit(expected = "unit") {
    const { type, value } = this.data;
    // An owned one takes `{}` for a unit, as a newtype variant of `()`.
    if (type === "unit" || (this.owned && type === "map" && value.length === 0)) return undefined;
    throw this.invalid(expected);
  }

  unitStruct(expected) {
    const { type, value } = this.data;
    if (type === "unit" || (this.owned && (type === "map" || type === "seq") && value.length === 0))
      return undefined;
    throw this.invalid(expected);
  }

  option(read) {
    return this.data.type === "unit" ? undefined : read(this);
  }

  ignoreValue() {}

  content() {
    return this.data;
  }

  enum(variants, visit, other) {
    const { type, value } = this.data;
    let variant;
    let held;
    if (type === "map") {
      if (value.length !== 1)
        throw $jsonError("invalid value: map, expected map with a single key");
      [[variant, held]] = value;
    } else if (type === "str") {
      variant = this.data;
    } else {
      throw this.invalid("string or map");
    }
    const name = new $JsonContent(variant, this.owned).identifier(variants, other);
    return visit(name, new $JsonContentVariant(held, this.owned));
  }

  // A variant's name, or its index among the variants.
  identifier(variants, other) {
    const { type, value } = this.data;
    if (type === "str") return $jsonVariantNamed(value, variants, other);
    if (type !== "num" || value.kind !== "u") throw this.invalid("variant identifier");
    if (value.value < variants.length) return $jsonName(variants[Number(value.value)]);
    if (other !== undefined) return other;
    throw $jsonError(
      `invalid value: integer \`${value.value}\`, expected variant index 0 <= i < ${variants.length}`,
    );
  }
}

// `SeqAccess`.
class $JsonSeq {
  constructor(reader) {
    this.reader = reader;
    this.first = true;
  }

  // `has_next_element`.
  next() {
    const reader = this.reader;
    const peek = reader.parseWhitespace();
    if (peek === -1) throw reader.peekError("EOF while parsing a list");
    if (peek === 93) return false;
    if (this.first) {
      this.first = false;
      return true;
    }
    if (peek !== 44) throw reader.peekError("expected `,` or `]`");
    reader.index++;
    const c = reader.parseWhitespace();
    if (c === 93) throw reader.peekError("trailing comma");
    if (c === -1) throw reader.peekError("EOF while parsing a value");
    return true;
  }

  value(read) {
    return read(this.reader);
  }

  // The `i`th of `expected`'s items.
  element(read, i, expected, missing, defaults) {
    if (this.next()) return this.value(read);
    if (missing) return missing(defaults);
    throw $jsonError(`invalid length ${i}, expected ${expected}`);
  }
}

// The items of a value already read.
class $JsonContentSeq {
  constructor(items, owned) {
    this.items = items;
    this.owned = owned;
    this.count = 0;
  }

  next() {
    return this.count < this.items.length && ++this.count > 0;
  }

  value(read) {
    return read(new $JsonContent(this.items[this.count - 1], this.owned));
  }

  element(read, i, expected, missing, defaults) {
    return $JsonSeq.prototype.element.call(this, read, i, expected, missing, defaults);
  }

  // Items left over: the length is wrong.
  end() {
    const length = this.items.length;
    if (this.count < length) {
      const count = this.count;
      throw $jsonError(
        `invalid length ${length}, expected ${count} element${count === 1 ? "" : "s"} in sequence`,
      );
    }
  }
}

// `MapAccess`.
class $JsonMap {
  constructor(reader) {
    this.reader = reader;
    this.first = true;
  }

  // `has_next_key`.
  next() {
    const reader = this.reader;
    const peek = reader.parseWhitespace();
    if (peek === -1) throw reader.peekError("EOF while parsing an object");
    if (peek === 125) return false;
    if (this.first) {
      this.first = false;
      if (peek === 34) return true;
      throw reader.peekError("key must be a string");
    }
    if (peek !== 44) throw reader.peekError("expected `,` or `}`");
    reader.index++;
    const c = reader.parseWhitespace();
    if (c === 34) return true;
    throw reader.peekError(
      c === 125
        ? "trailing comma"
        : c === -1
          ? "EOF while parsing a value"
          : "key must be a string",
    );
  }

  key() {
    return new $JsonKey(this.reader);
  }

  value(read) {
    this.reader.parseObjectColon();
    return read(this.reader);
  }
}

// The entries of a value already read.
class $JsonContentMap {
  constructor(entries, owned) {
    this.entries = entries;
    this.owned = owned;
    this.count = 0;
  }

  next() {
    return this.count < this.entries.length && ++this.count > 0;
  }

  key() {
    return new $JsonContentKey(this.entries[this.count - 1][0], this.owned);
  }

  value(read) {
    return read(new $JsonContent(this.entries[this.count - 1][1], this.owned));
  }

  end() {
    const length = this.entries.length;
    if (this.count < length) {
      const count = this.count;
      throw $jsonError(
        `invalid length ${length}, expected ${count} element${count === 1 ? "" : "s"} in map`,
      );
    }
  }
}

// `MapKey`: an object's key, from its opening quote. A number or a `bool`
// is read from inside the quotes.
class $JsonKey {
  constructor(reader) {
    this.reader = reader;
  }

  string() {
    this.reader.index++;
    return this.reader.parseStr();
  }

  char() {
    return $jsonChar(this.string());
  }

  ignore() {
    this.string();
  }

  content() {
    return { type: "str", value: this.string() };
  }

  number(read) {
    const reader = this.reader;
    reader.index++;
    const c = reader.peek();
    if (!(c === 45 || (c >= 48 && c <= 57)))
      throw reader.error("invalid value: expected key to be a number in quotes");
    const value = read(reader);
    if (reader.peek() !== 34) throw reader.peekError('expected `"`');
    reader.index++;
    return value;
  }

  bool() {
    const reader = this.reader;
    reader.index++;
    try {
      const c = reader.next();
      if (c === -1) throw reader.peekError("EOF while parsing a value");
      if (c === 116) {
        reader.parseIdent('rue"');
        return true;
      }
      if (c === 102) {
        reader.parseIdent('alse"');
        return false;
      }
      throw $jsonError(`invalid type: string ${$debugStr(reader.parseStr())}, expected a boolean`);
    } catch (e) {
      throw reader.fixPosition(e);
    }
  }
}

// A key already read: it's read as any other value is, so a number in
// quotes isn't a number, as in serde.
class $JsonContentKey {
  constructor(key, owned) {
    this.key = new $JsonContent(key, owned);
  }

  string() {
    return this.key.string();
  }

  char() {
    return this.key.char();
  }

  bool() {
    return this.key.bool();
  }

  ignore() {}

  content() {
    return this.key.content();
  }

  number(read) {
    return read(this.key);
  }
}

// `VariantAccess` of `{"Name": ..}`, or of `"Name"` (`unit`), which holds
// nothing.
class $JsonVariant {
  constructor(reader, unit) {
    this.reader = reader;
    this.isUnit = unit;
  }

  unit() {
    if (!this.isUnit) this.reader.unit();
  }

  newtype(read) {
    if (this.isUnit) throw $jsonError("invalid type: unit variant, expected newtype variant");
    return read(this.reader);
  }

  tuple(expected, fields, build, options) {
    if (this.isUnit) throw $jsonError("invalid type: unit variant, expected tuple variant");
    return this.reader.tupleStruct(expected, fields, build, options);
  }

  struct(expected, fields, build, options) {
    if (this.isUnit) throw $jsonError("invalid type: unit variant, expected struct variant");
    return this.reader.struct(expected, fields, build, options);
  }
}

// The same, of a value already read: what a variant holds, if anything.
class $JsonContentVariant {
  constructor(held, owned) {
    this.held = held;
    this.owned = owned;
  }

  reader(kind, types) {
    if (this.held === undefined) throw $jsonError(`invalid type: unit variant, expected ${kind}`);
    if (types && !types.includes(this.held.type)) {
      throw $jsonError(`invalid type: ${$jsonUnexpectedContent(this.held)}, expected ${kind}`);
    }
    return new $JsonContent(this.held, this.owned);
  }

  unit() {
    if (this.held !== undefined) new $JsonContent(this.held, this.owned).unit();
  }

  newtype(read) {
    return read(this.reader("newtype variant"));
  }

  tuple(expected, fields, build, options) {
    return this.reader("tuple variant", ["seq"]).tupleStruct(expected, fields, build, options);
  }

  struct(expected, fields, build, options) {
    return this.reader("struct variant", ["map", "seq"]).struct(expected, fields, build, options);
  }
}

// serde's `missing_field`: what a field that isn't there reads as, which is
// `None` for an `Option`, and otherwise an error. An adjacently tagged
// enum's content that isn't there is read so too, and is nothing for a
// unit variant.
class $JsonMissing {
  constructor(name) {
    this.name = name;
  }

  option() {
    return undefined;
  }

  untaggedUnit() {
    return undefined;
  }
}
for (const method of [
  "bool",
  "int",
  "f64",
  "string",
  "char",
  "unit",
  "unitStruct",
  "vec",
  "tuple",
  "array",
  "map",
  "struct",
  "untaggedStruct",
  "tupleStruct",
  "enum",
  "taggedUnit",
  "internallyTagged",
  "adjacentlyTagged",
  "untagged",
]) {
  $JsonMissing.prototype[method] = function () {
    throw $jsonError(`missing field \`${this.name}\``);
  };
}

const $JSON_UTF8 = new TextDecoder();
const $JSON_POW10 = Array.from({ length: 309 }, (_, i) => Number(`1e${i}`));

// `significand * 10 + digit`, a BigInt once it's past 2^53.
function $jsonGrow(significand, digit) {
  if (typeof significand === "number") {
    const grown = significand * 10 + digit;
    if (grown <= Number.MAX_SAFE_INTEGER) return grown;
  }
  return BigInt(significand) * 10n + BigInt(digit);
}

function $jsonHexDigit(c) {
  if (c >= 48 && c <= 57) return c - 48;
  if (c >= 65 && c <= 70) return c - 55;
  if (c >= 97 && c <= 102) return c - 87;
  return -1;
}

// serde's `Unexpected` of a number, a float as serde_json writes one.
function $jsonUnexpectedNumber(n) {
  return n.kind === "f" ? `floating point \`${$jsonNumber(n.value)}\`` : `integer \`${n.value}\``;
}

function $jsonChar(s) {
  if ([...s].length === 1) return s;
  throw $jsonError(`invalid value: string ${$debugStr(s)}, expected a character`);
}

// serde's `Unexpected` of a value already read.
function $jsonUnexpectedContent({ type, value }) {
  if (type === "unit") return "null";
  if (type === "bool") return `boolean \`${value}\``;
  if (type === "num") return $jsonUnexpectedNumber(value);
  if (type === "str") return `string ${$debugStr(value)}`;
  return type === "seq" ? "sequence" : "map";
}

// The variant a name names, or `other`'s, as a derive's variant visitor finds it.
function $jsonVariantNamed(name, variants, other) {
  for (const names of variants) {
    if (typeof names === "string" ? names === name : names.includes(name)) return $jsonName(names);
  }
  if (other !== undefined) return other;
  throw variants.length === 0
    ? $jsonError(`unknown variant \`${name}\`, there are no variants`)
    : $jsonError(`unknown variant \`${name}\`, expected ${$jsonOneOf(variants)}`);
}

function $jsonName(names) {
  return typeof names === "string" ? names : names[0];
}

// The field a key names, or -1 to skip its value.
function $jsonField(key, fields, deny) {
  const i = fields.findIndex(([names]) =>
    typeof names === "string" ? names === key : names.includes(key),
  );
  if (i >= 0 || !deny) return i;
  throw fields.length === 0
    ? $jsonError(`unknown field \`${key}\`, there are no fields`)
    : $jsonError(
        `unknown field \`${key}\`, expected ${$jsonOneOf(fields.map(([names]) => names))}`,
      );
}

// serde's `OneOf`, of each name and its aliases, which serde keeps sorted.
function $jsonOneOf(entries) {
  const byCodePoint = (a, b) => {
    const [x, y] = [[...a], [...b]];
    for (let i = 0; i < Math.min(x.length, y.length); i++) {
      const d = x[i].codePointAt(0) - y[i].codePointAt(0);
      if (d !== 0) return d;
    }
    return x.length - y.length;
  };
  const names = entries.flatMap((names) =>
    typeof names === "string" ? [names] : [...names].sort(byCodePoint),
  );
  const quoted = names.map((name) => `\`${name}\``);
  if (quoted.length === 1) return quoted[0];
  if (quoted.length === 2) return `${quoted[0]} or ${quoted[1]}`;
  return `one of ${quoted.join(", ")}`;
}

// What the crate reads with: `$json.u32`, `$json.option($json.string)`.
const $json = {
  bool: (json) => json.bool(),
  u8: (json) => json.int("u8", 0, 255),
  u16: (json) => json.int("u16", 0, 65535),
  u32: (json) => json.int("u32", 0, 4294967295),
  usize: (json) => json.int("usize", 0, 4294967295),
  i8: (json) => json.int("i8", -128, 127),
  i16: (json) => json.int("i16", -32768, 32767),
  i32: (json) => json.int("i32", -2147483648, 2147483647),
  isize: (json) => json.int("isize", -2147483648, 2147483647),
  f64: (json) => json.f64(),
  string: (json) => json.string(),
  char: (json) => json.char(),
  unit: (json) => json.unit(),
  option: (read) => (json) => json.option(read),
  // A generic `T` in an `Option`, boxed when it looks like `None` (ADR 0051).
  some: (read) => (json) => $some(read(json)),
  // A generic type's reader, given its type arguments' readers (ADR 0080).
  with:
    (deserialize, ...readers) =>
    (json) =>
      deserialize(json, ...readers),
  vec: (read) => (json) => json.vec(read),
  set: (read) => (json) => new Set(json.vec(read)),
  map: (readKey, read) => (json) => json.map(readKey, read),
  tuple:
    (...reads) =>
    (json) =>
      json.tuple(reads),
  // `#[serde(try_from = "T")]`: the value of a `TryFrom`'s `Ok`, and of an
  // `Err`, serde's `Error::custom` of its `display`.
  tried: (result, display) => {
    if (result.TAG === "Err") throw $jsonError(display(result._0));
    return result._0;
  },
  // serde's impl for `Result`: `{"Ok": ..}` or `{"Err": ..}`.
  result: (ok, err) => (json) =>
    json.enum(["Ok", "Err"], (variant, content) => ({
      TAG: variant,
      _0: content.newtype(variant === "Ok" ? ok : err),
    })),
  array: (length, read) => (json) => json.array(length, read),
  // An object's keys.
  key: {
    string: (key) => key.string(),
    char: (key) => key.char(),
    bool: (key) => key.bool(),
    number: (read) => (key) => key.number(read),
  },
};

// `serde_json::from_str`: a `Result` of what `read` reads, which must be
// all there is.
function $fromJson(text, read) {
  const json = new $JsonReader(text);
  try {
    const value = read(json);
    json.end();
    return { TAG: "Ok", _0: value };
  } catch (e) {
    if (e instanceof $JsonError)
      return { TAG: "Err", _0: { message: e.message, line: e.line, column: e.column } };
    throw e;
  }
}

function $displayJsonError(e) {
  return e.line === 0 ? e.message : `${e.message} at line ${e.line} column ${e.column}`;
}
function $debugJsonError(e) {
  return `Error(${$debugStr(e.message)}, line: ${e.line}, column: ${e.column})`;
}

function $unwrapOk(result, message = "called `Result::unwrap()` on an `Err` value") {
  if (result.TAG === "Err") {
    throw new Error(message + ": " + $debug(result._0));
  }
  return result._0;
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function $debugF64(value) {
  const size = Math.abs(value);
  if (Number.isFinite(value) && size !== 0 && (size < 1e-4 || size >= 1e16)) {
    return value.toExponential().replace("e+", "e");
  }
  const text = $displayF64(value);
  return Number.isFinite(value) && !text.includes(".") ? text + ".0" : text;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

var $pageDebug, $pairDebug, $userDebug, $oddErrorDisplay;

export function report() {
  let out = "";
  const match = $fromJson(
    '{"items":[1,2],"nextItem":3,"total":2}',
    $json.with(pageDeserialize_deserialize, $json.u32),
  );
  if (match.TAG === "Ok") {
    out += `ok ${pageDebug_fmt(match._0, { fmt: (value) => String(value) })} -> ${$unwrapOk(
      $toJson(
        match._0,
        (value, json) => {
          pageSerialize_serialize(value, json, (value$1, json$1) => {
            json$1.raw(String(value$1));
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match._0)}\n`;
  }
  const match$1 = $fromJson(
    '{"items":[],"nextItem":null,"total":0}',
    $json.with(pageDeserialize_deserialize, $json.u32),
  );
  if (match$1.TAG === "Ok") {
    out += `ok ${pageDebug_fmt(match$1._0, { fmt: (value) => String(value) })} -> ${$unwrapOk(
      $toJson(
        match$1._0,
        (value$2, json$2) => {
          pageSerialize_serialize(value$2, json$2, (value$3, json$3) => {
            json$3.raw(String(value$3));
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$1._0)}\n`;
  }
  const match$2 = $fromJson(
    '{"items":["x"],"total":1}',
    $json.with(pageDeserialize_deserialize, $json.u32),
  );
  if (match$2.TAG === "Ok") {
    out += `ok ${pageDebug_fmt(match$2._0, { fmt: (value) => String(value) })} -> ${$unwrapOk(
      $toJson(
        match$2._0,
        (value$4, json$4) => {
          pageSerialize_serialize(value$4, json$4, (value$5, json$5) => {
            json$5.raw(String(value$5));
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$2._0)}\n`;
  }
  const match$3 = $fromJson(
    '{"items":[{"name":"a","age":3}],"nextItem":null,"total":1}',
    $json.with(pageDeserialize_deserialize, userDeserialize_deserialize),
  );
  if (match$3.TAG === "Ok") {
    out += `ok ${pageDebug_fmt(match$3._0, userDebug())} -> ${$unwrapOk(
      $toJson(
        match$3._0,
        (value$6, json$6) => {
          pageSerialize_serialize(value$6, json$6, userSerialize_serialize);
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$3._0)}\n`;
  }
  const match$4 = $fromJson(
    '{"items":[{"name":"a"}],"total":1}',
    $json.with(pageDeserialize_deserialize, userDeserialize_deserialize),
  );
  if (match$4.TAG === "Ok") {
    out += `ok ${pageDebug_fmt(match$4._0, userDebug())} -> ${$unwrapOk(
      $toJson(
        match$4._0,
        (value$7, json$7) => {
          pageSerialize_serialize(value$7, json$7, userSerialize_serialize);
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$4._0)}\n`;
  }
  const match$5 = $fromJson(
    '{"items":[{"items":[1],"total":1}],"nextItem":{"items":[],"total":0},"total":1}',
    $json.with(pageDeserialize_deserialize, $json.with(pageDeserialize_deserialize, $json.u8)),
  );
  if (match$5.TAG === "Ok") {
    out += `ok ${pageDebug_fmt(match$5._0, pageDebug({ fmt: (value) => String(value) }))} -> ${$unwrapOk(
      $toJson(
        match$5._0,
        (value$8, json$8) => {
          pageSerialize_serialize(value$8, json$8, (value$9, json$9) => {
            pageSerialize_serialize(value$9, json$9, (value$10, json$10) => {
              json$10.raw(String(value$10));
            });
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$5._0)}\n`;
  }
  const match$6 = $fromJson(
    '{"items":[null,1],"nextItem":null,"total":2}',
    $json.with(pageDeserialize_deserialize, $json.option($json.u8)),
  );
  if (match$6.TAG === "Ok") {
    out += `ok ${pageDebug_fmt(match$6._0, { fmt: (value) => (value == null ? "None" : `Some(${value})`) })} -> ${$unwrapOk(
      $toJson(
        match$6._0,
        (value$11, json$11) => {
          pageSerialize_serialize(value$11, json$11, (value$12, json$12) => {
            if (value$12 == null) {
              json$12.raw("null");
            } else {
              json$12.raw(String(value$12));
            }
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$6._0)}\n`;
  }
  const match$7 = $fromJson(
    '{"left":"l","right":1.5,"by_name":{"a":2}}',
    $json.with(pairDeserialize_deserialize, $json.string, $json.f64),
  );
  if (match$7.TAG === "Ok") {
    out += `ok ${pairDebug_fmt(match$7._0, { fmt: (value) => $debugStr(value) }, { fmt: (value) => $debugF64(value) })} -> ${$unwrapOk(
      $toJson(
        match$7._0,
        (value$13, json$13) => {
          pairSerialize_serialize(
            value$13,
            json$13,
            (value$14, json$14) => {
              json$14.string(value$14);
            },
            (value$15, json$15) => {
              json$15.number(value$15);
            },
          );
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$7._0)}\n`;
  }
  const match$8 = $fromJson(
    '{"left":1,"right":1.5,"by_name":{}}',
    $json.with(pairDeserialize_deserialize, $json.string, $json.f64),
  );
  if (match$8.TAG === "Ok") {
    out += `ok ${pairDebug_fmt(match$8._0, { fmt: (value) => $debugStr(value) }, { fmt: (value) => $debugF64(value) })} -> ${$unwrapOk(
      $toJson(
        match$8._0,
        (value$16, json$16) => {
          pairSerialize_serialize(
            value$16,
            json$16,
            (value$17, json$17) => {
              json$17.string(value$17);
            },
            (value$18, json$18) => {
              json$18.number(value$18);
            },
          );
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$8._0)}\n`;
  }
  const match$9 = $fromJson(
    '{"Ok":{"name":"b","age":4}}',
    $json.with(replyDeserialize_deserialize, userDeserialize_deserialize),
  );
  if (match$9.TAG === "Ok") {
    out += `ok ${replyDebug_fmt(match$9._0, userDebug())} -> ${$unwrapOk(
      $toJson(
        match$9._0,
        (value$19, json$19) => {
          replySerialize_serialize(value$19, json$19, userSerialize_serialize);
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$9._0)}\n`;
  }
  const match$10 = $fromJson(
    '{"Err":{"message":"no"}}',
    $json.with(replyDeserialize_deserialize, userDeserialize_deserialize),
  );
  if (match$10.TAG === "Ok") {
    out += `ok ${replyDebug_fmt(match$10._0, userDebug())} -> ${$unwrapOk(
      $toJson(
        match$10._0,
        (value$20, json$20) => {
          replySerialize_serialize(value$20, json$20, userSerialize_serialize);
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$10._0)}\n`;
  }
  const match$11 = $fromJson(
    '"Empty"',
    $json.with(replyDeserialize_deserialize, userDeserialize_deserialize),
  );
  if (match$11.TAG === "Ok") {
    out += `ok ${replyDebug_fmt(match$11._0, userDebug())} -> ${$unwrapOk(
      $toJson(
        match$11._0,
        (value$21, json$21) => {
          replySerialize_serialize(value$21, json$21, userSerialize_serialize);
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$11._0)}\n`;
  }
  const match$12 = $fromJson(
    '{"Ok":5}',
    $json.with(replyDeserialize_deserialize, userDeserialize_deserialize),
  );
  if (match$12.TAG === "Ok") {
    out += `ok ${replyDebug_fmt(match$12._0, userDebug())} -> ${$unwrapOk(
      $toJson(
        match$12._0,
        (value$22, json$22) => {
          replySerialize_serialize(value$22, json$22, userSerialize_serialize);
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$12._0)}\n`;
  }
  const match$13 = $fromJson(
    '{"status":"done","data":[1,2]}',
    $json.with(statusDeserialize_deserialize, $json.vec($json.u8)),
  );
  if (match$13.TAG === "Ok") {
    out += `ok ${statusDebug_fmt(match$13._0, { fmt: (value) => `[${value.map((item) => String(item)).join(", ")}]` })} -> ${$unwrapOk(
      $toJson(
        match$13._0,
        (value$23, json$23) => {
          statusSerialize_serialize(value$23, json$23, (value$24, json$24) => {
            json$24.beginArray();
            for (const item of value$24) {
              json$24.element();
              json$24.raw(String(item));
            }
            json$24.endArray();
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$13._0)}\n`;
  }
  const match$14 = $fromJson(
    '{"status":"failed","reason":"x"}',
    $json.with(statusDeserialize_deserialize, $json.vec($json.u8)),
  );
  if (match$14.TAG === "Ok") {
    out += `ok ${statusDebug_fmt(match$14._0, { fmt: (value) => `[${value.map((item) => String(item)).join(", ")}]` })} -> ${$unwrapOk(
      $toJson(
        match$14._0,
        (value$25, json$25) => {
          statusSerialize_serialize(value$25, json$25, (value$26, json$26) => {
            json$26.beginArray();
            for (const item$1 of value$26) {
              json$26.element();
              json$26.raw(String(item$1));
            }
            json$26.endArray();
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$14._0)}\n`;
  }
  const match$15 = $fromJson(
    '{"data":[1],"status":"done"}',
    $json.with(statusDeserialize_deserialize, $json.vec($json.u8)),
  );
  if (match$15.TAG === "Ok") {
    out += `ok ${statusDebug_fmt(match$15._0, { fmt: (value) => `[${value.map((item) => String(item)).join(", ")}]` })} -> ${$unwrapOk(
      $toJson(
        match$15._0,
        (value$27, json$27) => {
          statusSerialize_serialize(value$27, json$27, (value$28, json$28) => {
            json$28.beginArray();
            for (const item$2 of value$28) {
              json$28.element();
              json$28.raw(String(item$2));
            }
            json$28.endArray();
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$15._0)}\n`;
  }
  const match$16 = $fromJson(
    '{"status":"done","data":{"name":"c","age":5}}',
    $json.with(statusDeserialize_deserialize, userDeserialize_deserialize),
  );
  if (match$16.TAG === "Ok") {
    out += `ok ${statusDebug_fmt(match$16._0, userDebug())} -> ${$unwrapOk(
      $toJson(
        match$16._0,
        (value$29, json$29) => {
          statusSerialize_serialize(value$29, json$29, userSerialize_serialize);
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$16._0)}\n`;
  }
  const match$17 = $fromJson(
    '{"t":"One","c":true}',
    $json.with(taggedDeserialize_deserialize, $json.bool),
  );
  if (match$17.TAG === "Ok") {
    out += `ok ${taggedDebug_fmt(match$17._0, { fmt: (value) => String(value) })} -> ${$unwrapOk(
      $toJson(
        match$17._0,
        (value$30, json$30) => {
          taggedSerialize_serialize(value$30, json$30, (value$31, json$31) => {
            json$31.raw(String(value$31));
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$17._0)}\n`;
  }
  const match$18 = $fromJson(
    '{"c":[true,false],"t":"Many"}',
    $json.with(taggedDeserialize_deserialize, $json.bool),
  );
  if (match$18.TAG === "Ok") {
    out += `ok ${taggedDebug_fmt(match$18._0, { fmt: (value) => String(value) })} -> ${$unwrapOk(
      $toJson(
        match$18._0,
        (value$32, json$32) => {
          taggedSerialize_serialize(value$32, json$32, (value$33, json$33) => {
            json$33.raw(String(value$33));
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$18._0)}\n`;
  }
  const match$19 = $fromJson(
    "5",
    $json.with(eitherDeserialize_deserialize, $json.u8, $json.string),
  );
  if (match$19.TAG === "Ok") {
    out += `ok ${eitherDebug_fmt(match$19._0, { fmt: (value) => String(value) }, { fmt: (value) => $debugStr(value) })} -> ${$unwrapOk(
      $toJson(
        match$19._0,
        (value$34, json$34) => {
          eitherSerialize_serialize(
            value$34,
            json$34,
            (value$35, json$35) => {
              json$35.raw(String(value$35));
            },
            (value$36, json$36) => {
              json$36.string(value$36);
            },
          );
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$19._0)}\n`;
  }
  const match$20 = $fromJson(
    '"s"',
    $json.with(eitherDeserialize_deserialize, $json.u8, $json.string),
  );
  if (match$20.TAG === "Ok") {
    out += `ok ${eitherDebug_fmt(match$20._0, { fmt: (value) => String(value) }, { fmt: (value) => $debugStr(value) })} -> ${$unwrapOk(
      $toJson(
        match$20._0,
        (value$37, json$37) => {
          eitherSerialize_serialize(
            value$37,
            json$37,
            (value$38, json$38) => {
              json$38.raw(String(value$38));
            },
            (value$39, json$39) => {
              json$39.string(value$39);
            },
          );
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$20._0)}\n`;
  }
  const match$21 = $fromJson(
    "true",
    $json.with(eitherDeserialize_deserialize, $json.u8, $json.string),
  );
  if (match$21.TAG === "Ok") {
    out += `ok ${eitherDebug_fmt(match$21._0, { fmt: (value) => String(value) }, { fmt: (value) => $debugStr(value) })} -> ${$unwrapOk(
      $toJson(
        match$21._0,
        (value$40, json$40) => {
          eitherSerialize_serialize(
            value$40,
            json$40,
            (value$41, json$41) => {
              json$41.raw(String(value$41));
            },
            (value$42, json$42) => {
              json$42.string(value$42);
            },
          );
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$21._0)}\n`;
  }
  const match$22 = $fromJson(
    '{"left":1,"right":2,"by_name":{"k":3}}',
    $json.with(
      wrapDeserialize_deserialize,
      $json.with(pairDeserialize_deserialize, $json.u8, $json.u8),
    ),
  );
  if (match$22.TAG === "Ok") {
    out += `ok ${wrapDebug_fmt(match$22._0, pairDebug({ fmt: (value) => String(value) }, { fmt: (value) => String(value) }))} -> ${$unwrapOk(
      $toJson(
        match$22._0,
        (value$43, json$43) => {
          wrapSerialize_serialize(value$43, json$43, (value$44, json$44) => {
            pairSerialize_serialize(
              value$44,
              json$44,
              (value$45, json$45) => {
                json$45.raw(String(value$45));
              },
              (value$46, json$46) => {
                json$46.raw(String(value$46));
              },
            );
          });
        },
        false,
      ),
    )}\n`;
  } else {
    out += `err ${$displayJsonError(match$22._0)}\n`;
  }
  const page = { items: [{ name: "z", age: 9 }], next_item: undefined, total: 1 };
  out += $unwrapOk(
    $toJson(
      page,
      (value$47, json$47) => {
        pageSerialize_serialize(value$47, json$47, userSerialize_serialize);
      },
      true,
    ),
  );
  out += "\n";
  for (const text of [
    '{"result":{"Ok":5},"all":[{"Ok":true},{"Err":3}]}',
    '{"result":{"Err":"bad"},"all":[]}',
    '{"result":"Ok","all":[]}',
    '{"result":{"Maybe":1},"all":[]}',
    '{"result":{"Ok":"x"},"all":[]}',
  ]) {
    const match$23 = $fromJson(text, outcomeDeserialize_deserialize);
    if (match$23.TAG === "Ok") {
      out += `ok ${outcomeDebug_fmt(match$23._0)} -> ${$unwrapOk($toJson(match$23._0, outcomeSerialize_serialize, false))}\n`;
    } else {
      out += `err ${$displayJsonError(match$23._0)}\n`;
    }
  }
  for (const text$1 of [
    '{"email":"a@b","temp":{"c":21.5},"even":4}',
    '{"email":"ab","temp":{"c":21.5},"even":4}',
    '{"email":"a@b","temp":{"c":21.5},"even":3}',
    '{"email":"a@b","temp":{"celsius":21.5},"even":4}',
    '{"email":5,"temp":{"c":1},"even":4}',
  ]) {
    const match$24 = $fromJson(text$1, contactDeserialize_deserialize);
    if (match$24.TAG === "Ok") {
      out += `ok ${contactDebug_fmt(match$24._0)}\n`;
    } else {
      out += `err ${$displayJsonError(match$24._0)}\n`;
    }
  }
  for (const text$2 of ['"x@y"', '"xy"']) {
    const match$25 = $fromJson(text$2, emailDeserialize_deserialize);
    if (match$25.TAG === "Ok") {
      out += `ok ${emailDebug_fmt(match$25._0)}\n`;
    } else {
      out += `err ${$displayJsonError(match$25._0)}\n`;
    }
  }
  const temp = { celsius: -3 };
  out += $unwrapOk($toJson(temp, tempSerialize_serialize, false));
  out += "\n";
  out += $unwrapOk(
    $toJson(
      [temp, temp],
      (value$48, json$48) => {
        json$48.beginArray();
        for (const item$3 of value$48) {
          json$48.element();
          tempSerialize_serialize(item$3, json$48);
        }
        json$48.endArray();
      },
      false,
    ),
  );
  out += "\n";
  return out;
}

function pageDebug_fmt(page, TDebug) {
  return `Page { items: [${page.items.map((item) => TDebug.fmt(item)).join(", ")}], next_item: ${page.next_item == null ? "None" : `Some(${TDebug.fmt($someValue(page.next_item))})`}, total: ${page.total} }`;
}

function pairDebug_fmt(pair, ADebug, BDebug) {
  return `Pair { left: ${ADebug.fmt(pair.left)}, right: ${BDebug.fmt(pair.right)}, by_name: {${Array.from(
    $sortedEntries(pair.by_name, $cmp),
  )
    .map(([key, value]) => `${$debugStr(key)}: ${BDebug.fmt(value)}`)
    .join(", ")}} }`;
}

function replyDebug_fmt(reply, TDebug) {
  if (reply.TAG === "Ok") {
    return `Ok(${TDebug.fmt(reply._0)})`;
  } else if (reply.TAG === "Err") {
    return `Err { message: ${$debugStr(reply.message)} }`;
  } else {
    return "Empty";
  }
}

function statusDebug_fmt(status, TDebug) {
  if (status.TAG === "Done") {
    return `Done { data: ${TDebug.fmt(status.data)} }`;
  } else {
    return `Failed { reason: ${$debugStr(status.reason)} }`;
  }
}

function taggedDebug_fmt(tagged, TDebug) {
  if (tagged.TAG === "One") {
    return `One(${TDebug.fmt(tagged._0)})`;
  } else {
    return `Many([${tagged._0.map((item) => TDebug.fmt(item)).join(", ")}])`;
  }
}

function eitherDebug_fmt(either, LDebug, RDebug) {
  if (either.TAG === "Left") {
    return `Left(${LDebug.fmt(either._0)})`;
  } else {
    return `Right(${RDebug.fmt(either._0)})`;
  }
}

function wrapDebug_fmt(wrap, TDebug) {
  return `Wrap(${TDebug.fmt(wrap[0])})`;
}

function userDebug_fmt(user) {
  return `User { name: ${$debugStr(user.name)}, age: ${user.age} }`;
}

function outcomeDebug_fmt(outcome) {
  return `Outcome { result: ${outcome.result.TAG === "Ok" ? `Ok(${outcome.result._0})` : `Err(${$debugStr(outcome.result._0)})`}, all: [${outcome.all.map((item) => (item.TAG === "Ok" ? `Ok(${item._0})` : `Err(${item._0})`)).join(", ")}] }`;
}

function tempDebug_fmt(temp) {
  return `Temp { celsius: ${$debugF64(temp.celsius)} }`;
}

function tempFromRawTemp_from(raw) {
  return { celsius: raw.c };
}

function rawTempFromTemp_from(temp) {
  return { c: temp.celsius };
}

function emailDebug_fmt(email) {
  return `Email(${$debugStr(email[0])})`;
}

function emailTryFromString_try_from(s) {
  if (s.includes("@")) {
    return { TAG: "Ok", _0: [s] };
  } else {
    return { TAG: "Err", _0: `\`${s}\` is not an email` };
  }
}

function oddErrorDisplay_fmt(oddError) {
  return `${oddError[0]} is odd`;
}

function evenDebug_fmt(even) {
  return `Even(${even[0]})`;
}

function evenTryFromU32_try_from(n) {
  if (n % 2 === 0) {
    return { TAG: "Ok", _0: [n] };
  } else {
    return { TAG: "Err", _0: [n] };
  }
}

function contactDebug_fmt(contact) {
  return `Contact { email: ${emailDebug_fmt(contact.email)}, temp: ${tempDebug_fmt(contact.temp)}, even: ${evenDebug_fmt(contact.even)} }`;
}

export function pageDebug(TDebug) {
  if ($pageDebug === undefined) {
    $pageDebug = new WeakMap();
  }
  return $traitImpl($pageDebug, [TDebug], () => ({ fmt: (arg0) => pageDebug_fmt(arg0, TDebug) }));
}

export function pairDebug(ADebug, BDebug) {
  if ($pairDebug === undefined) {
    $pairDebug = new WeakMap();
  }
  return $traitImpl($pairDebug, [ADebug, BDebug], () => ({
    fmt: (arg0) => pairDebug_fmt(arg0, ADebug, BDebug),
  }));
}

export function userDebug() {
  if ($userDebug === undefined) {
    $userDebug = { fmt: userDebug_fmt };
  }
  return $userDebug;
}

export function oddErrorDisplay() {
  if ($oddErrorDisplay === undefined) {
    $oddErrorDisplay = { fmt: oddErrorDisplay_fmt };
  }
  return $oddErrorDisplay;
}

function pageSerialize_serialize(page, json, writeT) {
  json.beginObject();
  json.key("items");
  json.beginArray();
  for (const item of page.items) {
    json.element();
    writeT(item, json);
  }
  json.endArray();
  json.key("nextItem");
  if (page.next_item == null) {
    json.raw("null");
  } else {
    writeT($someValue(page.next_item), json);
  }
  json.key("total");
  json.raw(String(page.total));
  json.endObject();
}

function pageDeserialize_deserialize(json, readT) {
  return json.struct(
    "struct Page",
    [
      ["items", $json.vec(readT)],
      ["nextItem", $json.option($json.some(readT))],
      ["total", $json.u32],
    ],
    ([items, next_item, total]) => ({ items, next_item, total }),
  );
}

function pairSerialize_serialize(pair, json, writeA, writeB) {
  json.beginObject();
  json.key("left");
  writeA(pair.left, json);
  json.key("right");
  writeB(pair.right, json);
  json.key("by_name");
  json.beginObject();
  for (const [key, item] of $sortedEntries(pair.by_name, $cmp)) {
    json.key(key);
    writeB(item, json);
  }
  json.endObject();
  json.endObject();
}

function pairDeserialize_deserialize(json, readA, readB) {
  return json.struct(
    "struct Pair",
    [
      ["left", readA],
      ["right", readB],
      ["by_name", $json.map($json.key.string, readB)],
    ],
    ([left, right, by_name]) => ({ left, right, by_name }),
  );
}

function replySerialize_serialize(reply, json, writeT) {
  if (reply.TAG === "Ok") {
    json.beginObject();
    json.key("Ok");
    writeT(reply._0, json);
    json.endObject();
  } else if (reply.TAG === "Err") {
    json.beginObject();
    json.key("Err");
    json.beginObject();
    json.key("message");
    json.string(reply.message);
    json.endObject();
    json.endObject();
  } else {
    json.string("Empty");
  }
}

function replyDeserialize_deserialize(json, readT) {
  return json.enum(["Ok", "Err", "Empty"], (variant, content) => {
    if (variant === "Ok") {
      return { TAG: "Ok", _0: content.newtype(readT) };
    } else if (variant === "Err") {
      return content.struct(
        "struct variant Reply::Err",
        [["message", $json.string]],
        ([message]) => ({ TAG: "Err", message }),
      );
    } else {
      content.unit();
      return "Empty";
    }
  });
}

function statusSerialize_serialize(status, json, writeT) {
  if (status.TAG === "Done") {
    json.beginObject();
    json.key("status");
    json.string("done");
    json.key("data");
    writeT(status.data, json);
    json.endObject();
  } else {
    json.beginObject();
    json.key("status");
    json.string("failed");
    json.key("reason");
    json.string(status.reason);
    json.endObject();
  }
}

function statusDeserialize_deserialize(json, readT) {
  return json.internallyTagged(
    "status",
    "internally tagged enum Status",
    ["done", "failed"],
    (variant, content) => {
      if (variant === "done") {
        return content.struct("struct variant Status::Done", [["data", readT]], ([data]) => ({
          TAG: "Done",
          data,
        }));
      } else {
        return content.struct(
          "struct variant Status::Failed",
          [["reason", $json.string]],
          ([reason]) => ({ TAG: "Failed", reason }),
        );
      }
    },
  );
}

function taggedSerialize_serialize(tagged, json, writeT) {
  if (tagged.TAG === "One") {
    json.beginObject();
    json.key("t");
    json.string("One");
    json.key("c");
    writeT(tagged._0, json);
    json.endObject();
  } else {
    json.beginObject();
    json.key("t");
    json.string("Many");
    json.key("c");
    json.beginArray();
    for (const item of tagged._0) {
      json.element();
      writeT(item, json);
    }
    json.endArray();
    json.endObject();
  }
}

function taggedDeserialize_deserialize(json, readT) {
  return json.adjacentlyTagged(
    "t",
    "c",
    "adjacently tagged enum Tagged",
    ["One", "Many"],
    (variant, content) => {
      if (variant === "One") {
        return { TAG: "One", _0: readT(content) };
      } else {
        return { TAG: "Many", _0: $json.vec(readT)(content) };
      }
    },
  );
}

function eitherSerialize_serialize(either, json, writeL, writeR) {
  if (either.TAG === "Left") {
    writeL(either._0, json);
  } else {
    writeR(either._0, json);
  }
}

function eitherDeserialize_deserialize(json, readL, readR) {
  return json.untagged("data did not match any variant of untagged enum Either", [
    (content) => ({ TAG: "Left", _0: readL(content) }),
    (content) => ({ TAG: "Right", _0: readR(content) }),
  ]);
}

function wrapSerialize_serialize(wrap, json, writeT) {
  writeT(wrap[0], json);
}

function wrapDeserialize_deserialize(json, readT) {
  return [readT(json)];
}

function userSerialize_serialize(user, json) {
  json.beginObject();
  json.key("name");
  json.string(user.name);
  json.key("age");
  json.raw(String(user.age));
  json.endObject();
}

function userDeserialize_deserialize(json) {
  return json.struct(
    "struct User",
    [
      ["name", $json.string],
      ["age", $json.u8],
    ],
    ([name, age]) => ({ name, age }),
  );
}

function outcomeSerialize_serialize(outcome, json) {
  json.beginObject();
  json.key("result");
  if (outcome.result.TAG === "Ok") {
    json.beginObject();
    json.key("Ok");
    json.raw(String(outcome.result._0));
    json.endObject();
  } else {
    json.beginObject();
    json.key("Err");
    json.string(outcome.result._0);
    json.endObject();
  }
  json.key("all");
  json.beginArray();
  for (const item of outcome.all) {
    json.element();
    if (item.TAG === "Ok") {
      json.beginObject();
      json.key("Ok");
      json.raw(String(item._0));
      json.endObject();
    } else {
      json.beginObject();
      json.key("Err");
      json.raw(String(item._0));
      json.endObject();
    }
  }
  json.endArray();
  json.endObject();
}

function outcomeDeserialize_deserialize(json) {
  return json.struct(
    "struct Outcome",
    [
      ["result", $json.result($json.u32, $json.string)],
      ["all", $json.vec($json.result($json.bool, $json.u8))],
    ],
    ([result, all]) => ({ result, all }),
  );
}

function tempSerialize_serialize(temp, json) {
  const value = rawTempFromTemp_from(temp);
  rawTempSerialize_serialize(value, json);
}

function emailDeserialize_deserialize(json) {
  return $json.tried(emailTryFromString_try_from($json.string(json)), (error) => error);
}

function contactDeserialize_deserialize(json) {
  return json.struct(
    "struct Contact",
    [
      ["email", emailDeserialize_deserialize],
      ["temp", tempDeserialize_deserialize],
      ["even", evenDeserialize_deserialize],
    ],
    ([email, temp, even]) => ({ email, temp, even }),
  );
}

function tempDeserialize_deserialize(json) {
  return tempFromRawTemp_from(rawTempDeserialize_deserialize(json));
}

function rawTempSerialize_serialize(rawTemp, json) {
  json.beginObject();
  json.key("c");
  json.number(rawTemp.c);
  json.endObject();
}

function evenDeserialize_deserialize(json) {
  return $json.tried(evenTryFromU32_try_from($json.u32(json)), (error) =>
    oddErrorDisplay_fmt(error),
  );
}

function rawTempDeserialize_deserialize(json) {
  return json.struct("struct RawTemp", [["c", $json.f64]], ([c]) => ({ c }));
}
//# sourceMappingURL=api.js.map
