// Generated by rust-js from examples/values.rs. Do not edit.

function $index(items, index) {
  if (index < 0 || index >= items.length)
    throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return items[index];
}

function $at(items, index) {
  if (index < 0 || index >= items.length)
    throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return index;
}

// Shortest round-trip decimal, using exact rational arithmetic.
// Rust Display uses decimal notation, including for very small/large values.
// Not JS's `String(x)`, though its digits are also the shortest: when two are
// equally close, JS takes the even one (1888570120608320.2), and Rust the
// larger (1888570120608320.3).
function $displayF64(value) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const x = Math.abs(value);
  if (x === 0) return sign + "0";

  const bitsView = new DataView(new ArrayBuffer(8));
  bitsView.setFloat64(0, x);
  const bits = bitsView.getBigUint64(0);
  const exponentBits = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponentBits === 0 ? fraction : fraction + (1n << 52n);
  const binaryExponent = exponentBits === 0 ? -1074 : exponentBits - 1023 - 52;
  const numerator = binaryExponent >= 0 ? significand << BigInt(binaryExponent) : significand;
  const denominator = binaryExponent < 0 ? 1n << BigInt(-binaryExponent) : 1n;

  // The floating-point logarithm is only an estimate; correct it exactly.
  let exponent = Math.floor(Math.log10(x));
  const atLeastPowerOfTen = (e) =>
    e >= 0
      ? numerator >= denominator * 10n ** BigInt(e)
      : numerator * 10n ** BigInt(-e) >= denominator;
  while (!atLeastPowerOfTen(exponent)) exponent--;
  while (atLeastPowerOfTen(exponent + 1)) exponent++;

  for (let precision = 1; precision <= 17; precision++) {
    const power = exponent - precision + 1;
    const n = power < 0 ? numerator * 10n ** BigInt(-power) : numerator;
    const d = power > 0 ? denominator * 10n ** BigInt(power) : denominator;
    const floor = n / d;
    const rounded = floor + (2n * (n % d) >= d ? 1n : 0n);
    // The rounding interval can be asymmetric at a binary power boundary.
    let best;
    let bestDistance;
    for (const candidate of [rounded, rounded - 1n, rounded + 1n]) {
      if (candidate > 0n && Number(`${candidate}e${power}`) === x) {
        const delta = candidate * d - n;
        const distance = delta < 0n ? -delta : delta;
        if (
          best === undefined ||
          distance < bestDistance ||
          (distance === bestDistance && candidate > best)
        ) {
          best = candidate;
          bestDistance = distance;
        }
      }
    }
    if (best !== undefined) {
      let digits = best.toString();
      let decimalPower = power;
      while (digits.endsWith("0")) {
        digits = digits.slice(0, -1);
        decimalPower++;
      }
      const point = digits.length + decimalPower;
      const body =
        point <= 0
          ? "0." + "0".repeat(-point) + digits
          : point >= digits.length
            ? digits + "0".repeat(point - digits.length)
            : digits.slice(0, point) + "." + digits.slice(point);
      return sign + body;
    }
  }
  throw new Error("No f64 round-trip decimal found");
}

function $eq(a, b) {
  if (a === b || (a == null && b == null)) {
    return true;
  }
  if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) {
    return false;
  }
  if (Array.isArray(a)) {
    return Array.isArray(b) && a.length === b.length && a.every((x, i) => $eq(x, b[i]));
  }
  const keys = Object.keys(a);
  return keys.length === Object.keys(b).length && keys.every((k) => $eq(a[k], b[k]));
}

function $sortedEntries(map, cmp) {
  return Array.from(map).sort((a, b) => cmp(a[0], b[0]));
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function $debugF64(value) {
  const size = Math.abs(value);
  if (Number.isFinite(value) && size !== 0 && (size < 1e-4 || size >= 1e16)) {
    return value.toExponential().replace("e+", "e");
  }
  const text = $displayF64(value);
  return Number.isFinite(value) && !text.includes(".") ? text + ".0" : text;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

function $max(items) {
  return items.length === 0 ? undefined : items.reduce((max, x) => (x >= max ? x : max));
}

var $valueDisplay;

export const Value = {
  get(value, key) {
    if (value.TAG === "Obj") {
      return value._0.get(key);
    } else {
      return undefined;
    }
  },
  at(value, i) {
    if (value.TAG === "List") {
      return value._0[i];
    } else {
      return undefined;
    }
  },
  as_num(value) {
    if (value.TAG === "Num") {
      return value._0;
    } else {
      return undefined;
    }
  },
  as_str(value) {
    if (value.TAG === "Str") {
      return value._0;
    } else {
      return undefined;
    }
  },
  is_null(value) {
    return value === "Null";
  },
  depth(value) {
    if (value.TAG === "List") {
      return (1 + ($max(value._0.map((x) => Value.depth(x))) ?? 0)) >>> 0;
    } else if (value.TAG === "Obj") {
      return (
        (1 +
          ($max(
            $sortedEntries(value._0, $cmp)
              .map((entry) => entry[1])
              .map(Value.depth),
          ) ?? 0)) >>>
        0
      );
    } else {
      return 0;
    }
  },
  pretty(value, indent, out) {
    const pad = " ".repeat(indent);
    if (value.TAG === "List" && value._0.length === 0) {
      out.value += "[]";
    } else if (value.TAG === "List") {
      out.value += "[\n";
      for (const [i, x] of value._0.entries()) {
        out.value += pad;
        out.value += "  ";
        Value.pretty(x, (indent + 2) >>> 0, out);
        if ((i + 1) >>> 0 < value._0.length) {
          out.value += ",";
        }
        out.value += "\n";
      }
      out.value += pad;
      out.value += "]";
    } else if (value.TAG === "Obj") {
      out.value += "{";
      let first = true;
      for (const [k, x$1] of $sortedEntries(value._0, $cmp)) {
        if (!first) {
          out.value += ", ";
        }
        first = false;
        out.value += `${$debugStr(k)}: `;
        Value.pretty(x$1, indent, out);
      }
      out.value += "}";
    } else {
      out.value += valueDisplay_fmt(value);
    }
  },
};

function price(v) {
  const value = Value.get(v, "items");
  if (value == null) {
    return undefined;
  }
  const item = Value.at(value, 1);
  if (item == null) {
    return undefined;
  }
  const value$1 = Value.get(item, "price");
  if (value$1 == null) {
    return undefined;
  }
  const p = Value.as_num(value$1);
  if (p == null) {
    return undefined;
  }
  const option = Value.get(v, "qty");
  return p * ((option != null ? Value.as_num(option) : undefined) ?? 1);
}

export function tree() {
  let shop = new Map();
  shop.set("name", { TAG: "Str", _0: 'corner "shop"' });
  shop.set("open", { TAG: "Bool", _0: true });
  shop.set("qty", { TAG: "Num", _0: 3 });
  let apple = new Map();
  apple.set("price", { TAG: "Num", _0: 0.5 });
  let pear = new Map();
  pear.set("price", { TAG: "Num", _0: 1.25 });
  pear.set("tags", { TAG: "List", _0: [{ TAG: "Str", _0: "ripe" }, "Null"] });
  shop.set("items", {
    TAG: "List",
    _0: [
      { TAG: "Obj", _0: apple },
      { TAG: "Obj", _0: pear },
      { TAG: "List", _0: [] },
    ],
  });
  const v = { TAG: "Obj", _0: shop };
  let out = "";
  out += `${valueDisplay_fmt(v)}\n`;
  let p = "";
  const out$1 = { value: p };
  Value.pretty(v, 0, out$1);
  p = out$1.value;
  out += `${p}\n`;
  const option = Value.get(v, "name");
  const s = option != null ? Value.as_str(option) : undefined;
  const name = s != null ? s.toUpperCase() : undefined;
  const option$1 = Value.get(v, "missing");
  const arg = price(v);
  out += `${arg == null ? "None" : `Some(${$debugF64(arg)})`} ${name == null ? "None" : `Some(${$debugStr(name)})`} ${Value.depth(v)} ${option$1 == null || Value.is_null(option$1)}\n`;
  const cloneValue = (value) =>
    value.TAG === "List"
      ? { ...value, _0: value._0.map((item) => cloneValue(item)) }
      : value.TAG === "Obj"
        ? {
            ...value,
            _0: new Map(Array.from(value._0).map(([key, value]) => [key, cloneValue(value)])),
          }
        : value;
  const copy = cloneValue(v);
  out += `${$eq(copy, v)} ${$eq({ TAG: "Num", _0: 1 }, { TAG: "Num", _0: 1 })}\n`;
  return out;
}

function bump(count, by) {
  count.value = (count.value + by) >>> 0;
  return count.value;
}

function log(out, line, count) {
  if (out.value.length !== 0) {
    out.value += "|";
  }
  out.value += line;
  bump(count, 1);
}

function settle(slot) {
  slot.value = ((slot.value ?? 0) + 10) >>> 0;
}

export function boxes() {
  let n = 0;
  const count = { value: n };
  const result = bump(count, 5);
  n = count.value;
  const first = result;
  const count$1 = { value: n };
  const result$1 = bump(count$1, 2);
  n = count$1.value;
  const total = (((first + result$1) >>> 0) + n) >>> 0;
  let text = "";
  for (const w of ["a", "b", "c"]) {
    const out = { value: text };
    const count$2 = { value: n };
    log(out, w, count$2);
    text = out.value;
    n = count$2.value;
  }
  let stats = { hits: 1, last: undefined };
  const count$3 = { value: stats.hits };
  bump(count$3, 4);
  stats.hits = count$3.value;
  const slot = { value: stats.last };
  settle(slot);
  stats.last = slot.value;
  const slot$1 = { value: stats.last };
  settle(slot$1);
  stats.last = slot$1.value;
  let counts = [1, 2, 3];
  const count$4 = { value: $index(counts, 1) };
  bump(count$4, 40);
  counts[$at(counts, 1)] = count$4.value;
  return `${first} ${total} ${n} ${text} ${stats.hits} ${stats.last == null ? "None" : `Some(${stats.last})`} [${counts.map((item) => String(item)).join(", ")}]`;
}

export function report() {
  return `${tree()}${boxes()}\n`;
}

function valueDisplay_fmt(value) {
  let f = "";
  if (value === "Null") {
    f += "null";
  } else if (value.TAG === "Bool") {
    f += String(value._0);
  } else if (value.TAG === "Num") {
    f += $displayF64(value._0);
  } else if (value.TAG === "Str") {
    f += $debugStr(value._0);
  } else if (value.TAG === "List") {
    f += "[";
    for (const [i, x] of value._0.entries()) {
      if (i > 0) {
        f += ",";
      }
      f += valueDisplay_fmt(x);
    }
    f += "]";
  } else {
    f += "{";
    for (const item of $sortedEntries(value._0, $cmp).entries()) {
      if (item[0] > 0) {
        f += ",";
      }
      f += `${$debugStr(item[1][0])}:${valueDisplay_fmt(item[1][1])}`;
    }
    f += "}";
  }
  return f;
}

export function valueDisplay() {
  if ($valueDisplay === undefined) {
    $valueDisplay = { fmt: valueDisplay_fmt };
  }
  return $valueDisplay;
}
//# sourceMappingURL=values.js.map
