// Generated by rust-js from examples/modules/geometry/area.rs. Do not edit.

import * as lib from "../lib.js";
import * as util from "./util.js";
import * as util$1 from "../util.js";

export function square(x) {
  const c = lib.clamp(x);
  return Math.imul(c, c) >>> 0;
}

export function mixed(x) {
  return util$1.double(x) + util.triple(x) >>> 0;
}

export function shadowed(x) {
  const util$2 = x + 1 >>> 0;
  return util$1.double(util$2);
}
//# sourceMappingURL=area.js.map
