// Generated by rust-js from examples/countdown.rs. Do not edit.

function $unwrap(value, message = "called `Option::unwrap()` on a `None` value") {
  if (value == null) {
    throw new Error(message);
  }
  return value;
}

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function count_down(output, from) {
  let n = from;
  while (n > 0) {
    output.textContent = String(n);
    await sleep(500);
    n = n - 1 >>> 0;
  }
  output.textContent = "Go!";
}

export function main() {
  const app = $unwrap(document.getElementById("app"), "the page has an #app");
  const start = document.createElement("button");
  start.textContent = "Start";
  const output = document.createElement("output");
  const running = { value: false };
  start.addEventListener("click", () => {
    if (running.value) {
      return;
    }
    running.value = true;
    const running$1 = running;
    (async () => {
      await count_down(output, 3);
      running$1.value = false;
    })();
  });
  app.append(start);
  app.append(output);
}
//# sourceMappingURL=countdown.js.map
