// Generated by rust-js from /wasm/web/rust/components/toolbar.rs. Do not edit.

import { ExamplePicker } from "./example_picker.jsx";
import { StatusLine } from "./status_line.jsx";
import { CONTROL } from "../styles.js";

export function Toolbar({ examples, example, onExample, ready, onCompile, status }) {
  const onTest = onCompile;
  return (
    <div className="mb-3 flex flex-wrap items-center gap-x-3 gap-y-2">
      <ExamplePicker examples={examples} chosen={example} onChoose={onExample} />
      <button id="compile" className={CONTROL} disabled={!ready} onClick={() => onCompile(false)}>
        Compile
      </button>
      <button
        id="test"
        className={CONTROL}
        disabled={!ready}
        title="Compile with --test and run the #[test] functions"
        onClick={() => onTest(true)}
      >
        Test
      </button>
      <kbd className="font-mono text-xs text-muted">⌘/Ctrl-Enter</kbd>
      <StatusLine status={status} />
    </div>
  );
}
//# sourceMappingURL=toolbar.jsx.map
