// Generated by rust-js from examples/thread_locals.rs. Do not edit.

const COUNT = { value: 0 };
const LOG = { value: [] };
const START = { value: Math.imul(10, 4) + 2 | 0 };

export function bump() {
  COUNT.value = COUNT.value + 1 >>> 0;
  return COUNT.value;
}

export function record(line) {
  ((log) => {
    log.push(line);
  })(LOG.value);
  return LOG.value.length;
}

export function start() {
  return START.value;
}
//# sourceMappingURL=thread_locals.js.map
