// Generated by rust-js from examples/strings.rs. Do not edit.

function $stripPrefix(s, prefix) {
  return s.startsWith(prefix) ? s.slice(prefix.length) : undefined;
}

function $stripSuffix(s, suffix) {
  return s.endsWith(suffix) ? s.slice(0, s.length - suffix.length) : undefined;
}

function $splitOnce(s, separator) {
  const i = s.indexOf(separator);
  return i < 0 ? undefined : [s.slice(0, i), s.slice(i + separator.length)];
}

function $rsplitOnce(s, separator) {
  const i = s.lastIndexOf(separator);
  return i < 0 ? undefined : [s.slice(0, i), s.slice(i + separator.length)];
}

export function labeled(name, n) {
  return name + ": " + String(n) + " item" + (n === 1 ? "" : "s");
}

export function tests(s) {
  return [
    s.startsWith("ab"),
    s.endsWith("c"),
    s.includes("b/"),
    s.includes("/")
  ];
}

export function cases(s) {
  return [s.toUpperCase(), s.toLowerCase()];
}

export function trimmed(s) {
  return [s.trimStart(), s.trimEnd()];
}

export function replaced(s) {
  return s.replaceAll("/", " / ").replaceAll("a", "A");
}

export function module_name(path) {
  let file;
  const match = $stripPrefix(path, "src/");
  if (match != null) {
    file = match;
  } else {
    file = path;
  }
  return $stripSuffix(file, ".rs") ?? file;
}

export function parts(path) {
  let kept = [];
  let empty = 0;
  for (const part of path.split("/")) {
    if (part.length === 0) {
      empty = empty + 1 >>> 0;
    } else {
      kept.push(part);
    }
  }
  const last = path.split("/").at(-1) ?? "";
  return [
    kept,
    empty,
    last
  ];
}

export function rejoined(path) {
  const pieces = path.split("/");
  return pieces.join(" > ");
}

export function built(n) {
  let s = "";
  for (let i = 0; i < n; i++) {
    s = s + String(i);
    s = s + ",";
  }
  s = s + "!";
  return s;
}

export function separator(windows) {
  const c = windows ? "\\" : "/";
  const same = c === "/";
  return c + (same ? " (unix)" : " (windows)");
}

export function folder_and_file(path) {
  let first;
  const match = $splitOnce(path, "/");
  if (match != null) {
    first = match[0];
  } else {
    first = "";
  }
  let file;
  const match$1 = $rsplitOnce(path, "/");
  if (match$1 != null) {
    file = match$1[1];
  } else {
    file = path;
  }
  return [first, file];
}

export function repeated(s, n) {
  return s.repeat(n);
}

export function kind(s) {
  if (s === "") {
    return 0;
  } else if (s === "abc" || s === "stats.rs") {
    return 1;
  } else if (s === "äbc/Ö") {
    return 2;
  } else if (s === "ab/c") {
    return 3;
  } else {
    return 4;
  }
}

export function tagged(s) {
  const option = $splitOnce(s, "/");
  const top = option != null ? option[0] : undefined;
  let n;
  const match = s.endsWith("/");
  if (top === "ab") {
    n = 1;
  } else if (top === "" && match === true) {
    n = 2;
  } else if (top == null) {
    n = 3;
  } else {
    n = 4;
  }
  return [n, top != null && (top === "a" || top === "src")];
}
//# sourceMappingURL=strings.js.map
