// Generated by rust-js from wasm/web/rust/components/app.rs. Do not edit.

import { useEffect, useMemo, useRef, useState, useTransition } from "react";

import * as codemirror from "../codemirror.js";
import * as compiler from "../compiler.js";
import * as editor from "./editor.jsx";
import * as file_tree from "./file_tree.jsx";
import * as pane from "./pane.jsx";
import * as result_frame from "./result_frame.jsx";
import * as stats_table from "./stats_table.jsx";
import * as toolbar from "./toolbar.jsx";
import * as programs from "../programs.js";
import * as projects from "../projects.js";
import * as tree from "../tree.js";

function $stripSuffix(s, suffix) {
  return s.endsWith(suffix) ? s.slice(0, s.length - suffix.length) : undefined;
}

function $rsplitOnce(s, separator) {
  const i = s.lastIndexOf(separator);
  return i < 0 ? undefined : [s.slice(0, i), s.slice(i + separator.length)];
}

function say(text, tone) {
  return { text, tone };
}

function appended(rows, label, value) {
  let next = rows.map((param) => [param[0], param[1]]);
  next.push([label, value]);
  return next;
}

function testsSummary(passed, failed, ignored) {
  const total = (passed + failed) >>> 0;
  const ignoredText = ignored > 0 ? `, ${ignored} ignored` : "";
  if (total === 0) {
    return say("No tests.", "Good");
  } else {
    const tone = failed > 0 ? "Bad" : "Good";
    return say(`Tests: ${passed} passed, ${failed} failed${ignoredText}.`, tone);
  }
}

export function App() {
  const [loaded, setLoaded] = useState(undefined);
  const [stats, setStats] = useState([]);
  const [status, setStatus] = useState(say("Loading…", "Plain"));
  const [example, setExample] = useState("");
  const [project, setProject] = useState(projects.Project.empty());
  const [output, setOutput] = useState("Nothing");
  const [program, setProgram] = useState(undefined);
  const [compiling, startTransition] = useTransition();
  const source = useRef(undefined);
  const runs = useRef(0);
  const compiles = useRef(0);
  useEffect(() => {
    const cancelled = { value: false };
    const dropped = cancelled;
    const stat = (label, value) => {
      if (!dropped.value) {
        setStats((rows) => appended(rows, label, value));
      }
    };
    const done = cancelled;
    (async () => {
      const loaded = await compiler.load(stat);
      let first;
      const match = loaded.examples[0];
      if (match != null) {
        first = [match.name, match.root, match.files.slice()];
      } else {
        first = undefined;
      }
      if (first != null && !done.value) {
        const texts = await compiler.loadExample(first[0], first[2]);
        if (!done.value) {
          setExample(first[0]);
          setProject(projects.Project.of(first[1], texts));
          setLoaded(loaded);
          setStatus(say("Ready.", "Plain"));
        }
      }
    })();
    return () => {
      cancelled.value = true;
    };
  }, []);
  const live = () => {
    const view = source.current;
    return view != null ? view.state : undefined;
  };
  const run = (files, rootJs, test) => {
    const n = (runs.current + 1) >>> 0;
    runs.current = n;
    const match = programs.prepare(files, rootJs, test, n);
    if (match === "Nothing") {
      setProgram(undefined);
    } else if (match === "Jsx") {
      setProgram(undefined);
      setStatus((s) => say(`${s.text} Preview React with the Vite example.`, "Plain"));
    } else if (match.TAG === "Blocked") {
      setProgram(undefined);
      const names = match._0.map((s) => `"${s}"`);
      const names$1 = names.join(", ");
      setStatus((s) => {
        const text = `${s.text} Not run: it imports ${names$1}, which the playground can't load. Bundle it with bun build.`;
        return say(text, "Bad");
      });
    } else {
      setProgram({ run: n, page: match._0 });
    }
  };
  const onCompile = (test) => {
    let loaded$1;
    if (loaded != null) {
      loaded$1 = loaded;
    } else {
      return;
    }
    if (compiling) {
      return;
    }
    const sources = projects.Project.sources(project, live());
    const root = project.root;
    const rootJs = projects.jsName(project.root);
    let shown;
    if (output.TAG === "Files") {
      shown = output.shown;
    } else {
      shown = "";
    }
    setStatus(say(test ? "Compiling the tests…" : "Compiling…", "Plain"));
    startTransition(() =>
      (async () => {
        const r = await compiler.compile(loaded$1, sources, root, test);
        const n = (compiles.current + 1) | 0;
        compiles.current = n;
        if (r.ok) {
          const files = Array.from(r.files);
          const count = files.length;
          const rootJsx = `${rootJs}x`;
          const rootJs$1 = files.some((param) => param[0] === rootJsx) ? rootJsx : rootJs;
          const shown$1 = files.some((param) => param[0] === shown) ? shown : rootJs$1;
          setOutput({ TAG: "Files", files, shown: shown$1 });
          setStatus(say(`Compiled: ${count} JS file${count === 1 ? "" : "s"}.`, "Good"));
          run(r.files, rootJs$1, test);
        } else {
          setOutput({ TAG: "Diagnostics", _0: r.stderr });
          setProgram(undefined);
          setStatus(say(`Failed: exit ${r.exit}.`, "Bad"));
        }
        const result = r.ok ? "ok" : "error";
        const times = `instantiate ${compiler.ms(r.instantiate)}, run ${compiler.ms(r.run)}, memory ${compiler.mb(r.memory)}, ${result}`;
        const label = `compile #${n}`;
        setStats((rows) => appended(rows, label, times));
        window.lastResult = r;
      })(),
    );
  };
  const onOutcome = (outcome) => {
    if (outcome.TAG === "Failed") {
      setStatus(say(`Runtime error: ${outcome._0}`, "Bad"));
    } else if (outcome === "Ran") {
      setStatus((s) => say(`${s.text} Ran main().`, "Good"));
    } else if (outcome.TAG === "Tested") {
      setStatus(testsSummary(outcome._0.passed, outcome._0.failed, outcome._0.ignored));
    } else {
      const text =
        "The Result frame didn't run. Is something blocking its script? See the console.";
      setStatus(say(text, "Bad"));
    }
  };
  const onExample = (name) => {
    let chosen;
    if (loaded != null) {
      chosen = loaded.examples.find((e) => e.name === name);
    } else {
      chosen = undefined;
    }
    if (chosen != null) {
      const [root, files] = [chosen.root, chosen.files.slice()];
      setExample(name);
      (async () => {
        const texts = await compiler.loadExample(name, files);
        setProject(projects.Project.of(root, texts));
        setOutput("Nothing");
        setProgram(undefined);
        setStatus(say("Ready.", "Plain"));
      })();
    }
  };
  const openFile = (path) => {
    setProject(projects.Project.opening(project, path, live()));
  };
  const deleteFile = (path) => {
    if (window.confirm(`Delete ${path}?`)) {
      setProject(projects.Project.removing(project, path));
    }
  };
  const newFile = () => {
    let answer;
    const match = window.prompt("New file, e.g. math.rs or geometry/shape.rs:");
    if (match != null) {
      answer = match;
    } else {
      return;
    }
    const path = answer.trim();
    if (path.length === 0) {
      return;
    }
    const modulePath = new RegExp("^([a-z_][a-z0-9_]*/)*[a-z_][a-z0-9_]*\\.rs$", "");
    if (!modulePath.test(path)) {
      const text = `"${path}" isn't a Rust module file name, like math.rs or geometry/shape.rs.`;
      setStatus(say(text, "Bad"));
      return;
    }
    if (projects.Project.has(project, path)) {
      setStatus(say(`${path} already exists.`, "Bad"));
      return;
    }
    setProject(projects.Project.adding(project, path, live()));
    let file;
    const match$1 = $rsplitOnce(path, "/");
    if (match$1 != null) {
      file = match$1[1];
    } else {
      file = path;
    }
    const module = $stripSuffix(file, ".rs") ?? file;
    const text$1 = `Created ${path}. Declare it with \`mod ${module};\` in its parent, or rustc won't include it.`;
    setStatus(say(text$1, "Plain"));
  };
  const openOutput = (path) => {
    if (output.TAG === "Files") {
      const files = output.files.map((param) => [param[0], param[1]]);
      setOutput({ TAG: "Files", files, shown: path });
    }
  };
  const blank = useMemo(() => codemirror.sourceState(""), []);
  let current;
  const match = projects.Project.currentState(project);
  if (match != null) {
    current = match;
  } else {
    current = blank;
  }
  const shownState = useMemo(() => {
    if (output === "Nothing") {
      return codemirror.outputState("", true);
    } else if (output.TAG === "Files") {
      let text;
      const match = output.files.find((param) => param[0] === output.shown);
      if (match != null) {
        text = match[1];
      } else {
        text = "";
      }
      return codemirror.outputState(text, true);
    } else {
      return codemirror.outputState(output._0, false);
    }
  }, [output]);
  const sourceTree = useMemo(() => tree.buildTree(projects.Project.paths(project)), [project]);
  let tmp;
  if (output.TAG === "Files") {
    tmp = [output.files.map((param) => param[0]), output.shown];
  } else {
    tmp = [[], ""];
  }
  const tmp$1 = tmp;
  const outputTree = useMemo(() => tree.buildTree(tmp$1[0]), [output]);
  let tmp$2;
  if (loaded != null) {
    tmp$2 = loaded.examples;
  } else {
    tmp$2 = [];
  }
  const examples = tmp$2;
  const submit = onCompile;
  return (
    <>
      <h1 className="mb-1 text-lg font-bold">rust-js playground</h1>
      <p className="mb-3 text-muted">
        rustc's front end and rust-js, as WebAssembly. No server compiles anything.
      </p>
      <toolbar.Toolbar
        examples={examples}
        example={example}
        onExample={onExample}
        ready={loaded != null && !compiling}
        onCompile={onCompile}
        status={status}
      />
      <div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,440px),1fr))] gap-3">
        <pane.Pane
          title="Rust"
          label="Rust files"
          explorer={
            <>
              <ul id="source-files">
                <file_tree.FileTree
                  tree={sourceTree}
                  depth={0}
                  first={project.root}
                  selected={project.current}
                  onOpen={openFile}
                  onDelete={deleteFile}
                />
              </ul>
              <button
                id="new-file"
                className="mx-2 mt-1.5 block cursor-pointer text-muted"
                onClick={() => newFile()}
              >
                + New file
              </button>
            </>
          }
          editor={<editor.Editor state={current} view={source} onSubmit={() => submit(false)} />}
        />
        <pane.Pane
          title="JavaScript"
          label="JavaScript files"
          explorer={
            <ul id="output-files">
              {outputTree.length === 0 ? (
                <li className="flex items-center px-2 py-0.5 text-muted">(none)</li>
              ) : (
                <file_tree.FileTree
                  tree={outputTree}
                  depth={0}
                  first={projects.jsName(project.root)}
                  selected={tmp$1[1]}
                  onOpen={openOutput}
                />
              )}
            </ul>
          }
          editor={<editor.Editor state={shownState} />}
        />
      </div>
      <result_frame.ResultFrame program={program} onOutcome={onOutcome} />
      <stats_table.StatsTable rows={stats} />
    </>
  );
}
//# sourceMappingURL=app.jsx.map
