// Generated by rust-js from wasm/web/rust/components/file_item.rs. Do not edit.

import { ROW } from "../styles.js";

export function FileItem({ name, path, depth, open, root, onOpen, onDelete }) {
  const opened = path;
  let end;
  if (onDelete != null && root) {
    end = <span className="text-[11px] text-muted">root </span>;
  } else if (onDelete != null) {
    end = (
      <button
        className="invisible cursor-pointer px-1.5 text-muted group-hover:visible focus:visible"
        aria-label={`Delete ${path}`}
        onClick={() => onDelete(path)}
      >
        ×
      </button>
    );
  } else {
    end = undefined;
  }
  return (
    <li className="group flex items-center">
      <button
        className={`min-w-0 flex-1 cursor-pointer truncate ${ROW} text-left aria-[current=true]:bg-selected`}
        style={{ paddingLeft: (8 + (Math.imul(depth, 12) >>> 0)) >>> 0 }}
        aria-current={open}
        onClick={() => onOpen(opened)}
      >
        {name}
      </button>
      {end}
    </li>
  );
}
//# sourceMappingURL=file_item.jsx.map
