// Generated by rust-js from wasm/web/rust/components/status_line.rs. Do not edit.

export function StatusLine({ status }) {
  let color;
  if (status.tone === "Plain") {
    color = "";
  } else if (status.tone === "Good") {
    color = "text-good";
  } else {
    color = "text-bad";
  }
  return (
    <span id="status" role="status" className={color}>
      {status.text}
    </span>
  );
}
//# sourceMappingURL=status_line.jsx.map
