// Generated by rust-js from examples/wire.rs. Do not edit.

// Shortest round-trip decimal, using exact rational arithmetic.
// Rust Display uses decimal notation, including for very small/large values.
// Not JS's `String(x)`, though its digits are also the shortest: when two are
// equally close, JS takes the even one (1888570120608320.2), and Rust the
// larger (1888570120608320.3).
function $displayF64(value) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const x = Math.abs(value);
  if (x === 0) return sign + "0";

  const bitsView = new DataView(new ArrayBuffer(8));
  bitsView.setFloat64(0, x);
  const bits = bitsView.getBigUint64(0);
  const exponentBits = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponentBits === 0 ? fraction : fraction + (1n << 52n);
  const binaryExponent = exponentBits === 0 ? -1074 : exponentBits - 1023 - 52;
  const numerator = binaryExponent >= 0 ? significand << BigInt(binaryExponent) : significand;
  const denominator = binaryExponent < 0 ? 1n << BigInt(-binaryExponent) : 1n;

  // The floating-point logarithm is only an estimate; correct it exactly.
  let exponent = Math.floor(Math.log10(x));
  const atLeastPowerOfTen = (e) =>
    e >= 0
      ? numerator >= denominator * 10n ** BigInt(e)
      : numerator * 10n ** BigInt(-e) >= denominator;
  while (!atLeastPowerOfTen(exponent)) exponent--;
  while (atLeastPowerOfTen(exponent + 1)) exponent++;

  for (let precision = 1; precision <= 17; precision++) {
    const power = exponent - precision + 1;
    const n = power < 0 ? numerator * 10n ** BigInt(-power) : numerator;
    const d = power > 0 ? denominator * 10n ** BigInt(power) : denominator;
    const floor = n / d;
    const rounded = floor + (2n * (n % d) >= d ? 1n : 0n);
    // The rounding interval can be asymmetric at a binary power boundary.
    let best;
    let bestDistance;
    for (const candidate of [rounded, rounded - 1n, rounded + 1n]) {
      if (candidate > 0n && Number(`${candidate}e${power}`) === x) {
        const delta = candidate * d - n;
        const distance = delta < 0n ? -delta : delta;
        if (
          best === undefined ||
          distance < bestDistance ||
          (distance === bestDistance && candidate > best)
        ) {
          best = candidate;
          bestDistance = distance;
        }
      }
    }
    if (best !== undefined) {
      let digits = best.toString();
      let decimalPower = power;
      while (digits.endsWith("0")) {
        digits = digits.slice(0, -1);
        decimalPower++;
      }
      const point = digits.length + decimalPower;
      const body =
        point <= 0
          ? "0." + "0".repeat(-point) + digits
          : point >= digits.length
            ? digits + "0".repeat(point - digits.length)
            : digits.slice(0, point) + "." + digits.slice(point);
      return sign + body;
    }
  }
  throw new Error("No f64 round-trip decimal found");
}

function $debug(v) {
  if (typeof v === "string") {
    return JSON.stringify(v);
  }
  if (Array.isArray(v)) {
    return "[" + v.map($debug).join(", ") + "]";
  }
  if (v === undefined) {
    return "()";
  }
  // A `HashMap` and a `HashSet` (ADR 0059), in braces as Rust shows them.
  if (v instanceof Map) {
    return "{" + [...v].map(([k, x]) => $debug(k) + ": " + $debug(x)).join(", ") + "}";
  }
  if (v instanceof Set) {
    return "{" + [...v].map($debug).join(", ") + "}";
  }
  if (typeof v === "object" && v !== null) {
    return (
      "{ " +
      Object.entries(v)
        .map(([k, x]) => k + ": " + $debug(x))
        .join(", ") +
      " }"
    );
  }
  return String(v);
}

function $sortedEntries(map, cmp) {
  return Array.from(map).sort((a, b) => cmp(a[0], b[0]));
}

class $JsonError extends Error {
  constructor(message, line = 0, column = 0) {
    super(message);
    this.line = line;
    this.column = column;
  }
}
function $jsonError(message) {
  return new $JsonError(message);
}
// A float as serde_json writes one: its shortest digits, fixed from 1e-5
// to 1e15, else `1.5e+16`.
function $jsonNumber(x) {
  if (!Number.isFinite(x)) return "null";
  if (x === 0) return Object.is(x, -0) ? "-0.0" : "0.0";
  const [mantissa, exponent] = x.toExponential().split("e");
  const e = Number(exponent);
  if (e < -5 || e > 15) return `${mantissa}e${e < 0 ? "-" : "+"}${Math.abs(e)}`;
  const fixed = String(x);
  return fixed.includes(".") ? fixed : `${fixed}.0`;
}

function $jsonWriter(pretty) {
  // For each array or object open: whether nothing is in it yet.
  const empty = [];
  const next = (json) => {
    const first = empty[empty.length - 1];
    empty[empty.length - 1] = false;
    if (pretty) json.text += (first ? "\n" : ",\n") + "  ".repeat(empty.length);
    else if (!first) json.text += ",";
  };
  const open = (json, bracket) => {
    empty.push(true);
    json.text += bracket;
  };
  const close = (json, bracket) => {
    if (!empty.pop() && pretty) json.text += "\n" + "  ".repeat(empty.length);
    json.text += bracket;
  };
  return {
    text: "",
    raw(text) {
      this.text += text;
    },
    string(s) {
      this.text += JSON.stringify(s);
    },
    number(x) {
      this.text += $jsonNumber(x);
    },
    beginArray() {
      open(this, "[");
    },
    element() {
      next(this);
    },
    endArray() {
      close(this, "]");
    },
    beginObject() {
      open(this, "{");
    },
    key(k) {
      next(this);
      this.text += JSON.stringify(k) + (pretty ? ": " : ":");
    },
    endObject() {
      close(this, "}");
    },
  };
}
function $toJson(value, write, pretty) {
  const json = $jsonWriter(pretty);
  try {
    write(value, json);
  } catch (e) {
    if (e instanceof $JsonError)
      return { TAG: "Err", _0: { message: e.message, line: e.line, column: e.column } };
    throw e;
  }
  return { TAG: "Ok", _0: json.text };
}

// What serde's impls and derives read, the same whatever they read from:
// the text (`$JsonReader`), or a value already read (`$JsonContent`), which
// is how serde reads a tagged or an untagged enum.
class $JsonDecoder {
  // An integer type, named as serde names it, from `min` to `max`.
  int(name, min, max) {
    return this.deserializeNumber(name, (n) => {
      if (n.kind === "f")
        throw $jsonError(
          `invalid type: floating point \`${$jsonNumber(n.value)}\`, expected ${name}`,
        );
      if (n.kind === "u" ? n.value > max : n.value < min) {
        throw $jsonError(`invalid value: integer \`${n.value}\`, expected ${name}`);
      }
      return Number(n.value);
    });
  }

  f64() {
    return this.deserializeNumber("f64", (n) => Number(n.value));
  }

  string() {
    return this.deserializeStr("a string", (s) => s);
  }

  char() {
    return this.deserializeStr("a character", $jsonChar);
  }

  vec(read) {
    return this.deserializeSeq("a sequence", (seq) => {
      const items = [];
      while (seq.next()) items.push(seq.value(read));
      return items;
    });
  }

  tuple(reads) {
    const expected = `a tuple of size ${reads.length}`;
    return this.deserializeSeq(expected, (seq) =>
      reads.map((read, i) => seq.element(read, i, expected)),
    );
  }

  array(length, read) {
    const expected = length === 0 ? "an empty array" : `an array of length ${length}`;
    return this.deserializeSeq(expected, (seq) =>
      Array.from({ length }, (_, i) => seq.element(read, i, expected)),
    );
  }

  map(readKey, read) {
    return this.deserializeMap("a map", (map) => {
      const entries = new Map();
      while (map.next()) {
        const key = readKey(map.key());
        entries.set(key, map.value(read));
      }
      return entries;
    });
  }

  // A struct's fields: `[name, read]`, or `[[name, ...aliases], read]`, and
  // `missing`, the value it has when it's not there, for `#[serde(default)]`.
  // `build` makes the struct of their values.
  struct(expected, fields, build, options = {}) {
    return this.deserializeMap(
      options.expecting ?? expected,
      (map) => this.structMap(map, fields, build, options),
      (seq) => this.structSeq(seq, expected, fields, build, options),
    );
  }

  // An untagged struct variant, which serde reads from an object only.
  untaggedStruct(expected, fields, build, options = {}) {
    return this.deserializeAny(options.expecting ?? expected, {
      map: (map) => this.structMap(map, fields, build, options),
    });
  }

  structMap(map, fields, build, { deny = false, container } = {}) {
    const values = new Array(fields.length);
    const seen = new Array(fields.length).fill(false);
    while (map.next()) {
      const i = $jsonField(map.key().string(), fields, deny);
      if (i < 0) {
        map.value((json) => json.ignoreValue());
        continue;
      }
      if (seen[i]) throw $jsonError(`duplicate field \`${$jsonName(fields[i][0])}\``);
      values[i] = map.value(fields[i][1]);
      seen[i] = true;
    }
    const defaults = container?.();
    fields.forEach(([names, read, missing], i) => {
      if (!seen[i])
        values[i] = missing ? missing(defaults) : read(new $JsonMissing($jsonName(names)));
    });
    return build(values, defaults);
  }

  structSeq(seq, expected, fields, build, { container, expecting } = {}) {
    const length =
      expecting ?? `${expected} with ${fields.length} element${fields.length === 1 ? "" : "s"}`;
    const defaults = container?.();
    const values = fields.map(([, read, missing], i) =>
      seq.element(read, i, length, missing, defaults),
    );
    return build(values, defaults);
  }

  // A tuple struct's fields: `read`, or `[read, missing]`.
  tupleStruct(expected, fields, build = (values) => values, { container, expecting } = {}) {
    const length =
      expecting ?? `${expected} with ${fields.length} element${fields.length === 1 ? "" : "s"}`;
    return this.deserializeSeq(expecting ?? expected, (seq) => {
      const defaults = container?.();
      const values = fields.map((field, i) => {
        const [read, missing] = typeof field === "function" ? [field] : field;
        return seq.element(read, i, length, missing, defaults);
      });
      return build(values, defaults);
    });
  }

  // An internally tagged enum's unit variant, whose other fields are
  // ignored (serde's `InternallyTaggedUnitVisitor`).
  taggedUnit(expected) {
    return this.deserializeAny(expected, {
      seq: () => undefined,
      map: (map) => {
        while (map.next()) {
          map.key().ignore();
          map.value((json) => json.ignoreValue());
        }
        return undefined;
      },
    });
  }

  // An untagged unit variant: `null` (serde's `UntaggedUnitVisitor`).
  untaggedUnit(expected) {
    return this.deserializeAny(expected, { unit: () => undefined });
  }

  // `#[serde(tag = "type")]`: the tag, found among the other fields, which
  // are kept for the variant to read (serde's `TaggedContentVisitor`).
  internallyTagged(tag, expected, variants, visit, other) {
    const [variant, rest] = this.deserializeAny(expected, {
      seq: (seq) => {
        if (!seq.next()) throw $jsonError(`missing field \`${tag}\``);
        const variant = seq.value((json) => json.identifier(variants, other));
        const items = [];
        while (seq.next()) items.push(seq.value((json) => json.content()));
        return [variant, { type: "seq", value: items }];
      },
      map: (map) => {
        let variant;
        const entries = [];
        while (map.next()) {
          const key = map.key().string();
          if (key !== tag) {
            entries.push([{ type: "str", value: key }, map.value((json) => json.content())]);
            continue;
          }
          if (variant !== undefined) throw $jsonError(`duplicate field \`${tag}\``);
          variant = map.value((json) => json.identifier(variants, other));
        }
        if (variant === undefined) throw $jsonError(`missing field \`${tag}\``);
        return [variant, { type: "map", value: entries }];
      },
    });
    return visit(variant, new $JsonContent(rest, true));
  }

  // `#[serde(tag = "t", content = "c")]`, as serde's derive reads one: the
  // tag, then the content, or the content first, kept until the tag says
  // how to read it.
  adjacentlyTagged(tag, content, expected, variants, visit, { deny = false, other } = {}) {
    const variantOf = (json) =>
      json.enum(
        variants,
        (name, access) => {
          access.unit();
          return name;
        },
        other,
      );
    // The next key that's the tag or the content, skipping any other.
    const relevant = (map) => {
      while (map.next()) {
        const key = map.key().string();
        if (key === tag) return "tag";
        if (key === content) return "content";
        if (deny) {
          throw $jsonError(
            `invalid value: string ${$debugStr(key)}, expected ${$debugStr(tag)} or ${$debugStr(content)}`,
          );
        }
        map.value((json) => json.ignoreValue());
      }
      return undefined;
    };
    const finish = (map, value) => {
      const key = relevant(map);
      if (key !== undefined)
        throw $jsonError(`duplicate field \`${key === "tag" ? tag : content}\``);
      return value;
    };
    return this.deserializeMap(
      expected,
      (map) => {
        const first = relevant(map);
        if (first === "tag") {
          const variant = map.value(variantOf);
          const second = relevant(map);
          if (second === "tag") throw $jsonError(`duplicate field \`${tag}\``);
          if (second === "content")
            return finish(
              map,
              map.value((json) => visit(variant, json)),
            );
          return visit(variant, new $JsonMissing(content));
        }
        if (first === "content") {
          const buffered = map.value((json) => json.content());
          const second = relevant(map);
          if (second === "tag") {
            const variant = map.value(variantOf);
            return finish(map, visit(variant, new $JsonContent(buffered, true)));
          }
          if (second === "content") throw $jsonError(`duplicate field \`${content}\``);
        }
        throw $jsonError(`missing field \`${tag}\``);
      },
      (seq) => {
        if (!seq.next()) throw $jsonError(`invalid length 0, expected ${expected}`);
        const variant = seq.value((json) => json.identifier(variants, other));
        if (!seq.next()) throw $jsonError(`invalid length 1, expected ${expected}`);
        return seq.value((json) => visit(variant, json));
      },
    );
  }

  // `#[serde(untagged)]`: the value, read once and kept, then each way of
  // reading it in turn, the first that works.
  untagged(message, attempts) {
    const content = this.content();
    for (const attempt of attempts) {
      try {
        return attempt(new $JsonContent(content, false));
      } catch (e) {
        if (!(e instanceof $JsonError)) throw e;
      }
    }
    throw $jsonError(message);
  }
}

// serde_json's reader (ADR 0078): its `Deserializer`, ported step for step,
// with its methods' names. It reads the text's UTF-8 bytes, as serde_json
// does, so a mistake is found at the same byte, with the same message, and
// its column counts bytes.
class $JsonReader extends $JsonDecoder {
  constructor(text) {
    super();
    this.bytes = new TextEncoder().encode(text);
    this.index = 0;
    this.remainingDepth = 128;
  }

  // The next byte, or -1 at the end.
  peek() {
    return this.index < this.bytes.length ? this.bytes[this.index] : -1;
  }

  next() {
    return this.index < this.bytes.length ? this.bytes[this.index++] : -1;
  }

  // `position_of_index`: the line, and the bytes before `index` on it.
  errorAt(index, message) {
    const start = index === 0 ? 0 : this.bytes.lastIndexOf(10, index - 1) + 1;
    let line = 1;
    for (let i = 0; i < start; i++) if (this.bytes[i] === 10) line++;
    return new $JsonError(message, line, index - start);
  }

  error(message) {
    return this.errorAt(this.index, message);
  }

  peekError(message) {
    return this.errorAt(Math.min(this.bytes.length, this.index + 1), message);
  }

  // `fix_position`: a visitor's message has no place, until it gets where
  // the reader is.
  fixPosition(e) {
    return e instanceof $JsonError && e.line === 0 ? this.error(e.message) : e;
  }

  end() {
    if (this.parseWhitespace() !== -1) throw this.peekError("trailing characters");
  }

  parseWhitespace() {
    for (;;) {
      const c = this.peek();
      if (c !== 32 && c !== 10 && c !== 9 && c !== 13) return c;
      this.index++;
    }
  }

  parseIdent(rest) {
    for (let i = 0; i < rest.length; i++) {
      const c = this.next();
      if (c === -1) throw this.error("EOF while parsing a value");
      if (c !== rest.charCodeAt(i)) throw this.error("expected ident");
    }
  }

  // What's there instead of `expected`, read past, in serde's words.
  peekInvalidType(expected) {
    const c = this.peek();
    let unexpected;
    if (c === 110) {
      this.index++;
      this.parseIdent("ull");
      unexpected = "null";
    } else if (c === 116) {
      this.index++;
      this.parseIdent("rue");
      unexpected = "boolean `true`";
    } else if (c === 102) {
      this.index++;
      this.parseIdent("alse");
      unexpected = "boolean `false`";
    } else if (c === 45) {
      this.index++;
      unexpected = $jsonUnexpectedNumber(this.parseInteger(false));
    } else if (c >= 48 && c <= 57) {
      unexpected = $jsonUnexpectedNumber(this.parseInteger(true));
    } else if (c === 34) {
      this.index++;
      unexpected = `string ${$debugStr(this.parseStr())}`;
    } else if (c === 91) {
      unexpected = "sequence";
    } else if (c === 123) {
      unexpected = "map";
    } else {
      return this.peekError("expected value");
    }
    return this.fixPosition($jsonError(`invalid type: ${unexpected}, expected ${expected}`));
  }

  // A number: `{ kind, value }`, a `"u"`nsigned or `"i"`nteger (a BigInt
  // past 2^53) where it's an integer that fits in 64 bits, else an `"f"`.
  deserializeNumber(expected, visit) {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek === 45) {
        this.index++;
        return visit(this.parseInteger(false));
      }
      if (peek >= 48 && peek <= 57) return visit(this.parseInteger(true));
      throw this.peekInvalidType(expected);
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  parseInteger(positive) {
    const c = this.next();
    if (c === -1) throw this.error("EOF while parsing a value");
    if (c === 48) {
      const p = this.peek();
      if (p >= 48 && p <= 57) throw this.peekError("invalid number");
      return this.parseNumber(positive, 0);
    }
    if (c < 49 || c > 57) throw this.error("invalid number");
    let significand = c - 48;
    for (;;) {
      const p = this.peek();
      if (p < 48 || p > 57) return this.parseNumber(positive, significand);
      const grown = $jsonGrow(significand, p - 48);
      if (grown > 18446744073709551615n) {
        return { kind: "f", value: this.parseLongInteger(positive, significand) };
      }
      this.index++;
      significand = grown;
    }
  }

  parseNumber(positive, significand) {
    const p = this.peek();
    if (p === 46) return { kind: "f", value: this.parseDecimal(positive, significand, 0) };
    if (p === 101 || p === 69)
      return { kind: "f", value: this.parseExponent(positive, significand, 0) };
    if (positive) return { kind: "u", value: significand };
    // `-0`, and below `i64::MIN`, are floats.
    if (significand === 0 || significand > 9223372036854775808n) {
      return { kind: "f", value: -Number(significand) };
    }
    return { kind: "i", value: -significand };
  }

  parseDecimal(positive, significand, exponentBeforeDecimalPoint) {
    this.index++;
    let exponentAfterDecimalPoint = 0;
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) {
      const grown = $jsonGrow(significand, p - 48);
      if (grown > 18446744073709551615n) {
        const exponent = exponentBeforeDecimalPoint + exponentAfterDecimalPoint;
        return this.parseDecimalOverflow(positive, significand, exponent);
      }
      this.index++;
      significand = grown;
      exponentAfterDecimalPoint--;
    }
    if (exponentAfterDecimalPoint === 0) {
      throw this.peekError(this.peek() === -1 ? "EOF while parsing a value" : "invalid number");
    }
    const exponent = exponentBeforeDecimalPoint + exponentAfterDecimalPoint;
    const p = this.peek();
    return p === 101 || p === 69
      ? this.parseExponent(positive, significand, exponent)
      : this.f64FromParts(positive, significand, exponent);
  }

  parseExponent(positive, significand, startingExp) {
    this.index++;
    let positiveExp = true;
    const sign = this.peek();
    if (sign === 43) {
      this.index++;
    } else if (sign === 45) {
      this.index++;
      positiveExp = false;
    }
    const c = this.next();
    if (c === -1) throw this.error("EOF while parsing a value");
    if (c < 48 || c > 57) throw this.error("invalid number");
    let exp = c - 48;
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) {
      this.index++;
      if (exp * 10 + (p - 48) > 2147483647) {
        return this.parseExponentOverflow(positive, significand == 0, positiveExp);
      }
      exp = exp * 10 + (p - 48);
    }
    // i32's saturating add and subtract.
    const finalExp = Math.max(
      -2147483648,
      Math.min(2147483647, positiveExp ? startingExp + exp : startingExp - exp),
    );
    return this.f64FromParts(positive, significand, finalExp);
  }

  // Not correctly rounded, as serde_json's isn't without its
  // `float_roundtrip` feature: the significand times or over a power of ten.
  f64FromParts(positive, significand, exponent) {
    let f = Number(significand);
    for (;;) {
      const pow = $JSON_POW10[Math.abs(exponent)];
      if (pow !== undefined) {
        if (exponent >= 0) {
          f *= pow;
          if (!Number.isFinite(f)) throw this.error("number out of range");
        } else {
          f /= pow;
        }
        break;
      }
      if (f === 0) break;
      if (exponent >= 0) throw this.error("number out of range");
      f /= 1e308;
      exponent += 308;
    }
    return positive ? f : -f;
  }

  parseLongInteger(positive, significand) {
    let exponent = 0;
    for (;;) {
      const p = this.peek();
      if (p >= 48 && p <= 57) {
        this.index++;
        exponent++;
      } else if (p === 46) {
        return this.parseDecimal(positive, significand, exponent);
      } else if (p === 101 || p === 69) {
        return this.parseExponent(positive, significand, exponent);
      } else {
        return this.f64FromParts(positive, significand, exponent);
      }
    }
  }

  parseDecimalOverflow(positive, significand, exponent) {
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) this.index++;
    const p = this.peek();
    return p === 101 || p === 69
      ? this.parseExponent(positive, significand, exponent)
      : this.f64FromParts(positive, significand, exponent);
  }

  parseExponentOverflow(positive, zeroSignificand, positiveExp) {
    if (!zeroSignificand && positiveExp) throw this.error("number out of range");
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) this.index++;
    return positive ? 0 : -0;
  }

  // A string, after its opening quote.
  parseStr() {
    const bytes = this.bytes;
    let text = "";
    let start = this.index;
    for (;;) {
      while (this.index < bytes.length) {
        const c = bytes[this.index];
        if (c === 34 || c === 92 || c < 32) break;
        this.index++;
      }
      if (this.index === bytes.length) throw this.error("EOF while parsing a string");
      const c = bytes[this.index];
      if (c === 34) {
        text += $JSON_UTF8.decode(bytes.subarray(start, this.index));
        this.index++;
        return text;
      }
      if (c !== 92) {
        this.index++;
        throw this.error("control character (\\u0000-\\u001F) found while parsing a string");
      }
      text += $JSON_UTF8.decode(bytes.subarray(start, this.index));
      this.index++;
      text += this.parseEscape();
      start = this.index;
    }
  }

  parseEscape() {
    const c = this.next();
    if (c === -1) throw this.error("EOF while parsing a string");
    switch (c) {
      case 34:
        return '"';
      case 92:
        return "\\";
      case 47:
        return "/";
      case 98:
        return "\b";
      case 102:
        return "\f";
      case 110:
        return "\n";
      case 114:
        return "\r";
      case 116:
        return "\t";
      case 117:
        return this.parseUnicodeEscape();
    }
    throw this.error("invalid escape");
  }

  parseUnicodeEscape() {
    const n = this.decodeHexEscape();
    // A trailing surrogate, which serde_json calls a leading one.
    if (n >= 0xdc00 && n <= 0xdfff) throw this.error("lone leading surrogate in hex escape");
    if (n < 0xd800 || n > 0xdbff) return String.fromCharCode(n);
    for (const expected of [92, 117]) {
      if (this.peek() === -1) throw this.error("EOF while parsing a string");
      const c = this.bytes[this.index++];
      if (c !== expected) throw this.error("unexpected end of hex escape");
    }
    const n2 = this.decodeHexEscape();
    if (n2 < 0xdc00 || n2 > 0xdfff) throw this.error("lone leading surrogate in hex escape");
    return String.fromCharCode(n, n2);
  }

  decodeHexEscape() {
    if (this.index + 4 > this.bytes.length) {
      this.index = this.bytes.length;
      throw this.error("EOF while parsing a string");
    }
    let n = 0;
    let valid = true;
    for (let i = 0; i < 4; i++) {
      const digit = $jsonHexDigit(this.bytes[this.index + i]);
      valid &&= digit >= 0;
      n = n * 16 + digit;
    }
    this.index += 4;
    if (!valid) throw this.error("invalid escape");
    return n;
  }

  ignoreStr() {
    const bytes = this.bytes;
    for (;;) {
      while (this.index < bytes.length) {
        const c = bytes[this.index];
        if (c === 34 || c === 92 || c < 32) break;
        this.index++;
      }
      if (this.index === bytes.length) throw this.error("EOF while parsing a string");
      const c = bytes[this.index];
      if (c === 34) {
        this.index++;
        return;
      }
      if (c !== 92)
        throw this.error("control character (\\u0000-\\u001F) found while parsing a string");
      this.index++;
      const escape = this.next();
      if (escape === -1) throw this.error("EOF while parsing a string");
      if (escape === 117) this.decodeHexEscape();
      else if (!'"\\/bfnrt'.includes(String.fromCharCode(escape)))
        throw this.error("invalid escape");
    }
  }

  parseObjectColon() {
    const c = this.parseWhitespace();
    if (c === 58) {
      this.index++;
      return;
    }
    throw this.peekError(c === -1 ? "EOF while parsing an object" : "expected `:`");
  }

  endSeq() {
    const c = this.parseWhitespace();
    if (c === 93) {
      this.index++;
      return;
    }
    if (c === 44) {
      this.index++;
      throw this.peekError(
        this.parseWhitespace() === 93 ? "trailing comma" : "trailing characters",
      );
    }
    throw this.peekError(c === -1 ? "EOF while parsing a list" : "trailing characters");
  }

  endMap() {
    const c = this.parseWhitespace();
    if (c === 125) {
      this.index++;
      return;
    }
    throw this.peekError(
      c === 44
        ? "trailing comma"
        : c === -1
          ? "EOF while parsing an object"
          : "trailing characters",
    );
  }

  ignoreValue() {
    const frames = [];
    let enclosing;
    for (;;) {
      const peek = this.parseWhitespace();
      if (peek === -1) throw this.peekError("EOF while parsing a value");
      let frame;
      if (peek === 110) {
        this.index++;
        this.parseIdent("ull");
      } else if (peek === 116) {
        this.index++;
        this.parseIdent("rue");
      } else if (peek === 102) {
        this.index++;
        this.parseIdent("alse");
      } else if (peek === 45) {
        this.index++;
        this.ignoreInteger();
      } else if (peek >= 48 && peek <= 57) {
        this.ignoreInteger();
      } else if (peek === 34) {
        this.index++;
        this.ignoreStr();
      } else if (peek === 91 || peek === 123) {
        if (enclosing !== undefined) frames.push(enclosing);
        enclosing = undefined;
        this.index++;
        frame = peek;
      } else {
        throw this.peekError("expected value");
      }
      let acceptComma = true;
      if (frame !== undefined) {
        acceptComma = false;
      } else if (enclosing !== undefined) {
        frame = enclosing;
        enclosing = undefined;
      } else if (frames.length > 0) {
        frame = frames.pop();
      } else {
        return;
      }
      for (;;) {
        const c = this.parseWhitespace();
        if (c === 44 && acceptComma) {
          this.index++;
          break;
        }
        if (c === -1)
          throw this.peekError(
            frame === 91 ? "EOF while parsing a list" : "EOF while parsing an object",
          );
        if (!((c === 93 && frame === 91) || (c === 125 && frame === 123))) {
          if (acceptComma)
            throw this.peekError(frame === 91 ? "expected `,` or `]`" : "expected `,` or `}`");
          break;
        }
        this.index++;
        if (frames.length === 0) return;
        frame = frames.pop();
        acceptComma = true;
      }
      if (frame === 123) {
        const quote = this.parseWhitespace();
        if (quote !== 34)
          throw this.peekError(
            quote === -1 ? "EOF while parsing an object" : "key must be a string",
          );
        this.index++;
        this.ignoreStr();
        const colon = this.parseWhitespace();
        if (colon !== 58)
          throw this.peekError(colon === -1 ? "EOF while parsing an object" : "expected `:`");
        this.index++;
      }
      enclosing = frame;
    }
  }

  ignoreInteger() {
    const c = this.next();
    if (c === 48) {
      const p = this.peek();
      if (p >= 48 && p <= 57) throw this.peekError("invalid number");
    } else if (c >= 49 && c <= 57) {
      for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) this.index++;
    } else {
      throw this.error("invalid number");
    }
    const p = this.peek();
    if (p === 46) this.ignoreDecimal();
    else if (p === 101 || p === 69) this.ignoreExponent();
  }

  ignoreDecimal() {
    this.index++;
    let atLeastOneDigit = false;
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) {
      this.index++;
      atLeastOneDigit = true;
    }
    if (!atLeastOneDigit) throw this.peekError("invalid number");
    const p = this.peek();
    if (p === 101 || p === 69) this.ignoreExponent();
  }

  ignoreExponent() {
    this.index++;
    const sign = this.peek();
    if (sign === 43 || sign === 45) this.index++;
    const c = this.next();
    if (c < 48 || c > 57) throw this.error("invalid number");
    for (let p = this.peek(); p >= 48 && p <= 57; p = this.peek()) this.index++;
  }

  // An array or an object: `visit` reads what's inside, and the closing
  // bracket is looked for even when it fails, as serde_json does.
  nested(visit, end) {
    if (--this.remainingDepth === 0) throw this.peekError("recursion limit exceeded");
    this.index++;
    let value;
    let failure;
    try {
      value = visit();
    } catch (e) {
      if (!(e instanceof $JsonError)) throw e;
      failure = e;
    }
    this.remainingDepth++;
    try {
      end();
    } catch (e) {
      if (!(e instanceof $JsonError)) throw e;
      failure ??= e;
    }
    if (failure) throw failure;
    return value;
  }

  // `deserialize_seq`: `[ .. ]`, which `visit` reads with a `$JsonSeq`.
  deserializeSeq(expected, visit) {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek !== 91) throw this.peekInvalidType(expected);
      return this.nested(
        () => visit(new $JsonSeq(this)),
        () => this.endSeq(),
      );
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  // `deserialize_map` and `deserialize_struct`: `{ .. }`, or for a struct,
  // `[ .. ]` too.
  deserializeMap(expected, visitMap, visitSeq) {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek === 91 && visitSeq)
        return this.nested(
          () => visitSeq(new $JsonSeq(this)),
          () => this.endSeq(),
        );
      if (peek !== 123) throw this.peekInvalidType(expected);
      return this.nested(
        () => visitMap(new $JsonMap(this)),
        () => this.endMap(),
      );
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  deserializeStr(expected, visit) {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek !== 34) throw this.peekInvalidType(expected);
      this.index++;
      return visit(this.parseStr());
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  // What serde's own impls read, from the text.

  bool() {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek === 116) {
        this.index++;
        this.parseIdent("rue");
        return true;
      }
      if (peek === 102) {
        this.index++;
        this.parseIdent("alse");
        return false;
      }
      throw this.peekInvalidType("a boolean");
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  unit(expected = "unit") {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    try {
      if (peek !== 110) throw this.peekInvalidType(expected);
      this.index++;
      this.parseIdent("ull");
      return undefined;
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  unitStruct(expected) {
    return this.unit(expected);
  }

  option(read) {
    if (this.parseWhitespace() !== 110) return read(this);
    this.index++;
    this.parseIdent("ull");
    return undefined;
  }

  // `deserialize_any`: whatever's there, for the `visitor` method of its
  // kind (`unit`, `bool`, `number`, `string`, `seq` or `map`), which is
  // `expected` if the visitor has none.
  deserializeAny(expected, visitor) {
    const peek = this.parseWhitespace();
    if (peek === -1) throw this.peekError("EOF while parsing a value");
    const invalid = (unexpected) => $jsonError(`invalid type: ${unexpected}, expected ${expected}`);
    try {
      if (peek === 110) {
        this.index++;
        this.parseIdent("ull");
        if (visitor.unit) return visitor.unit();
        throw invalid("null");
      }
      if (peek === 116 || peek === 102) {
        this.index++;
        this.parseIdent(peek === 116 ? "rue" : "alse");
        if (visitor.bool) return visitor.bool(peek === 116);
        throw invalid(`boolean \`${peek === 116}\``);
      }
      if (peek === 45 || (peek >= 48 && peek <= 57)) {
        if (peek === 45) this.index++;
        const n = this.parseInteger(peek !== 45);
        if (visitor.number) return visitor.number(n);
        throw invalid($jsonUnexpectedNumber(n));
      }
      if (peek === 34) {
        this.index++;
        const s = this.parseStr();
        if (visitor.string) return visitor.string(s);
        throw invalid(`string ${$debugStr(s)}`);
      }
      if (peek === 91) {
        return this.nested(
          () => {
            if (!visitor.seq) throw invalid("sequence");
            return visitor.seq(new $JsonSeq(this));
          },
          () => this.endSeq(),
        );
      }
      if (peek === 123) {
        return this.nested(
          () => {
            if (!visitor.map) throw invalid("map");
            return visitor.map(new $JsonMap(this));
          },
          () => this.endMap(),
        );
      }
      throw this.peekError("expected value");
    } catch (e) {
      throw this.fixPosition(e);
    }
  }

  // serde's `ContentVisitor`: the value, read into a `{ type, value }`.
  content() {
    return this.deserializeAny("any value", {
      unit: () => ({ type: "unit" }),
      bool: (value) => ({ type: "bool", value }),
      number: (value) => ({ type: "num", value }),
      string: (value) => ({ type: "str", value }),
      seq: (seq) => {
        const items = [];
        while (seq.next()) items.push(seq.value((json) => json.content()));
        return { type: "seq", value: items };
      },
      map: (map) => {
        const entries = [];
        while (map.next()) {
          const key = map.key().content();
          entries.push([key, map.value((json) => json.content())]);
        }
        return { type: "map", value: entries };
      },
    });
  }

  // `deserialize_enum`: `"Name"`, or `{"Name": ..}`. `visit` gets the
  // variant's name and a `$JsonVariant` to read what it holds.
  enum(variants, visit, other) {
    const peek = this.parseWhitespace();
    if (peek === 34) return visit(this.identifier(variants, other), new $JsonVariant(this, true));
    if (peek !== 123)
      throw this.peekError(peek === -1 ? "EOF while parsing a value" : "expected value");
    if (--this.remainingDepth === 0) throw this.peekError("recursion limit exceeded");
    this.index++;
    let value;
    try {
      const c = this.parseWhitespace();
      if (c !== 34) {
        throw this.peekError(
          c === 125
            ? "expected value"
            : c === -1
              ? "EOF while parsing an object"
              : "key must be a string",
        );
      }
      const name = this.identifier(variants, other);
      this.parseObjectColon();
      value = visit(name, new $JsonVariant(this, false));
    } finally {
      this.remainingDepth++;
    }
    const c = this.parseWhitespace();
    if (c === 125) {
      this.index++;
      return value;
    }
    throw this.error(c === -1 ? "EOF while parsing an object" : "expected value");
  }

  // A variant's name, from a string.
  identifier(variants, other) {
    return this.deserializeStr("variant identifier", (name) =>
      $jsonVariantNamed(name, variants, other),
    );
  }
}

// A value already read (serde's `ContentDeserializer`, or when not `owned`,
// its `ContentRefDeserializer`): `{ type, value }`, where `type` is `unit`,
// `bool`, `num`, `str`, `seq` or `map`.
class $JsonContent extends $JsonDecoder {
  constructor(content, owned) {
    super();
    this.data = content;
    this.owned = owned;
  }

  invalid(expected) {
    return $jsonError(`invalid type: ${$jsonUnexpectedContent(this.data)}, expected ${expected}`);
  }

  deserializeNumber(expected, visit) {
    if (this.data.type === "num") return visit(this.data.value);
    throw this.invalid(expected);
  }

  deserializeStr(expected, visit) {
    if (this.data.type === "str") return visit(this.data.value);
    throw this.invalid(expected);
  }

  visitSeq(visit) {
    const seq = new $JsonContentSeq(this.data.value, this.owned);
    const value = visit(seq);
    seq.end();
    return value;
  }

  visitMap(visit) {
    const map = new $JsonContentMap(this.data.value, this.owned);
    const value = visit(map);
    map.end();
    return value;
  }

  deserializeSeq(expected, visit) {
    if (this.data.type === "seq") return this.visitSeq(visit);
    throw this.invalid(expected);
  }

  deserializeMap(expected, visitMap, visitSeq) {
    if (this.data.type === "seq" && visitSeq) return this.visitSeq(visitSeq);
    if (this.data.type === "map") return this.visitMap(visitMap);
    throw this.invalid(expected);
  }

  deserializeAny(expected, visitor) {
    const { type, value } = this.data;
    if (type === "seq" && visitor.seq) return this.visitSeq(visitor.seq);
    if (type === "map" && visitor.map) return this.visitMap(visitor.map);
    const visit = {
      unit: visitor.unit,
      bool: visitor.bool,
      num: visitor.number,
      str: visitor.string,
    }[type];
    if (visit) return visit(value);
    throw this.invalid(expected);
  }

  bool() {
    if (this.data.type === "bool") return this.data.value;
    throw this.invalid("a boolean");
  }

  unit(expected = "unit") {
    const { type, value } = this.data;
    // An owned one takes `{}` for a unit, as a newtype variant of `()`.
    if (type === "unit" || (this.owned && type === "map" && value.length === 0)) return undefined;
    throw this.invalid(expected);
  }

  unitStruct(expected) {
    const { type, value } = this.data;
    if (type === "unit" || (this.owned && (type === "map" || type === "seq") && value.length === 0))
      return undefined;
    throw this.invalid(expected);
  }

  option(read) {
    return this.data.type === "unit" ? undefined : read(this);
  }

  ignoreValue() {}

  content() {
    return this.data;
  }

  enum(variants, visit, other) {
    const { type, value } = this.data;
    let variant;
    let held;
    if (type === "map") {
      if (value.length !== 1)
        throw $jsonError("invalid value: map, expected map with a single key");
      [[variant, held]] = value;
    } else if (type === "str") {
      variant = this.data;
    } else {
      throw this.invalid("string or map");
    }
    const name = new $JsonContent(variant, this.owned).identifier(variants, other);
    return visit(name, new $JsonContentVariant(held, this.owned));
  }

  // A variant's name, or its index among the variants.
  identifier(variants, other) {
    const { type, value } = this.data;
    if (type === "str") return $jsonVariantNamed(value, variants, other);
    if (type !== "num" || value.kind !== "u") throw this.invalid("variant identifier");
    if (value.value < variants.length) return $jsonName(variants[Number(value.value)]);
    if (other !== undefined) return other;
    throw $jsonError(
      `invalid value: integer \`${value.value}\`, expected variant index 0 <= i < ${variants.length}`,
    );
  }
}

// `SeqAccess`.
class $JsonSeq {
  constructor(reader) {
    this.reader = reader;
    this.first = true;
  }

  // `has_next_element`.
  next() {
    const reader = this.reader;
    const peek = reader.parseWhitespace();
    if (peek === -1) throw reader.peekError("EOF while parsing a list");
    if (peek === 93) return false;
    if (this.first) {
      this.first = false;
      return true;
    }
    if (peek !== 44) throw reader.peekError("expected `,` or `]`");
    reader.index++;
    const c = reader.parseWhitespace();
    if (c === 93) throw reader.peekError("trailing comma");
    if (c === -1) throw reader.peekError("EOF while parsing a value");
    return true;
  }

  value(read) {
    return read(this.reader);
  }

  // The `i`th of `expected`'s items.
  element(read, i, expected, missing, defaults) {
    if (this.next()) return this.value(read);
    if (missing) return missing(defaults);
    throw $jsonError(`invalid length ${i}, expected ${expected}`);
  }
}

// The items of a value already read.
class $JsonContentSeq {
  constructor(items, owned) {
    this.items = items;
    this.owned = owned;
    this.count = 0;
  }

  next() {
    return this.count < this.items.length && ++this.count > 0;
  }

  value(read) {
    return read(new $JsonContent(this.items[this.count - 1], this.owned));
  }

  element(read, i, expected, missing, defaults) {
    return $JsonSeq.prototype.element.call(this, read, i, expected, missing, defaults);
  }

  // Items left over: the length is wrong.
  end() {
    const length = this.items.length;
    if (this.count < length) {
      const count = this.count;
      throw $jsonError(
        `invalid length ${length}, expected ${count} element${count === 1 ? "" : "s"} in sequence`,
      );
    }
  }
}

// `MapAccess`.
class $JsonMap {
  constructor(reader) {
    this.reader = reader;
    this.first = true;
  }

  // `has_next_key`.
  next() {
    const reader = this.reader;
    const peek = reader.parseWhitespace();
    if (peek === -1) throw reader.peekError("EOF while parsing an object");
    if (peek === 125) return false;
    if (this.first) {
      this.first = false;
      if (peek === 34) return true;
      throw reader.peekError("key must be a string");
    }
    if (peek !== 44) throw reader.peekError("expected `,` or `}`");
    reader.index++;
    const c = reader.parseWhitespace();
    if (c === 34) return true;
    throw reader.peekError(
      c === 125
        ? "trailing comma"
        : c === -1
          ? "EOF while parsing a value"
          : "key must be a string",
    );
  }

  key() {
    return new $JsonKey(this.reader);
  }

  value(read) {
    this.reader.parseObjectColon();
    return read(this.reader);
  }
}

// The entries of a value already read.
class $JsonContentMap {
  constructor(entries, owned) {
    this.entries = entries;
    this.owned = owned;
    this.count = 0;
  }

  next() {
    return this.count < this.entries.length && ++this.count > 0;
  }

  key() {
    return new $JsonContentKey(this.entries[this.count - 1][0], this.owned);
  }

  value(read) {
    return read(new $JsonContent(this.entries[this.count - 1][1], this.owned));
  }

  end() {
    const length = this.entries.length;
    if (this.count < length) {
      const count = this.count;
      throw $jsonError(
        `invalid length ${length}, expected ${count} element${count === 1 ? "" : "s"} in map`,
      );
    }
  }
}

// `MapKey`: an object's key, from its opening quote. A number or a `bool`
// is read from inside the quotes.
class $JsonKey {
  constructor(reader) {
    this.reader = reader;
  }

  string() {
    this.reader.index++;
    return this.reader.parseStr();
  }

  char() {
    return $jsonChar(this.string());
  }

  ignore() {
    this.string();
  }

  content() {
    return { type: "str", value: this.string() };
  }

  number(read) {
    const reader = this.reader;
    reader.index++;
    const c = reader.peek();
    if (!(c === 45 || (c >= 48 && c <= 57)))
      throw reader.error("invalid value: expected key to be a number in quotes");
    const value = read(reader);
    if (reader.peek() !== 34) throw reader.peekError('expected `"`');
    reader.index++;
    return value;
  }

  bool() {
    const reader = this.reader;
    reader.index++;
    try {
      const c = reader.next();
      if (c === -1) throw reader.peekError("EOF while parsing a value");
      if (c === 116) {
        reader.parseIdent('rue"');
        return true;
      }
      if (c === 102) {
        reader.parseIdent('alse"');
        return false;
      }
      throw $jsonError(`invalid type: string ${$debugStr(reader.parseStr())}, expected a boolean`);
    } catch (e) {
      throw reader.fixPosition(e);
    }
  }
}

// A key already read: it's read as any other value is, so a number in
// quotes isn't a number, as in serde.
class $JsonContentKey {
  constructor(key, owned) {
    this.key = new $JsonContent(key, owned);
  }

  string() {
    return this.key.string();
  }

  char() {
    return this.key.char();
  }

  bool() {
    return this.key.bool();
  }

  ignore() {}

  content() {
    return this.key.content();
  }

  number(read) {
    return read(this.key);
  }
}

// `VariantAccess` of `{"Name": ..}`, or of `"Name"` (`unit`), which holds
// nothing.
class $JsonVariant {
  constructor(reader, unit) {
    this.reader = reader;
    this.isUnit = unit;
  }

  unit() {
    if (!this.isUnit) this.reader.unit();
  }

  newtype(read) {
    if (this.isUnit) throw $jsonError("invalid type: unit variant, expected newtype variant");
    return read(this.reader);
  }

  tuple(expected, fields, build, options) {
    if (this.isUnit) throw $jsonError("invalid type: unit variant, expected tuple variant");
    return this.reader.tupleStruct(expected, fields, build, options);
  }

  struct(expected, fields, build, options) {
    if (this.isUnit) throw $jsonError("invalid type: unit variant, expected struct variant");
    return this.reader.struct(expected, fields, build, options);
  }
}

// The same, of a value already read: what a variant holds, if anything.
class $JsonContentVariant {
  constructor(held, owned) {
    this.held = held;
    this.owned = owned;
  }

  reader(kind, types) {
    if (this.held === undefined) throw $jsonError(`invalid type: unit variant, expected ${kind}`);
    if (types && !types.includes(this.held.type)) {
      throw $jsonError(`invalid type: ${$jsonUnexpectedContent(this.held)}, expected ${kind}`);
    }
    return new $JsonContent(this.held, this.owned);
  }

  unit() {
    if (this.held !== undefined) new $JsonContent(this.held, this.owned).unit();
  }

  newtype(read) {
    return read(this.reader("newtype variant"));
  }

  tuple(expected, fields, build, options) {
    return this.reader("tuple variant", ["seq"]).tupleStruct(expected, fields, build, options);
  }

  struct(expected, fields, build, options) {
    return this.reader("struct variant", ["map", "seq"]).struct(expected, fields, build, options);
  }
}

// serde's `missing_field`: what a field that isn't there reads as, which is
// `None` for an `Option`, and otherwise an error. An adjacently tagged
// enum's content that isn't there is read so too, and is nothing for a
// unit variant.
class $JsonMissing {
  constructor(name) {
    this.name = name;
  }

  option() {
    return undefined;
  }

  untaggedUnit() {
    return undefined;
  }
}
for (const method of [
  "bool",
  "int",
  "f64",
  "string",
  "char",
  "unit",
  "unitStruct",
  "vec",
  "tuple",
  "array",
  "map",
  "struct",
  "untaggedStruct",
  "tupleStruct",
  "enum",
  "taggedUnit",
  "internallyTagged",
  "adjacentlyTagged",
  "untagged",
]) {
  $JsonMissing.prototype[method] = function () {
    throw $jsonError(`missing field \`${this.name}\``);
  };
}

const $JSON_UTF8 = new TextDecoder();
const $JSON_POW10 = Array.from({ length: 309 }, (_, i) => Number(`1e${i}`));

// `significand * 10 + digit`, a BigInt once it's past 2^53.
function $jsonGrow(significand, digit) {
  if (typeof significand === "number") {
    const grown = significand * 10 + digit;
    if (grown <= Number.MAX_SAFE_INTEGER) return grown;
  }
  return BigInt(significand) * 10n + BigInt(digit);
}

function $jsonHexDigit(c) {
  if (c >= 48 && c <= 57) return c - 48;
  if (c >= 65 && c <= 70) return c - 55;
  if (c >= 97 && c <= 102) return c - 87;
  return -1;
}

// serde's `Unexpected` of a number, a float as serde_json writes one.
function $jsonUnexpectedNumber(n) {
  return n.kind === "f" ? `floating point \`${$jsonNumber(n.value)}\`` : `integer \`${n.value}\``;
}

function $jsonChar(s) {
  if ([...s].length === 1) return s;
  throw $jsonError(`invalid value: string ${$debugStr(s)}, expected a character`);
}

// serde's `Unexpected` of a value already read.
function $jsonUnexpectedContent({ type, value }) {
  if (type === "unit") return "null";
  if (type === "bool") return `boolean \`${value}\``;
  if (type === "num") return $jsonUnexpectedNumber(value);
  if (type === "str") return `string ${$debugStr(value)}`;
  return type === "seq" ? "sequence" : "map";
}

// The variant a name names, or `other`'s, as a derive's variant visitor finds it.
function $jsonVariantNamed(name, variants, other) {
  for (const names of variants) {
    if (typeof names === "string" ? names === name : names.includes(name)) return $jsonName(names);
  }
  if (other !== undefined) return other;
  throw variants.length === 0
    ? $jsonError(`unknown variant \`${name}\`, there are no variants`)
    : $jsonError(`unknown variant \`${name}\`, expected ${$jsonOneOf(variants)}`);
}

function $jsonName(names) {
  return typeof names === "string" ? names : names[0];
}

// The field a key names, or -1 to skip its value.
function $jsonField(key, fields, deny) {
  const i = fields.findIndex(([names]) =>
    typeof names === "string" ? names === key : names.includes(key),
  );
  if (i >= 0 || !deny) return i;
  throw fields.length === 0
    ? $jsonError(`unknown field \`${key}\`, there are no fields`)
    : $jsonError(
        `unknown field \`${key}\`, expected ${$jsonOneOf(fields.map(([names]) => names))}`,
      );
}

// serde's `OneOf`, of each name and its aliases, which serde keeps sorted.
function $jsonOneOf(entries) {
  const byCodePoint = (a, b) => {
    const [x, y] = [[...a], [...b]];
    for (let i = 0; i < Math.min(x.length, y.length); i++) {
      const d = x[i].codePointAt(0) - y[i].codePointAt(0);
      if (d !== 0) return d;
    }
    return x.length - y.length;
  };
  const names = entries.flatMap((names) =>
    typeof names === "string" ? [names] : [...names].sort(byCodePoint),
  );
  const quoted = names.map((name) => `\`${name}\``);
  if (quoted.length === 1) return quoted[0];
  if (quoted.length === 2) return `${quoted[0]} or ${quoted[1]}`;
  return `one of ${quoted.join(", ")}`;
}

// What the crate reads with: `$json.u32`, `$json.option($json.string)`.
const $json = {
  bool: (json) => json.bool(),
  u8: (json) => json.int("u8", 0, 255),
  u16: (json) => json.int("u16", 0, 65535),
  u32: (json) => json.int("u32", 0, 4294967295),
  usize: (json) => json.int("usize", 0, 4294967295),
  i8: (json) => json.int("i8", -128, 127),
  i16: (json) => json.int("i16", -32768, 32767),
  i32: (json) => json.int("i32", -2147483648, 2147483647),
  isize: (json) => json.int("isize", -2147483648, 2147483647),
  f64: (json) => json.f64(),
  string: (json) => json.string(),
  char: (json) => json.char(),
  unit: (json) => json.unit(),
  option: (read) => (json) => json.option(read),
  vec: (read) => (json) => json.vec(read),
  set: (read) => (json) => new Set(json.vec(read)),
  map: (readKey, read) => (json) => json.map(readKey, read),
  tuple:
    (...reads) =>
    (json) =>
      json.tuple(reads),
  array: (length, read) => (json) => json.array(length, read),
  // An object's keys.
  key: {
    string: (key) => key.string(),
    char: (key) => key.char(),
    bool: (key) => key.bool(),
    number: (read) => (key) => key.number(read),
  },
};

// `serde_json::from_str`: a `Result` of what `read` reads, which must be
// all there is.
function $fromJson(text, read) {
  const json = new $JsonReader(text);
  try {
    const value = read(json);
    json.end();
    return { TAG: "Ok", _0: value };
  } catch (e) {
    if (e instanceof $JsonError)
      return { TAG: "Err", _0: { message: e.message, line: e.line, column: e.column } };
    throw e;
  }
}

function $unwrapOk(result, message = "called `Result::unwrap()` on an `Err` value") {
  if (result.TAG === "Err") {
    throw new Error(message + ": " + $debug(result._0));
  }
  return result._0;
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function $debugF64(value) {
  const size = Math.abs(value);
  if (Number.isFinite(value) && size !== 0 && (size < 1e-4 || size >= 1e16)) {
    return value.toExponential().replace("e+", "e");
  }
  const text = $displayF64(value);
  return Number.isFinite(value) && !text.includes(".") ? text + ".0" : text;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

function $debugFields(name, fields, values) {
  return name + " { " + fields.map((field, i) => field + ": " + values[i]).join(", ") + " }";
}

export function sample() {
  const order = {
    order_id: 7,
    item_name: 'pen "blue"',
    qty: 3,
    note: undefined,
    price: 2.5,
    tags: ["a", "b\n"],
    paid: true,
    cache: 99,
  };
  let counts = new Map();
  counts.set("x", 1);
  counts.set("a", 2);
  let byId = new Map();
  byId.set(10, true);
  byId.set(2, false);
  return {
    id: [5],
    at: [-1, 2],
    unit: undefined,
    len: { value: 1 },
    shapes: [
      "Dot",
      { TAG: "Circle", _0: 1.5 },
      { TAG: "Rect", _0: 2, _1: 3 },
      { TAG: "Poly", sides: 6, name: "hex" },
    ],
    events: ["Started", { TAG: "Moved", dx: 1, dy: -2 }, { TAG: "Placed", _0: order }],
    msgs: ["Ping", { TAG: "Text", _0: "hi" }, { TAG: "Pair", _0: 1, _1: 2 }],
    loose: [{ TAG: "Num", _0: 1e21 }, { TAG: "Word", _0: "w" }, "Nothing"],
    counts,
    by_id: byId,
    pair: [255, "é", undefined],
    empty: [],
    nested: [[], [1, 2]],
    text: "tab	ü😀",
    floats: [0.1, -0, 1e-7, 123456789, NaN, 10000000000000000],
  };
}

export function report() {
  const e = sample();
  const order = {
    order_id: 1,
    item_name: "x",
    qty: 1,
    note: "gift",
    price: 0,
    tags: [],
    paid: false,
    cache: 0,
  };
  const events = $unwrapOk(
    $fromJson(
      $unwrapOk(
        $toJson(
          e.events,
          (value, json) => {
            json.beginArray();
            for (const item of value) {
              json.element();
              eventSerialize_serialize(item, json);
            }
            json.endArray();
          },
          false,
        ),
      ),
      $json.vec(eventDeserialize_deserialize),
    ),
  );
  const msgs = $unwrapOk(
    $fromJson(
      $unwrapOk(
        $toJson(
          e.msgs,
          (value$1, json$1) => {
            json$1.beginArray();
            for (const item$1 of value$1) {
              json$1.element();
              msgSerialize_serialize(item$1, json$1);
            }
            json$1.endArray();
          },
          false,
        ),
      ),
      $json.vec(msgDeserialize_deserialize),
    ),
  );
  const loose = $unwrapOk(
    $fromJson(
      $unwrapOk(
        $toJson(
          e.loose,
          (value$2, json$2) => {
            json$2.beginArray();
            for (const item$2 of value$2) {
              json$2.element();
              looseSerialize_serialize(item$2, json$2);
            }
            json$2.endArray();
          },
          false,
        ),
      ),
      $json.vec(looseDeserialize_deserialize),
    ),
  );
  return `${$unwrapOk($toJson(e, everythingSerialize_serialize, false))}\n${$unwrapOk($toJson(e, everythingSerialize_serialize, true))}\n${$unwrapOk($toJson(order, orderSerialize_serialize, false))}\n[${events.map((item) => eventDebug_fmt(item)).join(", ")}]\n[${msgs.map((item) => msgDebug_fmt(item)).join(", ")}]\n[${loose.map((item) => looseDebug_fmt(item)).join(", ")}]\n`;
}

function orderDebug_fmt(order) {
  const names = ["order_id", "item_name", "qty", "note", "price", "tags", "paid", "cache"];
  const values = [
    String(order.order_id),
    $debugStr(order.item_name),
    String(order.qty),
    order.note == null ? "None" : `Some(${$debugStr(order.note)})`,
    $debugF64(order.price),
    `[${order.tags.map((item) => $debugStr(item)).join(", ")}]`,
    String(order.paid),
    String(order.cache),
  ];
  return $debugFields("Order", names, values);
}

function eventDebug_fmt(event) {
  if (event === "Started") {
    return "Started";
  } else if (event.TAG === "Moved") {
    return `Moved { dx: ${event.dx}, dy: ${event.dy} }`;
  } else {
    return `Placed(${orderDebug_fmt(event._0)})`;
  }
}

function msgDebug_fmt(msg) {
  if (msg === "Ping") {
    return "Ping";
  } else if (msg.TAG === "Text") {
    return `Text(${$debugStr(msg._0)})`;
  } else {
    return `Pair(${msg._0}, ${msg._1})`;
  }
}

function looseDebug_fmt(loose) {
  if (loose.TAG === "Num") {
    return `Num(${$debugF64(loose._0)})`;
  } else if (loose.TAG === "Word") {
    return `Word(${$debugStr(loose._0)})`;
  } else {
    return "Nothing";
  }
}

function orderSerialize_serialize(order, json) {
  json.beginObject();
  json.key("orderId");
  json.raw(String(order.order_id));
  json.key("itemName");
  json.string(order.item_name);
  json.key("qty");
  json.raw(String(order.qty));
  if (order.note != null) {
    json.key("note");
    json.string(order.note);
  }
  json.key("price");
  json.number(order.price);
  json.key("tags");
  json.beginArray();
  for (const item of order.tags) {
    json.element();
    json.string(item);
  }
  json.endArray();
  json.key("ok");
  json.raw(String(order.paid));
  json.endObject();
}

function eventSerialize_serialize(event, json) {
  if (event === "Started") {
    json.beginObject();
    json.key("type");
    json.string("started");
    json.endObject();
  } else if (event.TAG === "Moved") {
    json.beginObject();
    json.key("type");
    json.string("moved");
    json.key("dx");
    json.raw(String(event.dx));
    json.key("dy");
    json.raw(String(event.dy));
    json.endObject();
  } else {
    json.beginObject();
    json.key("type");
    json.string("placed");
    json.key("orderId");
    json.raw(String(event._0.order_id));
    json.key("itemName");
    json.string(event._0.item_name);
    json.key("qty");
    json.raw(String(event._0.qty));
    if (event._0.note != null) {
      json.key("note");
      json.string(event._0.note);
    }
    json.key("price");
    json.number(event._0.price);
    json.key("tags");
    json.beginArray();
    for (const item of event._0.tags) {
      json.element();
      json.string(item);
    }
    json.endArray();
    json.key("ok");
    json.raw(String(event._0.paid));
    json.endObject();
  }
}

function eventDeserialize_deserialize(json) {
  return json.internallyTagged(
    "type",
    "internally tagged enum Event",
    ["started", "moved", "placed"],
    (variant, content) => {
      if (variant === "started") {
        content.taggedUnit("unit variant Event::Started");
        return "Started";
      } else if (variant === "moved") {
        return content.struct(
          "struct variant Event::Moved",
          [
            ["dx", $json.i32],
            ["dy", $json.i32],
          ],
          ([dx, dy]) => ({ TAG: "Moved", dx, dy }),
        );
      } else {
        return { TAG: "Placed", _0: orderDeserialize_deserialize(content) };
      }
    },
  );
}

function msgSerialize_serialize(msg, json) {
  if (msg === "Ping") {
    json.beginObject();
    json.key("t");
    json.string("Ping");
    json.endObject();
  } else if (msg.TAG === "Text") {
    json.beginObject();
    json.key("t");
    json.string("Text");
    json.key("c");
    json.string(msg._0);
    json.endObject();
  } else {
    json.beginObject();
    json.key("t");
    json.string("Pair");
    json.key("c");
    json.beginArray();
    json.element();
    json.raw(String(msg._0));
    json.element();
    json.raw(String(msg._1));
    json.endArray();
    json.endObject();
  }
}

function msgDeserialize_deserialize(json) {
  return json.adjacentlyTagged(
    "t",
    "c",
    "adjacently tagged enum Msg",
    ["Ping", "Text", "Pair"],
    (variant, content) => {
      if (variant === "Ping") {
        content.untaggedUnit("unit variant Msg::Ping");
        return "Ping";
      } else if (variant === "Text") {
        return { TAG: "Text", _0: $json.string(content) };
      } else {
        return content.tupleStruct(
          "tuple variant Msg::Pair",
          [$json.u32, $json.u32],
          ([_0, _1]) => ({ TAG: "Pair", _0, _1 }),
        );
      }
    },
  );
}

function looseSerialize_serialize(loose, json) {
  if (loose.TAG === "Num") {
    json.number(loose._0);
  } else if (loose.TAG === "Word") {
    json.string(loose._0);
  } else {
    json.raw("null");
  }
}

function looseDeserialize_deserialize(json) {
  return json.untagged("data did not match any variant of untagged enum Loose", [
    (content) => ({ TAG: "Num", _0: $json.f64(content) }),
    (content) => ({ TAG: "Word", _0: $json.string(content) }),
    (content) => {
      content.untaggedUnit("unit variant Loose::Nothing");
      return "Nothing";
    },
  ]);
}

function everythingSerialize_serialize(everything, json) {
  json.beginObject();
  json.key("id");
  idSerialize_serialize(everything.id, json);
  json.key("at");
  pointSerialize_serialize(everything.at, json);
  json.key("unit");
  unitSerialize_serialize(everything.unit, json);
  json.key("len");
  metersSerialize_serialize(everything.len, json);
  json.key("shapes");
  json.beginArray();
  for (const item of everything.shapes) {
    json.element();
    shapeSerialize_serialize(item, json);
  }
  json.endArray();
  json.key("events");
  json.beginArray();
  for (const item$1 of everything.events) {
    json.element();
    eventSerialize_serialize(item$1, json);
  }
  json.endArray();
  json.key("msgs");
  json.beginArray();
  for (const item$2 of everything.msgs) {
    json.element();
    msgSerialize_serialize(item$2, json);
  }
  json.endArray();
  json.key("loose");
  json.beginArray();
  for (const item$3 of everything.loose) {
    json.element();
    looseSerialize_serialize(item$3, json);
  }
  json.endArray();
  json.key("counts");
  json.beginObject();
  for (const [key, item$4] of $sortedEntries(everything.counts, $cmp)) {
    json.key(key);
    json.raw(String(item$4));
  }
  json.endObject();
  json.key("by_id");
  json.beginObject();
  for (const [key$1, item$5] of $sortedEntries(everything.by_id, $cmp)) {
    json.key(String(key$1));
    json.raw(String(item$5));
  }
  json.endObject();
  json.key("pair");
  json.beginArray();
  json.element();
  json.raw(String(everything.pair[0]));
  json.element();
  json.string(everything.pair[1]);
  json.element();
  if (everything.pair[2] == null) {
    json.raw("null");
  } else {
    json.raw(String(everything.pair[2]));
  }
  json.endArray();
  json.key("empty");
  json.beginArray();
  for (const item$6 of everything.empty) {
    json.element();
    json.raw(String(item$6));
  }
  json.endArray();
  json.key("nested");
  json.beginArray();
  for (const item$7 of everything.nested) {
    json.element();
    json.beginArray();
    for (const item$8 of item$7) {
      json.element();
      json.raw(String(item$8));
    }
    json.endArray();
  }
  json.endArray();
  json.key("text");
  json.string(everything.text);
  json.key("floats");
  json.beginArray();
  for (const item$9 of everything.floats) {
    json.element();
    json.number(item$9);
  }
  json.endArray();
  json.endObject();
}

function orderDeserialize_deserialize(json) {
  return json.struct(
    "struct Order",
    [
      ["orderId", $json.u32],
      ["itemName", $json.string],
      ["qty", $json.u8],
      ["note", $json.option($json.string)],
      ["price", $json.f64],
      ["tags", $json.vec($json.string)],
      ["ok", $json.bool],
    ],
    ([order_id, item_name, qty, note, price, tags, paid]) => ({
      order_id,
      item_name,
      qty,
      note,
      price,
      tags,
      paid,
      cache: 0,
    }),
  );
}

function shapeSerialize_serialize(shape, json) {
  if (shape === "Dot") {
    json.string("Dot");
  } else if (shape.TAG === "Circle") {
    json.beginObject();
    json.key("Circle");
    json.number(shape._0);
    json.endObject();
  } else if (shape.TAG === "Rect") {
    json.beginObject();
    json.key("Rect");
    json.beginArray();
    json.element();
    json.number(shape._0);
    json.element();
    json.number(shape._1);
    json.endArray();
    json.endObject();
  } else {
    json.beginObject();
    json.key("Poly");
    json.beginObject();
    json.key("sides");
    json.raw(String(shape.sides));
    json.key("name");
    json.string(shape.name);
    json.endObject();
    json.endObject();
  }
}

function idSerialize_serialize(id, json) {
  json.raw(String(id[0]));
}

function pointSerialize_serialize(point, json) {
  json.beginArray();
  json.element();
  json.raw(String(point[0]));
  json.element();
  json.raw(String(point[1]));
  json.endArray();
}

function unitSerialize_serialize(unit, json) {
  json.raw("null");
}

function metersSerialize_serialize(meters, json) {
  json.number(meters.value);
}
//# sourceMappingURL=wire.js.map
