// Generated by rust-js from examples/wire.rs. Do not edit.

function $debug(v) {
  if (typeof v === "string") {
    return JSON.stringify(v);
  }
  if (Array.isArray(v)) {
    return "[" + v.map($debug).join(", ") + "]";
  }
  if (v === undefined) {
    return "()";
  }
  // A `HashMap` and a `HashSet` (ADR 0059), in braces as Rust shows them.
  if (v instanceof Map) {
    return "{" + [...v].map(([k, x]) => $debug(k) + ": " + $debug(x)).join(", ") + "}";
  }
  if (v instanceof Set) {
    return "{" + [...v].map($debug).join(", ") + "}";
  }
  if (typeof v === "object" && v !== null) {
    return (
      "{ " +
      Object.entries(v)
        .map(([k, x]) => k + ": " + $debug(x))
        .join(", ") +
      " }"
    );
  }
  return String(v);
}

function $sortedEntries(map, cmp) {
  return Array.from(map).sort((a, b) => cmp(a[0], b[0]));
}

class $JsonError extends Error {
  constructor(message, line = 0, column = 0) {
    super(message);
    this.line = line;
    this.column = column;
  }
}
function $jsonError(message) {
  return new $JsonError(message);
}
// A float as serde_json writes one: its shortest digits, fixed from 1e-5
// to 1e15, else `1.5e+16`.
function $jsonNumber(x) {
  if (!Number.isFinite(x)) return "null";
  if (x === 0) return Object.is(x, -0) ? "-0.0" : "0.0";
  const [mantissa, exponent] = x.toExponential().split("e");
  const e = Number(exponent);
  if (e < -5 || e > 15) return `${mantissa}e${e < 0 ? "-" : "+"}${Math.abs(e)}`;
  const fixed = String(x);
  return fixed.includes(".") ? fixed : `${fixed}.0`;
}

function $jsonWriter(pretty) {
  // For each array or object open: whether nothing is in it yet.
  const empty = [];
  const next = (json) => {
    const first = empty[empty.length - 1];
    empty[empty.length - 1] = false;
    if (pretty) json.text += (first ? "\n" : ",\n") + "  ".repeat(empty.length);
    else if (!first) json.text += ",";
  };
  const open = (json, bracket) => {
    empty.push(true);
    json.text += bracket;
  };
  const close = (json, bracket) => {
    if (!empty.pop() && pretty) json.text += "\n" + "  ".repeat(empty.length);
    json.text += bracket;
  };
  return {
    text: "",
    raw(text) {
      this.text += text;
    },
    string(s) {
      this.text += JSON.stringify(s);
    },
    number(x) {
      this.text += $jsonNumber(x);
    },
    beginArray() {
      open(this, "[");
    },
    element() {
      next(this);
    },
    endArray() {
      close(this, "]");
    },
    beginObject() {
      open(this, "{");
    },
    key(k) {
      next(this);
      this.text += JSON.stringify(k) + (pretty ? ": " : ":");
    },
    endObject() {
      close(this, "}");
    },
  };
}
function $toJson(value, write, pretty) {
  const json = $jsonWriter(pretty);
  try {
    write(value, json);
  } catch (e) {
    if (e instanceof $JsonError)
      return { TAG: "Err", _0: { message: e.message, line: e.line, column: e.column } };
    throw e;
  }
  return { TAG: "Ok", _0: json.text };
}

function $unwrapOk(result, message = "called `Result::unwrap()` on an `Err` value") {
  if (result.TAG === "Err") {
    throw new Error(message + ": " + $debug(result._0));
  }
  return result._0;
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

export function sample() {
  const order = {
    order_id: 7,
    item_name: 'pen "blue"',
    qty: 3,
    note: undefined,
    price: 2.5,
    tags: ["a", "b\n"],
    paid: true,
    cache: 99,
  };
  let counts = new Map();
  counts.set("x", 1);
  counts.set("a", 2);
  let byId = new Map();
  byId.set(10, true);
  byId.set(2, false);
  return {
    id: [5],
    at: [-1, 2],
    unit: undefined,
    len: { value: 1 },
    shapes: [
      "Dot",
      { TAG: "Circle", _0: 1.5 },
      { TAG: "Rect", _0: 2, _1: 3 },
      { TAG: "Poly", sides: 6, name: "hex" },
    ],
    events: ["Started", { TAG: "Moved", dx: 1, dy: -2 }, { TAG: "Placed", _0: order }],
    msgs: ["Ping", { TAG: "Text", _0: "hi" }, { TAG: "Pair", _0: 1, _1: 2 }],
    loose: [{ TAG: "Num", _0: 1e21 }, { TAG: "Word", _0: "w" }, "Nothing"],
    counts,
    by_id: byId,
    pair: [255, "é", undefined],
    empty: [],
    nested: [[], [1, 2]],
    text: "tab	ü😀",
    floats: [0.1, -0, 1e-7, 123456789, NaN, 10000000000000000],
  };
}

export function report() {
  const e = sample();
  const order = {
    order_id: 1,
    item_name: "x",
    qty: 1,
    note: "gift",
    price: 0,
    tags: [],
    paid: false,
    cache: 0,
  };
  return `${$unwrapOk($toJson(e, everythingSerialize_serialize, false))}\n${$unwrapOk($toJson(e, everythingSerialize_serialize, true))}\n${$unwrapOk($toJson(order, orderSerialize_serialize, false))}\n`;
}

function orderSerialize_serialize(order, json) {
  json.beginObject();
  json.key("orderId");
  json.raw(String(order.order_id));
  json.key("itemName");
  json.string(order.item_name);
  json.key("qty");
  json.raw(String(order.qty));
  if (order.note != null) {
    json.key("note");
    json.string(order.note);
  }
  json.key("price");
  json.number(order.price);
  json.key("tags");
  json.beginArray();
  for (const item of order.tags) {
    json.element();
    json.string(item);
  }
  json.endArray();
  json.key("ok");
  json.raw(String(order.paid));
  json.endObject();
}

function everythingSerialize_serialize(everything, json) {
  json.beginObject();
  json.key("id");
  idSerialize_serialize(everything.id, json);
  json.key("at");
  pointSerialize_serialize(everything.at, json);
  json.key("unit");
  unitSerialize_serialize(everything.unit, json);
  json.key("len");
  metersSerialize_serialize(everything.len, json);
  json.key("shapes");
  json.beginArray();
  for (const item of everything.shapes) {
    json.element();
    shapeSerialize_serialize(item, json);
  }
  json.endArray();
  json.key("events");
  json.beginArray();
  for (const item$1 of everything.events) {
    json.element();
    eventSerialize_serialize(item$1, json);
  }
  json.endArray();
  json.key("msgs");
  json.beginArray();
  for (const item$2 of everything.msgs) {
    json.element();
    msgSerialize_serialize(item$2, json);
  }
  json.endArray();
  json.key("loose");
  json.beginArray();
  for (const item$3 of everything.loose) {
    json.element();
    looseSerialize_serialize(item$3, json);
  }
  json.endArray();
  json.key("counts");
  json.beginObject();
  for (const [key, item$4] of $sortedEntries(everything.counts, $cmp)) {
    json.key(key);
    json.raw(String(item$4));
  }
  json.endObject();
  json.key("by_id");
  json.beginObject();
  for (const [key$1, item$5] of $sortedEntries(everything.by_id, $cmp)) {
    json.key(String(key$1));
    json.raw(String(item$5));
  }
  json.endObject();
  json.key("pair");
  json.beginArray();
  json.element();
  json.raw(String(everything.pair[0]));
  json.element();
  json.string(everything.pair[1]);
  json.element();
  if (everything.pair[2] == null) {
    json.raw("null");
  } else {
    json.raw(String(everything.pair[2]));
  }
  json.endArray();
  json.key("empty");
  json.beginArray();
  for (const item$6 of everything.empty) {
    json.element();
    json.raw(String(item$6));
  }
  json.endArray();
  json.key("nested");
  json.beginArray();
  for (const item$7 of everything.nested) {
    json.element();
    json.beginArray();
    for (const item$8 of item$7) {
      json.element();
      json.raw(String(item$8));
    }
    json.endArray();
  }
  json.endArray();
  json.key("text");
  json.string(everything.text);
  json.key("floats");
  json.beginArray();
  for (const item$9 of everything.floats) {
    json.element();
    json.number(item$9);
  }
  json.endArray();
  json.endObject();
}

function shapeSerialize_serialize(shape, json) {
  if (shape === "Dot") {
    json.string("Dot");
  } else if (shape.TAG === "Circle") {
    json.beginObject();
    json.key("Circle");
    json.number(shape._0);
    json.endObject();
  } else if (shape.TAG === "Rect") {
    json.beginObject();
    json.key("Rect");
    json.beginArray();
    json.element();
    json.number(shape._0);
    json.element();
    json.number(shape._1);
    json.endArray();
    json.endObject();
  } else {
    json.beginObject();
    json.key("Poly");
    json.beginObject();
    json.key("sides");
    json.raw(String(shape.sides));
    json.key("name");
    json.string(shape.name);
    json.endObject();
    json.endObject();
  }
}

function eventSerialize_serialize(event, json) {
  if (event === "Started") {
    json.beginObject();
    json.key("type");
    json.string("started");
    json.endObject();
  } else if (event.TAG === "Moved") {
    json.beginObject();
    json.key("type");
    json.string("moved");
    json.key("dx");
    json.raw(String(event.dx));
    json.key("dy");
    json.raw(String(event.dy));
    json.endObject();
  } else {
    json.beginObject();
    json.key("type");
    json.string("placed");
    json.key("orderId");
    json.raw(String(event._0.order_id));
    json.key("itemName");
    json.string(event._0.item_name);
    json.key("qty");
    json.raw(String(event._0.qty));
    if (event._0.note != null) {
      json.key("note");
      json.string(event._0.note);
    }
    json.key("price");
    json.number(event._0.price);
    json.key("tags");
    json.beginArray();
    for (const item of event._0.tags) {
      json.element();
      json.string(item);
    }
    json.endArray();
    json.key("ok");
    json.raw(String(event._0.paid));
    json.endObject();
  }
}

function msgSerialize_serialize(msg, json) {
  if (msg === "Ping") {
    json.beginObject();
    json.key("t");
    json.string("Ping");
    json.endObject();
  } else if (msg.TAG === "Text") {
    json.beginObject();
    json.key("t");
    json.string("Text");
    json.key("c");
    json.string(msg._0);
    json.endObject();
  } else {
    json.beginObject();
    json.key("t");
    json.string("Pair");
    json.key("c");
    json.beginArray();
    json.element();
    json.raw(String(msg._0));
    json.element();
    json.raw(String(msg._1));
    json.endArray();
    json.endObject();
  }
}

function looseSerialize_serialize(loose, json) {
  if (loose.TAG === "Num") {
    json.number(loose._0);
  } else if (loose.TAG === "Word") {
    json.string(loose._0);
  } else {
    json.raw("null");
  }
}

function idSerialize_serialize(id, json) {
  json.raw(String(id[0]));
}

function pointSerialize_serialize(point, json) {
  json.beginArray();
  json.element();
  json.raw(String(point[0]));
  json.element();
  json.raw(String(point[1]));
  json.endArray();
}

function unitSerialize_serialize(unit, json) {
  json.raw("null");
}

function metersSerialize_serialize(meters, json) {
  json.number(meters.value);
}
//# sourceMappingURL=wire.js.map
