// Generated by rust-js from examples/queues.rs. Do not edit.

function $traitImpl(cache, keys, make) {
  for (let i = 0; i < keys.length - 1; i++) {
    const key = keys[i];
    if (!cache.has(key)) cache.set(key, new WeakMap());
    cache = cache.get(key);
  }
  const key = keys[keys.length - 1];
  if (!cache.has(key)) cache.set(key, make());
  return cache.get(key);
}

function $index(items, index) {
  if (index < 0 || index >= items.length)
    throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return items[index];
}

function $at(items, index) {
  if (index < 0 || index >= items.length)
    throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return index;
}

// Shortest round-trip decimal, using exact rational arithmetic.
// Rust Display uses decimal notation, including for very small/large values.
// Not JS's `String(x)`, though its digits are also the shortest: when two are
// equally close, JS takes the even one (1888570120608320.2), and Rust the
// larger (1888570120608320.3).
function $displayF64(value) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const x = Math.abs(value);
  if (x === 0) return sign + "0";

  const bitsView = new DataView(new ArrayBuffer(8));
  bitsView.setFloat64(0, x);
  const bits = bitsView.getBigUint64(0);
  const exponentBits = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponentBits === 0 ? fraction : fraction + (1n << 52n);
  const binaryExponent = exponentBits === 0 ? -1074 : exponentBits - 1023 - 52;
  const numerator = binaryExponent >= 0 ? significand << BigInt(binaryExponent) : significand;
  const denominator = binaryExponent < 0 ? 1n << BigInt(-binaryExponent) : 1n;

  // The floating-point logarithm is only an estimate; correct it exactly.
  let exponent = Math.floor(Math.log10(x));
  const atLeastPowerOfTen = (e) =>
    e >= 0
      ? numerator >= denominator * 10n ** BigInt(e)
      : numerator * 10n ** BigInt(-e) >= denominator;
  while (!atLeastPowerOfTen(exponent)) exponent--;
  while (atLeastPowerOfTen(exponent + 1)) exponent++;

  for (let precision = 1; precision <= 17; precision++) {
    const power = exponent - precision + 1;
    const n = power < 0 ? numerator * 10n ** BigInt(-power) : numerator;
    const d = power > 0 ? denominator * 10n ** BigInt(power) : denominator;
    const floor = n / d;
    const rounded = floor + (2n * (n % d) >= d ? 1n : 0n);
    // The rounding interval can be asymmetric at a binary power boundary.
    let best;
    let bestDistance;
    for (const candidate of [rounded, rounded - 1n, rounded + 1n]) {
      if (candidate > 0n && Number(`${candidate}e${power}`) === x) {
        const delta = candidate * d - n;
        const distance = delta < 0n ? -delta : delta;
        if (
          best === undefined ||
          distance < bestDistance ||
          (distance === bestDistance && candidate > best)
        ) {
          best = candidate;
          bestDistance = distance;
        }
      }
    }
    if (best !== undefined) {
      let digits = best.toString();
      let decimalPower = power;
      while (digits.endsWith("0")) {
        digits = digits.slice(0, -1);
        decimalPower++;
      }
      const point = digits.length + decimalPower;
      const body =
        point <= 0
          ? "0." + "0".repeat(-point) + digits
          : point >= digits.length
            ? digits + "0".repeat(point - digits.length)
            : digits.slice(0, point) + "." + digits.slice(point);
      return sign + body;
    }
  }
  throw new Error("No f64 round-trip decimal found");
}

function $retain(v, keep) {
  let n = 0;
  for (const x of v) {
    if (keep(x)) {
      v[n++] = x;
    }
  }
  v.length = n;
}

function $eq(a, b) {
  if (a === b || (a == null && b == null)) {
    return true;
  }
  if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) {
    return false;
  }
  if (Array.isArray(a)) {
    return Array.isArray(b) && a.length === b.length && a.every((x, i) => $eq(x, b[i]));
  }
  const keys = Object.keys(a);
  return keys.length === Object.keys(b).length && keys.every((k) => $eq(a[k], b[k]));
}

function $unwrap(value, message = "called `Option::unwrap()` on a `None` value") {
  if (value == null) {
    throw new Error(message);
  }
  return value;
}

// `Some(x)` of a generic `T` (ADR 0051): `x`, unless it looks like `None`,
// as `undefined`, `null` or such a box does. Then it's a box one deeper.
function $some(x) {
  if (x == null) return { $someNone: 0 };
  if (typeof x === "object" && "$someNone" in x) return { $someNone: x.$someNone + 1 };
  return x;
}

// `Some` of the item at `index`, or `None` when there's none there.
function $someAt(items, index) {
  return index >= 0 && index < items.length ? $some(items[index]) : undefined;
}

// `Vec::pop` of a generic `T`: `None` for an empty one, else `Some` of the last.
function $pop(items) {
  return items.length === 0 ? undefined : $some(items.pop());
}

function $orInsert(map, key, value) {
  if (!map.has(key)) {
    map.set(key, value);
  }
  return map.get(key);
}

function $removeOpt(items, index) {
  return index < items.length ? items.splice(index, 1)[0] : undefined;
}

function $siftUp(heap, start, pos, cmp) {
  const item = heap[pos];
  while (pos > start) {
    const parent = (pos - 1) >>> 1;
    if (cmp(item, heap[parent]) <= 0) {
      break;
    }
    heap[pos] = heap[parent];
    pos = parent;
  }
  heap[pos] = item;
  return pos;
}

function $siftDown(heap, pos, end, cmp) {
  const item = heap[pos];
  let child = 2 * pos + 1;
  while (child <= end - 2) {
    if (cmp(heap[child], heap[child + 1]) <= 0) {
      child += 1;
    }
    if (cmp(item, heap[child]) >= 0) {
      heap[pos] = item;
      return pos;
    }
    heap[pos] = heap[child];
    pos = child;
    child = 2 * pos + 1;
  }
  if (child === end - 1 && cmp(item, heap[child]) < 0) {
    heap[pos] = heap[child];
    pos = child;
  }
  heap[pos] = item;
  return pos;
}

function $heapPush(heap, item, cmp) {
  heap.push(item);
  $siftUp(heap, 0, heap.length - 1, cmp);
}

function $heapPop(heap, cmp) {
  if (heap.length === 0) {
    return undefined;
  }
  let top = heap.pop();
  if (heap.length > 0) {
    [top, heap[0]] = [heap[0], top];
    const end = heap.length;
    const item = heap[0];
    let pos = 0;
    let child = 1;
    while (child <= end - 2) {
      if (cmp(heap[child], heap[child + 1]) <= 0) {
        child += 1;
      }
      heap[pos] = heap[child];
      pos = child;
      child = 2 * pos + 1;
    }
    if (child === end - 1) {
      heap[pos] = heap[child];
      pos = child;
    }
    heap[pos] = item;
    $siftUp(heap, 0, pos, cmp);
  }
  return top;
}

function $heapSorted(items, cmp) {
  const heap = items.slice();
  let end = heap.length;
  while (end > 1) {
    end -= 1;
    [heap[0], heap[end]] = [heap[end], heap[0]];
    $siftDown(heap, 0, end, cmp);
  }
  return heap;
}

function $heapFrom(items, cmp) {
  const heap = items.slice();
  let n = heap.length >>> 1;
  while (n > 0) {
    n -= 1;
    $siftDown(heap, n, heap.length, cmp);
  }
  return heap;
}

function $range(start, end) {
  return Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

var $labeledDisplay, $taskOrd, $taskPartialOrd;

export const Stack = {
  new(TClone, TDebug) {
    return { items: [] };
  },
  push(stack, x, TClone, TDebug) {
    stack.items.push(x);
  },
  pop(stack, TClone, TDebug) {
    return $pop(stack.items);
  },
  peek(stack, TClone, TDebug) {
    return $someAt(stack.items, stack.items.length - 1);
  },
  len(stack, TClone, TDebug) {
    return stack.items.length;
  },
};

export const Pipeline = {
  run(pipeline, x) {
    return pipeline.steps.reduce((acc, f) => f(acc), x);
  },
};

function first_even_square(v) {
  const e = v.find((x) => x % 2 === 0);
  if (e == null) {
    return undefined;
  }
  return Math.imul(e, e);
}

export function dijkstra(edges, n, src) {
  let adj = Array.from({ length: n }, () => []);
  for (const [a, b, w] of edges) {
    $index(adj, a).push([b, w]);
    $index(adj, b).push([a, w]);
  }
  let dist = new Array(n).fill(undefined);
  let heap = [];
  dist[$at(dist, src)] = 0;
  $heapPush(heap, [[0, src]], (a, b) => $cmp(b[0][0], a[0][0]) || $cmp(b[0][1], a[0][1]));
  while (true) {
    const value = $heapPop(heap, (a, b) => $cmp(b[0][0], a[0][0]) || $cmp(b[0][1], a[0][1]));
    if (value != null) {
      const option = $index(dist, value[0][1]);
      if (option != null && value[0][0] > option) {
        continue;
      }
      for (const [v, w$1] of $index(adj, value[0][1])) {
        const nd = (value[0][0] + w$1) >>> 0;
        const option$1 = $index(dist, v);
        if (option$1 == null || nd < option$1) {
          dist[$at(dist, v)] = nd;
          $heapPush(heap, [[nd, v]], (a, b) => $cmp(b[0][0], a[0][0]) || $cmp(b[0][1], a[0][1]));
        }
      }
    } else {
      break;
    }
  }
  return dist;
}

export function bfs_order(n, edges) {
  let seen = new Array(n).fill(false);
  let q = [];
  let order = [];
  q.push(0);
  seen[$at(seen, 0)] = true;
  while (true) {
    const u = q.shift();
    if (u != null) {
      order.push(u);
      for (const [a, b] of edges) {
        if (a === u && !$index(seen, b)) {
          seen[$at(seen, b)] = true;
          q.push(b);
        }
      }
    } else {
      break;
    }
  }
  return order;
}

export function heaps() {
  let out = "";
  let h = [];
  for (const [i, pri] of [3, 1, 3, 5, 1, 3, 2, 5, 0].entries()) {
    $heapPush(h, { pri, name: String.fromCharCode((97 + (i & 255)) & 255) }, taskOrd_cmp);
    out += `${$debugStr(h.map((t) => t.name).join(""))}\n`;
  }
  const t = h[0];
  const arg = t != null ? t.name : undefined;
  out += `peek ${arg == null ? "None" : `Some(${$debugStr(arg, "'")})`} len ${h.length}\n`;
  let popped = "";
  for (let i$1 = 0; i$1 < 4; i$1++) {
    popped += $unwrap($heapPop(h, taskOrd_cmp)).name;
    popped += h.map((t) => t.name).join("");
    popped += " ";
  }
  out += `${popped}\n`;
  const sorted = $heapSorted(h.slice(), taskOrd_cmp)
    .map((t) => t.name)
    .join("");
  const from = $heapFrom([4, 8, 1, 9, 9, 2, 7, 3], $cmp);
  const collected = $heapFrom([5, 1, 5, 2, 8].slice(), $cmp);
  const arg$1 = collected;
  const arg$2 = $heapSorted(from, $cmp);
  out += `${sorted} [${from.map((item) => String(item)).join(", ")}] [${arg$1.map((item) => String(item)).join(", ")}] [${arg$2.map((item) => String(item)).join(", ")}]\n`;
  let empty = [];
  const arg$3 = $heapPop(empty, $cmp);
  out += `${arg$3 == null ? "None" : `Some(${arg$3})`} ${empty[0] == null ? "None" : `Some(${empty[0]})`} ${empty.length === 0}\n`;
  return out;
}

export function deques() {
  let d = [3, 4];
  d.unshift(2);
  d.push(5);
  d.unshift(1);
  const [front, back] = [d[0], d.at(-1)];
  const removed = [$removeOpt(d, 1), $removeOpt(d, 10)];
  const popped = [d.shift(), d.pop()];
  $retain(d, (x) => x !== 4);
  const arg = d.length;
  const arg$1 = d.includes(3);
  return `[${d.map((item) => String(item)).join(", ")}] ${front == null ? "None" : `Some(${front})`} ${back == null ? "None" : `Some(${back})`} (${removed[0] == null ? "None" : `Some(${removed[0]})`}, ${removed[1] == null ? "None" : `Some(${removed[1]})`}) (${popped[0] == null ? "None" : `Some(${popped[0]})`}, ${popped[1] == null ? "None" : `Some(${popped[1]})`}) ${arg} ${arg$1}`;
}

export function reverses(a, b) {
  const x = [[a, 1]];
  const y = [[b, 2]];
  let v = [a, b, 7, 1];
  const key = (k) => [k];
  v.sort((a, b) => {
    const left = key(a);
    const right = key(b);
    return $cmp(right[0], left[0]);
  });
  return [
    ($cmp(y[0][0], x[0][0]) || $cmp(y[0][1], x[0][1])) < 0,
    $eq(($cmp(y[0][0], x[0][0]) || $cmp(y[0][1], x[0][1])) > 0 ? x : y, x),
    x[0][0],
    `Reverse((${y[0][0]}, ${y[0][1]}))`,
    v,
  ];
}

export function report() {
  let out = "";
  let s = Stack.new({ clone: (value) => value }, { fmt: (value) => $debugStr(value) });
  for (const w of ["a", "b", "c"]) {
    Stack.push(s, w, { clone: (value) => value }, { fmt: (value) => $debugStr(value) });
  }
  const arg = Stack.pop(s, { clone: (value) => value }, { fmt: (value) => $debugStr(value) });
  const arg$1 = Stack.peek(s, { clone: (value) => value }, { fmt: (value) => $debugStr(value) });
  out += `${arg == null ? "None" : `Some(${$debugStr(arg)})`} ${arg$1 == null ? "None" : `Some(${$debugStr(arg$1)})`} ${Stack.len(s, { clone: (value) => value }, { fmt: (value) => $debugStr(value) })}\n`;
  const g = { w: 3, cells: $range(0, 9) };
  out += `${gridIndex_usize__usize__index(g, [1, 2])} ${gridIndex_usize__usize__index(g, [2, 0])}\n`;
  const l = { label: "pi", value: 3.25 };
  out += `${labeledDisplay_fmt(l, { fmt: $displayF64 })} ${labeledDisplay_fmt(
    { label: "n", value: 7 },
    { fmt: String },
  )}\n`;
  const p = { steps: [(x) => (x + 1) | 0, (x) => Math.imul(x, 10), (x) => (x - 3) | 0] };
  const arg$2 = Pipeline.run(p, 4);
  const arg$3 = first_even_square([3, 5, 6, 8]);
  const arg$4 = first_even_square([1]);
  out += `${arg$2} ${arg$3 == null ? "None" : `Some(${arg$3})`} ${arg$4 == null ? "None" : `Some(${arg$4})`}\n`;
  out += `[${dijkstra(
    [
      [0, 1, 4],
      [0, 2, 1],
      [2, 1, 2],
      [1, 3, 5],
    ],
    5,
    0,
  )
    .map((item) => (item == null ? "None" : `Some(${item})`))
    .join(", ")}]\n`;
  out += `[${bfs_order(5, [
    [0, 1],
    [0, 2],
    [1, 3],
    [2, 4],
  ])
    .map((item) => String(item))
    .join(", ")}]\n`;
  let words = new Map();
  for (const w$1 of "the quick brown fox jumps over the lazy dog".split(" ")) {
    const key = Array.from(w$1).length;
    $orInsert(words, key, []).push(w$1);
  }
  let lens = Array.from(words.keys());
  lens.sort((a, b) => $cmp(b, a));
  const arg$5 = $unwrap(words.get(5), "key not found");
  out += `[${lens.map((item) => String(item)).join(", ")}] [${arg$5.map((item) => $debugStr(item)).join(", ")}]\n`;
  out += heaps();
  const arg$6 = deques();
  const arg$7 = reverses(1, 2);
  const arg$8 = reverses(5, 3);
  out += `${arg$6}\n(${arg$7[0]}, ${arg$7[1]}, ${arg$7[2]}, ${$debugStr(arg$7[3])}, [${arg$7[4].map((item) => String(item)).join(", ")}]) (${arg$8[0]}, ${arg$8[1]}, ${arg$8[2]}, ${$debugStr(arg$8[3])}, [${arg$8[4].map((item) => String(item)).join(", ")}])\n`;
  return out;
}

function gridIndex_usize__usize__index(grid, [r, c]) {
  return $index(grid.cells, ((Math.imul(r, grid.w) >>> 0) + c) >>> 0);
}

function labeledDisplay_fmt(labeled, TDisplay) {
  return `${labeled.label}=${TDisplay.fmt(labeled.value)}`;
}

function taskOrd_cmp(task, other) {
  return $cmp(task.pri, other.pri);
}

function taskPartialOrd_partial_cmp(task, other) {
  return taskOrd_cmp(task, other);
}

export function labeledDisplay(TDisplay) {
  if ($labeledDisplay === undefined) {
    $labeledDisplay = new WeakMap();
  }
  return $traitImpl($labeledDisplay, [TDisplay], () => ({
    fmt: (arg0) => labeledDisplay_fmt(arg0, TDisplay),
  }));
}

export function taskOrd() {
  if ($taskOrd === undefined) {
    $taskOrd = { PartialOrd: () => taskPartialOrd(), cmp: taskOrd_cmp };
  }
  return $taskOrd;
}

export function taskPartialOrd() {
  if ($taskPartialOrd === undefined) {
    $taskPartialOrd = { PartialEq: () => ({ eq: $eq }), partial_cmp: taskPartialOrd_partial_cmp };
  }
  return $taskPartialOrd;
}
//# sourceMappingURL=queues.js.map
