// Generated by rust-js from examples/numbers.rs. Do not edit.

function $index(items, index) {
  if (index < 0 || index >= items.length)
    throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return items[index];
}

function $at(items, index) {
  if (index < 0 || index >= items.length)
    throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return index;
}

// Shortest round-trip decimal, using exact rational arithmetic.
// Rust Display uses decimal notation, including for very small/large values.
// Not JS's `String(x)`, though its digits are also the shortest: when two are
// equally close, JS takes the even one (1888570120608320.2), and Rust the
// larger (1888570120608320.3).
function $displayF64(value) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const x = Math.abs(value);
  if (x === 0) return sign + "0";

  const bitsView = new DataView(new ArrayBuffer(8));
  bitsView.setFloat64(0, x);
  const bits = bitsView.getBigUint64(0);
  const exponentBits = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponentBits === 0 ? fraction : fraction + (1n << 52n);
  const binaryExponent = exponentBits === 0 ? -1074 : exponentBits - 1023 - 52;
  const numerator = binaryExponent >= 0 ? significand << BigInt(binaryExponent) : significand;
  const denominator = binaryExponent < 0 ? 1n << BigInt(-binaryExponent) : 1n;

  // The floating-point logarithm is only an estimate; correct it exactly.
  let exponent = Math.floor(Math.log10(x));
  const atLeastPowerOfTen = (e) =>
    e >= 0
      ? numerator >= denominator * 10n ** BigInt(e)
      : numerator * 10n ** BigInt(-e) >= denominator;
  while (!atLeastPowerOfTen(exponent)) exponent--;
  while (atLeastPowerOfTen(exponent + 1)) exponent++;

  for (let precision = 1; precision <= 17; precision++) {
    const power = exponent - precision + 1;
    const n = power < 0 ? numerator * 10n ** BigInt(-power) : numerator;
    const d = power > 0 ? denominator * 10n ** BigInt(power) : denominator;
    const floor = n / d;
    const rounded = floor + (2n * (n % d) >= d ? 1n : 0n);
    // The rounding interval can be asymmetric at a binary power boundary.
    let best;
    let bestDistance;
    for (const candidate of [rounded, rounded - 1n, rounded + 1n]) {
      if (candidate > 0n && Number(`${candidate}e${power}`) === x) {
        const delta = candidate * d - n;
        const distance = delta < 0n ? -delta : delta;
        if (
          best === undefined ||
          distance < bestDistance ||
          (distance === bestDistance && candidate > best)
        ) {
          best = candidate;
          bestDistance = distance;
        }
      }
    }
    if (best !== undefined) {
      let digits = best.toString();
      let decimalPower = power;
      while (digits.endsWith("0")) {
        digits = digits.slice(0, -1);
        decimalPower++;
      }
      const point = digits.length + decimalPower;
      const body =
        point <= 0
          ? "0." + "0".repeat(-point) + digits
          : point >= digits.length
            ? digits + "0".repeat(point - digits.length)
            : digits.slice(0, point) + "." + digits.slice(point);
      return sign + body;
    }
  }
  throw new Error("No f64 round-trip decimal found");
}

function $f64Max(a, b) {
  return Number.isNaN(a) ? b : Number.isNaN(b) ? a : Math.max(a, b);
}

function $div(a, b, min) {
  if (b === 0) {
    throw new Error("attempt to divide by zero");
  }
  if (a === min && b === -1) {
    throw new Error("attempt to divide with overflow");
  }
  return a / b;
}

function $rem(a, b, min) {
  if (b === 0) {
    throw new Error("attempt to calculate the remainder with a divisor of zero");
  }
  if (a === min && b === -1) {
    throw new Error("attempt to calculate the remainder with overflow");
  }
  return a % b;
}

function $pow(base, exp) {
  let result = 1;
  while (exp > 0) {
    if (exp & 1) {
      result = Math.imul(result, base);
    }
    base = Math.imul(base, base);
    exp >>>= 1;
  }
  return result;
}

function $powi(x, n) {
  const reciprocal = n < 0;
  let result = 1;
  while (true) {
    if (n & 1) {
      result *= x;
    }
    n = (n / 2) | 0;
    if (n === 0) {
      break;
    }
    x *= x;
  }
  return reciprocal ? 1 / result : result;
}

function $round(x) {
  return Math.sign(x) * Math.round(Math.abs(x));
}

function $checked(value, lo, hi) {
  return value >= lo && value <= hi ? value + 0 : undefined;
}

function $checkedDiv(a, b, min) {
  return b === 0 || (a === min && b === -1) ? undefined : Math.trunc(a / b) + 0;
}

function $remEuclid(a, b, min) {
  const r = $rem(a, b, min) + 0;
  return r < 0 ? (b < 0 ? r - b : r + b) : r;
}

function $divEuclid(a, b, min) {
  const q = Math.trunc($div(a, b, min)) + 0;
  return a % b < 0 ? (b > 0 ? q - 1 : q + 1) : q;
}

function $trailingZeros(x, bits) {
  return x === 0 ? bits : 31 - Math.clz32(x & -x);
}

function $countOnes(x) {
  let ones = 0;
  x >>>= 0;
  while (x !== 0) {
    ones += x & 1;
    x >>>= 1;
  }
  return ones;
}

function $binarySearch(items, x) {
  let size = items.length;
  if (size === 0) {
    return { TAG: "Err", _0: 0 };
  }
  let base = 0;
  while (size > 1) {
    const half = size >>> 1;
    const mid = base + half;
    if (!(items[mid] > x)) {
      base = mid;
    }
    size -= half;
  }
  const found = items[base];
  return found === x ? { TAG: "Ok", _0: base } : { TAG: "Err", _0: base + (found < x ? 1 : 0) };
}

function $toFixed(value, digits) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, Math.abs(value));
  const bits = view.getBigUint64(0);
  const exponent = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponent === 0 ? fraction : fraction | (1n << 52n);
  const shift = exponent === 0 ? -1074 : exponent - 1075;
  // |value| * 10^digits, as a fraction.
  let numerator = significand * 10n ** BigInt(digits);
  let denominator = 1n;
  if (shift >= 0) numerator <<= BigInt(shift);
  else denominator <<= BigInt(-shift);
  let rounded = numerator / denominator;
  const twice = 2n * (numerator % denominator);
  if (twice > denominator || (twice === denominator && rounded % 2n === 1n)) rounded += 1n;
  const text = rounded.toString().padStart(digits + 1, "0");
  return sign + (digits === 0 ? text : text.slice(0, -digits) + "." + text.slice(-digits));
}

function $debugF64(value) {
  const size = Math.abs(value);
  if (Number.isFinite(value) && size !== 0 && (size < 1e-4 || size >= 1e16)) {
    return value.toExponential().replace("e+", "e");
  }
  const text = $displayF64(value);
  return Number.isFinite(value) && !text.includes(".") ? text + ".0" : text;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

export const Vec2 = {
  new(x, y) {
    return { x, y };
  },
  len(vec2) {
    return Math.sqrt(vec2.x * vec2.x + vec2.y * vec2.y);
  },
};

export function vectors() {
  const a = Vec2.new(3, 4);
  const b = Vec2.new(1, -2);
  let c = vec2Add_add(
    vec2Sub_sub(vec2Add_add({ ...a }, vec2MulF64_mul({ ...b }, 2)), vec2Neg_neg({ ...a })),
    { x: 0, y: 0 },
  );
  vec2AddAssign_add_assign(c, { ...b });
  return `${vec2Debug_fmt({ ...c })} ${$displayF64(Vec2.len(a))} ${$debugF64(Vec2.len(vec2Sub_sub({ ...a }, { ...b })))} ${$displayF64(0)}`;
}

export function integers(a, b) {
  const arg = Math.abs(a) | 0;
  const arg$1 = $pow(a, 2);
  const arg$2 = $remEuclid(a, 7, -2147483648);
  const arg$3 = $divEuclid(a, 7, -2147483648);
  const arg$4 = $checked(b - 10, 0, 4294967295);
  const arg$5 = $checked(a + 2147483647, -2147483648, 2147483647);
  const arg$6 = $checked(a * a, -2147483648, 2147483647);
  const arg$7 = $checkedDiv(a, ((b | 0) - 3) | 0, -2147483648);
  return `${arg} ${arg$1} ${arg$2} ${arg$3} ${arg$4 == null ? "None" : `Some(${arg$4})`} ${arg$5 == null ? "None" : `Some(${arg$5})`} ${arg$6 == null ? "None" : `Some(${arg$6})`} ${arg$7 == null ? "None" : `Some(${arg$7})`} ${Math.max(b - 100, 0)} ${Math.min(b + 4294967290, 4294967295)} ${Math.min(Math.max(a * ((1 << 20) | 0), -2147483648), 2147483647) | 0} ${(b - 5) >>> 0} ${Math.imul(a, (1 << 30) | 0)} ${Math.sign(a)} ${Math.clz32(b)} ${$trailingZeros(b, 32)} ${$countOnes(a)} ${Math.abs(b - 100)}`;
}

export function narrow(a, b) {
  return `${($pow(a, 3) << 24) >> 24} ${$pow(b, 3) & 255} ${(Math.abs(a) << 24) >> 24} ${Math.clz32(a & 255) - 24} ${$countOnes(a & 255)} ${$trailingZeros(b, 8)} ${b !== 0 && (b & (b - 1)) === 0} ${$remEuclid(a, -3, -128)}`;
}

export function floats(x) {
  return `${$displayF64(Math.floor(x))} ${$displayF64(Math.ceil(x))} ${$displayF64($round(x))} ${$displayF64(Math.trunc(x))} ${$displayF64(Math.abs(x))} ${$displayF64($f64Max(x, 1.5))} ${$toFixed(x ** 0.5, 3)} ${$displayF64($powi(x, 3))} ${$displayF64($powi(x, -2))} ${Number.isNaN(x)} ${Number.isFinite(x)} ${$displayF64(Math.hypot(x, 4))}`;
}

export function gcd(a, b) {
  if (b === 0) {
    return a;
  } else {
    return gcd(b, $rem(a, b) >>> 0);
  }
}

export function grids(n) {
  let m = Array.from({ length: n }, () => new Array(n).fill(0));
  for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      const items = $index(m, i);
      items[$at(items, j)] = ((Math.imul(i, n) >>> 0) + j) >>> 0;
    }
  }
  let t = Array.from({ length: n }, () => new Array(n).fill(0));
  for (const [i$1, row] of m.entries()) {
    for (const [j$1, v] of row.entries()) {
      const items$1 = $index(t, j$1);
      items$1[$at(items$1, i$1)] = v;
    }
  }
  const cell = { hits: 0 };
  let cells = Array.from({ length: 3 }, () => ({ ...cell }));
  $index(cells, 1).hits = ($index(cells, 1).hits + 5) >>> 0;
  const flags = new Array(n).fill(1);
  return [t, flags, `[${cells.map((item) => cell2Debug_fmt(item)).join(", ")}]`];
}

export function searches() {
  const v = [1, 3, 3, 3, 5, 7, 7];
  const found = [0, 1, 3, 4, 7, 8].map((x) => {
    const arg = $binarySearch(v, x);
    return arg.TAG === "Ok" ? `Ok(${arg._0})` : `Err(${arg._0})`;
  });
  const empty = [];
  const arg = found.join(" ");
  const arg$1 = $binarySearch(empty, 1);
  return `${arg} ${arg$1.TAG === "Ok" ? `Ok(${arg$1._0})` : `Err(${arg$1._0})`}`;
}

export function zeros(a) {
  const parts = [
    $remEuclid(a, 7, -2147483648),
    $divEuclid(a, -9, -2147483648),
    $checked(a * -3, -2147483648, 2147483647) ?? 1,
    Math.min(Math.max(a * -4, -2147483648), 2147483647) | 0,
    $checkedDiv(a, -8, -2147483648) ?? 1,
  ];
  return parts.map((p) => 1 / p);
}

export function panics(i) {
  const d = ((i | 0) - 1) | 0;
  return $remEuclid($index([7, -2147483648], i % 2), d, -2147483648);
}

export function report() {
  let out = vectors() + "\n";
  for (const [a, b] of [
    [-12, 3],
    [7, 200],
    [-2147483648, 0],
    [0, 4294967295],
    [-1, (1 << 31) >>> 0],
    [-14, 1],
  ]) {
    out += `${integers(a, b)}\n`;
  }
  for (const [a$1, b$1] of [
    [-5, 7],
    [127, 128],
    [-128, 0],
    [6, 64],
  ]) {
    out += `${narrow(a$1, b$1)}\n`;
  }
  for (const x of [2.5, -2.5, 0.49999999999999994, -1.25, 9, -0, 1e21, NaN, Infinity]) {
    out += `${floats(x)}\n`;
  }
  out += `${gcd(48, 18)} ${$displayF64(2.220446049250313e-16)} ${$displayF64(0.1 + 0.2)}\n`;
  out += `[${zeros(-14)
    .map((item) => $debugF64(item))
    .join(", ")}] [${zeros(0)
    .map((item) => $debugF64(item))
    .join(", ")}]\n`;
  const arg = grids(3);
  out += `([${arg[0].map((item) => `[${item.map((item) => String(item)).join(", ")}]`).join(", ")}], [${arg[1].map((item) => String(item)).join(", ")}], ${$debugStr(arg[2])})\n${searches()}\n`;
  return out;
}

function vec2Debug_fmt(vec2) {
  return `Vec2 { x: ${$debugF64(vec2.x)}, y: ${$debugF64(vec2.y)} }`;
}

function vec2Add_add(vec2, o) {
  return Vec2.new(vec2.x + o.x, vec2.y + o.y);
}

function vec2Sub_sub(vec2, o) {
  return Vec2.new(vec2.x - o.x, vec2.y - o.y);
}

function vec2MulF64_mul(vec2, k) {
  return Vec2.new(vec2.x * k, vec2.y * k);
}

function vec2Neg_neg(vec2) {
  return Vec2.new(-vec2.x, -vec2.y);
}

function vec2AddAssign_add_assign(vec2, o) {
  vec2.x += o.x;
  vec2.y += o.y;
}

function cell2Debug_fmt(cell2) {
  return `Cell2 { hits: ${cell2.hits} }`;
}
//# sourceMappingURL=numbers.js.map
