// Generated by rust-js from test/jsx/lib.rs. Do not edit.

import { Fragment } from "react";

import { Card, Empty } from "./ui.jsx";

export function App() {
  const attrs = { title: "spread", className: "card" };
  const props = { title: "panel", children: <i>old</i> };
  const Selected = Empty;
  const tmp = <div title="named" {...attrs} />;
  let tmp$1;
  const match = <b>new</b>;
  tmp$1 = <Card title={props.title}>{match}</Card>;
  return (
    <Fragment key="group">
      {tmp}
      {tmp$1}
      <Card title="dot">
        <i />
      </Card>
      <Card title="path">
        <u />
      </Card>
      <Selected />
    </Fragment>
  );
}
//# sourceMappingURL=lib.jsx.map
