// Generated by rust-js from examples/counter.rs. Do not edit.

import { $unwrap } from "@rust-js/runtime";

function button(label) {
  const b = document.createElement("button");
  b.textContent = label;
  return b;
}

function stepper(label, by, count, output) {
  const b = button(label);
  const count$1 = count;
  b.addEventListener("click", () => {
    count$1.value = (count$1.value + by) | 0;
    output.textContent = String(count$1.value);
  });
  return b;
}

export function main() {
  const app = $unwrap(document.getElementById("app"), "the page has an #app");
  const count = { value: 0 };
  const output = document.createElement("output");
  output.textContent = "0";
  app.append(stepper("-", -1, count, output));
  app.append(output);
  app.append(stepper("+", 1, count, output));
}
//# sourceMappingURL=counter.js.map
