// Generated by rust-js from examples/collections.rs. Do not edit.

function $index(items, index) {
  if (index < 0 || index >= items.length) throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return items[index];
}

function $at(items, index) {
  if (index < 0 || index >= items.length) throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return index;
}

function $retain(v, keep) {
  let n = 0;
  for (const x of v) {
    if (keep(x)) {
      v[n++] = x;
    }
  }
  v.length = n;
}

function $unwrap(value, message = "called `Option::unwrap()` on a `None` value") {
  if (value == null) {
    throw new Error(message);
  }
  return value;
}

function $insert(map, key, value) {
  const old = map.get(key);
  map.set(key, value);
  return old;
}

function $add(set, item) {
  const added = !set.has(item);
  set.add(item);
  return added;
}

function $remove(map, key) {
  const old = map.get(key);
  map.delete(key);
  return old;
}

function $orInsert(map, key, value) {
  if (!map.has(key)) {
    map.set(key, value);
  }
  return map.get(key);
}

function $sortedEntries(map, cmp) {
  return Array.from(map).sort((a, b) => cmp(a[0], b[0]));
}

function $sortedKeys(set, cmp) {
  return Array.from(set).sort(cmp);
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (/[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) || (c !== " " && /\p{Zs}/u.test(c)))
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

function $cmpIn(names, a, b) {
  return $cmp(names.indexOf(a), names.indexOf(b));
}

function $cmpItems(a, b, cmp) {
  for (let i = 0; i < a.length && i < b.length; i++) {
    const order = cmp(a[i], b[i]);
    if (order !== 0) {
      return order;
    }
  }
  return $cmp(a.length, b.length);
}

export function sum_to(n) {
  let total = 0;
  for (let i = 0; i < n; i++) {
    total = total + i >>> 0;
  }
  return total;
}

export function end_once(n) {
  let n$1 = n;
  let times = 0;
  const end = n$1;
  for (let i = 0; i < end; i++) {
    n$1 = n$1 + 1 | 0;
    times = times + 1 | 0;
  }
  return Math.imul(times, 1000) + n$1 | 0;
}

export function mut_counter(n) {
  let total = 0;
  for (let i = 0; i < n; i++) {
    let i$1 = i;
    i$1 = Math.imul(i$1, 10);
    total = total + i$1 | 0;
  }
  return total;
}

export function evens(n) {
  let v = [];
  for (let i = 0; i < n; i++) {
    if (i % 2 === 0) {
      v.push(i);
    }
  }
  return v;
}

export function keep_over(limit) {
  let v = [
    5,
    1,
    8,
    3,
    9,
    2
  ];
  $retain(v, (x) => x > limit);
  return v;
}

export function lengths(n) {
  let v = evens(n);
  const before = v.length;
  v.length = 0;
  return [before, v.length === 0];
}

export function iterate(n) {
  const v = evens(n);
  let total = 0;
  for (const x of v) {
    total = total + x >>> 0;
  }
  for (const x$1 of v) {
    total = total + (Math.imul(x$1, 100) >>> 0) >>> 0;
  }
  for (const item of [[1, 2], [3, 4]]) {
    total = total + (Math.imul(item[0], item[1]) >>> 0) >>> 0;
  }
  return total;
}

export function labeled(n) {
  let found = 0;
  outer: for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      if (j > i) {
        continue outer;
      }
      if (Math.imul(i, j) >>> 0 > 20) {
        break outer;
      }
      found = found + 1 >>> 0;
    }
  }
  return found;
}

function toggle(todos, id) {
  for (const todo of todos) {
    if (todo.id === id) {
      todo.done = !todo.done;
    }
  }
}

export function toggled(n) {
  let todos = [];
  for (let id = 0; id < n; id++) {
    todos.push({
      id,
      done: id % 3 === 0
    });
  }
  toggle(todos, 1);
  toggle(todos, 3);
  for (const todo of todos) {
    todo.id = todo.id + 100 >>> 0;
  }
  $retain(todos, (t) => !t.done);
  let ids = 0;
  let done = 0;
  for (const todo$1 of todos) {
    ids = ids + todo$1.id >>> 0;
    if (todo$1.done) {
      done = done + 1 >>> 0;
    }
  }
  return [ids, done];
}

export function cell(times) {
  const c = { value: 0 };
  for (let i = 0; i < times; i++) {
    c.value = c.value + 2 | 0;
  }
  return c.value + 1 | 0;
}

export function shared(times) {
  const log = { value: [] };
  const writer = log;
  for (let i = 0; i < times; i++) {
    writer.value.push(Math.imul(i, i));
  }
  const v = log.value;
  let total = 0;
  for (const x of v) {
    total = total + x | 0;
  }
  return [total, v.length];
}

export function words(s) {
  const owned = s;
  const trimmed = owned.trim();
  return [
    trimmed,
    trimmed.length === 0,
    trimmed === "hi"
  ];
}

export function indexed(i) {
  let v = [
    10,
    20,
    30
  ];
  const read = $index(v, i);
  v[$at(v, i)] = read + 1 >>> 0;
  v[$at(v, 0)] = v[$at(v, 0)] + 5 >>> 0;
  const slice = v;
  slice[$at(slice, 2)] = Math.imul(slice[$at(slice, 2)], 2) >>> 0;
  return [
    read,
    $index(v, i),
    v
  ];
}

export function element_fields(i) {
  let cells = [{ hits: 0 }, { hits: 0 }];
  $index(cells, i).hits = $index(cells, i).hits + 1 >>> 0;
  const before = { ...$index(cells, i) };
  const r = $index(cells, i);
  r.hits = 10;
  return [
    before.hits,
    $index(cells, i).hits,
    $index(cells, 1 - i >>> 0).hits
  ];
}

export function arrays(i) {
  let a = [
    1,
    2,
    3
  ];
  const b = a.slice();
  a[$at(a, i)] = 9;
  return [$index(a, i), $index(b, i)];
}

export function word_counts(text) {
  let counts = new Map();
  for (const word of text.split(" ")) {
    counts.set(word, (counts.get(word) ?? 0) + 1 >>> 0);
  }
  let all = Array.from(counts);
  all.sort((a, b) => $cmp(a[0], b[0]) || $cmp(a[1], b[1]));
  return all;
}

export function map_basics(n) {
  let m = new Map();
  m.set("a", n);
  const old = $insert(m, "a", n + 1 >>> 0);
  m.set("b", 3);
  const removed = $remove(m, "b");
  const first = m.get("a");
  let total = 0;
  for (const item of m) {
    total = total + item[1] >>> 0;
  }
  m.set("a", $unwrap(m.get("a")) + 10 >>> 0);
  return [
    old,
    first,
    m.has("b"),
    m.size,
    removed,
    total + $unwrap(m.get("a"), "key not found") >>> 0
  ];
}

export function set_basics(n) {
  let s = new Set([
    3,
    1,
    2
  ]);
  const new$ = $add(s, n);
  const again = $add(s, n);
  const gone = s.delete(1);
  let items = Array.from(s);
  items.sort((a, b) => a - b);
  const one = new Map([["k", n]]);
  return [
    new$,
    again,
    gone,
    s.size,
    items,
    "{" + Array.from(one).map(([key, value]) => $debugStr(key) + ": " + String(value)).join(", ") + "}"
  ];
}

export function grouped(n) {
  let groups = new Map();
  for (let i = 1; i < n; i++) {
    const key = i % 3;
    $orInsert(groups, key, []).push(i);
  }
  const copy = new Map(Array.from(groups).map(([key, value]) => [key, value.slice()]));
  const zero = groups.get(0);
  if (zero != null) {
    zero.push(99);
  }
  let all = Array.from(copy);
  all.sort((a, b) => {
    const left = a[1];
    const right = b[1];
    return $cmp(a[0], b[0]) || $cmpItems(left, right, $cmp);
  });
  return all;
}

export function sorted_maps(text) {
  let counts = new Map();
  for (const word of text.split(" ")) {
    counts.set(word, (counts.get(word) ?? 0) + 1 >>> 0);
  }
  let order = [];
  for (const item of $sortedEntries(counts, $cmp)) {
    order.push(item[0] + "=" + String(item[1]));
  }
  const set = new Set([
    30,
    4,
    100,
    7
  ]);
  const tiers = new Map([
    ["Silver", 2],
    ["Gold", 3],
    ["Bronze", 1]
  ]);
  const tmp = $sortedEntries(counts, $cmp).slice();
  const tmp$1 = order;
  const arg = $sortedKeys(set, $cmp).toReversed();
  const tmp$2 = "{" + Array.from($sortedKeys(set, $cmp)).map((item) => String(item)).join(", ") + "}" + " " + ("[" + arg.map((item) => String(item)).join(", ") + "]");
  const arg$1 = $unwrap(tiers.get("Bronze"), "key not found");
  return [
    tmp,
    tmp$1,
    tmp$2,
    "{" + Array.from($sortedEntries(tiers, (a, b) => $cmpIn([
      "Gold",
      "Bronze",
      "Silver"
    ], a, b))).map(([key, value]) => tierDebug_fmt(key) + ": " + String(value)).join(", ") + "}" + " " + String(arg$1)
  ];
}

function tierDebug_fmt(tier) {
  let f = "";
  let tmp;
  if (tier === "Gold") {
    tmp = "Gold";
  } else if (tier === "Bronze") {
    tmp = "Bronze";
  } else {
    tmp = "Silver";
  }
  f += tmp;
  return f;
}
//# sourceMappingURL=collections.js.map
