// Generated by rust-js from examples/collections.rs. Do not edit.

function $retain(v, keep) {
  let n = 0;
  for (const x of v) {
    if (keep(x)) {
      v[n++] = x;
    }
  }
  v.length = n;
}

export function sum_to(n) {
  let total = 0;
  for (let i = 0; i < n; i++) {
    total = total + i >>> 0;
  }
  return total;
}

export function end_once(n) {
  let n$1 = n;
  let times = 0;
  const end = n$1;
  for (let i = 0; i < end; i++) {
    n$1 = n$1 + 1 | 0;
    times = times + 1 | 0;
  }
  return Math.imul(times, 1000) + n$1 | 0;
}

export function mut_counter(n) {
  let total = 0;
  for (let i = 0; i < n; i++) {
    let i$1 = i;
    i$1 = Math.imul(i$1, 10);
    total = total + i$1 | 0;
  }
  return total;
}

export function evens(n) {
  let v = [];
  for (let i = 0; i < n; i++) {
    if (i % 2 === 0) {
      v.push(i);
    }
  }
  return v;
}

export function keep_over(limit) {
  let v = [
    5,
    1,
    8,
    3,
    9,
    2
  ];
  $retain(v, (x) => x > limit);
  return v;
}

export function lengths(n) {
  let v = evens(n);
  const before = v.length;
  v.length = 0;
  return [before, v.length === 0];
}

export function iterate(n) {
  const v = evens(n);
  let total = 0;
  for (const x of v) {
    total = total + x >>> 0;
  }
  for (const x$1 of v) {
    total = total + (Math.imul(x$1, 100) >>> 0) >>> 0;
  }
  for (const item of [[1, 2], [3, 4]]) {
    total = total + (Math.imul(item[0], item[1]) >>> 0) >>> 0;
  }
  return total;
}

export function labeled(n) {
  let found = 0;
  outer: for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      if (j > i) {
        continue outer;
      }
      if (Math.imul(i, j) >>> 0 > 20) {
        break outer;
      }
      found = found + 1 >>> 0;
    }
  }
  return found;
}

function toggle(todos, id) {
  for (const todo of todos) {
    if (todo.id === id) {
      todo.done = !todo.done;
    }
  }
}

export function toggled(n) {
  let todos = [];
  for (let id = 0; id < n; id++) {
    todos.push({
      id,
      done: id % 3 === 0
    });
  }
  toggle(todos, 1);
  toggle(todos, 3);
  for (const todo of todos) {
    todo.id = todo.id + 100 >>> 0;
  }
  $retain(todos, (t) => !t.done);
  let ids = 0;
  let done = 0;
  for (const todo$1 of todos) {
    ids = ids + todo$1.id >>> 0;
    if (todo$1.done) {
      done = done + 1 >>> 0;
    }
  }
  return [ids, done];
}

export function cell(times) {
  const c = { value: 0 };
  for (let i = 0; i < times; i++) {
    c.value = c.value + 2 | 0;
  }
  return c.value + 1 | 0;
}

export function shared(times) {
  const log = { value: [] };
  const writer = log;
  for (let i = 0; i < times; i++) {
    writer.value.push(Math.imul(i, i));
  }
  const v = log.value;
  let total = 0;
  for (const x of v) {
    total = total + x | 0;
  }
  return [total, v.length];
}

export function words(s) {
  const owned = s;
  const trimmed = owned.trim();
  return [
    trimmed,
    trimmed.length === 0,
    trimmed === "hi"
  ];
}
//# sourceMappingURL=collections.js.map
