// Generated by rust-js from test/throws.rs. Do not edit.

function $try(f) {
  try {
    return { TAG: "Ok", _0: f() };
  } catch (e) {
    return { TAG: "Err", _0: e };
  }
}

function $settle(promise) {
  return promise.then((value) => ({ TAG: "Ok", _0: value }), (e) => ({ TAG: "Err", _0: e }));
}

export function sum_json(json) {
  const match = $try(() => JSON.parse(json));
  if (match.TAG === "Ok") {
    let sum = 0;
    for (const n of match._0) {
      sum = sum + n >>> 0;
    }
    return {
      TAG: "Ok",
      _0: sum
    };
  } else {
    return {
      TAG: "Err",
      _0: String(match._0)
    };
  }
}

export function first_twice(json) {
  const result = $try(() => JSON.parse(json));
  if (result.TAG === "Err") {
    return result;
  }
  const numbers = result._0;
  let first = 0;
  for (const n of numbers) {
    first = Math.imul(n, 2) >>> 0;
    break;
  }
  return {
    TAG: "Ok",
    _0: first
  };
}

export async function settled(fail) {
  const result = fail ? await $settle(Promise.reject("no")) : await $settle(Promise.resolve(7));
  if (result.TAG === "Ok") {
    return String(result._0);
  } else {
    return "rejected: " + String(result._0);
  }
}
//# sourceMappingURL=throws.js.map
