// Generated by rust-js from /wasm/web/rust/programs.rs. Do not edit.

function $stripSuffix(s, suffix) {
  return s.endsWith(suffix) ? s.slice(0, s.length - suffix.length) : undefined;
}

const TEST_RUNNER =
  '\n    const results = registered.map(({ name, f }) => {\n      if (!f) return { name, outcome: "skip" };\n      try {\n        f();\n        return { name, outcome: "pass" };\n      } catch (e) {\n        return { name, outcome: "fail", message: e instanceof Error ? e.message : String(e) };\n      }\n    });\n    document.body.replaceChildren(...results.map(({ name, outcome, message }) => {\n      const line = document.createElement("div");\n      line.className = outcome;\n      line.textContent = { pass: "✓ ", fail: "✗ ", skip: "– " }[outcome] + name + (outcome === "skip" ? " (ignored)" : "");\n      if (message) {\n        const why = document.createElement("pre");\n        why.textContent = message;\n        line.append(why);\n      }\n      return line;\n    }));\n    const count = (outcome) => results.filter((r) => r.outcome === outcome).length;';
const FRAME_HEAD =
  '<!doctype html>\n<meta charset="utf-8">\n<style>\n  :root { color-scheme: light dark; font: 15px/1.5 system-ui, sans-serif; }\n  body { margin: 12px; }\n  button { font: inherit; min-width: 2.5em; padding: 2px 10px; }\n  output { display: inline-block; min-width: 3em; text-align: center; font-variant-numeric: tabular-nums; }\n  .pass { color: #2f6b3a; } .fail { color: #a3321f; } .skip { color: #6b6b66; }\n  @media (prefers-color-scheme: dark) { .pass { color: #8fcf98; } .fail { color: #ef8a78; } }\n  pre { margin: 2px 0 8px 1.5em; white-space: pre-wrap; font-size: 13px; }\n</style>\n<div id="app"></div>';

export function resolve(from, specifier) {
  let parts = from.split("/");
  parts.pop();
  for (const part of specifier.split("/")) {
    if (part === "..") {
      parts.pop();
    } else if (part !== ".") {
      parts.push(part);
    }
  }
  return parts.join("/");
}

export function link(files) {
  const imports = new RegExp('^import ([^;]+?) from "([^"]+)";$', "gm");
  const sourceMap = new RegExp("^//# sourceMappingURL=.*$", "m");
  let entries = [];
  for (const [path, code] of Array.from(files)) {
    const from = path;
    const body = code.replace(imports, (_, names, specifier) => {
      const target = JSON.stringify(`rust-js:${resolve(from, specifier)}`);
      return `import ${names} from ${target};`;
    });
    const body$1 = body.replace(sourceMap, "");
    const specifier = JSON.stringify(`rust-js:${path}`);
    const url = JSON.stringify(
      `data:text/javascript,${encodeURIComponent(body$1)}#${encodeURIComponent(path)}`,
    );
    entries.push(`${specifier}: ${url}`);
  }
  const entries$1 = entries.join(",");
  return `<script type="importmap">{"imports":{${entries$1}}}<\/script>`;
}

export function prepare(files, rootFile, test, run) {
  const sources = Array.from(files);
  let tests;
  const option = $stripSuffix(rootFile, ".jsx");
  const match = option ?? $stripSuffix(rootFile, ".js");
  if (match != null) {
    tests = `${match}.test.js`;
  } else {
    tests = rootFile;
  }
  const hasMain = new RegExp("^export (async )?function main\\(\\)", "m");
  const runnable = test
    ? sources.some((param) => param[0] === tests)
    : sources.some((param) => param[0] === rootFile && hasMain.test(param[1]));
  if (!runnable) {
    return "Nothing";
  }
  if (sources.some((param) => param[0].endsWith(".jsx"))) {
    return "Jsx";
  }
  const imports = new RegExp('^import (?:[^;]+? from )?"([^"]+)";$', "gm");
  let external = [];
  for (const item of sources) {
    for (const [, specifier] of Array.from(item[1].matchAll(imports))) {
      const target = resolve(item[0], specifier);
      if (!sources.some((param) => param[0] === target) && !external.includes(specifier)) {
        external.push(specifier);
      }
    }
  }
  if (external.length !== 0) {
    return { TAG: "Blocked", _0: external };
  }
  const report = (message) => `parent.postMessage({ run: ${run}, ${message} }, "*")`;
  const linked = link(files);
  const entry = JSON.stringify(`rust-js:${test ? tests : rootFile}`);
  const start = test
    ? `await import(${entry});\n${TEST_RUNNER}`
    : `const root = await import(${entry});\nawait root.main();`;
  const finished = test
    ? report('tested: { passed: count("pass"), failed: count("fail"), ignored: count("skip") }')
    : report("ran: true");
  const arg = report("error: String(e.message)");
  const arg$1 = report("error: String(e.reason)");
  const arg$2 = report("error: String(e)");
  return {
    TAG: "Page",
    _0: `${FRAME_HEAD}\n${linked}\n<script>\n  // Errors later on, in an event handler say.\n  addEventListener("error", (e) => ${arg});\n  // And in async code, which rejects its promise instead (ADR 0029).\n  addEventListener("unhandledrejection", (e) => ${arg$1});\n  // What a test file calls, as bun test provides it (ADR 0026).\n  const registered = [];\n  globalThis.test = (name, f) => registered.push({ name, f });\n  test.skip = (name) => registered.push({ name });\n<\/script>\n<script type="module">\n  try {\n${start}\n    ${finished};\n  } catch (e) {\n    ${arg$2};\n  }\n<\/script>`,
  };
}

export function outcome(report) {
  if (report.error != null) {
    return { TAG: "Failed", _0: report.error };
  } else if (report.ran === true) {
    return "Ran";
  } else if (report.tested != null) {
    return { TAG: "Tested", _0: report.tested };
  } else {
    return undefined;
  }
}
//# sourceMappingURL=programs.js.map
