// Generated by rust-js from test/web_forms.rs. Do not edit.

import { $unwrap } from "@rust-js/runtime";

export function forms() {
  const input = document.createElement("input");
  input.value = "typed";
  const app = $unwrap(document.getElementById("app"), "the page has an #app");
  app.append(input);
  app.append("!");
  const ping = new Event("ping");
  app.addEventListener("ping", (e) => {
    e.preventDefault();
  });
  window.dispatchEvent(ping);
  return $unwrap(app.textContent) + input.value;
}

export function round_trip(text) {
  const bytes = new TextEncoder().encode(text);
  const back = new TextDecoder("utf-8").decode(bytes);
  return [bytes.length, back];
}

export function from_frame(frame, e) {
  const sender = e.source;
  const windowOf = frame.contentWindow;
  return [Object.is(sender, windowOf), window.performance.now()];
}
//# sourceMappingURL=web_forms.js.map
