// Generated by rust-js from test/web_forms.rs. Do not edit.

function $unwrap(value, message = "called `Option::unwrap()` on a `None` value") {
  if (value == null) {
    throw new Error(message);
  }
  return value;
}

export function forms() {
  const input = document.createElement("input");
  input.value = "typed";
  const app = $unwrap(document.getElementById("app"), "the page has an #app");
  app.append(input);
  app.append("!");
  const ping = new Event("ping");
  app.addEventListener("ping", (e) => {
    e.preventDefault();
  });
  window.dispatchEvent(ping);
  return $unwrap(app.textContent) + input.value;
}

export function round_trip(text) {
  const bytes = new TextEncoder().encode(text);
  const back = new TextDecoder("utf-8").decode(bytes);
  return [bytes.length, back];
}
//# sourceMappingURL=web_forms.js.map
