// Generated by rust-js from frontend/src/form.rs. Do not edit.

import { validate } from "../../models/src/lib.js";
import { useState } from "react";
import { toast } from "sonner";

import { Failure, create } from "./api.js";
import { go } from "./route.js";

function $retain(v, keep) {
  let n = 0;
  for (const x of v) {
    if (keep(x)) {
      v[n++] = x;
    }
  }
  v.length = n;
}

function $parseInt(s, min, max) {
  const error = (message) => ({ TAG: "Err", _0: message });
  if (s === "") return error("cannot parse integer from empty string");
  if (!(min < 0 ? /^[+-]?[0-9]+$/ : /^\+?[0-9]+$/).test(s))
    return error("invalid digit found in string");
  const n = Number(s);
  if (n > max) return error("number too large to fit in target type");
  if (n < min) return error("number too small to fit in target type");
  return { TAG: "Ok", _0: n };
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

function message(errors, field) {
  const error = errors.find((error) => error.field === field);
  return error != null ? error.message : undefined;
}

export function NewContactForm() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [age, setAge] = useState("");
  const [errors, setErrors] = useState([]);
  const [sending, setSending] = useState(false);
  const submit = (e) => {
    e.preventDefault();
    const result = $parseInt(age.trim(), 0, 4294967295);
    const parsed = result.TAG === "Ok" ? result._0 : undefined;
    const new$ = { name, email, age: parsed ?? 0 };
    let found = validate(new$);
    if (parsed == null) {
      $retain(found, (error) => error.field !== "age");
      found.push({ field: "age", message: `${$debugStr(age)} isn't a whole number` });
    }
    if (found.length !== 0) {
      setErrors(found);
      return;
    }
    setErrors([]);
    setSending(true);
    (async () => {
      const match = await create(new$);
      if (match.TAG === "Ok") {
        toast(`Added ${match._0.name}`);
        go(`#/contacts/${match._0.id}`);
      } else if (
        match.TAG === "Err" &&
        match._0.TAG === "Refused" &&
        match._0._1.errors.length !== 0
      ) {
        setErrors(match._0._1.errors);
      } else {
        toast(Failure.message(match._0));
      }
      setSending(false);
    })();
  };
  const field = (label, key, value, set) => {
    const error = message(errors, key);
    return (
      <label className="field">
        <span>{label}</span>
        <input
          name={key}
          value={value}
          aria-invalid={error != null}
          onChange={(e) => set(e.target.value)}
        />
        {error != null ? <span className="field-error">{error}</span> : undefined}
      </label>
    );
  };
  const children = field("Name", "name", name, (v) => {
    setName(v);
  });
  return (
    <form onSubmit={submit} noValidate>
      <h1>New contact</h1>
      {children}
      {field("Email", "email", email, (v) => {
        setEmail(v);
      })}
      {field("Age", "age", age, (v) => {
        setAge(v);
      })}
      <button type="submit" disabled={sending}>
        {sending ? "Adding…" : "Add contact"}
      </button>
    </form>
  );
}
//# sourceMappingURL=form.jsx.map
