// Generated by rust-js from frontend/src/route.rs. Do not edit.

import { useEffect, useState } from "react";

function $parseInt(s, min, max) {
  const error = (message) => ({ TAG: "Err", _0: message });
  if (s === "") return error("cannot parse integer from empty string");
  if (!(min < 0 ? /^[+-]?[0-9]+$/ : /^\+?[0-9]+$/).test(s))
    return error("invalid digit found in string");
  const n = Number(s);
  if (n > max) return error("number too large to fit in target type");
  if (n < min) return error("number too small to fit in target type");
  return { TAG: "Ok", _0: n };
}

function $stripPrefix(s, prefix) {
  return s.startsWith(prefix) ? s.slice(prefix.length) : undefined;
}

export function parse(hash$1) {
  const match = $stripPrefix(hash$1, "#") ?? hash$1;
  if (match === "" || match === "/") {
    return "List";
  } else if (match === "/new") {
    return "New";
  } else {
    const option = $stripPrefix(match, "/contacts/");
    const then = (id) => {
      const result = $parseInt(id, 0, 4294967295);
      return result.TAG === "Ok" ? result._0 : undefined;
    };
    const match$1 = option != null ? then(option) : undefined;
    if (match$1 != null) {
      return { TAG: "Contact", _0: match$1 };
    } else {
      return "NotFound";
    }
  }
}

function hash() {
  return window.location.hash;
}

export function go(to) {
  window.location.hash = to;
}

export function use_route() {
  const [current, setCurrent] = useState(hash());
  useEffect(() => {
    const controller = new AbortController();
    const options = {
      capture: undefined,
      passive: undefined,
      once: undefined,
      signal: controller.signal,
    };
    window.addEventListener(
      "hashchange",
      () => {
        setCurrent(hash());
      },
      options,
    );
    return () => {
      controller.abort();
    };
  }, []);
  return parse(current);
}
//# sourceMappingURL=route.js.map
