// Generated by rust-js from examples/modules/stats.rs. Do not edit.

import { HALVES, clamp } from "./lib.js";

export function mean(a, b) {
  return half((clamp(a) + clamp(b)) >>> 0);
}

function half(x) {
  return (x / HALVES) >>> 0;
}
//# sourceMappingURL=stats.js.map
