// Generated by rust-js from examples/iterators.rs. Do not edit.

function $range(start, end) {
  return Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function $max(items) {
  return items.length === 0 ? undefined : items.reduce((max, x) => (x >= max ? x : max));
}

function $min(items) {
  return items.length === 0 ? undefined : items.reduce((min, x) => (x < min ? x : min));
}

function $position(items, found) {
  const i = items.findIndex(found);
  return i < 0 ? undefined : i;
}

export function squares(n) {
  return $range(0, n).map((i) => Math.imul(i, i) >>> 0);
}

export function evens(v) {
  return v.filter((x) => x % 2 === 0);
}

export function stats(v) {
  const positive = v.filter((x) => x > 0).length;
  const sum = v.reduce((a, b) => a + b | 0, 0);
  const anyNegative = v.some((x) => x < 0);
  const noZero = v.every((x) => x !== 0);
  const big = v.find((x) => x > 10);
  const three = $position(v, (x) => x === 3);
  return [
    positive,
    sum,
    anyNegative,
    noZero,
    big,
    three
  ];
}

export function extremes(v) {
  return [$max(v), $min(v)];
}

export function indexed(words) {
  return words.map((x, i) => [i, x]).map(([i, w]) => String(i) + ":" + w);
}

export function middle(v) {
  return v.slice(1).slice(0, 2).toReversed();
}

export function non_empty(words) {
  return words.reduce((count, w) => {
    if (w.length === 0) {
      return count;
    } else {
      return count + 1 >>> 0;
    }
  }, 0);
}

export function shouted(words) {
  return words.map((w) => w.toUpperCase()).join("-");
}

export function backwards(s) {
  return Array.from(s).toReversed().join("");
}

export function sorted_copy(v) {
  let copy = v.slice();
  copy.sort((a, b) => a - b);
  return [v, copy];
}

export function sorted(v) {
  let w = v.slice();
  w.sort((a, b) => a - b);
  return w;
}

export function descending(v) {
  let w = v.slice();
  w.sort((a, b) => $cmp(b, a));
  return w;
}

export function by_last_digit(v) {
  let w = v.slice();
  const key = (x) => x % 10;
  w.sort((a, b) => $cmp(key(a), key(b)));
  return w;
}

export function sorted_words(words) {
  let w = words.map((s) => s);
  w.sort();
  w.reverse();
  return w;
}

export function by_length_then_name(words) {
  let w = words.map((s) => s);
  w.sort((a, b) => $cmp(a.length === 0, b.length === 0) || $cmp(a, b));
  return w;
}

export function compare(a, b) {
  const match = $cmp(a, b);
  if (match === -1) {
    return -1;
  } else if (match === 0) {
    return 0;
  } else {
    return 1;
  }
}

export function bigger(a, b) {
  return [Math.max(a, b), Math.min(a, b)];
}

export function negated(v) {
  const positive = v.map((x) => x > 0);
  return [v.map((x) => -x | 0), positive.map((p) => !p)];
}

export function inclusive(n) {
  let total = 0;
  for (let i = 1; i <= n; i++) {
    total = total + i >>> 0;
  }
  const down = $range(0, n + 1).toReversed();
  return [
    total,
    down,
    $range(1, n + 1).map((x) => Math.imul(x, x) >>> 0).reduce((a, b) => a + b >>> 0, 0)
  ];
}

export function order_number(a, b) {
  return [$cmp(a, b), $cmp(a, b) & 255];
}
//# sourceMappingURL=iterators.js.map
