// Generated by rust-js from examples/enums.rs. Do not edit.

function $div(a, b, min) {
  if (b === 0) {
    throw new Error("attempt to divide by zero");
  }
  if (a === min && b === -1) {
    throw new Error("attempt to divide with overflow");
  }
  return a / b;
}

function $eq(a, b) {
  if (a === b || (a == null && b == null)) {
    return true;
  }
  if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) {
    return false;
  }
  if (Array.isArray(a)) {
    return Array.isArray(b) && a.length === b.length && a.every((x, i) => $eq(x, b[i]));
  }
  const keys = Object.keys(a);
  return keys.length === Object.keys(b).length && keys.every((k) => $eq(a[k], b[k]));
}

export function circle(r) {
  return { TAG: "Circle", _0: r };
}

export function rect(w, h) {
  return { TAG: "Rect", w, h };
}

export function empty() {
  return "Empty";
}

export function area(s) {
  if (s === "Empty") {
    return 0;
  } else if (s.TAG === "Circle") {
    return Math.imul(Math.imul(3, s._0), s._0);
  } else {
    return Math.imul(s.w, s.h);
  }
}

export function classify(s) {
  if (s.TAG === "Circle" && s._0 > 10) {
    return 3;
  } else if (s.TAG === "Circle") {
    return 2;
  } else if ((s.TAG === "Rect" && s.w === 0) || s === "Empty") {
    return 0;
  } else {
    return 1;
  }
}

export function is_round(s) {
  return s.TAG === "Circle";
}

export function width(s) {
  if (s.TAG === "Rect") {
    return s.w;
  } else {
    return -1;
  }
}

export function same(a, b) {
  return $eq(a, b);
}

function build(depth) {
  if (depth === 0) {
    return { TAG: "Leaf", _0: 1 };
  } else {
    return { TAG: "Node", _0: build((depth - 1) >>> 0), _1: { TAG: "Leaf", _0: depth | 0 } };
  }
}

function sum(t) {
  if (t.TAG === "Leaf") {
    return t._0;
  } else {
    return (sum(t._0) + sum(t._1)) | 0;
  }
}

export function tree_sum(depth) {
  return sum(build(depth));
}

export function checked_div(a, b) {
  if (b === 0) {
    return { TAG: "Err", _0: "divide by zero" };
  } else {
    return { TAG: "Ok", _0: $div(a, b, -2147483648) | 0 };
  }
}

export function div_or(a, b, fallback) {
  const match = checked_div(a, b);
  if (match.TAG === "Ok") {
    return match._0;
  } else {
    return fallback;
  }
}

export function discriminants(i) {
  let level;
  const match = i % 3;
  if (match === 0) {
    level = "Low";
  } else if (match === 1) {
    level = "Mid";
  } else {
    level = "High";
  }
  let status;
  const match$1 = i % 3;
  if (match$1 === 0) {
    status = "Ok";
  } else if (match$1 === 1) {
    status = "NotFound";
  } else {
    status = "Teapot";
  }
  return [
    ["Low", "Mid", "High"].indexOf(level),
    { Ok: 200, NotFound: 404, Teapot: 418 }[status],
    (418 - { Ok: 200, NotFound: 404, Teapot: 418 }[status]) | 0,
  ];
}

function grow(f) {
  if (f !== "Dot") {
    if (f.TAG === "Poly") {
      f._0.push(0);
    } else {
      f.r *= 2;
    }
  }
}

function points(f) {
  if (f.TAG === "Poly") {
    return f._0.length;
  } else {
    return 0;
  }
}

export function changed_in_place(r) {
  let poly = { TAG: "Poly", _0: [1] };
  const before =
    poly.TAG === "Poly"
      ? { ...poly, _0: poly._0.slice() }
      : poly.TAG === "Circle"
        ? { ...poly }
        : poly;
  grow(poly);
  let circle$1 = { TAG: "Circle", r };
  grow(circle$1);
  const value = circle$1;
  if (value.TAG === "Circle") {
    value.r += 0.5;
  }
  let dot = "Dot";
  grow(dot);
  let radius;
  if (circle$1.TAG === "Circle") {
    const r$1 = circle$1.r;
    radius = r$1;
  } else {
    radius = 0;
  }
  return [points(poly), points(before), radius, points(dot)];
}
//# sourceMappingURL=enums.js.map
