// Generated by rust-js from examples/inventory.rs. Do not edit.

// Shortest round-trip decimal, using exact rational arithmetic.
// Rust Display uses decimal notation, including for very small/large values.
// Not JS's `String(x)`, though its digits are also the shortest: when two are
// equally close, JS takes the even one (1888570120608320.2), and Rust the
// larger (1888570120608320.3).
function $displayF64(value) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const x = Math.abs(value);
  if (x === 0) return sign + "0";

  const bitsView = new DataView(new ArrayBuffer(8));
  bitsView.setFloat64(0, x);
  const bits = bitsView.getBigUint64(0);
  const exponentBits = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponentBits === 0 ? fraction : fraction + (1n << 52n);
  const binaryExponent = exponentBits === 0 ? -1074 : exponentBits - 1023 - 52;
  const numerator = binaryExponent >= 0 ? significand << BigInt(binaryExponent) : significand;
  const denominator = binaryExponent < 0 ? 1n << BigInt(-binaryExponent) : 1n;

  // The floating-point logarithm is only an estimate; correct it exactly.
  let exponent = Math.floor(Math.log10(x));
  const atLeastPowerOfTen = (e) =>
    e >= 0
      ? numerator >= denominator * 10n ** BigInt(e)
      : numerator * 10n ** BigInt(-e) >= denominator;
  while (!atLeastPowerOfTen(exponent)) exponent--;
  while (atLeastPowerOfTen(exponent + 1)) exponent++;

  for (let precision = 1; precision <= 17; precision++) {
    const power = exponent - precision + 1;
    const n = power < 0 ? numerator * 10n ** BigInt(-power) : numerator;
    const d = power > 0 ? denominator * 10n ** BigInt(power) : denominator;
    const floor = n / d;
    const rounded = floor + (2n * (n % d) >= d ? 1n : 0n);
    // The rounding interval can be asymmetric at a binary power boundary.
    let best;
    let bestDistance;
    for (const candidate of [rounded, rounded - 1n, rounded + 1n]) {
      if (candidate > 0n && Number(`${candidate}e${power}`) === x) {
        const delta = candidate * d - n;
        const distance = delta < 0n ? -delta : delta;
        if (
          best === undefined ||
          distance < bestDistance ||
          (distance === bestDistance && candidate > best)
        ) {
          best = candidate;
          bestDistance = distance;
        }
      }
    }
    if (best !== undefined) {
      let digits = best.toString();
      let decimalPower = power;
      while (digits.endsWith("0")) {
        digits = digits.slice(0, -1);
        decimalPower++;
      }
      const point = digits.length + decimalPower;
      const body =
        point <= 0
          ? "0." + "0".repeat(-point) + digits
          : point >= digits.length
            ? digits + "0".repeat(point - digits.length)
            : digits.slice(0, point) + "." + digits.slice(point);
      return sign + body;
    }
  }
  throw new Error("No f64 round-trip decimal found");
}

function $unwrap(value, message = "called `Option::unwrap()` on a `None` value") {
  if (value == null) {
    throw new Error(message);
  }
  return value;
}

function $orInsert(map, key, value) {
  if (!map.has(key)) {
    map.set(key, value);
  }
  return map.get(key);
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function $partialCmp(a, b) {
  return a < b ? -1 : a > b ? 1 : a === b ? 0 : undefined;
}

function $toFixed(value, digits) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, Math.abs(value));
  const bits = view.getBigUint64(0);
  const exponent = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponent === 0 ? fraction : fraction | (1n << 52n);
  const shift = exponent === 0 ? -1074 : exponent - 1075;
  // |value| * 10^digits, as a fraction.
  let numerator = significand * 10n ** BigInt(digits);
  let denominator = 1n;
  if (shift >= 0) numerator <<= BigInt(shift);
  else denominator <<= BigInt(-shift);
  let rounded = numerator / denominator;
  const twice = 2n * (numerator % denominator);
  if (twice > denominator || (twice === denominator && rounded % 2n === 1n)) rounded += 1n;
  const text = rounded.toString().padStart(digits + 1, "0");
  return sign + (digits === 0 ? text : text.slice(0, -digits) + "." + text.slice(-digits));
}

function $debugF64(value) {
  const size = Math.abs(value);
  if (Number.isFinite(value) && size !== 0 && (size < 1e-4 || size >= 1e16)) {
    return value.toExponential().replace("e+", "e");
  }
  const text = $displayF64(value);
  return Number.isFinite(value) && !text.includes(".") ? text + ".0" : text;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

var $minStockRule, $revenueRule, $storeDisplay;

export const Store = {
  apply(store, e) {
    if (e.TAG === "Restock") {
      const current = $orInsert(store.stock, e.item, 0);
      store.stock.set(e.item, (current + e.qty) >>> 0);
    } else if (e.TAG === "Sale") {
      let have = store.stock.get(e.item);
      if (have == null) {
        return { TAG: "Err", _0: `unknown item ${e.item}` };
      }
      if (have < e.qty) {
        return { TAG: "Err", _0: `not enough ${e.item}: ${have} < ${e.qty}` };
      }
      have = (have - e.qty) >>> 0;
      store.stock.set(e.item, have);
      store.revenue += e.qty * e.price;
    } else {
      store.log.push(`audit at ${$toFixed(store.revenue, 2)}`);
    }
    return { TAG: "Ok", _0: undefined };
  },
};

function discount(pct) {
  return (p) => p * (1 - pct / 100);
}

function classify(n) {
  if (n <= -1) {
    return "negative";
  } else if (n === 0) {
    return "zero";
  } else if (n >= 1 && n <= 9 && n % 2 === 0) {
    return "small even";
  } else if (n >= 1 && n <= 9) {
    return "small odd";
  } else {
    return "large";
  }
}

export function report() {
  let store = { stock: new Map(), revenue: 0, log: [] };
  const events = [
    { TAG: "Restock", item: "apple", qty: 10 },
    { TAG: "Restock", item: "pear", qty: 3 },
    { TAG: "Sale", item: "apple", qty: 4, price: 0.5 },
    { TAG: "Sale", item: "kiwi", qty: 1, price: 2 },
    { TAG: "Sale", item: "pear", qty: 5, price: 1 },
    "Audit",
  ];
  let out = "";
  for (const e of events) {
    const msg = Store.apply(store, e);
    if (msg.TAG === "Err") {
      out += `error: ${msg._0}\n`;
    }
  }
  const rules = [
    { value: { item: "pear", min: 5 }, impl: minStockRule() },
    { value: [10], impl: revenueRule() },
  ];
  for (const r of rules) {
    const match = r.impl.check(r.value, store);
    if (match != null) {
      out += `[${r.impl.name(r.value)}] ${match}\n`;
    } else {
      out += `[${r.impl.name(r.value)}] ok\n`;
    }
  }
  out += `${storeDisplay_fmt(store)}\n[${store.log.map((item) => $debugStr(item)).join(", ")}]\n`;
  const half = discount(50);
  let prices = [3.5, 1.25, 9, 0.75];
  prices.sort((a, b) => $unwrap($partialCmp(b, a)));
  const cheap = prices.map((p) => half(p));
  const arg = events.filter((e) => e.TAG === "Sale").length;
  out += `[${prices.map((item) => $debugF64(item)).join(", ")}] [${cheap.map((item) => $debugF64(item)).join(", ")}] ${arg}\n`;
  const counter = { value: 0 };
  const c = counter;
  const bump = (n) => {
    c.value = (c.value + n) | 0;
  };
  for (const n of [-3, 0, 4, 7, 12]) {
    bump(n);
    out += `${classify(n)} `;
  }
  out += `total=${counter.value} again=${counter.value}\n`;
  let stack = [1, 2, 3];
  let popped = [];
  while (true) {
    const top = stack.pop();
    if (top != null) {
      if (top === 2) {
        stack.push(10);
      }
      popped.push(top);
    } else {
      break;
    }
  }
  out += `[${popped.map((item) => String(item)).join(", ")}]\n`;
  out += `[${tallies(["a", "b", "a", "b", "c"])
    .map((item) => `(${$debugStr(item[0])}, ${item[1]})`)
    .join(", ")}] [${bands([0, 3, 42, 150, 250])
    .map((item) => $debugStr(item))
    .join(", ")}]\n`;
  return out;
}

export function tallies(words) {
  let counts = new Map();
  const one = 1;
  for (const w of words) {
    const current = $orInsert(counts, w, 0);
    counts.set(w, (current + one) >>> 0);
    let n = counts.get("b");
    if (n != null) {
      n = Math.imul(n, 2) >>> 0;
      counts.set("b", n);
    }
  }
  let all = Array.from(counts);
  all.sort((a, b) => $cmp(a[0], b[0]) || $cmp(a[1], b[1]));
  return all;
}

export function bands(xs) {
  return xs.map((x) => {
    if (x === 0) {
      return "none";
    } else if (x >= 1 && x < 10) {
      return `few ${x}`;
    } else if ((x >= 10 && x <= 99) || x >= 200) {
      return `many ${x}`;
    } else {
      return "odd";
    }
  });
}

function minStockRule_name(minStock) {
  return `min-stock(${minStock.item})`;
}

function minStockRule_check(minStock, store) {
  const have = store.stock.get(minStock.item) ?? 0;
  if (have < minStock.min) {
    return `${minStock.item} low: ${have} < ${minStock.min}`;
  } else {
    return undefined;
  }
}

function revenueRule_name(revenue) {
  return "revenue";
}

function revenueRule_check(revenue, store) {
  return store.revenue < revenue[0]
    ? `revenue ${$toFixed(store.revenue, 2)} under ${$toFixed(revenue[0], 2)}`
    : undefined;
}

function storeDisplay_fmt(store) {
  let f = "";
  let items = Array.from(store.stock);
  items.sort((a, b) => $cmp(a[0], b[0]) || $cmp(a[1], b[1]));
  for (const [name, qty] of items) {
    f += `${name}=${qty} `;
  }
  f += `| ${$toFixed(store.revenue, 2)}`;
  return f;
}

export function minStockRule() {
  if ($minStockRule === undefined) {
    $minStockRule = { name: minStockRule_name, check: minStockRule_check };
  }
  return $minStockRule;
}

export function revenueRule() {
  if ($revenueRule === undefined) {
    $revenueRule = { name: revenueRule_name, check: revenueRule_check };
  }
  return $revenueRule;
}

export function storeDisplay() {
  if ($storeDisplay === undefined) {
    $storeDisplay = { fmt: storeDisplay_fmt };
  }
  return $storeDisplay;
}
//# sourceMappingURL=inventory.js.map
