// Generated by rust-js from examples/std_traits.rs. Do not edit.

function $traitImpl(cache, keys, make) {
  for (let i = 0; i < keys.length - 1; i++) {
    const key = keys[i];
    if (!cache.has(key)) cache.set(key, new WeakMap());
    cache = cache.get(key);
  }
  const key = keys[keys.length - 1];
  if (!cache.has(key)) cache.set(key, make());
  return cache.get(key);
}

function $index(items, index) {
  if (index < 0 || index >= items.length) throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return items[index];
}

// Shortest round-trip decimal, using exact rational arithmetic.
// Rust Display uses decimal notation, including for very small/large values.
// Not JS's `String(x)`, though its digits are also the shortest: when two are
// equally close, JS takes the even one (1888570120608320.2), and Rust the
// larger (1888570120608320.3).
function $displayF64(value) {
  if (Number.isNaN(value)) return 'NaN';
  if (value === Infinity) return 'inf';
  if (value === -Infinity) return '-inf';
  const sign = value < 0 || Object.is(value, -0) ? '-' : '';
  const x = Math.abs(value);
  if (x === 0) return sign + '0';

  const bitsView = new DataView(new ArrayBuffer(8));
  bitsView.setFloat64(0, x);
  const bits = bitsView.getBigUint64(0);
  const exponentBits = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponentBits === 0 ? fraction : fraction + (1n << 52n);
  const binaryExponent = exponentBits === 0 ? -1074 : exponentBits - 1023 - 52;
  const numerator = binaryExponent >= 0 ? significand << BigInt(binaryExponent) : significand;
  const denominator = binaryExponent < 0 ? 1n << BigInt(-binaryExponent) : 1n;

  // The floating-point logarithm is only an estimate; correct it exactly.
  let exponent = Math.floor(Math.log10(x));
  const atLeastPowerOfTen = e => e >= 0
    ? numerator >= denominator * 10n ** BigInt(e)
    : numerator * 10n ** BigInt(-e) >= denominator;
  while (!atLeastPowerOfTen(exponent)) exponent--;
  while (atLeastPowerOfTen(exponent + 1)) exponent++;

  for (let precision = 1; precision <= 17; precision++) {
    const power = exponent - precision + 1;
    const n = power < 0 ? numerator * 10n ** BigInt(-power) : numerator;
    const d = power > 0 ? denominator * 10n ** BigInt(power) : denominator;
    const floor = n / d;
    const rounded = floor + (2n * (n % d) >= d ? 1n : 0n);
    // The rounding interval can be asymmetric at a binary power boundary.
    let best;
    let bestDistance;
    for (const candidate of [rounded, rounded - 1n, rounded + 1n]) {
      if (candidate > 0n && Number(`${candidate}e${power}`) === x) {
        const delta = candidate * d - n;
        const distance = delta < 0n ? -delta : delta;
        if (best === undefined || distance < bestDistance || (distance === bestDistance && candidate > best)) {
          best = candidate;
          bestDistance = distance;
        }
      }
    }
    if (best !== undefined) {
      let digits = best.toString();
      let decimalPower = power;
      while (digits.endsWith('0')) {
        digits = digits.slice(0, -1);
        decimalPower++;
      }
      const point = digits.length + decimalPower;
      const body = point <= 0 ? '0.' + '0'.repeat(-point) + digits
        : point >= digits.length ? digits + '0'.repeat(point - digits.length)
        : digits.slice(0, point) + '.' + digits.slice(point);
      return sign + body;
    }
  }
  throw new Error('No f64 round-trip decimal found');
}

function $eq(a, b) {
  if (a === b || (a == null && b == null)) {
    return true;
  }
  if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) {
    return false;
  }
  if (Array.isArray(a)) {
    return Array.isArray(b) && a.length === b.length && a.every((x, i) => $eq(x, b[i]));
  }
  const keys = Object.keys(a);
  return keys.length === Object.keys(b).length && keys.every((k) => $eq(a[k], b[k]));
}

// `Some(x)` of a generic `T` (ADR 0051): `x`, unless it looks like `None`,
// as `undefined`, `null` or such a box does. Then it's a box one deeper.
function $some(x) {
  if (x == null) return { $someNone: 0 };
  if (typeof x === "object" && "$someNone" in x) return { $someNone: x.$someNone + 1 };
  return x;
}

// What's in a `$some`: the box one level shallower.
function $someValue(x) {
  if (x != null && typeof x === "object" && "$someNone" in x) {
    return x.$someNone === 0 ? undefined : { $someNone: x.$someNone - 1 };
  }
  return x;
}

// A Rust iterator of the crate's own as a JS one: its `next` returns the
// item, or `None` at the end. JS's iterator helpers are lazy, like Rust's
// adapters, so an endless one is fine until something wants all of it. A
// generic `next` may box its `Some` (ADR 0051): `boxed` unboxes it.
function $iterator(iterator, next, boxed = false) {
  return Iterator.from({
    next() {
      const item = next(iterator);
      if (item == null) {
        return { done: true, value: undefined };
      }
      return { done: false, value: boxed ? $someValue(item) : item };
    }
  });
}

function $range(start, end) {
  return Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function $partialCmp(a, b) {
  return a < b ? -1 : a > b ? 1 : a === b ? 0 : undefined;
}

function $debugF64(value) {
  const size = Math.abs(value);
  if (Number.isFinite(value) && size !== 0 && (size < 1e-4 || size >= 1e16)) {
    return value.toExponential().replace("e+", "e");
  }
  const text = $displayF64(value);
  return Number.isFinite(value) && !text.includes(".") ? text + ".0" : text;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (/[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) || (c !== " " && /\p{Zs}/u.test(c)))
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

function $debugFields(name, fields, values) {
  return name + " { " + fields.map((field, i) => field + ": " + values[i]).join(", ") + " }";
}

function $cmpIn(names, a, b) {
  return $cmp(names.indexOf(a), names.indexOf(b));
}

function $cmpItems(a, b, cmp) {
  for (let i = 0; i < a.length && i < b.length; i++) {
    const order = cmp(a[i], b[i]);
    if (order !== 0) {
      return order;
    }
  }
  return $cmp(a.length, b.length);
}

function $thenCmp(...orders) {
  for (const order of orders) {
    if (order !== 0) {
      return order;
    }
  }
  return 0;
}

function $maxBy(items, cmp, boxed = false) {
  if (items.length === 0) {
    return undefined;
  }
  const max = items.reduce((max, x) => (cmp(x, max) >= 0 ? x : max));
  return boxed ? $some(max) : max;
}

function $minBy(items, cmp, boxed = false) {
  if (items.length === 0) {
    return undefined;
  }
  const min = items.reduce((min, x) => (cmp(x, min) < 0 ? x : min));
  return boxed ? $some(min) : min;
}

function $max(items) {
  return items.length === 0 ? undefined : items.reduce((max, x) => (x >= max ? x : max));
}

var $configDefault, $trackedClone, $figureClone, $versionPartialEq, $metersPartialEqF64, $pointDisplay, $routeDisplay, $figureDisplay, $labeledDisplay, $wordPartialOrd, $wordOrd, $posDebug, $hiddenDebug;

export function fresh(TDefault) {
  return TDefault.default();
}

export function twice(x, TClone) {
  return [TClone.clone(x), TClone.clone(x)];
}

export function copied(x, TCopy) {
  return TCopy.copy(x);
}

export function defaults() {
  const s = {
    size: 0,
    tags: [],
    mode: "Off"
  };
  const c = fresh(configDefault());
  const n = fresh({ default: () => 0 });
  return [
    s.size,
    c.retries,
    s.mode === "Off",
    n,
    c.name,
    s.tags.length
  ];
}

export function vec_clones() {
  let v = [1, 2];
  const w = v.slice();
  v.push(3);
  return [v.length, w.length];
}

export function struct_clones() {
  const s = {
    size: 1,
    tags: ["a"],
    mode: "On"
  };
  let t = {
    ...s,
    tags: s.tags.slice()
  };
  t.tags.push("b");
  t.size = 2;
  return [
    s.tags.length,
    t.tags.length,
    s.size,
    t.size
  ];
}

export function hand_written() {
  const a = { generation: 0 };
  const b = trackedClone_clone(a);
  const holder = {
    tracked: b,
    label: "h"
  };
  const copy = {
    ...holder,
    tracked: trackedClone_clone(holder.tracked)
  };
  const all = [{ generation: 5 }];
  const cloned = all.map((item) => trackedClone_clone(item));
  const both = twice(copy.tracked, trackedClone());
  return [
    copy.tracked.generation,
    cloned.map((t) => t.generation).reduce((a, b) => a + b >>> 0, 0),
    both.map((t) => t.generation).reduce((a, b) => a + b >>> 0, 0),
    copied(7, { copy: (value) => value })
  ];
}

function points(s) {
  if (s === "Dot") {
    return 0;
  } else {
    return s._0.length;
  }
}

export function enum_clones() {
  const a = {
    TAG: "Poly",
    _0: [1]
  };
  let b;
  const match = a.TAG === "Poly" ? {
    ...a,
    _0: a._0.slice()
  } : a;
  if (match.TAG === "Poly") {
    let p = match._0;
    p.push(2);
    b = {
      TAG: "Poly",
      _0: p
    };
  } else {
    b = match;
  }
  const dot = "Dot";
  const f = figureClone_clone({
    TAG: "Poly",
    _0: [
      1,
      2,
      3
    ]
  });
  let n;
  if (f === "Dot") {
    n = 0;
  } else {
    n = f._0.length;
  }
  return [
    points(a),
    points(b),
    points(dot) + n >>> 0
  ];
}

export function conversions() {
  const a = metersFromF64_from(2.5);
  const b = metersFromU32_from(3);
  const c = metersFromF64_from(1.5);
  return [
    a[0],
    b[0],
    c[0]
  ];
}

function version(major, label) {
  return {
    major,
    label
  };
}

export function same(a, b, TPartialEq) {
  return TPartialEq.eq(a, b);
}

export function count_equal(items, x, TPartialEq) {
  return items.filter((item) => TPartialEq.eq(item, x)).length;
}

export function equalities() {
  const r1 = {
    version: version(1, "a"),
    notes: ["x"]
  };
  const r2 = {
    version: version(1, "b"),
    notes: ["x"]
  };
  const r3 = {
    version: version(1, "c"),
    notes: []
  };
  const left = {
    TAG: "Bump",
    _0: version(4, "a")
  };
  const right = {
    TAG: "Bump",
    _0: version(4, "b")
  };
  const left$1 = version(5, "a");
  const right$1 = version(5, "b");
  return [
    versionPartialEq_eq(r1.version, r2.version) && $eq(r1.notes, r2.notes),
    !(versionPartialEq_eq(r1.version, r3.version) && $eq(r1.notes, r3.notes)),
    same(version(2, "a"), version(3, "a"), versionPartialEq()),
    left.TAG === "Bump" ? right.TAG === "Bump" && versionPartialEq_eq(left._0, right._0) : $eq(left, right),
    {
      TAG: "Note",
      _0: "n"
    } === "Nothing",
    left$1 == null || right$1 == null ? left$1 == right$1 : versionPartialEq_eq(left$1, right$1)
  ];
}

export function generic_equalities() {
  const all = [
    version(1, "a"),
    version(2, "b"),
    version(1, "c")
  ];
  const pairs = [[1, "a"], [2, "b"]];
  return [
    count_equal(all, version(1, "z"), versionPartialEq()),
    same(pairs, [[1, "a"], [2, "b"]], { eq: $eq }),
    same([version(1, "a")], [version(2, "a")], { eq: (a, b) => a.length === b.length && a.every((x, i) => versionPartialEq_eq(x, b[i])) })
  ];
}

export function compared() {
  const m = metersFromF64_from(2);
  return [
    metersPartialEqF64_eq(m, 2),
    !metersPartialEqF64_eq(m, 3),
    !metersPartialEqF64_eq(m, 2)
  ];
}

function write_loop(stops) {
  return " (a loop of " + String(stops) + ")";
}

export function shown(x, TDisplay) {
  return "<" + TDisplay.fmt(x) + ">";
}

export function displays() {
  const p = {
    x: 1,
    y: -2
  };
  const route = {
    stops: [{
      x: 0,
      y: 0
    }, {
      x: 3,
      y: 4
    }],
    closed: true
  };
  const empty = {
    stops: [],
    closed: false
  };
  const labeled = {
    label: "at",
    value: {
      x: 5,
      y: 6
    }
  };
  return [
    pointDisplay_fmt(p),
    routeDisplay_fmt(route) + " / " + routeDisplay_fmt(empty),
    figureDisplay_fmt("Dot") + " and " + figureDisplay_fmt({
      TAG: "Poly",
      _0: [1, 2]
    }),
    labeledDisplay_fmt(labeled, pointDisplay()),
    shown(labeled, labeledDisplay(pointDisplay())),
    shown({
      label: "n",
      value: 2.5
    }, labeledDisplay({ fmt: $displayF64 }))
  ];
}

function fibonacci() {
  return {
    a: 0,
    b: 1
  };
}

export function iterations() {
  let total$1 = 0;
  for (const x of $iterator({ n: 3 }, countdownIterator_next)) {
    total$1 = total$1 + x >>> 0;
  }
  let c = { n: 2 };
  const first = countdownIterator_next(c) ?? 0;
  return [
    total$1,
    first,
    $iterator(fibonacci(), fibonacciIterator_next).drop(1).take(6).toArray(),
    $iterator(fibonacci(), fibonacciIterator_next).take(5).map((x) => Math.imul(x, 2) >>> 0).reduce((a, b) => a + b >>> 0, 0),
    $iterator({ n: 4 }, countdownIterator_next).toArray().length,
    $iterator(fibonacci(), fibonacciIterator_next).find((x) => x > 50)
  ];
}

export function generic_iterations() {
  return [
    $iterator({
      item: undefined,
      times: 3
    }, (iterator) => repeatIterator_next(iterator, { clone: (value) => value }), true).toArray().length,
    $iterator({
      item: undefined,
      times: 2
    }, (iterator) => repeatIterator_next(iterator, { clone: (value) => value }), true).filter((o) => o == null).toArray().length,
    $iterator({
      item: 2,
      times: 3
    }, (iterator) => repeatIterator_next(iterator, { clone: (value) => value }), true).toArray(),
    $max($iterator({ n: 5 }, countdownIterator_next).map((x, i) => [i, x]).map(([i, x]) => Math.imul(i, x) >>> 0).toArray())
  ];
}

export function largest(xs, TOrd, TCopy) {
  return $maxBy(xs.map((item) => TCopy.copy(item)), TOrd.cmp, true);
}

export function in_order(a, b, TPartialOrd) {
  return TPartialOrd.partial_cmp(a, b) <= 0;
}

export function orderings() {
  const a = {
    major: 1,
    minor: 2
  };
  const b = {
    major: 1,
    minor: 10
  };
  let all = [
    b,
    {
      major: 0,
      minor: 9
    },
    a
  ];
  all.sort((a, b) => $cmp(a.major, b.major) || $cmp(a.minor, b.minor));
  const v = largest(all, { cmp: (a, b) => $cmp(a.major, b.major) || $cmp(a.minor, b.minor) }, { copy: (value) => ({ ...value }) });
  const v$1 = $minBy(all, (a, b) => $cmp(a.major, b.major) || $cmp(a.minor, b.minor));
  return [
    ($cmp(a.major, b.major) || $cmp(a.minor, b.minor)) < 0,
    $eq(($cmp(a.major, b.major) || $cmp(a.minor, b.minor)) > 0 ? a : b, b),
    ($cmp(a.major, b.major) || $cmp(a.minor, b.minor)) === -1,
    (v != null ? v.minor : undefined) ?? 0,
    (v$1 != null ? v$1.minor : undefined) ?? 0,
    all.map((v) => v.minor)
  ];
}

export function partial_orderings() {
  const p = {
    x: 1,
    y: NaN
  };
  const q = {
    x: 1,
    y: 2
  };
  const r = {
    x: .5,
    y: NaN
  };
  return [
    $thenCmp($partialCmp(p.x, q.x), $partialCmp(p.y, q.y)) < 0,
    $thenCmp($partialCmp(p.x, q.x), $partialCmp(p.y, q.y)) >= 0,
    $thenCmp($partialCmp(r.x, q.x), $partialCmp(r.y, q.y)) < 0,
    $thenCmp($partialCmp(p.x, q.x), $partialCmp(p.y, q.y)) == null
  ];
}

export function more_orderings() {
  let words = [
    ["pear"],
    ["fig"],
    ["apple"],
    ["kiwi"]
  ];
  words.sort(wordOrd_cmp);
  let priorities = [
    "High",
    "Low",
    "Mid"
  ];
  priorities.sort((a, b) => $cmpIn([
    "Low",
    "Mid",
    "High"
  ], a, b));
  let lists = [
    [2, 1],
    [
      1,
      5,
      0
    ],
    [1, 5]
  ];
  lists.sort((a, b) => $cmpItems(a, b, $cmp));
  let sizes = words.map((w) => Array.from(w[0]).length);
  for (const list of lists) {
    sizes.push(list.length);
  }
  let byKey = [{
    major: 2,
    minor: 0
  }, {
    major: 1,
    minor: 5
  }];
  const key = (v) => [v.minor, v.major];
  byKey.sort((a, b) => {
    const left = key(a);
    const right = key(b);
    return $cmp(left[0], right[0]) || $cmp(left[1], right[1]);
  });
  return [
    $cmpIn([
      "Low",
      "Mid",
      "High"
    ], "Low", "High") < 0,
    $index(priorities, 0) === "Low",
    (3 == null ? undefined == null ? 0 : -1 : undefined == null ? 1 : $cmp(3, undefined)) > 0,
    sizes,
    in_order("abc", "abd", { partial_cmp: $cmp }),
    $index(byKey, 0).major
  ];
}

export function debugged(x, TDebug) {
  return TDebug.fmt(x);
}

export function debugs(n) {
  const p = {
    x: n,
    y: -2.5
  };
  const r = n > 1 ? {
    TAG: "Ok",
    _0: n
  } : {
    TAG: "Err",
    _0: "small"
  };
  return [
    posDebug_fmt(p),
    dimsDebug_fmt([n, 2]) + " " + nothingDebug_fmt(undefined) + " " + glyphDebug_fmt("Dot"),
    glyphDebug_fmt({
      TAG: "Ring",
      _0: 1.5
    }) + " " + glyphDebug_fmt({
      TAG: "Box",
      w: n,
      h: 3
    }),
    sixDebug_fmt({
      a: 1,
      b: 2,
      c: 3,
      d: 4,
      e: 5,
      f: "x"
    }),
    boxedDebug_fmt({ item: p }, posDebug()) + " " + boxedDebug_fmt({ item: "s" }, { fmt: (value) => value == null ? "None" : "Some(" + $debugStr(value) + ")" }),
    (1 == null ? "None" : "Some(" + $debugF64(1) + ")") + " " + (undefined == null ? "None" : "Some(" + String(undefined) + ")") + " " + ((tuple) => "(" + String(tuple[0]) + ", " + $debugStr(tuple[1]) + ", " + $debugStr(tuple[2], "'") + ")")([
      n,
      "a",
      "'"
    ]) + " " + ((tuple) => "(" + String(tuple[0]) + ",)")([5]),
    "[" + [p, p].map((item) => posDebug_fmt(item)).join(", ") + "]" + " " + (r.TAG === "Ok" ? "Ok(" + String(r._0) + ")" : "Err(" + $debugStr(r._0) + ")") + " " + [
      "Less",
      "Equal",
      "Greater"
    ][$cmp(n, 1) + 1],
    hiddenDebug_fmt(undefined) + " " + debugged([[3, 4]], { fmt: (value) => "[" + value.map((item) => item == null ? "None" : "Some(" + dimsDebug_fmt(item) + ")").join(", ") + "]" })
  ];
}

export function evens_below(n) {
  return $range(0, n).filter((x) => x % 2 === 0);
}

export function countdown(n) {
  return { n };
}

export function total(items) {
  return Iterator.from(items).reduce((a, b) => a + b >>> 0, 0);
}

export function middle(items, k) {
  return Iterator.from(items).drop(1).take(k).toArray();
}

export function looped(items) {
  let sum = 0;
  for (const x of items) {
    sum = sum + x >>> 0;
  }
  return sum;
}

export function generic_iterators(n) {
  return [
    total(evens_below(n)),
    middle($iterator(countdown(n), countdownIterator_next), 2),
    middle(evens_below(Math.imul(n, 2) >>> 0), 3),
    looped([
      n,
      2,
      3
    ]),
    total($iterator({ n }, countdownIterator_next)),
    $iterator(countdown(n), countdownIterator_next).map((x) => x + 1 >>> 0).reduce((a, b) => a + b >>> 0, 0)
  ];
}

function configDefault_default() {
  return {
    retries: 3,
    name: "main"
  };
}

function trackedClone_clone(tracked) {
  return { generation: tracked.generation + 1 >>> 0 };
}

function figureClone_clone(figure) {
  if (figure === "Dot") {
    return "Dot";
  } else {
    return {
      TAG: "Poly",
      _0: figure._0.slice()
    };
  }
}

function metersFromF64_from(m) {
  return [m];
}

function metersFromU32_from(km) {
  return [km * 1000];
}

function versionPartialEq_eq(version$1, other) {
  return version$1.major === other.major;
}

function metersPartialEqF64_eq(meters, other) {
  return meters[0] === other;
}

function pointDisplay_fmt(point) {
  return "(" + String(point.x) + ", " + String(point.y) + ")";
}

function routeDisplay_fmt(route) {
  let f = "";
  if (route.stops.length === 0) {
    f += "nowhere";
    return f;
  }
  for (const item of route.stops.map((x, i) => [i, x])) {
    if (item[0] > 0) {
      f += " -> ";
    }
    f += pointDisplay_fmt(item[1]);
  }
  if (route.closed) {
    f += write_loop(route.stops.length);
  }
  return f;
}

function figureDisplay_fmt(figure) {
  if (figure === "Dot") {
    return "a dot";
  } else {
    return "a polygon of " + String(figure._0.length);
  }
}

function labeledDisplay_fmt(labeled, TDisplay) {
  return labeled.label + ": " + TDisplay.fmt(labeled.value);
}

function countdownIterator_next(countdown$1) {
  if (countdown$1.n === 0) {
    return undefined;
  } else {
    countdown$1.n = countdown$1.n - 1 >>> 0;
    return countdown$1.n + 1 >>> 0;
  }
}

function fibonacciIterator_next(fibonacci$1) {
  const a = fibonacci$1.a;
  fibonacci$1.a = fibonacci$1.b;
  fibonacci$1.b = fibonacci$1.b + a >>> 0;
  return a;
}

function repeatIterator_next(repeat, TClone) {
  if (repeat.times === 0) {
    return undefined;
  }
  repeat.times = repeat.times - 1 >>> 0;
  return $some(TClone.clone(repeat.item));
}

function wordPartialOrd_partial_cmp(word, other) {
  return wordOrd_cmp(word, other);
}

function wordOrd_cmp(word, other) {
  const byLength = $cmp(Array.from(word[0]).length, Array.from(other[0]).length);
  if (byLength !== 0) {
    return byLength;
  } else {
    return $cmp(word[0], other[0]);
  }
}

function posDebug_fmt(pos) {
  return "Pos { x: " + $debugF64(pos.x) + ", y: " + $debugF64(pos.y) + " }";
}

function dimsDebug_fmt(dims) {
  return "Dims(" + String(dims[0]) + ", " + String(dims[1]) + ")";
}

function nothingDebug_fmt(nothing) {
  return "Nothing";
}

function glyphDebug_fmt(glyph) {
  if (glyph === "Dot") {
    return "Dot";
  } else if (glyph.TAG === "Ring") {
    return "Ring(" + $debugF64(glyph._0) + ")";
  } else {
    return "Box { w: " + String(glyph.w) + ", h: " + String(glyph.h) + " }";
  }
}

function sixDebug_fmt(six) {
  const names = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f"
  ];
  const values = [
    String(six.a),
    String(six.b),
    String(six.c),
    String(six.d),
    String(six.e),
    $debugStr(six.f, "'")
  ];
  return $debugFields("Six", names, values);
}

function boxedDebug_fmt(boxed, TDebug) {
  return "Boxed { item: " + TDebug.fmt(boxed.item) + " }";
}

function hiddenDebug_fmt(hidden) {
  return "<hidden>";
}

export function configDefault() {
  if ($configDefault === undefined) {
    $configDefault = { default: configDefault_default };
  }
  return $configDefault;
}

export function trackedClone() {
  if ($trackedClone === undefined) {
    $trackedClone = { clone: trackedClone_clone };
  }
  return $trackedClone;
}

export function figureClone() {
  if ($figureClone === undefined) {
    $figureClone = { clone: figureClone_clone };
  }
  return $figureClone;
}

export function versionPartialEq() {
  if ($versionPartialEq === undefined) {
    $versionPartialEq = { eq: versionPartialEq_eq };
  }
  return $versionPartialEq;
}

export function metersPartialEqF64() {
  if ($metersPartialEqF64 === undefined) {
    $metersPartialEqF64 = { eq: metersPartialEqF64_eq };
  }
  return $metersPartialEqF64;
}

export function pointDisplay() {
  if ($pointDisplay === undefined) {
    $pointDisplay = { fmt: pointDisplay_fmt };
  }
  return $pointDisplay;
}

export function routeDisplay() {
  if ($routeDisplay === undefined) {
    $routeDisplay = { fmt: routeDisplay_fmt };
  }
  return $routeDisplay;
}

export function figureDisplay() {
  if ($figureDisplay === undefined) {
    $figureDisplay = { fmt: figureDisplay_fmt };
  }
  return $figureDisplay;
}

export function labeledDisplay(TDisplay) {
  if ($labeledDisplay === undefined) {
    $labeledDisplay = new WeakMap();
  }
  return $traitImpl($labeledDisplay, [TDisplay], () => ({ fmt: (arg0) => labeledDisplay_fmt(arg0, TDisplay) }));
}

export function wordPartialOrd() {
  if ($wordPartialOrd === undefined) {
    $wordPartialOrd = {
      PartialEq: () => ({ eq: $eq }),
      partial_cmp: wordPartialOrd_partial_cmp
    };
  }
  return $wordPartialOrd;
}

export function wordOrd() {
  if ($wordOrd === undefined) {
    $wordOrd = {
      PartialOrd: () => wordPartialOrd(),
      cmp: wordOrd_cmp
    };
  }
  return $wordOrd;
}

export function posDebug() {
  if ($posDebug === undefined) {
    $posDebug = { fmt: posDebug_fmt };
  }
  return $posDebug;
}

export function hiddenDebug() {
  if ($hiddenDebug === undefined) {
    $hiddenDebug = { fmt: hiddenDebug_fmt };
  }
  return $hiddenDebug;
}
//# sourceMappingURL=std_traits.js.map
