// Generated by rust-js from examples/std_traits.rs. Do not edit.

function $traitImpl(cache, keys, make) {
  for (let i = 0; i < keys.length - 1; i++) {
    const key = keys[i];
    if (!cache.has(key)) cache.set(key, new WeakMap());
    cache = cache.get(key);
  }
  const key = keys[keys.length - 1];
  if (!cache.has(key)) cache.set(key, make());
  return cache.get(key);
}

// Shortest round-trip decimal, using exact rational arithmetic.
// Rust Display uses decimal notation, including for very small/large values.
// Not JS's `String(x)`, though its digits are also the shortest: when two are
// equally close, JS takes the even one (1888570120608320.2), and Rust the
// larger (1888570120608320.3).
function $displayF64(value) {
  if (Number.isNaN(value)) return 'NaN';
  if (value === Infinity) return 'inf';
  if (value === -Infinity) return '-inf';
  const sign = value < 0 || Object.is(value, -0) ? '-' : '';
  const x = Math.abs(value);
  if (x === 0) return sign + '0';

  const bitsView = new DataView(new ArrayBuffer(8));
  bitsView.setFloat64(0, x);
  const bits = bitsView.getBigUint64(0);
  const exponentBits = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponentBits === 0 ? fraction : fraction + (1n << 52n);
  const binaryExponent = exponentBits === 0 ? -1074 : exponentBits - 1023 - 52;
  const numerator = binaryExponent >= 0 ? significand << BigInt(binaryExponent) : significand;
  const denominator = binaryExponent < 0 ? 1n << BigInt(-binaryExponent) : 1n;

  // The floating-point logarithm is only an estimate; correct it exactly.
  let exponent = Math.floor(Math.log10(x));
  const atLeastPowerOfTen = e => e >= 0
    ? numerator >= denominator * 10n ** BigInt(e)
    : numerator * 10n ** BigInt(-e) >= denominator;
  while (!atLeastPowerOfTen(exponent)) exponent--;
  while (atLeastPowerOfTen(exponent + 1)) exponent++;

  for (let precision = 1; precision <= 17; precision++) {
    const power = exponent - precision + 1;
    const n = power < 0 ? numerator * 10n ** BigInt(-power) : numerator;
    const d = power > 0 ? denominator * 10n ** BigInt(power) : denominator;
    const floor = n / d;
    const rounded = floor + (2n * (n % d) >= d ? 1n : 0n);
    // The rounding interval can be asymmetric at a binary power boundary.
    let best;
    let bestDistance;
    for (const candidate of [rounded, rounded - 1n, rounded + 1n]) {
      if (candidate > 0n && Number(`${candidate}e${power}`) === x) {
        const delta = candidate * d - n;
        const distance = delta < 0n ? -delta : delta;
        if (best === undefined || distance < bestDistance || (distance === bestDistance && candidate > best)) {
          best = candidate;
          bestDistance = distance;
        }
      }
    }
    if (best !== undefined) {
      let digits = best.toString();
      let decimalPower = power;
      while (digits.endsWith('0')) {
        digits = digits.slice(0, -1);
        decimalPower++;
      }
      const point = digits.length + decimalPower;
      const body = point <= 0 ? '0.' + '0'.repeat(-point) + digits
        : point >= digits.length ? digits + '0'.repeat(point - digits.length)
        : digits.slice(0, point) + '.' + digits.slice(point);
      return sign + body;
    }
  }
  throw new Error('No f64 round-trip decimal found');
}

function $eq(a, b) {
  if (a === b || (a == null && b == null)) {
    return true;
  }
  if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) {
    return false;
  }
  if (Array.isArray(a)) {
    return Array.isArray(b) && a.length === b.length && a.every((x, i) => $eq(x, b[i]));
  }
  const keys = Object.keys(a);
  return keys.length === Object.keys(b).length && keys.every((k) => $eq(a[k], b[k]));
}

// `Some(x)` of a generic `T` (ADR 0051): `x`, unless it looks like `None`,
// as `undefined`, `null` or such a box does. Then it's a box one deeper.
function $some(x) {
  if (x == null) return { $someNone: 0 };
  if (typeof x === "object" && "$someNone" in x) return { $someNone: x.$someNone + 1 };
  return x;
}

// What's in a `$some`: the box one level shallower.
function $someValue(x) {
  if (x != null && typeof x === "object" && "$someNone" in x) {
    return x.$someNone === 0 ? undefined : { $someNone: x.$someNone - 1 };
  }
  return x;
}

// A Rust iterator of the crate's own as a JS one: its `next` returns the
// item, or `None` at the end. JS's iterator helpers are lazy, like Rust's
// adapters, so an endless one is fine until something wants all of it. A
// generic `next` may box its `Some` (ADR 0051): `boxed` unboxes it.
function $iterator(iterator, next, boxed = false) {
  return Iterator.from({
    next() {
      const item = next(iterator);
      if (item == null) {
        return { done: true, value: undefined };
      }
      return { done: false, value: boxed ? $someValue(item) : item };
    }
  });
}

function $max(items) {
  return items.length === 0 ? undefined : items.reduce((max, x) => (x >= max ? x : max));
}

var $configDefault, $trackedClone, $figureClone, $versionPartialEq, $metersPartialEqF64, $pointDisplay, $routeDisplay, $figureDisplay, $labeledDisplay;

export function fresh(TDefault) {
  return TDefault.default();
}

export function twice(x, TClone) {
  return [TClone.clone(x), TClone.clone(x)];
}

export function copied(x, TCopy) {
  return TCopy.copy(x);
}

export function defaults() {
  const s = {
    size: 0,
    tags: [],
    mode: "Off"
  };
  const c = fresh(configDefault());
  const n = fresh({ default: () => 0 });
  return [
    s.size,
    c.retries,
    s.mode === "Off",
    n,
    c.name,
    s.tags.length
  ];
}

export function vec_clones() {
  let v = [1, 2];
  const w = v.slice();
  v.push(3);
  return [v.length, w.length];
}

export function struct_clones() {
  const s = {
    size: 1,
    tags: ["a"],
    mode: "On"
  };
  let t = {
    ...s,
    tags: s.tags.slice()
  };
  t.tags.push("b");
  t.size = 2;
  return [
    s.tags.length,
    t.tags.length,
    s.size,
    t.size
  ];
}

export function hand_written() {
  const a = { generation: 0 };
  const b = trackedClone_clone(a);
  const holder = {
    tracked: b,
    label: "h"
  };
  const copy = {
    ...holder,
    tracked: trackedClone_clone(holder.tracked)
  };
  const all = [{ generation: 5 }];
  const cloned = all.map((item) => trackedClone_clone(item));
  const both = twice(copy.tracked, trackedClone());
  return [
    copy.tracked.generation,
    cloned.map((t) => t.generation).reduce((a, b) => a + b >>> 0, 0),
    both.map((t) => t.generation).reduce((a, b) => a + b >>> 0, 0),
    copied(7, { copy: (value) => value })
  ];
}

function points(s) {
  if (s === "Dot") {
    return 0;
  } else {
    return s._0.length;
  }
}

export function enum_clones() {
  const a = {
    TAG: "Poly",
    _0: [1]
  };
  let b;
  const match = a.TAG === "Poly" ? {
    ...a,
    _0: a._0.slice()
  } : a;
  if (match.TAG === "Poly") {
    let p = match._0;
    p.push(2);
    b = {
      TAG: "Poly",
      _0: p
    };
  } else {
    b = match;
  }
  const dot = "Dot";
  const f = figureClone_clone({
    TAG: "Poly",
    _0: [
      1,
      2,
      3
    ]
  });
  let n;
  if (f === "Dot") {
    n = 0;
  } else {
    n = f._0.length;
  }
  return [
    points(a),
    points(b),
    points(dot) + n >>> 0
  ];
}

export function conversions() {
  const a = metersFromF64_from(2.5);
  const b = metersFromU32_from(3);
  const c = metersFromF64_from(1.5);
  return [
    a[0],
    b[0],
    c[0]
  ];
}

function version(major, label) {
  return {
    major,
    label
  };
}

export function same(a, b, TPartialEq) {
  return TPartialEq.eq(a, b);
}

export function count_equal(items, x, TPartialEq) {
  return items.filter((item) => TPartialEq.eq(item, x)).length;
}

export function equalities() {
  const r1 = {
    version: version(1, "a"),
    notes: ["x"]
  };
  const r2 = {
    version: version(1, "b"),
    notes: ["x"]
  };
  const r3 = {
    version: version(1, "c"),
    notes: []
  };
  const a = {
    TAG: "Bump",
    _0: version(4, "a")
  };
  const b = {
    TAG: "Bump",
    _0: version(4, "b")
  };
  const a$1 = version(5, "a");
  const b$1 = version(5, "b");
  return [
    versionPartialEq_eq(r1.version, r2.version) && $eq(r1.notes, r2.notes),
    !(versionPartialEq_eq(r1.version, r3.version) && $eq(r1.notes, r3.notes)),
    same(version(2, "a"), version(3, "a"), versionPartialEq()),
    a.TAG === "Bump" ? b.TAG === "Bump" && versionPartialEq_eq(a._0, b._0) : $eq(a, b),
    {
      TAG: "Note",
      _0: "n"
    } === "Nothing",
    a$1 == null || b$1 == null ? a$1 == b$1 : versionPartialEq_eq(a$1, b$1)
  ];
}

export function generic_equalities() {
  const all = [
    version(1, "a"),
    version(2, "b"),
    version(1, "c")
  ];
  const pairs = [[1, "a"], [2, "b"]];
  return [
    count_equal(all, version(1, "z"), versionPartialEq()),
    same(pairs, [[1, "a"], [2, "b"]], { eq: $eq }),
    same([version(1, "a")], [version(2, "a")], { eq: (a, b) => a.length === b.length && a.every((x, i) => versionPartialEq_eq(x, b[i])) })
  ];
}

export function compared() {
  const m = metersFromF64_from(2);
  return [
    metersPartialEqF64_eq(m, 2),
    !metersPartialEqF64_eq(m, 3),
    !metersPartialEqF64_eq(m, 2)
  ];
}

function write_loop(stops) {
  return " (a loop of " + String(stops) + ")";
}

export function shown(x, TDisplay) {
  return "<" + TDisplay.fmt(x) + ">";
}

export function displays() {
  const p = {
    x: 1,
    y: -2
  };
  const route = {
    stops: [{
      x: 0,
      y: 0
    }, {
      x: 3,
      y: 4
    }],
    closed: true
  };
  const empty = {
    stops: [],
    closed: false
  };
  const labeled = {
    label: "at",
    value: {
      x: 5,
      y: 6
    }
  };
  const tmp = pointDisplay_fmt(p);
  const tmp$1 = routeDisplay_fmt(route) + " / " + routeDisplay_fmt(empty);
  return [
    tmp,
    tmp$1,
    figureDisplay_fmt("Dot") + " and " + figureDisplay_fmt({
      TAG: "Poly",
      _0: [1, 2]
    }),
    labeledDisplay_fmt(labeled, pointDisplay()),
    shown(labeled, labeledDisplay(pointDisplay())),
    shown({
      label: "n",
      value: 2.5
    }, labeledDisplay({ fmt: $displayF64 }))
  ];
}

function fibonacci() {
  return {
    a: 0,
    b: 1
  };
}

export function iterations() {
  let total = 0;
  for (const x of $iterator({ n: 3 }, countdownIterator_next)) {
    total = total + x >>> 0;
  }
  let c = { n: 2 };
  const first = countdownIterator_next(c) ?? 0;
  return [
    total,
    first,
    $iterator(fibonacci(), fibonacciIterator_next).drop(1).take(6).toArray(),
    $iterator(fibonacci(), fibonacciIterator_next).take(5).map((x) => Math.imul(x, 2) >>> 0).reduce((a, b) => a + b >>> 0, 0),
    $iterator({ n: 4 }, countdownIterator_next).toArray().length,
    $iterator(fibonacci(), fibonacciIterator_next).find((x) => x > 50)
  ];
}

export function generic_iterations() {
  return [
    $iterator({
      item: undefined,
      times: 3
    }, (iterator) => repeatIterator_next(iterator, { clone: (value) => value }), true).toArray().length,
    $iterator({
      item: undefined,
      times: 2
    }, (iterator) => repeatIterator_next(iterator, { clone: (value) => value }), true).filter((o) => o == null).toArray().length,
    $iterator({
      item: 2,
      times: 3
    }, (iterator) => repeatIterator_next(iterator, { clone: (value) => value }), true).toArray(),
    $max($iterator({ n: 5 }, countdownIterator_next).map((x, i) => [i, x]).map(([i, x]) => Math.imul(i, x) >>> 0).toArray())
  ];
}

function configDefault_default() {
  return {
    retries: 3,
    name: "main"
  };
}

function trackedClone_clone(tracked) {
  return { generation: tracked.generation + 1 >>> 0 };
}

function figureClone_clone(figure) {
  if (figure === "Dot") {
    return "Dot";
  } else {
    return {
      TAG: "Poly",
      _0: figure._0.slice()
    };
  }
}

function metersFromF64_from(m) {
  return [m];
}

function metersFromU32_from(km) {
  return [km * 1000];
}

function versionPartialEq_eq(version$1, other) {
  return version$1.major === other.major;
}

function metersPartialEqF64_eq(meters, other) {
  return meters[0] === other;
}

function pointDisplay_fmt(point) {
  return "(" + String(point.x) + ", " + String(point.y) + ")";
}

function routeDisplay_fmt(route) {
  let f = "";
  if (route.stops.length === 0) {
    f += "nowhere";
    return f;
  }
  for (const item of route.stops.map((x, i) => [i, x])) {
    if (item[0] > 0) {
      f += " -> ";
    }
    f += pointDisplay_fmt(item[1]);
  }
  if (route.closed) {
    f += write_loop(route.stops.length);
  }
  return f;
}

function figureDisplay_fmt(figure) {
  if (figure === "Dot") {
    return "a dot";
  } else {
    return "a polygon of " + String(figure._0.length);
  }
}

function labeledDisplay_fmt(labeled, TDisplay) {
  return labeled.label + ": " + TDisplay.fmt(labeled.value);
}

function countdownIterator_next(countdown) {
  if (countdown.n === 0) {
    return undefined;
  } else {
    countdown.n = countdown.n - 1 >>> 0;
    return countdown.n + 1 >>> 0;
  }
}

function fibonacciIterator_next(fibonacci$1) {
  const a = fibonacci$1.a;
  fibonacci$1.a = fibonacci$1.b;
  fibonacci$1.b = fibonacci$1.b + a >>> 0;
  return a;
}

function repeatIterator_next(repeat, TClone) {
  if (repeat.times === 0) {
    return undefined;
  }
  repeat.times = repeat.times - 1 >>> 0;
  return $some(TClone.clone(repeat.item));
}

export function configDefault() {
  if ($configDefault === undefined) {
    $configDefault = { default: configDefault_default };
  }
  return $configDefault;
}

export function trackedClone() {
  if ($trackedClone === undefined) {
    $trackedClone = { clone: trackedClone_clone };
  }
  return $trackedClone;
}

export function figureClone() {
  if ($figureClone === undefined) {
    $figureClone = { clone: figureClone_clone };
  }
  return $figureClone;
}

export function versionPartialEq() {
  if ($versionPartialEq === undefined) {
    $versionPartialEq = { eq: versionPartialEq_eq };
  }
  return $versionPartialEq;
}

export function metersPartialEqF64() {
  if ($metersPartialEqF64 === undefined) {
    $metersPartialEqF64 = { eq: metersPartialEqF64_eq };
  }
  return $metersPartialEqF64;
}

export function pointDisplay() {
  if ($pointDisplay === undefined) {
    $pointDisplay = { fmt: pointDisplay_fmt };
  }
  return $pointDisplay;
}

export function routeDisplay() {
  if ($routeDisplay === undefined) {
    $routeDisplay = { fmt: routeDisplay_fmt };
  }
  return $routeDisplay;
}

export function figureDisplay() {
  if ($figureDisplay === undefined) {
    $figureDisplay = { fmt: figureDisplay_fmt };
  }
  return $figureDisplay;
}

export function labeledDisplay(TDisplay) {
  if ($labeledDisplay === undefined) {
    $labeledDisplay = new WeakMap();
  }
  return $traitImpl($labeledDisplay, [TDisplay], () => ({ fmt: (arg0) => labeledDisplay_fmt(arg0, TDisplay) }));
}
//# sourceMappingURL=std_traits.js.map
