// Generated by rust-js from examples/std_traits.rs. Do not edit.

var $configDefault, $trackedClone, $figureClone;

export function fresh(TDefault) {
  return TDefault.default();
}

export function twice(x, TClone) {
  return [TClone.clone(x), TClone.clone(x)];
}

export function copied(x, TCopy) {
  return TCopy.copy(x);
}

export function defaults() {
  const s = {
    size: 0,
    tags: [],
    mode: "Off"
  };
  const c = fresh(configDefault());
  const n = fresh({ default: () => 0 });
  return [
    s.size,
    c.retries,
    s.mode === "Off",
    n,
    c.name,
    s.tags.length
  ];
}

export function vec_clones() {
  let v = [1, 2];
  const w = v.slice();
  v.push(3);
  return [v.length, w.length];
}

export function struct_clones() {
  const s = {
    size: 1,
    tags: ["a"],
    mode: "On"
  };
  let t = {
    ...s,
    tags: s.tags.slice()
  };
  t.tags.push("b");
  t.size = 2;
  return [
    s.tags.length,
    t.tags.length,
    s.size,
    t.size
  ];
}

export function hand_written() {
  const a = { generation: 0 };
  const b = trackedClone_clone(a);
  const holder = {
    tracked: b,
    label: "h"
  };
  const copy = {
    ...holder,
    tracked: trackedClone_clone(holder.tracked)
  };
  const all = [{ generation: 5 }];
  const cloned = all.map((item) => trackedClone_clone(item));
  const both = twice(copy.tracked, trackedClone());
  return [
    copy.tracked.generation,
    cloned.map((t) => t.generation).reduce((a, b) => a + b >>> 0, 0),
    both.map((t) => t.generation).reduce((a, b) => a + b >>> 0, 0),
    copied(7, { copy: (value) => value })
  ];
}

function points(s) {
  if (s === "Dot") {
    return 0;
  } else {
    return s._0.length;
  }
}

export function enum_clones() {
  const a = {
    TAG: "Poly",
    _0: [1]
  };
  let b;
  const match = a.TAG === "Poly" ? {
    ...a,
    _0: a._0.slice()
  } : a;
  if (match.TAG === "Poly") {
    let p = match._0;
    p.push(2);
    b = {
      TAG: "Poly",
      _0: p
    };
  } else {
    b = match;
  }
  const dot = "Dot";
  const f = figureClone_clone({
    TAG: "Poly",
    _0: [
      1,
      2,
      3
    ]
  });
  let n;
  if (f === "Dot") {
    n = 0;
  } else {
    n = f._0.length;
  }
  return [
    points(a),
    points(b),
    points(dot) + n >>> 0
  ];
}

export function conversions() {
  const a = metersFromF64_from(2.5);
  const b = metersFromU32_from(3);
  const c = metersFromF64_from(1.5);
  return [
    a[0],
    b[0],
    c[0]
  ];
}

function configDefault_default() {
  return {
    retries: 3,
    name: "main"
  };
}

function trackedClone_clone(tracked) {
  return { generation: tracked.generation + 1 >>> 0 };
}

function figureClone_clone(figure) {
  if (figure === "Dot") {
    return "Dot";
  } else {
    return {
      TAG: "Poly",
      _0: figure._0.slice()
    };
  }
}

function metersFromF64_from(m) {
  return [m];
}

function metersFromU32_from(km) {
  return [km * 1000];
}

export function configDefault() {
  if ($configDefault === undefined) {
    $configDefault = { default: configDefault_default };
  }
  return $configDefault;
}

export function trackedClone() {
  if ($trackedClone === undefined) {
    $trackedClone = { clone: trackedClone_clone };
  }
  return $trackedClone;
}

export function figureClone() {
  if ($figureClone === undefined) {
    $figureClone = { clone: figureClone_clone };
  }
  return $figureClone;
}
//# sourceMappingURL=std_traits.js.map
