//! rust-js: compile Rust to readable JavaScript, in the spirit of ReScript.
//!
//! ReScript reuses OCaml's type checker and swaps in a JS backend. We do
//! the same with rustc:
//!
//! ```text
//!   .rs ─► rustc: parse, resolve, type check ─► THIR ──┐ (copied)
//!                                                │      │
//!                                   borrowck (MIR)      ▼
//!                                                │   lower.rs ─► js.rs ─► to_oxc.rs ─► .js + .js.map
//!                          errors? stop here ◄───┘
//! ```
//!
//! Usage: `rust-js <input.rs> [-o <output.js>] [-- <rustc flags>]`. Also writes
//! `<output.js>.map`. Flags after `--` go to rustc unchanged.

#![feature(rustc_private)]

extern crate rustc_ast;
extern crate rustc_driver;
extern crate rustc_hir;
extern crate rustc_interface;
extern crate rustc_middle;
extern crate rustc_span;

mod js;
mod lower;
mod to_oxc;

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use rustc_driver::{Callbacks, Compilation};
use rustc_interface::interface::Compiler;
use rustc_middle::ty::TyCtxt;

struct RustJs {
    input: PathBuf,
    output: PathBuf,
}

impl Callbacks for RustJs {
    fn after_expansion<'tcx>(&mut self, _compiler: &Compiler, tcx: TyCtxt<'tcx>) -> Compilation {
        // 1. Copy each function's THIR. MIR building (for borrowck) steals it.
        let bodies = lower::collect_bodies(tcx);

        // 2. Run rustc's full analysis: type check, borrow check, lints.
        tcx.ensure_ok().analysis(());

        // 3. Only a program rustc accepts becomes JavaScript.
        if tcx.dcx().has_errors().is_none()
            && let Some(modules) = lower::lower_crate(tcx, &bodies)
            && let Err(err) = self.write(modules)
        {
            tcx.dcx().err(format!("rust-js: {err}"));
        }

        // We never want rustc's own codegen.
        Compilation::Stop
    }
}

impl RustJs {
    /// Write one `.js` and `.js.map` per module (ADR 0019).
    fn write(&self, modules: Vec<lower::LoweredModule>) -> Result<(), String> {
        for module in modules {
            let js_path = self.js_path(&module.path);
            if !module.path.is_empty() && js_path == self.output {
                return Err(format!(
                    "module `{}` would be written over `{}`; pick another output name",
                    module.path.join("::"),
                    self.output.display()
                ));
            }
            let rust_path = module.file.name.clone().into_local_path().unwrap_or_else(|| self.input.clone());
            let imports = module
                .imports
                .iter()
                .map(|(alias, target)| js::Import { alias: alias.clone(), from: self.specifier(&module.path, target) })
                .collect();
            let js_module = js::Module {
                header: format!("// Generated by rust-js from {}. Do not edit.", rust_path.display()),
                imports,
                runtime: module.runtime.iter().map(|helper| helper.source()).collect(),
                functions: module.functions,
            };

            let dir = parent_dir(&js_path);
            std::fs::create_dir_all(dir).map_err(|err| format!("cannot create `{}`: {err}", dir.display()))?;
            // rustc's copy of the source (with line endings normalized), so
            // byte offsets in our spans line up with it exactly.
            let source = module.file.src.as_deref().ok_or_else(|| format!("no source for `{}`", rust_path.display()))?;
            let js_file_name = js_path.file_name().unwrap_or_default().to_string_lossy();
            let output = to_oxc::emit(&js_module, source, &relative(dir, &rust_path), &js_file_name);
            let map_path = PathBuf::from(format!("{}.map", js_path.display()));
            for (path, text) in [(&js_path, &output.code), (&map_path, &output.map)] {
                std::fs::write(path, text).map_err(|err| format!("cannot write `{}`: {err}", path.display()))?;
            }
        }
        Ok(())
    }

    /// Where a module's JS goes: the root to the output file, `a::b` to
    /// `a/b.js` beside it, mirroring how Rust lays out `src/`.
    fn js_path(&self, module: &[String]) -> PathBuf {
        if module.is_empty() {
            return self.output.clone();
        }
        let mut path = parent_dir(&self.output).to_path_buf();
        path.extend(module);
        path.set_extension("js");
        path
    }

    /// The import specifier, in module `from`'s file, for module `to`'s file:
    /// `./util.js`, `../lib.js`. Computed from module paths alone, since the
    /// target file may not have been written yet.
    fn specifier(&self, from: &[String], to: &[String]) -> String {
        // A module's file sits in the directory named by all but the last
        // segment of its path; the root's file is in the top directory.
        let dir = |path: &[String]| path.len().saturating_sub(1);
        let (from_dir, to_dir) = (&from[..dir(from)], &to[..dir(to)]);
        let common = from_dir.iter().zip(to_dir).take_while(|(a, b)| a == b).count();
        let file = match to.last() {
            Some(name) => format!("{name}.js"),
            None => self.output.file_name().unwrap_or_default().to_string_lossy().into_owned(),
        };
        let mut specifier = if from_dir.len() == common { "./".to_string() } else { "../".repeat(from_dir.len() - common) };
        for segment in &to_dir[common..] {
            specifier.push_str(segment);
            specifier.push('/');
        }
        specifier.push_str(&file);
        specifier
    }
}

/// A file's directory, as a path that works even for a bare file name.
fn parent_dir(path: &Path) -> &Path {
    match path.parent() {
        Some(dir) if !dir.as_os_str().is_empty() => dir,
        _ => Path::new("."),
    }
}

/// `to` as seen from directory `from`, e.g. `../examples/fib.rs`. Both
/// must exist, so they can be resolved to real paths first.
fn relative(from: &Path, to: &Path) -> String {
    let absolute = |p: &Path| std::fs::canonicalize(p).unwrap_or_else(|_| p.to_path_buf());
    let (from, to) = (absolute(from), absolute(to));
    let from: Vec<_> = from.components().collect();
    let to: Vec<_> = to.components().collect();
    let common = from.iter().zip(&to).take_while(|(a, b)| a == b).count();
    let mut relative: PathBuf = std::iter::repeat_n("..", from.len() - common).collect();
    relative.extend(&to[common..]);
    relative.to_string_lossy().into_owned()
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    // Anything after `--` goes to rustc as-is, e.g. `-- --sysroot /sysroot`.
    let (ours, to_rustc) = match args.iter().position(|a| a == "--") {
        Some(i) => (&args[..i], &args[i + 1..]),
        None => (&args[..], &[][..]),
    };
    let (input, output) = match ours {
        [input] => (PathBuf::from(input), PathBuf::from(input).with_extension("js")),
        [input, flag, output] if flag == "-o" => (PathBuf::from(input), PathBuf::from(output)),
        _ => {
            eprintln!("usage: rust-js <input.rs> [-o <output.js>] [-- <rustc flags>]");
            return ExitCode::FAILURE;
        }
    };

    let mut rustc_args = vec![
        "rust-js".to_string(), // argv[0], ignored by rustc
        input.display().to_string(),
        "--crate-type=lib".to_string(),
        "--edition=2024".to_string(),
    ];
    rustc_args.extend(to_rustc.iter().cloned());
    let mut callbacks = RustJs { input, output };
    rustc_driver::catch_with_exit_code(|| rustc_driver::run_compiler(&rustc_args, &mut callbacks))
}
