//! rust-js: compile Rust to readable JavaScript, in the spirit of ReScript.
//!
//! ReScript reuses OCaml's type checker and swaps in a JS backend. We do
//! the same with rustc:
//!
//! ```text
//!   .rs ─► rustc: parse, resolve, type check ─► THIR ──┐ (copied)
//!                                                │      │
//!                                   borrowck (MIR)      ▼
//!                                                │   lower.rs ─► js.rs ─► to_oxc.rs ─► .js + .js.map
//!                          errors? stop here ◄───┘
//! ```
//!
//! Usage: `rust-js [--test] <input.rs> [-o <output.js>] [-- <rustc flags>]`. Also
//! writes `<output.js>.map`. Flags after `--` go to rustc unchanged. With
//! `--test`, the crate's `#[test]` functions are compiled too, and
//! `<output>.test.js` runs them with `bun test` (ADR 0026).

#![feature(rustc_private)]

extern crate rustc_ast;
extern crate rustc_driver;
extern crate rustc_hir;
extern crate rustc_interface;
extern crate rustc_middle;
extern crate rustc_span;

mod js;
mod lower;
mod to_oxc;

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use rustc_driver::{Callbacks, Compilation};
use rustc_interface::interface::Compiler;
use rustc_middle::ty::TyCtxt;

struct RustJs {
    input: PathBuf,
    output: PathBuf,
    test: bool,
}

impl Callbacks for RustJs {
    fn after_expansion<'tcx>(&mut self, _compiler: &Compiler, tcx: TyCtxt<'tcx>) -> Compilation {
        // 1. Copy each function's THIR. MIR building (for borrowck) steals it.
        let bodies = lower::collect_bodies(tcx);

        // 2. Run rustc's full analysis: type check, borrow check, lints.
        tcx.ensure_ok().analysis(());

        // 3. Only a program rustc accepts becomes JavaScript.
        if tcx.dcx().has_errors().is_none()
            && let Some(lowered) = lower::lower_crate(tcx, &bodies)
            && let Err(err) = self.write(lowered.modules).and_then(|()| self.write_tests(&lowered.tests))
        {
            tcx.dcx().err(format!("rust-js: {err}"));
        }

        // We never want rustc's own codegen.
        Compilation::Stop
    }
}

impl RustJs {
    /// Write one `.js` and `.js.map` per module (ADR 0019).
    fn write(&self, modules: Vec<lower::LoweredModule>) -> Result<(), String> {
        for module in modules {
            let js_path = self.js_path(&module.path);
            if !module.path.is_empty() && js_path == self.output {
                return Err(format!(
                    "module `{}` would be written over `{}`; pick another output name",
                    module.path.join("::"),
                    self.output.display()
                ));
            }
            let rust_path = module.file.name.clone().into_local_path().unwrap_or_else(|| self.input.clone());
            let imports = module
                .imports
                .iter()
                .map(|(alias, target)| js::Import { alias: alias.clone(), from: self.specifier(&module.path, target) })
                .collect();
            let js_module = js::Module {
                header: format!("// Generated by rust-js from {}. Do not edit.", rust_path.display()),
                imports,
                runtime: module.runtime.iter().map(|helper| helper.source()).collect(),
                functions: module.functions,
            };

            let dir = parent_dir(&js_path);
            std::fs::create_dir_all(dir).map_err(|err| format!("cannot create `{}`: {err}", dir.display()))?;
            // rustc's copy of the source (with line endings normalized), so
            // byte offsets in our spans line up with it exactly.
            let source = module.file.src.as_deref().ok_or_else(|| format!("no source for `{}`", rust_path.display()))?;
            let js_file_name = js_path.file_name().unwrap_or_default().to_string_lossy();
            let output = to_oxc::emit(&js_module, source, &relative(dir, &rust_path), &js_file_name);
            let map_path = PathBuf::from(format!("{}.map", js_path.display()));
            for (path, text) in [(&js_path, &output.code), (&map_path, &output.map)] {
                std::fs::write(path, text).map_err(|err| format!("cannot write `{}`: {err}", path.display()))?;
            }
        }
        Ok(())
    }

    /// In test mode, `<output>.test.js` beside the output: one `test(..)`
    /// per `#[test]` function, for `bun test` (ADR 0026). `test` is the
    /// runner's global, so nothing here is specific to one runner.
    fn write_tests(&self, tests: &[lower::TestFn]) -> Result<(), String> {
        if !self.test {
            return Ok(());
        }
        let mut modules: Vec<&Vec<String>> = Vec::new();
        for test in tests {
            if !modules.contains(&&test.module) {
                modules.push(&test.module);
            }
        }
        // One namespace import per module, named after it, like ADR 0019.
        let crate_name = self.output.file_stem().unwrap_or_default().to_string_lossy().into_owned();
        let mut taken = vec!["test".to_string(), "shouldPanic".to_string()];
        let mut aliases = Vec::new();
        let mut code = format!(
            "// Generated by rust-js from {}: its `#[test]` functions, for `bun test`. Do not edit.\n\n",
            self.input.display()
        );
        for module in &modules {
            let base = module.last().cloned().unwrap_or_else(|| crate_name.clone()).replace('-', "_");
            let alias = (0..).map(|k| if k == 0 { base.clone() } else { format!("{base}${k}") }).find(|a| !taken.contains(a)).unwrap();
            taken.push(alias.clone());
            code.push_str(&format!("import * as {alias} from {:?};\n", self.specifier(&[], module)));
            aliases.push(alias);
        }
        if tests.iter().any(|t| t.should_panic.is_some()) {
            code.push_str(SHOULD_PANIC);
        }
        code.push('\n');
        for test in tests {
            let alias = &aliases[modules.iter().position(|m| **m == test.module).unwrap()];
            let f = format!("{alias}.{}", test.name);
            let body = match &test.should_panic {
                None => f,
                Some(expected) => format!("() => shouldPanic({f}, {})", expected.as_ref().map_or("undefined".to_string(), |e| format!("{e:?}"))),
            };
            let register = if test.ignore { "test.skip" } else { "test" };
            code.push_str(&format!("{register}({:?}, {body});\n", test.label));
        }
        let stem = self.output.file_stem().unwrap_or_default().to_string_lossy().into_owned();
        let path = self.output.with_file_name(format!("{stem}.test.js"));
        std::fs::write(&path, code).map_err(|err| format!("cannot write `{}`: {err}", path.display()))
    }

    /// Where a module's JS goes: the root to the output file, `a::b` to
    /// `a/b.js` beside it, mirroring how Rust lays out `src/`.
    fn js_path(&self, module: &[String]) -> PathBuf {
        if module.is_empty() {
            return self.output.clone();
        }
        let mut path = parent_dir(&self.output).to_path_buf();
        path.extend(module);
        path.set_extension("js");
        path
    }

    /// The import specifier, in module `from`'s file, for module `to`'s file:
    /// `./util.js`, `../lib.js`. Computed from module paths alone, since the
    /// target file may not have been written yet.
    fn specifier(&self, from: &[String], to: &[String]) -> String {
        // A module's file sits in the directory named by all but the last
        // segment of its path; the root's file is in the top directory.
        let dir = |path: &[String]| path.len().saturating_sub(1);
        let (from_dir, to_dir) = (&from[..dir(from)], &to[..dir(to)]);
        let common = from_dir.iter().zip(to_dir).take_while(|(a, b)| a == b).count();
        let file = match to.last() {
            Some(name) => format!("{name}.js"),
            None => self.output.file_name().unwrap_or_default().to_string_lossy().into_owned(),
        };
        let mut specifier = if from_dir.len() == common { "./".to_string() } else { "../".repeat(from_dir.len() - common) };
        for segment in &to_dir[common..] {
            specifier.push_str(segment);
            specifier.push('/');
        }
        specifier.push_str(&file);
        specifier
    }
}

/// `#[should_panic]`: the test passes only if it panics, and if `expected`
/// is given, only if the panic message contains it, as with libtest.
const SHOULD_PANIC: &str = r#"
function shouldPanic(f, expected) {
  try {
    f();
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    if (expected === undefined || message.includes(expected)) {
      return;
    }
    throw new Error("panic did not contain expected string\n      panic message: " + JSON.stringify(message) + "\n expected substring: " + JSON.stringify(expected));
  }
  throw new Error("test did not panic as expected");
}
"#;

/// A file's directory, as a path that works even for a bare file name.
fn parent_dir(path: &Path) -> &Path {
    match path.parent() {
        Some(dir) if !dir.as_os_str().is_empty() => dir,
        _ => Path::new("."),
    }
}

/// `to` as seen from directory `from`, e.g. `../examples/fib.rs`. Both
/// must exist, so they can be resolved to real paths first.
fn relative(from: &Path, to: &Path) -> String {
    let absolute = |p: &Path| std::fs::canonicalize(p).unwrap_or_else(|_| p.to_path_buf());
    let (from, to) = (absolute(from), absolute(to));
    let from: Vec<_> = from.components().collect();
    let to: Vec<_> = to.components().collect();
    let common = from.iter().zip(&to).take_while(|(a, b)| a == b).count();
    let mut relative: PathBuf = std::iter::repeat_n("..", from.len() - common).collect();
    relative.extend(&to[common..]);
    relative.to_string_lossy().into_owned()
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    // Anything after `--` goes to rustc as-is, e.g. `-- --sysroot /sysroot`.
    let (ours, to_rustc) = match args.iter().position(|a| a == "--") {
        Some(i) => (&args[..i], &args[i + 1..]),
        None => (&args[..], &[][..]),
    };
    let test = ours.first().is_some_and(|a| a == "--test");
    let ours = if test { &ours[1..] } else { ours };
    let (input, output) = match ours {
        [input] => (PathBuf::from(input), PathBuf::from(input).with_extension("js")),
        [input, flag, output] if flag == "-o" => (PathBuf::from(input), PathBuf::from(output)),
        _ => {
            eprintln!("usage: rust-js [--test] <input.rs> [-o <output.js>] [-- <rustc flags>]");
            return ExitCode::FAILURE;
        }
    };

    let mut rustc_args = vec![
        "rust-js".to_string(), // argv[0], ignored by rustc
        input.display().to_string(),
        "--crate-type=lib".to_string(),
        "--edition=2024".to_string(),
        // `#[cfg(browser)]` marks tests that need a real browser (ADR 0027):
        // `-- --cfg browser` turns it on. Declaring any cfg makes rustc check them
        // all, so `test` is declared too, as Cargo does.
        "--check-cfg=cfg(browser, test)".to_string(),
    ];
    if test {
        rustc_args.push("--test".to_string());
    }
    rustc_args.extend(to_rustc.iter().cloned());
    let mut callbacks = RustJs { input, output, test };
    rustc_driver::catch_with_exit_code(|| rustc_driver::run_compiler(&rustc_args, &mut callbacks))
}
