//! rsjs: compile Rust to readable JavaScript, in the spirit of ReScript.
//!
//! ReScript reuses OCaml's type checker and swaps in a JS backend. We do
//! the same with rustc:
//!
//! ```text
//!   .rs ─► rustc: parse, resolve, type check ─► THIR ──┐ (copied)
//!                                                │      │
//!                                   borrowck (MIR)      ▼
//!                                                │   lower.rs ─► js.rs ─► to_oxc.rs ─► .js + .js.map
//!                          errors? stop here ◄───┘
//! ```
//!
//! Usage: `rsjs <input.rs> [-o <output.js>]`. Also writes `<output.js>.map`.

#![feature(rustc_private)]

extern crate rustc_ast;
extern crate rustc_driver;
extern crate rustc_hir;
extern crate rustc_interface;
extern crate rustc_middle;
extern crate rustc_span;

mod js;
mod lower;
mod to_oxc;

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use rustc_driver::{Callbacks, Compilation};
use rustc_interface::interface::Compiler;
use rustc_middle::ty::TyCtxt;

struct Rsjs {
    input: PathBuf,
    output: PathBuf,
}

impl Callbacks for Rsjs {
    fn after_expansion<'tcx>(&mut self, _compiler: &Compiler, tcx: TyCtxt<'tcx>) -> Compilation {
        // 1. Copy each function's THIR. MIR building (for borrowck) steals it.
        let bodies = lower::collect_bodies(tcx);

        // 2. Run rustc's full analysis: type check, borrow check, lints.
        tcx.ensure_ok().analysis(());

        // 3. Only a program rustc accepts becomes JavaScript.
        let file = lower::root_file(tcx);
        if tcx.dcx().has_errors().is_none()
            && let Some(lowered) = lower::lower_crate(tcx, &bodies, &file)
        {
            let mut runtime: Vec<_> = lowered.iter().flat_map(|f| f.runtime.iter().copied()).collect();
            runtime.sort();
            runtime.dedup();
            let module = js::Module {
                header: format!("// Generated by rsjs from {}. Do not edit.", self.input.display()),
                runtime: runtime.into_iter().map(lower::Helper::source).collect(),
                functions: lowered.into_iter().map(|f| f.function).collect(),
            };
            // rustc's copy of the source (with line endings normalized), so
            // byte offsets in our spans line up with it exactly.
            let source = file.src.as_deref().expect("the root file was read from disk");
            let js_file_name = self.output.file_name().unwrap_or_default().to_string_lossy();
            let output = to_oxc::emit(&module, source, &self.map_source_path(), &js_file_name);
            let map_path = PathBuf::from(format!("{}.map", self.output.display()));
            for (path, text) in [(&self.output, &output.code), (&map_path, &output.map)] {
                if let Err(err) = std::fs::write(path, text) {
                    tcx.dcx().err(format!("rsjs: cannot write `{}`: {err}", path.display()));
                }
            }
        }

        // We never want rustc's own codegen.
        Compilation::Stop
    }
}

impl Rsjs {
    /// The Rust file's path as the source map should name it: relative to
    /// the map's own directory, e.g. `../examples/fib.rs`.
    fn map_source_path(&self) -> String {
        let absolute = |p: &Path| std::fs::canonicalize(p).unwrap_or_else(|_| p.to_path_buf());
        let out_dir = match self.output.parent() {
            Some(dir) if !dir.as_os_str().is_empty() => dir,
            _ => Path::new("."),
        };
        let (out_dir, input) = (absolute(out_dir), absolute(&self.input));
        let from: Vec<_> = out_dir.components().collect();
        let to: Vec<_> = input.components().collect();
        let common = from.iter().zip(&to).take_while(|(a, b)| a == b).count();
        let mut relative: PathBuf = std::iter::repeat_n("..", from.len() - common).collect();
        relative.extend(&to[common..]);
        relative.to_string_lossy().into_owned()
    }
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let (input, output) = match args.as_slice() {
        [input] => (PathBuf::from(input), PathBuf::from(input).with_extension("js")),
        [input, flag, output] if flag == "-o" => (PathBuf::from(input), PathBuf::from(output)),
        _ => {
            eprintln!("usage: rsjs <input.rs> [-o <output.js>]");
            return ExitCode::FAILURE;
        }
    };

    let rustc_args = vec![
        "rsjs".to_string(), // argv[0], ignored by rustc
        input.display().to_string(),
        "--crate-type=lib".to_string(),
        "--edition=2024".to_string(),
    ];
    let mut callbacks = Rsjs { input, output };
    rustc_driver::catch_with_exit_code(|| rustc_driver::run_compiler(&rustc_args, &mut callbacks))
}
