//! Resolve and validate all artifacts before touching output files.

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use serde_json::{Value, json};

use crate::{js, lower, to_oxc};

struct Artifact {
    path: PathBuf,
    text: String,
}

pub struct OutputPlan {
    pub input: PathBuf,
    pub output: PathBuf,
    pub test: bool,
    pub manifest: Option<PathBuf>,
    jsx: HashSet<Vec<String>>,
}

impl OutputPlan {
    /// Write one `.js` and `.js.map` per module (ADR 0019).
    fn generate(&self, modules: Vec<lower::LoweredModule>) -> Result<Vec<Artifact>, String> {
        let mut artifacts = Vec::new();
        for module in modules {
            let js_path = self.js_path(&module.path);
            let rust_path = module
                .file
                .name
                .clone()
                .into_local_path()
                .unwrap_or_else(|| self.input.clone());
            let imports = module
                .imports
                .iter()
                .map(|(alias, target)| js::Import {
                    alias: alias.clone(),
                    from: self.specifier(&module.path, target),
                })
                .collect();
            // A relative module in `#[link_name]` is relative to the root's
            // file (ADR 0028), so a file in a subdirectory climbs up to it.
            let depth = module.path.len().saturating_sub(1);
            let packages = module
                .packages
                .into_iter()
                .map(|package| js::Package {
                    from: relocate(&package.from, depth),
                    ..package
                })
                .collect();
            let mut js_module = js::Module {
                header: format!("// Generated by rust-js from {}. Do not edit.", rust_path.display()),
                packages,
                imports,
                runtime: module.runtime.iter().map(|helper| helper.source()).collect(),
                namespaces: module.namespaces,
                consts: module.consts,
                functions: module.functions,
                caches: module.caches,
            };

            crate::prepare::module(&mut js_module);
            let dir = parent_dir(&js_path);
            // rustc's copy of the source (with line endings normalized), so
            // byte offsets in our spans line up with it exactly.
            let source = module
                .file
                .src
                .as_deref()
                .ok_or_else(|| format!("no source for `{}`", rust_path.display()))?;
            let js_file_name = js_path.file_name().unwrap_or_default().to_string_lossy();
            let output = to_oxc::emit(&js_module, source, &relative(dir, &rust_path), &js_file_name);
            let map_path = PathBuf::from(format!("{}.map", js_path.display()));
            for (path, text) in [(&js_path, &output.code), (&map_path, &output.map)] {
                artifacts.push(Artifact {
                    path: path.clone(),
                    text: text.clone(),
                });
            }
        }
        Ok(artifacts)
    }

    /// In test mode, `<output>.test.js` beside the output: one `test(..)`
    /// per `#[test]` function, for `bun test` (ADR 0026). `test` is the
    /// runner's global, so nothing here is specific to one runner.
    fn tests(&self, tests: &[lower::TestFn]) -> Option<Artifact> {
        if !self.test {
            return None;
        }
        let mut modules: Vec<&Vec<String>> = Vec::new();
        for test in tests {
            if !modules.contains(&&test.module) {
                modules.push(&test.module);
            }
        }
        // One namespace import per module, named after it, like ADR 0019.
        let crate_name = self
            .output
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        let mut taken = vec!["test".to_string(), "shouldPanic".to_string()];
        let mut aliases = Vec::new();
        let mut code = format!(
            "// Generated by rust-js from {}: its `#[test]` functions, for `bun test`. Do not edit.\n\n",
            self.input.display()
        );
        for module in &modules {
            let base = module
                .last()
                .cloned()
                .unwrap_or_else(|| crate_name.clone())
                .replace('-', "_");
            let alias = (0..)
                .map(|k| if k == 0 { base.clone() } else { format!("{base}${k}") })
                .find(|a| !taken.contains(a))
                .unwrap();
            taken.push(alias.clone());
            code.push_str(&format!(
                "import * as {alias} from {:?};\n",
                self.specifier(&[], module)
            ));
            aliases.push(alias);
        }
        if tests.iter().any(|t| t.should_panic.is_some()) {
            code.push_str(SHOULD_PANIC);
        }
        code.push('\n');
        for test in tests {
            let alias = &aliases[modules.iter().position(|m| **m == test.module).unwrap()];
            let f = format!("{alias}.{}", test.name);
            let body = match &test.should_panic {
                None => f,
                Some(expected) => format!(
                    "() => shouldPanic({f}, {})",
                    expected.as_ref().map_or("undefined".to_string(), |e| format!("{e:?}"))
                ),
            };
            let register = if test.ignore { "test.skip" } else { "test" };
            code.push_str(&format!("{register}({:?}, {body});\n", test.label));
        }
        let stem = self
            .output
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        let path = self.output.with_file_name(format!("{stem}.test.js"));
        Some(Artifact { path, text: code })
    }

    /// Where a module's JS goes: the root to the output file, `a::b` to
    /// `a/b.js` beside it, mirroring how Rust lays out `src/`. A module
    /// with JSX is a `.jsx` file, as JSX tools expect (ADR 0040).
    fn js_path(&self, module: &[String]) -> PathBuf {
        let jsx = self.jsx.contains(module);
        if module.is_empty() {
            return if jsx {
                self.output.with_extension("jsx")
            } else {
                self.output.clone()
            };
        }
        let mut path = parent_dir(&self.output).to_path_buf();
        path.extend(module);
        path.set_extension(if jsx { "jsx" } else { "js" });
        path
    }

    /// The import specifier, in module `from`'s file, for module `to`'s file:
    /// `./util.js`, `../lib.js`. Computed from module paths alone, since the
    /// target file may not have been written yet.
    fn specifier(&self, from: &[String], to: &[String]) -> String {
        // A module's file sits in the directory named by all but the last
        // segment of its path; the root's file is in the top directory.
        let dir = |path: &[String]| path.len().saturating_sub(1);
        let (from_dir, to_dir) = (&from[..dir(from)], &to[..dir(to)]);
        let common = from_dir.iter().zip(to_dir).take_while(|(a, b)| a == b).count();
        let file = self
            .js_path(to)
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        let mut specifier = if from_dir.len() == common {
            "./".to_string()
        } else {
            "../".repeat(from_dir.len() - common)
        };
        for segment in &to_dir[common..] {
            specifier.push_str(segment);
            specifier.push('/');
        }
        specifier.push_str(&file);
        specifier
    }
}

/// `#[should_panic]`: the test passes only if it panics, and if `expected`
/// is given, only if the panic message contains it, as with libtest.
const SHOULD_PANIC: &str = r#"
function shouldPanic(f, expected) {
  try {
    f();
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    if (expected === undefined || message.includes(expected)) {
      return;
    }
    throw new Error("panic did not contain expected string\n      panic message: " + JSON.stringify(message) + "\n expected substring: " + JSON.stringify(expected));
  }
  throw new Error("test did not panic as expected");
}
"#;

/// A module specifier, as seen from `depth` directories below the root's
/// file: `./greet.js` is `../greet.js` one down. Package names stay as they are.
fn relocate(specifier: &str, depth: usize) -> String {
    let up = "../".repeat(depth);
    match specifier.strip_prefix("./") {
        Some(rest) if depth > 0 => format!("{up}{rest}"),
        _ if depth > 0 && specifier.starts_with("../") => format!("{up}{specifier}"),
        _ => specifier.to_string(),
    }
}

/// A file's directory, as a path that works even for a bare file name.
fn parent_dir(path: &Path) -> &Path {
    match path.parent() {
        Some(dir) if !dir.as_os_str().is_empty() => dir,
        _ => Path::new("."),
    }
}

/// `to` as seen from directory `from`, e.g. `../examples/fib.rs`. Resolve
/// existing ancestors without requiring the output directory to exist yet.
fn relative(from: &Path, to: &Path) -> String {
    let resolve = |p: &Path| absolute(p).unwrap_or_else(|_| p.to_path_buf());
    let (from, to) = (resolve(from), resolve(to));
    let from: Vec<_> = from.components().collect();
    let to: Vec<_> = to.components().collect();
    let common = from.iter().zip(&to).take_while(|(a, b)| a == b).count();
    let mut relative: PathBuf = std::iter::repeat_n("..", from.len() - common).collect();
    relative.extend(&to[common..]);
    relative.to_string_lossy().into_owned()
}

impl OutputPlan {
    pub fn new(input: PathBuf, output: PathBuf, test: bool, manifest: Option<PathBuf>) -> Self {
        Self {
            input,
            output,
            test,
            manifest,
            jsx: HashSet::new(),
        }
    }

    pub fn write(&mut self, lowered: lower::Lowered, sources: Vec<PathBuf>) -> Result<(), String> {
        self.jsx = lowered
            .modules
            .iter()
            .filter(|m| m.jsx)
            .map(|m| m.path.clone())
            .collect();
        let sources: Vec<PathBuf> = sources.into_iter().map(|p| absolute(&p)).collect::<Result<_, _>>()?;
        let mut planned = Vec::new();
        let mut modules = Vec::new();
        for module in &lowered.modules {
            let requested = self.js_path(&module.path);
            let file = absolute(&requested)?;
            let map = absolute(&PathBuf::from(format!("{}.map", requested.display())))?;
            planned.extend([file.clone(), map.clone()]);
            let imports = module
                .imports
                .iter()
                .map(|(_, target)| absolute(&self.js_path(target)))
                .collect::<Result<Vec<_>, _>>()?;
            modules.push(json!({
                "module": module.path, "file": file, "map": map,
                "source": module.file.name.clone().into_local_path().as_deref().map(absolute).transpose()?,
                "imports": imports,
            }));
        }
        let test_artifact = self.tests(&lowered.tests);
        if let Some(test) = &test_artifact {
            planned.push(absolute(&test.path)?);
        }
        let input = absolute(&self.input)?;
        let output = absolute(&self.output)?;
        let manifest_path = self.manifest.as_deref().map(absolute).transpose()?;
        let mut paths = HashSet::new();
        for path in planned.iter().chain(manifest_path.iter()) {
            if sources.contains(path) || path == &input || !paths.insert(path.clone()) {
                return Err(format!(
                    "output collision at `{}`; pick another output name",
                    path.display()
                ));
            }
            if path.exists() && !path.is_file() {
                return Err(format!("output `{}` is not a file", path.display()));
            }
        }

        let mut artifacts = self.generate(lowered.modules)?;
        artifacts.extend(test_artifact);
        for artifact in &mut artifacts {
            artifact.path = absolute(&artifact.path)?;
        }

        let mut stale = Vec::new();
        if let Some(path) = manifest_path {
            // Only remove files owned by this input/output pair, still containing
            // exactly the bytes this compiler wrote. User edits are preserved.
            if path.exists() {
                let previous: Value = serde_json::from_slice(&std::fs::read(&path).map_err(|e| e.to_string())?)
                    .map_err(|e| format!("invalid manifest `{}`: {e}", path.display()))?;
                if previous["version"] != 1 || previous["input"] != json!(input) || previous["output"] != json!(output)
                {
                    return Err(format!("manifest `{}` belongs to another compilation", path.display()));
                }
                if let Some(files) = previous["artifacts"].as_array() {
                    for file in files {
                        if let (Some(name), Some(hash)) = (file["file"].as_str(), file["hash"].as_str()) {
                            let old = absolute(Path::new(name))?;
                            let generated = ["js", "jsx", "map"]
                                .iter()
                                .any(|ext| old.extension().is_some_and(|e| e == *ext));
                            if generated
                                && old.starts_with(parent_dir(&output))
                                && !sources.contains(&old)
                                && !paths.contains(&old)
                                && old != input
                                && std::fs::read(&old).is_ok_and(|bytes| fingerprint(&bytes) == hash)
                            {
                                stale.push(old);
                            }
                        }
                    }
                }
            }
            let manifest = json!({
                "version": 1, "input": input, "output": output,
                "sources": sources, "modules": modules,
                "artifacts": artifacts.iter().map(|a| json!({
                    "file": a.path, "hash": fingerprint(a.text.as_bytes()),
                })).collect::<Vec<_>>(),
            });
            artifacts.push(Artifact {
                path,
                text: format!(
                    "{}\n",
                    serde_json::to_string_pretty(&manifest).map_err(|e| e.to_string())?
                ),
            });
        }
        publish(&artifacts, &stale)
    }
}

fn absolute(path: &Path) -> Result<PathBuf, String> {
    if cfg!(target_os = "wasi") {
        // The virtual filesystem has absolute preopened paths; realpath is not
        // provided by all WASI hosts (including browser shims).
        return Ok(path.to_path_buf());
    }
    // Resolve existing ancestors too, so aliases through symlinks collide.
    if path.exists() {
        std::fs::canonicalize(path).map_err(|e| e.to_string())
    } else {
        let path = std::path::absolute(path).map_err(|e| e.to_string())?;
        let parent = absolute(parent_dir(&path))?;
        Ok(parent.join(path.file_name().ok_or("output has no filename")?))
    }
}

fn fingerprint(bytes: &[u8]) -> String {
    // Stable across compiler releases; an ownership check, not a security hash.
    let hash = bytes.iter().fold(0xcbf29ce484222325_u64, |hash, byte| {
        (hash ^ u64::from(*byte)).wrapping_mul(0x100000001b3)
    });
    format!("{hash:016x}")
}

fn publish(artifacts: &[Artifact], stale: &[PathBuf]) -> Result<(), String> {
    // WASI compiles into a fresh, disposable virtual filesystem. The browser
    // shim does not provide native rename semantics; callers expose files only
    // after success. Validation and generation above still finish before writes.
    if cfg!(target_os = "wasi") {
        for a in artifacts {
            std::fs::create_dir_all(parent_dir(&a.path)).map_err(|e| e.to_string())?;
            std::fs::write(&a.path, &a.text).map_err(|e| e.to_string())?;
        }
        return Ok(());
    }
    let artifacts: Vec<&Artifact> = artifacts
        .iter()
        .filter(|a| !std::fs::read(&a.path).is_ok_and(|bytes| bytes == a.text.as_bytes()))
        .collect();
    // Stage every file next to its destination before replacing any output.
    // Keep originals for rollback on an I/O error. This is not a multi-file
    // transaction against process crashes; the manifest is committed last.
    let mut staged = Vec::new();
    let result = (|| -> Result<(), String> {
        for a in &artifacts {
            let dir = parent_dir(&a.path);
            std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
            let mut number = 0;
            let temp = loop {
                let candidate = dir.join(format!(".rust-js-stage-{number}"));
                match std::fs::create_dir(&candidate) {
                    Ok(()) => break candidate,
                    Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => number += 1,
                    Err(e) => return Err(format!("cannot stage in {}: {e}", dir.display())),
                }
            };
            staged.push(temp.clone());
            std::fs::write(temp.join("next"), &a.text).map_err(|e| e.to_string())?;
        }
        let originals: Vec<(PathBuf, Option<Vec<u8>>)> = artifacts
            .iter()
            .map(|a| &a.path)
            .chain(stale)
            .map(|path| {
                let bytes = match std::fs::read(path) {
                    Ok(bytes) => Some(bytes),
                    Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
                    Err(e) => return Err(e.to_string()),
                };
                Ok((path.clone(), bytes))
            })
            .collect::<Result<_, String>>()?;
        let commit = (|| -> std::io::Result<()> {
            // Publish the manifest last, after removal of obsolete artifacts.
            for path in stale {
                std::fs::remove_file(path)?;
            }
            for (a, temp) in artifacts.iter().zip(&staged) {
                std::fs::rename(temp.join("next"), &a.path)?;
            }
            Ok(())
        })();
        if let Err(error) = commit {
            let mut failures = Vec::new();
            for (path, bytes) in originals {
                let restored = match bytes {
                    Some(bytes) => std::fs::write(&path, bytes),
                    None if path.exists() => std::fs::remove_file(&path),
                    None => Ok(()),
                };
                if let Err(e) = restored {
                    failures.push(format!("{}: {e}", path.display()));
                }
            }
            return Err(format!(
                "cannot publish output: {error}; rollback errors: {}",
                failures.join(", ")
            ));
        }
        Ok(())
    })();
    for dir in staged {
        let _ = std::fs::remove_dir_all(dir);
    }
    result
}
