// Generated by rust-js from examples/report.rs. Do not edit.

function $index(items, index) {
  if (index < 0 || index >= items.length)
    throw new Error(`index out of bounds: the len is ${items.length} but the index is ${index}`);
  return items[index];
}

// Shortest round-trip decimal, using exact rational arithmetic.
// Rust Display uses decimal notation, including for very small/large values.
// Not JS's `String(x)`, though its digits are also the shortest: when two are
// equally close, JS takes the even one (1888570120608320.2), and Rust the
// larger (1888570120608320.3).
function $displayF64(value) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const x = Math.abs(value);
  if (x === 0) return sign + "0";

  const bitsView = new DataView(new ArrayBuffer(8));
  bitsView.setFloat64(0, x);
  const bits = bitsView.getBigUint64(0);
  const exponentBits = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponentBits === 0 ? fraction : fraction + (1n << 52n);
  const binaryExponent = exponentBits === 0 ? -1074 : exponentBits - 1023 - 52;
  const numerator = binaryExponent >= 0 ? significand << BigInt(binaryExponent) : significand;
  const denominator = binaryExponent < 0 ? 1n << BigInt(-binaryExponent) : 1n;

  // The floating-point logarithm is only an estimate; correct it exactly.
  let exponent = Math.floor(Math.log10(x));
  const atLeastPowerOfTen = (e) =>
    e >= 0
      ? numerator >= denominator * 10n ** BigInt(e)
      : numerator * 10n ** BigInt(-e) >= denominator;
  while (!atLeastPowerOfTen(exponent)) exponent--;
  while (atLeastPowerOfTen(exponent + 1)) exponent++;

  for (let precision = 1; precision <= 17; precision++) {
    const power = exponent - precision + 1;
    const n = power < 0 ? numerator * 10n ** BigInt(-power) : numerator;
    const d = power > 0 ? denominator * 10n ** BigInt(power) : denominator;
    const floor = n / d;
    const rounded = floor + (2n * (n % d) >= d ? 1n : 0n);
    // The rounding interval can be asymmetric at a binary power boundary.
    let best;
    let bestDistance;
    for (const candidate of [rounded, rounded - 1n, rounded + 1n]) {
      if (candidate > 0n && Number(`${candidate}e${power}`) === x) {
        const delta = candidate * d - n;
        const distance = delta < 0n ? -delta : delta;
        if (
          best === undefined ||
          distance < bestDistance ||
          (distance === bestDistance && candidate > best)
        ) {
          best = candidate;
          bestDistance = distance;
        }
      }
    }
    if (best !== undefined) {
      let digits = best.toString();
      let decimalPower = power;
      while (digits.endsWith("0")) {
        digits = digits.slice(0, -1);
        decimalPower++;
      }
      const point = digits.length + decimalPower;
      const body =
        point <= 0
          ? "0." + "0".repeat(-point) + digits
          : point >= digits.length
            ? digits + "0".repeat(point - digits.length)
            : digits.slice(0, point) + "." + digits.slice(point);
      return sign + body;
    }
  }
  throw new Error("No f64 round-trip decimal found");
}

function $debug(v) {
  if (typeof v === "string") {
    return JSON.stringify(v);
  }
  if (Array.isArray(v)) {
    return "[" + v.map($debug).join(", ") + "]";
  }
  if (v === undefined) {
    return "()";
  }
  // A `HashMap` and a `HashSet` (ADR 0059), in braces as Rust shows them.
  if (v instanceof Map) {
    return "{" + [...v].map(([k, x]) => $debug(k) + ": " + $debug(x)).join(", ") + "}";
  }
  if (v instanceof Set) {
    return "{" + [...v].map($debug).join(", ") + "}";
  }
  if (typeof v === "object" && v !== null) {
    return (
      "{ " +
      Object.entries(v)
        .map(([k, x]) => k + ": " + $debug(x))
        .join(", ") +
      " }"
    );
  }
  return String(v);
}

function $orInsertWith(map, key, make) {
  if (!map.has(key)) {
    map.set(key, make());
  }
  return map.get(key);
}

function $sortedEntries(map, cmp) {
  return Array.from(map).sort((a, b) => cmp(a[0], b[0]));
}

function $lines(s) {
  const lines = s.split("\n");
  const last = lines.pop();
  const ended = lines.map((line) => (line.endsWith("\r") ? line.slice(0, -1) : line));
  if (last !== "") {
    ended.push(last);
  }
  return ended;
}

function $unwrapErr(result, message = "called `Result::unwrap_err()` on an `Ok` value") {
  if (result.TAG === "Ok") {
    throw new Error(message + ": " + $debug(result._0));
  }
  return result._0;
}

function $debugParseError(message, name) {
  const kinds = {
    "cannot parse integer from empty string": "Empty",
    "invalid digit found in string": "InvalidDigit",
    "number too large to fit in target type": "PosOverflow",
    "number too small to fit in target type": "NegOverflow",
    "number would be zero for non-zero type": "Zero",
    "cannot parse float from empty string": "Empty",
    "invalid float literal": "Invalid",
    "cannot parse char from empty string": "EmptyString",
    "too many characters in string": "TooManyChars",
  };
  return name === "ParseBoolError" ? name : `${name} { kind: ${kinds[message]} }`;
}

function $parseInt(s, min, max) {
  const error = (message) => ({ TAG: "Err", _0: message });
  if (s === "") return error("cannot parse integer from empty string");
  if (!(min < 0 ? /^[+-]?[0-9]+$/ : /^\+?[0-9]+$/).test(s))
    return error("invalid digit found in string");
  const n = Number(s);
  if (n > max) return error("number too large to fit in target type");
  if (n < min) return error("number too small to fit in target type");
  return { TAG: "Ok", _0: n };
}

function $parseF64(s) {
  if (s === "") return { TAG: "Err", _0: "cannot parse float from empty string" };
  const lower = s.toLowerCase();
  const sign = lower.startsWith("-") ? -1 : 1;
  const rest = lower.replace(/^[+-]/, "");
  if (rest === "inf" || rest === "infinity") return { TAG: "Ok", _0: sign * Infinity };
  if (rest === "nan") return { TAG: "Ok", _0: NaN };
  if (!/^([0-9]+\.?[0-9]*|\.[0-9]+)(e[+-]?[0-9]+)?$/.test(rest))
    return { TAG: "Err", _0: "invalid float literal" };
  return { TAG: "Ok", _0: sign * Number(rest) };
}

function $parseBool(s) {
  return s === "true" || s === "false"
    ? { TAG: "Ok", _0: s === "true" }
    : { TAG: "Err", _0: "provided string was not `true` or `false`" };
}

function $parseChar(s) {
  const chars = [...s];
  if (chars.length === 1) return { TAG: "Ok", _0: s };
  return {
    TAG: "Err",
    _0:
      chars.length === 0 ? "cannot parse char from empty string" : "too many characters in string",
  };
}

function $windows(v, size) {
  if (size === 0) {
    throw new Error("window size must be non-zero");
  }
  return Array.from({ length: Math.max(0, v.length - size + 1) }, (_, i) => v.slice(i, i + size));
}

function $cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function $toFixed(value, digits) {
  if (Number.isNaN(value)) return "NaN";
  if (value === Infinity) return "inf";
  if (value === -Infinity) return "-inf";
  const sign = value < 0 || Object.is(value, -0) ? "-" : "";
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, Math.abs(value));
  const bits = view.getBigUint64(0);
  const exponent = Number((bits >> 52n) & 2047n);
  const fraction = bits & ((1n << 52n) - 1n);
  const significand = exponent === 0 ? fraction : fraction | (1n << 52n);
  const shift = exponent === 0 ? -1074 : exponent - 1075;
  // |value| * 10^digits, as a fraction.
  let numerator = significand * 10n ** BigInt(digits);
  let denominator = 1n;
  if (shift >= 0) numerator <<= BigInt(shift);
  else denominator <<= BigInt(-shift);
  let rounded = numerator / denominator;
  const twice = 2n * (numerator % denominator);
  if (twice > denominator || (twice === denominator && rounded % 2n === 1n)) rounded += 1n;
  const text = rounded.toString().padStart(digits + 1, "0");
  return sign + (digits === 0 ? text : text.slice(0, -digits) + "." + text.slice(-digits));
}

function $debugF64(value) {
  const size = Math.abs(value);
  if (Number.isFinite(value) && size !== 0 && (size < 1e-4 || size >= 1e16)) {
    return value.toExponential().replace("e+", "e");
  }
  const text = $displayF64(value);
  return Number.isFinite(value) && !text.includes(".") ? text + ".0" : text;
}

function $debugStr(s, quote = '"') {
  let out = quote;
  for (const c of s) {
    if (c === quote || c === "\\") out += "\\" + c;
    else if (c === "\n") out += "\\n";
    else if (c === "\r") out += "\\r";
    else if (c === "\t") out += "\\t";
    else if (c === "\0") out += "\\0";
    else if (
      /[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}\p{Zl}\p{Zp}\p{Grapheme_Extend}]/u.test(c) ||
      (c !== " " && /\p{Zs}/u.test(c))
    )
      out += "\\u{" + c.codePointAt(0).toString(16) + "}";
    else out += c;
  }
  return out + quote;
}

function $pad(text, width, align, fill = " ") {
  const room = width - [...text].length;
  if (room <= 0) return text;
  const before = align === ">" ? room : align === "^" ? Math.floor(room / 2) : 0;
  return fill.repeat(before) + text + fill.repeat(room - before);
}

function $maxBy(items, cmp, boxed = false) {
  if (items.length === 0) {
    return undefined;
  }
  const max = items.reduce((max, x) => (cmp(x, max) >= 0 ? x : max));
  return boxed ? $some(max) : max;
}

function $position(items, found) {
  const i = items.findIndex(found);
  return i < 0 ? undefined : i;
}

var $rowErrorDisplay;

const HEADERS = ["name", "team", "score", "age"];

function parse_row(line) {
  const parts = line.split(",").map((s) => s.trim());
  if (parts.length !== 4) {
    return { TAG: "Err", _0: { TAG: "Fields", _0: parts.length } };
  }
  if ($index(parts, 0).length === 0) {
    return { TAG: "Err", _0: { TAG: "Empty", _0: "name" } };
  }
  const result = $parseInt($index(parts, 2), 0, 4294967295);
  if (result.TAG === "Err") {
    return { TAG: "Err", _0: rowErrorFromParseIntError_from(result._0) };
  }
  const score = result._0;
  const result$1 = $parseInt($index(parts, 3), 0, 4294967295);
  if (result$1.TAG === "Err") {
    return { TAG: "Err", _0: rowErrorFromParseIntError_from(result$1._0) };
  }
  const age = result$1._0;
  return { TAG: "Ok", _0: { name: $index(parts, 0), team: $index(parts, 1), score, age } };
}

function capitalize(s) {
  return Array.from(s)
    .slice(0, 1)
    .flatMap((c) => Array.from(c.toUpperCase()))
    .concat(Array.from(s).slice(1))
    .join("");
}

function grade(score, age) {
  if (score >= 90) {
    return "A";
  } else if (score >= 70 && score <= 89 && age < 30) {
    return "B+";
  } else if (score >= 70 && score <= 89) {
    return "B";
  } else {
    return "C";
  }
}

export function table(input) {
  let out = "";
  let rows = [];
  for (const [i, line] of $lines(input)
    .map((x, i) => [i, x])
    .slice(1)) {
    const match = parse_row(line);
    if (match.TAG === "Ok") {
      rows.push(match._0);
    } else {
      out += `line ${(i + 1) >>> 0}: ${rowErrorDisplay_fmt(match._0)}\n`;
    }
  }
  rows.sort((a, b) => $cmp(b.score, a.score) || $cmp(a.name, b.name));
  out += `${$pad(HEADERS[0], 8, "<")}|${$pad(HEADERS[2], 6, ">")}|${$pad("grade", 7, "^")}|${HEADERS[1]}\n`;
  for (const r of rows) {
    out += `${$pad(capitalize(r.name), 8, "<")}|${String(r.score).padStart(6)}|${$pad(grade(r.score, r.age), 7, "^")}|${r.team.toUpperCase()}\n`;
  }
  let byTeam = new Map();
  for (const r$1 of rows) {
    $orInsertWith(byTeam, r$1.team, () => []).push(r$1);
  }
  for (const [team, members] of $sortedEntries(byTeam, $cmp)) {
    const total = members.map((r) => r.score).reduce((a, b) => (a + b) >>> 0, 0);
    const avg = total / members.length;
    const key = (r) => [r.score, [r.age]];
    const r$2 = $maxBy(members, (a, b) => {
      const left = key(a);
      const right = key(b);
      return $cmp(left[0], right[0]) || $cmp(right[1][0], left[1][0]);
    });
    const best = (r$2 != null ? r$2.name : undefined) ?? "-";
    out += `${$pad(team, 6, ">")}: n=${members.length} avg=${$toFixed(avg, 1).padStart(6)} best=${best}\n`;
  }
  const ages = rows.map((r) => r.age);
  const gaps = $windows(ages, 2).map((w) => (($index(w, 1) | 0) - ($index(w, 0) | 0)) | 0);
  out += `[${gaps.map((item) => String(item)).join(", ")}]\n`;
  const arg = rows.every((r) => r.score > 50);
  const arg$1 = rows.some((r) => r.team === "red");
  const arg$2 = $position(rows, (r) => r.age > 40);
  out += `${arg} ${arg$1} ${arg$2 == null ? "None" : `Some(${arg$2})`}\n`;
  return out;
}

export function parse_errors() {
  return `${$debugParseError($unwrapErr($parseInt("", 0, 255)), "ParseIntError")} ${$debugParseError($unwrapErr($parseInt("300", 0, 255)), "ParseIntError")} ${$debugParseError($unwrapErr($parseInt("-40000", -32768, 32767)), "ParseIntError")} ${$debugParseError($unwrapErr($parseF64("x")), "ParseFloatError")} ${$debugParseError($unwrapErr($parseBool("no")), "ParseBoolError")} ${$debugParseError($unwrapErr($parseChar("ab")), "ParseCharError")}`;
}

export function function_values(words) {
  const upper = words.map((w) => w.toUpperCase());
  const spaces = Array.from("a b	c").map((c) => /^\p{White_Space}$/u.test(c));
  const roots = [4, 2.25, 9].map((n) => Math.sqrt(n));
  const owned = words.map((s) => s);
  return [upper, spaces, roots, owned];
}

export function report() {
  const input =
    "name,team,score,age\nann, red, 91, 34\nbob,blue,78,25\ncy,red,78,45\n,blue,5,5\ndee,blue,x,3\neve,green,64,29\nfay,red\ngus, blue ,88,31\nßen,red,70,20\n";
  const arg = table(input);
  const arg$1 = parse_errors();
  const arg$2 = function_values(["x", "é"]);
  return `${arg}${arg$1}\n([${arg$2[0].map((item) => $debugStr(item)).join(", ")}], [${arg$2[1].map((item) => String(item)).join(", ")}], [${arg$2[2].map((item) => $debugF64(item)).join(", ")}], [${arg$2[3].map((item) => $debugStr(item)).join(", ")}])\n`;
}

function rowErrorFromParseIntError_from(e) {
  return { TAG: "Number", _0: e };
}

function rowErrorDisplay_fmt(rowError) {
  if (rowError.TAG === "Fields") {
    return `expected 4 fields, got ${rowError._0}`;
  } else if (rowError.TAG === "Number") {
    return `bad number: ${rowError._0}`;
  } else {
    return `empty ${rowError._0}`;
  }
}

export function rowErrorDisplay() {
  if ($rowErrorDisplay === undefined) {
    $rowErrorDisplay = { fmt: rowErrorDisplay_fmt };
  }
  return $rowErrorDisplay;
}
//# sourceMappingURL=report.js.map
